pi: Path integral Quantum Monte Carlo: Estimator Class Reference
Estimator Class Reference
Base class for all estimators.
#include <Estimator.h>
Public Member Functions
Estimator (const std::string &name)
Construct by giving the name of the estimator.
Estimator (const std::string &name, const std::string &typeString, const std::string &unitName)
Construct by giving the name of the estimator.
virtual ~Estimator ()
Virtual destructor.
const std::string & getName () const
Get the name of the estimator.
const std::string & getUnitName () const
Get the name of the unit for the estimator.
const std::string & getTypeString () const
Get the type string for this estimators.
virtual void evaluate (const Paths &)=0
Evaluate estimator for a path configuration.
virtual void averageOverClones (const MPIManager *)
Average over clones.
virtual void startReport (EstimatorReportBuilder &builder)
Callback EstimatorReportBuilder method.
virtual void reportStep (EstimatorReportBuilder &builder)
Callback EstimatorReportBuilder method.
Private Attributes
const std::string name
The name of the estimator.
const std::string typeString
The type string.
const std::string unitName
The unit name.
Detailed Description
Base class for all estimators.
Estimators should be subclassed to handle different data types.
Version:
$Revision$
Author:
John Shumway
Definition at line 32 of file Estimator.h.
Constructor & Destructor Documentation
Estimator::Estimator (const std::string & name) inline
Construct by giving the name of the estimator.
Definition at line 35 of file Estimator.h.
Estimator::Estimator (const std::string & name, const std::string & typeString, const std::string & unitName) inline
Construct by giving the name of the estimator.
Definition at line 37 of file Estimator.h.
virtual Estimator::~Estimator () inline virtual
Virtual destructor.
Definition at line 41 of file Estimator.h.
Member Function Documentation
virtual void Estimator::averageOverClones (const MPIManager *) inline virtual
Average over clones.
Reimplemented in AccRejEstimator, ScalarEstimator, BlitzArrayBlkdEst< N >, BlitzArrayBlkdEst< NDIM+3 >, BlitzArrayBlkdEst< NDIM+2 >, BlitzArrayBlkdEst< 1 >, BlitzArrayBlkdEst< 2 >, BlitzArrayBlkdEst< 3 >, BlitzArrayBlkdEst< 5 >, BlitzArrayBlkdEst< NDIM+1 >, BlitzArrayBlkdEst< 6 >, BlitzArrayBlkdEst< 7 >, BlitzArrayBlkdEst< NDIM >, BlitzArrayBlkdEst< 2 *NDIM+3 >, BlitzArrayBlkdEst< 2 *NDIM+1 >, ArrayEstimator, FreeEnergyEstimator, and PermutationEstimator.
Definition at line 51 of file Estimator.h.
virtual void Estimator::evaluate (const Paths &) pure virtual
Evaluate estimator for a path configuration.
Implemented in ZeroVarDensityEstimator, SpinChoicePCFEstimator< N >, PairCFEstimator< N >, DensCountEstimator, CountCountEstimator, DensDensEstimator, DynamicPCFEstimator, VIndEstimator, ConductanceEstimator, EIndEstimator, SpinChargeEstimator, ConductivityEstimator, SKOmegaEstimator, AccRejEstimator, VirialEnergyEstimator, DensityEstimator, DensityCurrentEstimator, EwaldCoulombEstimator, ThermoEnergyEstimator, AngularMomentumEstimator, BondLengthEstimator, BoxEstimator, FrequencyEstimator, SpinEstimator, DiamagneticEstimator, PositionEstimator, CoulombEnergyEstimator, ConductivityEstimator2D, DipoleMomentEstimator, FreeEnergyEstimator, PermutationEstimator, EMARateEstimator, JEstimator, and WindingEstimator.
const std::string& Estimator::getName () const inline
Get the name of the estimator.
Definition at line 43 of file Estimator.h.
References name.
Referenced by StdoutReportBuilder::reportAccRejStep(), StdoutReportBuilder::reportArrayBlockedStep(), StdoutReportBuilder::reportScalarStep(), H5ReportBuilder::startArrayBlockedReport(), and H5ReportBuilder::startScalarReport().
const std::string& Estimator::getTypeString () const inline
Get the type string for this estimators.
Definition at line 47 of file Estimator.h.
References typeString.
Referenced by H5ReportBuilder::startArrayBlockedReport(), and H5ReportBuilder::startScalarReport().
const std::string& Estimator::getUnitName () const inline
Get the name of the unit for the estimator.
Definition at line 45 of file Estimator.h.
References unitName.
Referenced by StdoutReportBuilder::reportScalarStep(), and H5ReportBuilder::startScalarReport().
virtual void Estimator::reportStep (EstimatorReportBuilder & builder) inline virtual
Callback EstimatorReportBuilder method.
Reimplemented in AccRejEstimator, ScalarEstimator, ArrayEstimator, and ArrayBlockedEstimator.
Definition at line 55 of file Estimator.h.
virtual void Estimator::startReport (EstimatorReportBuilder & builder) inline virtual
Callback EstimatorReportBuilder method.
Reimplemented in AccRejEstimator, ScalarEstimator, ArrayEstimator, and ArrayBlockedEstimator.
Definition at line 53 of file Estimator.h.
Member Data Documentation
const std::string Estimator::name private
The name of the estimator.
Definition at line 58 of file Estimator.h.
Referenced by getName().
const std::string Estimator::typeString private
The type string.
Definition at line 60 of file Estimator.h.
Referenced by getTypeString().
const std::string Estimator::unitName private
The unit name.
Definition at line 62 of file Estimator.h.
Referenced by getUnitName().
The documentation for this class was generated from the following file:
Estimator.h