pi: Path integral Quantum Monte Carlo: ScalarEstimator Class Reference
ScalarEstimator Class Reference
Base class for scalar estimators.
#include <ScalarEstimator.h>
Public Member Functions
ScalarEstimator (const std::string &name)
Construct by giving the name.
ScalarEstimator (const std::string &name, const std::string &typeString, const std::string &unitName, double shift, double scale)
Construct by giving the name.
virtual ~ScalarEstimator ()
Virtual destructor.
virtual double calcValue ()=0
Get the value.
double getValue () const
Get the value.
void setValue (const double v)
Get the value.
virtual void reset ()=0
Clear the value.
virtual void averageOverClones (const MPIManager *mpi)
Average over clones.
virtual void startReport (EstimatorReportBuilder &builder)
Callback EstimatorReportBuilder method for scalars.
virtual void reportStep (EstimatorReportBuilder &builder)
Callback EstimatorReportBuilder method for scalars.
Public Member Functions inherited from Estimator
Estimator (const std::string &name)
Construct by giving the name of the estimator.
Estimator (const std::string &name, const std::string &typeString, const std::string &unitName)
Construct by giving the name of the estimator.
virtual ~Estimator ()
Virtual destructor.
const std::string & getName () const
Get the name of the estimator.
const std::string & getUnitName () const
Get the name of the unit for the estimator.
const std::string & getTypeString () const
Get the type string for this estimators.
virtual void evaluate (const Paths &)=0
Evaluate estimator for a path configuration.
Protected Attributes
double value
const double scale
Scale value.
const double shift
Shift value.
Detailed Description
Base class for scalar estimators.
Version:
$Revision$
Author:
John Shumway
Definition at line 27 of file ScalarEstimator.h.
Constructor & Destructor Documentation
ScalarEstimator::ScalarEstimator (const std::string & name)
Construct by giving the name.
Definition at line 8 of file ScalarEstimator.cc.
ScalarEstimator::ScalarEstimator (const std::string & name, const std::string & typeString, const std::string & unitName, double shift, double scale)
Construct by giving the name.
Definition at line 12 of file ScalarEstimator.cc.
virtual ScalarEstimator::~ScalarEstimator () inline virtual
Virtual destructor.
Definition at line 35 of file ScalarEstimator.h.
Member Function Documentation
void ScalarEstimator::averageOverClones (const MPIManager * mpi) virtual
Average over clones.
Reimplemented from Estimator.
Definition at line 18 of file ScalarEstimator.cc.
References calcValue(), MPIManager::isCloneMain(), reset(), setValue(), and value.
virtual double ScalarEstimator::calcValue () pure virtual
Get the value.
Implemented in VirialEnergyEstimator, EwaldCoulombEstimator, ThermoEnergyEstimator, AngularMomentumEstimator, BondLengthEstimator, BoxEstimator, SpinEstimator, DiamagneticEstimator, PositionEstimator, CoulombEnergyEstimator, DipoleMomentEstimator, and EMARateEstimator.
Referenced by averageOverClones().
double ScalarEstimator::getValue () const inline
Get the value.
Definition at line 39 of file ScalarEstimator.h.
References shift, and value.
Referenced by AsciiReportBuilder::reportScalarStep(), StdoutReportBuilder::reportScalarStep(), and H5ReportBuilder::reportScalarStep().
virtual void ScalarEstimator::reportStep (EstimatorReportBuilder & builder) inline virtual
Callback EstimatorReportBuilder method for scalars.
Reimplemented from Estimator.
Definition at line 50 of file ScalarEstimator.h.
References EstimatorReportBuilder::reportScalarStep().
virtual void ScalarEstimator::reset () pure virtual
Clear the value.
Implemented in VirialEnergyEstimator, EwaldCoulombEstimator, ThermoEnergyEstimator, AngularMomentumEstimator, BondLengthEstimator, BoxEstimator, SpinEstimator, DiamagneticEstimator, PositionEstimator, CoulombEnergyEstimator, DipoleMomentEstimator, and EMARateEstimator.
Referenced by averageOverClones().
void ScalarEstimator::setValue (const double v) inline
Get the value.
Definition at line 41 of file ScalarEstimator.h.
References value.
Referenced by averageOverClones().
virtual void ScalarEstimator::startReport (EstimatorReportBuilder & builder) inline virtual
Callback EstimatorReportBuilder method for scalars.
Reimplemented from Estimator.
Definition at line 47 of file ScalarEstimator.h.
References EstimatorReportBuilder::startScalarReport().
Member Data Documentation
const double ScalarEstimator::scale protected
Scale value.
Definition at line 55 of file ScalarEstimator.h.
const double ScalarEstimator::shift protected
Shift value.
Definition at line 57 of file ScalarEstimator.h.
Referenced by getValue().
double ScalarEstimator::value protected
Reimplemented in DiamagneticEstimator.
Definition at line 53 of file ScalarEstimator.h.
Referenced by averageOverClones(), DipoleMomentEstimator::calcValue(), CoulombEnergyEstimator::calcValue(), PositionEstimator::calcValue(), SpinEstimator::calcValue(), BondLengthEstimator::calcValue(), AngularMomentumEstimator::calcValue(), BoxEstimator::calcValue(), ThermoEnergyEstimator::calcValue(), EwaldCoulombEstimator::calcValue(), VirialEnergyEstimator::calcValue(), getValue(), and setValue().
The documentation for this class was generated from the following files:
ScalarEstimator.h
ScalarEstimator.cc