pi: Path integral Quantum Monte Carlo: SuperCell Class Reference
SuperCell Class Reference
A simple rectangular supercell.
#include <SuperCell.h>
Public Types
typedef blitz::TinyVector
< double, NDIM > Vec
Public Member Functions
SuperCell (const Vec a)
Constructor.
virtual ~SuperCell ()
Virtual destructor.
void computeRecipricalVectors ()
Compute the reciprical lattice vectors.
Vec & pbc (Vec &) const
Set to the smallest displacement with PBC.
double pbc (double dist, int idim) const
smallest displacement along an axis with PBC
virtual std::ostream & write (std::ostream &) const
Write info to an ostream.
double operator[] (const int i) const
Indexed access to box lengths.
Public Attributes
const Vec a
Supercell dimensions.
Vec b
Inverse dimensions.
double rcut2
Cutoff for projecting to smallest vector in pbc method.
Detailed Description
A simple rectangular supercell.
Version:
$Revision$
Author:
John Shumway
Definition at line 31 of file SuperCell.h.
Member Typedef Documentation
typedef blitz::TinyVector<double,NDIM> SuperCell::Vec
Definition at line 33 of file SuperCell.h.
Constructor & Destructor Documentation
SuperCell::SuperCell (const Vec a)
Constructor.
Definition at line 8 of file SuperCell.cc.
References computeRecipricalVectors().
SuperCell::~SuperCell () virtual
Virtual destructor.
Definition at line 12 of file SuperCell.cc.
Member Function Documentation
void SuperCell::computeRecipricalVectors ()
Compute the reciprical lattice vectors.
Set the rcut2 to be the square of half the shortest side.
Definition at line 14 of file SuperCell.cc.
References a, b, and rcut2.
Referenced by SuperCell().
double SuperCell::operator[] (const int i) const inline
Indexed access to box lengths.
Definition at line 54 of file SuperCell.h.
References a.
SuperCell::Vec & SuperCell::pbc (Vec & v) const
Set to the smallest displacement with PBC.
Todo:
May want to improve algorithm here.
Definition at line 25 of file SuperCell.cc.
References a, b, and rcut2.
Referenced by EMARateMover::calculateDiagonalProbability(), EMARateMover::calculateRadiatingProbability(), EMARateMover::calculateTransitionProbability(), AnisotropicNodes::evaluate(), ExcitonNodes::evaluate(), WireNodes::evaluate(), FreeParticleNodes::evaluate(), FreePartNodesNoUpdate::evaluate(), AugmentedNodes::evaluate(), ExcitonNodes::evaluateDistance(), WireNodes::evaluateDistance(), FreeParticleNodes::evaluateDistance(), FreePartNodesNoUpdate::evaluateDistance(), AugmentedNodes::evaluateDistance(), AnisotropicNodes::evaluateDistances(), EMARateEstimator::evaluateElectronBeforeRecombination(), AnisotropicNodes::evaluateGrad(), AugmentedNodes::evaluateGradLogDist(), FreeParticleNodes::evaluateGradLogDist(), EMARateEstimator::evaluateHoleAfterRecombination(), AnisotropicNodes::evaluateUpdate(), FreeParticleNodes::findNormAtr1jnew(), CoulombAction::getActionDifference(), PrimColloidalAction::getActionDifference(), GrapheneAction::getActionDifference(), RingGateAction::getActionDifference(), GaussianDotAction::getActionDifference(), EwaldImagePairAction::getActionDifference(), GateAction::getActionDifference(), GaussianAction::getActionDifference(), PrimImageAction::getActionDifference(), PrimTorusAction::getActionDifference(), GroundStateWFNodes::getActionDifference(), OpticalLatticeAction::getActionDifference(), PrimAnisSHOAction::getActionDifference(), PrimShellAction::getActionDifference(), PrimSHOAction::getActionDifference(), SphereAction::getActionDifference(), SHODotAction::getActionDifference(), SpringTensorAction::getActionDifference(), TimpQPC::getActionDifference(), GridPotential::getActionDifference(), DotGeomAction::getActionDifference(), PrimCosineAction::getActionDifference(), EFieldAction::getActionDifference(), SpringAction::getActionDifference(), HyperbolicAction::getActionDifference(), StillWebAction::getActionDifference(), ImagePairAction::getActionDifference(), SmoothedGridPotential::getActionDifference(), JelliumSlab::getActionDifference(), PairAction::getActionDifference(), FixedNodeAction::getActionDifference(), WellImageAction::getActionDifference(), EFieldAction::getBeadAction(), StillWebAction::getBeadAction(), ImagePairAction::getBeadAction(), PairAction::getBeadAction(), WellImageAction::getBeadAction(), FreePartNodesNoUpdate::getBeadAction(), FreeParticleNodes::getDetAtrnew(), FreeParticleNodes::getMaxDist2(), SHODotAction::getSemiClassicalAction(), CoulombEnergyEstimator::handleLink(), WindingEstimator::handleLink(), BondLengthEstimator::handleLink(), EwaldCoulombEstimator::handleLink(), VirialEnergyEstimator::handleLink(), ConductanceEstimator::handleLink(), ZeroVarDensityEstimator::handleLink(), FreeParticleNodes::newtonRaphson(), PairRadial::operator()(), PairCart::operator()(), FreeParticleNodes::plotNRPoints(), RingLattice::run(), CubicLattice::run(), and EMARateMover::sampleDiagonal().
double SuperCell::pbc (double dist, int idim) const
smallest displacement along an axis with PBC
Definition at line 36 of file SuperCell.cc.
References a, and b.
std::ostream & SuperCell::write (std::ostream & os) const virtual
Write info to an ostream.
Definition at line 46 of file SuperCell.cc.
References a.
Referenced by operator<<().
Member Data Documentation
const Vec SuperCell::a
Supercell dimensions.
Definition at line 48 of file SuperCell.h.
Referenced by AnisotropicNodes::AnisotropicNodes(), AugmentedNodes::AugmentedNodes(), computeRecipricalVectors(), CoulombAction::CoulombAction(), EFieldAction::EFieldAction(), ExcitonNodes::ExcitonNodes(), FreeParticleNodes::FreeParticleNodes(), ImagePairAction::getActionDifference(), ImagePairAction::getBeadAction(), operator[](), PIMCParser::parseAlgorithm(), pbc(), FreeParticleNodes::plotRho2D(), EwaldCoulombEstimator::testEwaldTotalCharge(), WireEwald::WireEwald(), WireNodes::WireNodes(), and write().
Vec SuperCell::b
Inverse dimensions.
Definition at line 50 of file SuperCell.h.
Referenced by computeRecipricalVectors(), WindingEstimator::endCalc(), and pbc().
double SuperCell::rcut2
Cutoff for projecting to smallest vector in pbc method.
Definition at line 52 of file SuperCell.h.
Referenced by computeRecipricalVectors(), and pbc().
The documentation for this class was generated from the following files:
SuperCell.h
SuperCell.cc