pi: Path integral Quantum Monte Carlo: CollectiveSectionMover Class Reference
CollectiveSectionMover Class Reference
#include <CollectiveSectionMover.h>
Public Types
typedef blitz::TinyVector
< double, NDIM > Vec
typedef blitz::TinyVector< int,
NDIM > IVec
typedef blitz::TinyMatrix
< double, NDIM, NDIM > Mat
Public Member Functions
CollectiveSectionMover (SuperCell *cell)
~CollectiveSectionMover ()
double makeMove (CollectiveSectionSampler &)
Vec calcShift (const Vec &, int sliceIndex) const
Vec calcInverseShift (const Vec &, int sliceIndex) const
Mat calcJacobian (const Vec &, int sliceIndex) const
double calcJacobianDet (const Mat &)
void setAmplitude (Vec amplitude)
Vec getAmplitude () const
void setRadius (double radius)
void setCenter (Vec center)
double getRadius () const
void setSliceCount (int)
int getSliceCount () const
Vec getCenter () const
Private Member Functions
Vec calcDisplacement (const Vec &, int sliceIndex) const
double timeEnvelope (int sliceIndex) const
bool isOutsideRadius (const Vec &rin) const
Private Attributes
double radius
Vec amplitude
Vec center
int sliceCount
SuperCell * cell
Detailed Description
Definition at line 14 of file CollectiveSectionMover.h.
Member Typedef Documentation
typedef blitz::TinyVector<int, NDIM> CollectiveSectionMover::IVec
Definition at line 17 of file CollectiveSectionMover.h.
typedef blitz::TinyMatrix<double, NDIM, NDIM> CollectiveSectionMover::Mat
Definition at line 18 of file CollectiveSectionMover.h.
typedef blitz::TinyVector<double, NDIM> CollectiveSectionMover::Vec
Definition at line 16 of file CollectiveSectionMover.h.
Constructor & Destructor Documentation
CollectiveSectionMover::CollectiveSectionMover (SuperCell * cell)
Definition at line 16 of file CollectiveSectionMover.cc.
References amplitude, center, radius, and sliceCount.
CollectiveSectionMover::~CollectiveSectionMover ()
Definition at line 24 of file CollectiveSectionMover.cc.
Member Function Documentation
CollectiveSectionMover::Vec CollectiveSectionMover::calcDisplacement (const Vec & rin, int sliceIndex) const inline private
Definition at line 60 of file CollectiveSectionMover.cc.
References amplitude, cell, center, isOutsideRadius(), SuperCell::pbc(), radius, and timeEnvelope().
Referenced by calcInverseShift(), and calcShift().
CollectiveSectionMover::Vec CollectiveSectionMover::calcInverseShift (const Vec & rin, int sliceIndex) const
Calculate the inverse shift by Newton iteration.
Definition at line 87 of file CollectiveSectionMover.cc.
References calcDisplacement(), calcJacobian(), calcShift(), cell, DGESV_F77, isOutsideRadius(), and SuperCell::pbc().
Referenced by makeMove().
CollectiveSectionMover::Mat CollectiveSectionMover::calcJacobian (const Vec & rin, int sliceIndex) const
Definition at line 135 of file CollectiveSectionMover.cc.
References amplitude, cell, center, isOutsideRadius(), SuperCell::pbc(), radius, and timeEnvelope().
Referenced by calcInverseShift(), and makeMove().
double CollectiveSectionMover::calcJacobianDet (const Mat & jacobian)
Definition at line 156 of file CollectiveSectionMover.cc.
Referenced by makeMove().
CollectiveSectionMover::Vec CollectiveSectionMover::calcShift (const Vec & rin, int sliceIndex) const
Definition at line 80 of file CollectiveSectionMover.cc.
References calcDisplacement(), cell, and SuperCell::pbc().
Referenced by calcInverseShift(), and makeMove().
CollectiveSectionMover::Vec CollectiveSectionMover::getAmplitude () const
Definition at line 177 of file CollectiveSectionMover.cc.
References amplitude.
CollectiveSectionMover::Vec CollectiveSectionMover::getCenter () const
Definition at line 201 of file CollectiveSectionMover.cc.
References center.
double CollectiveSectionMover::getRadius () const
Definition at line 181 of file CollectiveSectionMover.cc.
References radius.
int CollectiveSectionMover::getSliceCount () const
Definition at line 189 of file CollectiveSectionMover.cc.
References sliceCount.
bool CollectiveSectionMover::isOutsideRadius (const Vec & rin) const inline private
Definition at line 74 of file CollectiveSectionMover.cc.
References cell, center, SuperCell::pbc(), and radius.
Referenced by calcDisplacement(), calcInverseShift(), and calcJacobian().
double CollectiveSectionMover::makeMove (CollectiveSectionSampler & sampler)
Definition at line 27 of file CollectiveSectionMover.cc.
References calcInverseShift(), calcJacobian(), calcJacobianDet(), calcShift(), cell, center, CollectiveSectionSampler::getMovingBeads(), Beads< TDIM >::getNPart(), Beads< TDIM >::getNSlice(), RandomNumGenerator::getRand(), CollectiveSectionSampler::getSectionBeads(), SuperCell::pbc(), and sliceCount.
Referenced by DoubleCollectiveSectionSampler::tryMove(), and CollectiveSectionSampler::tryMove().
void CollectiveSectionMover::setAmplitude (Vec amplitude)
Definition at line 185 of file CollectiveSectionMover.cc.
References amplitude.
Referenced by PIMCParser::parseAlgorithm().
void CollectiveSectionMover::setCenter (Vec center)
Definition at line 205 of file CollectiveSectionMover.cc.
References center.
void CollectiveSectionMover::setRadius (double radius)
Definition at line 197 of file CollectiveSectionMover.cc.
References radius.
Referenced by PIMCParser::parseAlgorithm().
void CollectiveSectionMover::setSliceCount (int count)
Definition at line 193 of file CollectiveSectionMover.cc.
References sliceCount.
double CollectiveSectionMover::timeEnvelope (int sliceIndex) const inline private
Definition at line 54 of file CollectiveSectionMover.cc.
References sliceCount.
Referenced by calcDisplacement(), and calcJacobian().
Member Data Documentation
Vec CollectiveSectionMover::amplitude private
Definition at line 46 of file CollectiveSectionMover.h.
Referenced by calcDisplacement(), calcJacobian(), CollectiveSectionMover(), getAmplitude(), and setAmplitude().
SuperCell* CollectiveSectionMover::cell private
Definition at line 49 of file CollectiveSectionMover.h.
Referenced by calcDisplacement(), calcInverseShift(), calcJacobian(), calcShift(), isOutsideRadius(), and makeMove().
Vec CollectiveSectionMover::center private
Definition at line 47 of file CollectiveSectionMover.h.
Referenced by calcDisplacement(), calcJacobian(), CollectiveSectionMover(), getCenter(), isOutsideRadius(), makeMove(), and setCenter().
double CollectiveSectionMover::radius private
Definition at line 45 of file CollectiveSectionMover.h.
Referenced by calcDisplacement(), calcJacobian(), CollectiveSectionMover(), getRadius(), isOutsideRadius(), and setRadius().
int CollectiveSectionMover::sliceCount private
Definition at line 48 of file CollectiveSectionMover.h.
Referenced by CollectiveSectionMover(), getSliceCount(), makeMove(), setSliceCount(), and timeEnvelope().
The documentation for this class was generated from the following files:
CollectiveSectionMover.h
CollectiveSectionMover.cc