pi: Path integral Quantum Monte Carlo: EnumeratedModelState Class Reference
EnumeratedModelState Class Reference
Base class for model state.
#include <EnumeratedModelState.h>
Public Member Functions
EnumeratedModelState (int modelCount)
virtual ~EnumeratedModelState ()
virtual void write (std::ostream &os) const
virtual bool read (const std::string &line)
void setModelState (int i)
virtual int getModelCount () const
virtual int getModelState () const
virtual void broadcastToMPIWorkers (const MPIManager *mpi)
Public Member Functions inherited from ModelState
virtual ~ModelState ()
virtual bool isSpinModelState ()
Private Attributes
const int modelCount
int modelState
Detailed Description
Base class for model state.
Version:
Revision:
338
Author:
John Shumway and Jianheng Liu
Definition at line 25 of file EnumeratedModelState.h.
Constructor & Destructor Documentation
EnumeratedModelState::EnumeratedModelState (int modelCount)
Definition at line 27 of file EnumeratedModelState.cc.
virtual EnumeratedModelState::~EnumeratedModelState () inline virtual
Definition at line 28 of file EnumeratedModelState.h.
Member Function Documentation
void EnumeratedModelState::broadcastToMPIWorkers (const MPIManager * mpi) virtual
Reimplemented from ModelState.
Definition at line 53 of file EnumeratedModelState.cc.
References modelState.
Referenced by ActionParser::parseActions(), and ModelSampler::tryMove().
virtual int EnumeratedModelState::getModelCount () const inline virtual
Implements ModelState.
Definition at line 32 of file EnumeratedModelState.h.
References modelCount.
virtual int EnumeratedModelState::getModelState () const inline virtual
Implements ModelState.
Definition at line 33 of file EnumeratedModelState.h.
References modelState.
Referenced by DoubleActionChoice::acceptLastMove(), ActionChoice::acceptLastMove(), DoubleActionChoice::getActionDifference(), ActionChoice::getActionDifference(), DoubleActionChoice::getBeadAction(), ActionChoice::getBeadAction(), DoubleActionChoice::getTotalAction(), ActionChoice::getTotalAction(), DoubleActionChoice::handleLink(), ActionChoice::handleLink(), DoubleActionChoice::initialize(), ActionChoice::initialize(), and ModelSampler::tryMove().
bool EnumeratedModelState::read (const std::string & line) virtual
Implements ModelState.
Definition at line 35 of file EnumeratedModelState.cc.
References modelState.
void EnumeratedModelState::setModelState (int i) inline
Definition at line 31 of file EnumeratedModelState.h.
References modelState.
Referenced by ActionParser::parseActions(), and ModelSampler::tryMove().
void EnumeratedModelState::write (std::ostream & os) const virtual
Implements ModelState.
Definition at line 31 of file EnumeratedModelState.cc.
References modelCount, and modelState.
Member Data Documentation
const int EnumeratedModelState::modelCount private
Definition at line 36 of file EnumeratedModelState.h.
Referenced by getModelCount(), and write().
int EnumeratedModelState::modelState private
Definition at line 37 of file EnumeratedModelState.h.
Referenced by broadcastToMPIWorkers(), getModelState(), read(), setModelState(), and write().
The documentation for this class was generated from the following files:
EnumeratedModelState.h
EnumeratedModelState.cc