pi: Path integral Quantum Monte Carlo: DoubleDisplaceMoveSampler Class Reference
DoubleDisplaceMoveSampler Class Reference
Class to perform classical displacements of the particles.
#include <DoubleDisplaceMoveSampler.h>
Public Types
typedef blitz::Array< int, 1 > IArray
typedef blitz::TinyVector
< double, NDIM > Vec
typedef blitz::Array< Vec, 1 > VArray
Public Types inherited from DisplaceMoveSampler
Public Member Functions
DoubleDisplaceMoveSampler (const int nmoving, const int nrepeat, Paths &, ParticleChooser &, const UniformMover &, Action *, DoubleAction *, const MPIManager *mpi)
Constructor.
virtual ~DoubleDisplaceMoveSampler ()
Destructor.
Public Member Functions inherited from DisplaceMoveSampler
DisplaceMoveSampler (const int nmoving, const int nrepeat, Paths &, ParticleChooser &, const UniformMover &, Action *, const MPIManager *mpi)
Constructor.
virtual ~DisplaceMoveSampler ()
Destructor.
virtual void run ()
Run method, performs nrepeat samplings with probability ifreq.
virtual AccRejEstimator * getAccRejEstimator (const std::string &name)
Get a pointer to the accept/reject statistic estimator.
Permutation getGlobalPermutation ()
void handleBoundary (int bd1, int bd2, int sign)
Public Member Functions inherited from Algorithm
virtual ~Algorithm ()
Protected Member Functions
virtual bool tryMove ()
Method to atempt a Monte Carlo move, return true if accepted.
Protected Attributes
DoubleAction * doubleAction
Pointer to the double action.
const int nsliceOver2
Flag for double paths.
Protected Attributes inherited from DisplaceMoveSampler
const int nmoving
The number of particles to move together.
const int nrepeat
The number of times to try dispace moves.
const int npart
The number of particles.
int iFirstSlice
The first slice this worker is moving.
int iLastSlice
The last slice this worker is moving.
VArray displacement
The dispalcement of the moving particles in a particular attempt.
IArray movingIndex
Index of the particles to be moved.
ParticleChooser & particleChooser
Helper class to choose the particles to move.
const UniformMover & mover
Helper class to choose the displacement.
Paths & paths
A reference to the paths.
const SuperCell & cell
A reference to the simulation super cell.
Action * action
The action to be evaluated during the move.
AccRejEstimator * accRejEst
A pointer to the accept-reject estimator.
const MPIManager * mpi
A pointer to the MPI manager, zero if MPI is not used.
const int nworker
blitz::Array< int, 2 > iworkerPerm
Detailed Description
Class to perform classical displacements of the particles.
Author:
Saad Khairallah, John Shumway
Definition at line 14 of file DoubleDisplaceMoveSampler.h.
Member Typedef Documentation
typedef blitz::Array<int, 1> DoubleDisplaceMoveSampler::IArray
Reimplemented from DisplaceMoveSampler.
Definition at line 16 of file DoubleDisplaceMoveSampler.h.
typedef blitz::Array<Vec, 1> DoubleDisplaceMoveSampler::VArray
Reimplemented from DisplaceMoveSampler.
Definition at line 18 of file DoubleDisplaceMoveSampler.h.
typedef blitz::TinyVector<double, NDIM> DoubleDisplaceMoveSampler::Vec
Reimplemented from DisplaceMoveSampler.
Definition at line 17 of file DoubleDisplaceMoveSampler.h.
Constructor & Destructor Documentation
DoubleDisplaceMoveSampler::DoubleDisplaceMoveSampler (const int nmoving, const int nrepeat, Paths & paths, ParticleChooser & particleChooser, const UniformMover & mover, Action * action, DoubleAction * doubleAction, const MPIManager * mpi)
Constructor.
Definition at line 23 of file DoubleDisplaceMoveSampler.cc.
References Paths::getHighestOwnedSlice(), Paths::getLowestOwnedSlice(), DisplaceMoveSampler::iFirstSlice, DisplaceMoveSampler::iLastSlice, and nsliceOver2.
DoubleDisplaceMoveSampler::~DoubleDisplaceMoveSampler () virtual
Destructor.
Definition at line 40 of file DoubleDisplaceMoveSampler.cc.
Member Function Documentation
bool DoubleDisplaceMoveSampler::tryMove () protected virtual
Method to atempt a Monte Carlo move, return true if accepted.
Reimplemented from DisplaceMoveSampler.
Definition at line 43 of file DoubleDisplaceMoveSampler.cc.
References Action::acceptLastMove(), DisplaceMoveSampler::accRejEst, DisplaceMoveSampler::action, DisplaceMoveSampler::cell, DisplaceMoveSampler::displacement, doubleAction, DoubleAction::getActionDifference(), Action::getActionDifference(), MPIManager::getNWorker(), RandomNumGenerator::getRand(), MPIManager::getWorkerID(), DisplaceMoveSampler::handleBoundary(), DisplaceMoveSampler::iFirstSlice, DisplaceMoveSampler::iLastSlice, UniformMover::makeMove(), AccRejEstimator::moveAccepted(), DisplaceMoveSampler::mover, DisplaceMoveSampler::movingIndex, DisplaceMoveSampler::mpi, DisplaceMoveSampler::nmoving, nsliceOver2, DisplaceMoveSampler::nworker, DisplaceMoveSampler::paths, SuperCell::pbc(), and AccRejEstimator::tryingMove().
Member Data Documentation
DoubleAction* DoubleDisplaceMoveSampler::doubleAction protected
Pointer to the double action.
Definition at line 27 of file DoubleDisplaceMoveSampler.h.
Referenced by tryMove().
const int DoubleDisplaceMoveSampler::nsliceOver2 protected
Flag for double paths.
Half the total slices.
Definition at line 31 of file DoubleDisplaceMoveSampler.h.
Referenced by DoubleDisplaceMoveSampler(), and tryMove().
The documentation for this class was generated from the following files:
DoubleDisplaceMoveSampler.h
DoubleDisplaceMoveSampler.cc