pi: Path integral Quantum Monte Carlo: ParticleChooser Class Reference
ParticleChooser Class Reference
Base class for algorithms for choosing particles to move.
#include <ParticleChooser.h>
Public Types
typedef blitz::Array< int, 1 > IArray
Public Member Functions
ParticleChooser (const int npart)
virtual ~ParticleChooser ()
virtual void chooseParticles ()=0
int operator[] (const int i) const
std::string & getName ()
Protected Attributes
IArray index
std::string name
Detailed Description
Base class for algorithms for choosing particles to move.
Definition at line 9 of file ParticleChooser.h.
Member Typedef Documentation
typedef blitz::Array<int, 1> ParticleChooser::IArray
Reimplemented in EMARateMover, WalkingChooser, SpinStatePermutationChooser, and MultiSpeciesParticleChooser.
Definition at line 11 of file ParticleChooser.h.
Constructor & Destructor Documentation
ParticleChooser::ParticleChooser (const int npart)
Definition at line 5 of file ParticleChooser.cc.
References index.
virtual ParticleChooser::~ParticleChooser () inline virtual
Definition at line 15 of file ParticleChooser.h.
Member Function Documentation
virtual void ParticleChooser::chooseParticles () pure virtual
Implemented in EMARateMover, WalkingChooser, PairChooser, MultiSpeciesParticleChooser, AlternatingParticleChooser, TwoPairChooser, SpeciesParticleChooser, and SimpleParticleChooser.
Referenced by DoubleMLSampler::run(), DisplaceMoveSampler::run(), and MultiLevelSampler::run().
std::string& ParticleChooser::getName () inline
Definition at line 24 of file ParticleChooser.h.
References name.
Referenced by DisplaceMoveSampler::getAccRejEstimator(), DoubleMLSampler::getAccRejEstimator(), and MultiLevelSampler::getAccRejEstimator().
int ParticleChooser::operator[] (const int i) const inline
Definition at line 20 of file ParticleChooser.h.
References index.
Member Data Documentation
IArray ParticleChooser::index protected
Definition at line 28 of file ParticleChooser.h.
Referenced by SimpleParticleChooser::chooseParticles(), SpeciesParticleChooser::chooseParticles(), TwoPairChooser::chooseParticles(), AlternatingParticleChooser::chooseParticles(), MultiSpeciesParticleChooser::chooseParticles(), PairChooser::choosePermutation(), WalkingChooser::choosePermutation(), operator[](), and ParticleChooser().
std::string ParticleChooser::name protected
Definition at line 29 of file ParticleChooser.h.
Referenced by getName(), and SpeciesParticleChooser::SpeciesParticleChooser().
The documentation for this class was generated from the following files:
ParticleChooser.h
ParticleChooser.cc