pi: Path integral Quantum Monte Carlo: SectionSamplerInterface Class Reference
SectionSamplerInterface Class Reference
#include <SectionSamplerInterface.h>
Public Types
typedef blitz::Array< int, 1 > IArray
Public Member Functions
virtual ~SectionSamplerInterface ()
virtual const Beads< NDIM > & getSectionBeads () const =0
virtual const Beads< NDIM > & getSectionBeads (const int) const =0
virtual const Beads< NDIM > & getMovingBeads () const =0
virtual const Beads< NDIM > & getMovingBeads (const int) const =0
virtual Beads< NDIM > & getSectionBeads ()=0
virtual Beads< NDIM > & getSectionBeads (int)=0
virtual Beads< NDIM > & getMovingBeads ()=0
virtual Beads< NDIM > & getMovingBeads (int)=0
virtual const IArray & getMovingIndex () const =0
virtual const IArray & getMovingIndex (const int) const =0
virtual int getFirstSliceIndex () const =0
virtual const SuperCell & getSuperCell () const =0
virtual bool isSamplingBoth () const =0
Detailed Description
Definition at line 12 of file SectionSamplerInterface.h.
Member Typedef Documentation
typedef blitz::Array<int, 1> SectionSamplerInterface::IArray
Reimplemented in MultiLevelSampler.
Definition at line 14 of file SectionSamplerInterface.h.
Constructor & Destructor Documentation
virtual SectionSamplerInterface::~SectionSamplerInterface () inline virtual
Definition at line 15 of file SectionSamplerInterface.h.
Member Function Documentation
virtual int SectionSamplerInterface::getFirstSliceIndex () const pure virtual
Implemented in CollectiveSectionSampler, and MultiLevelSampler.
Referenced by EMARateAction::isCenteredOnSliceZero().
virtual const Beads<NDIM>& SectionSamplerInterface::getMovingBeads () const pure virtual
Implemented in MultiLevelSampler, and CollectiveSectionSampler.
Referenced by WireNodes::MatrixUpdate::evaluateChange(), FreeParticleNodes::MatrixUpdate::evaluateChange(), AugmentedNodes::MatrixUpdate::evaluateChange(), CoulombAction::getActionDifference(), PrimColloidalAction::getActionDifference(), GrapheneAction::getActionDifference(), RingGateAction::getActionDifference(), GaussianDotAction::getActionDifference(), EwaldImagePairAction::getActionDifference(), EMARateAction::getActionDifference(), GateAction::getActionDifference(), GaussianAction::getActionDifference(), GroundStateWFNodes::getActionDifference(), OpticalLatticeAction::getActionDifference(), TwoQDAction::getActionDifference(), PrimAnisSHOAction::getActionDifference(), PrimShellAction::getActionDifference(), PrimSHOAction::getActionDifference(), PrimTorusAction::getActionDifference(), SHODotAction::getActionDifference(), SphereAction::getActionDifference(), GridPotential::getActionDifference(), SpringTensorAction::getActionDifference(), DotGeomAction::getActionDifference(), PrimCosineAction::getActionDifference(), EFieldAction::getActionDifference(), SpringAction::getActionDifference(), QPCAction::getActionDifference(), AnisotropicNodes::getActionDifference(), SpinAction::getActionDifference(), TimpQPC::getActionDifference(), HyperbolicAction::getActionDifference(), StillWebAction::getActionDifference(), SHOAction::getActionDifference(), ImagePairAction::getActionDifference(), JelliumSlab::getActionDifference(), SmoothedGridPotential::getActionDifference(), PairAction::getActionDifference(), FixedNodeAction::getActionDifference(), FixedPhaseAction::getActionDifference(), SpinFixedPhaseAction::getActionDifference(), WellImageAction::getActionDifference(), and FreePartNodesNoUpdate::getActionDifference().
virtual const Beads<NDIM>& SectionSamplerInterface::getMovingBeads (const int) const pure virtual
Implemented in MultiLevelSampler, CollectiveSectionSampler, DoubleMLSampler, and DoubleCollectiveSectionSampler.
virtual Beads<NDIM>& SectionSamplerInterface::getMovingBeads () pure virtual
Implemented in MultiLevelSampler, and CollectiveSectionSampler.
virtual Beads<NDIM>& SectionSamplerInterface::getMovingBeads (int) pure virtual
Implemented in MultiLevelSampler, CollectiveSectionSampler, DoubleMLSampler, and DoubleCollectiveSectionSampler.
virtual const IArray& SectionSamplerInterface::getMovingIndex () const pure virtual
Implemented in MultiLevelSampler, and CollectiveSectionSampler.
Referenced by WireNodes::MatrixUpdate::evaluateChange(), FreeParticleNodes::MatrixUpdate::evaluateChange(), AugmentedNodes::MatrixUpdate::evaluateChange(), CoulombAction::getActionDifference(), PrimColloidalAction::getActionDifference(), GrapheneAction::getActionDifference(), RingGateAction::getActionDifference(), GaussianDotAction::getActionDifference(), EwaldImagePairAction::getActionDifference(), EMARateAction::getActionDifference(), GateAction::getActionDifference(), GaussianAction::getActionDifference(), GroundStateWFNodes::getActionDifference(), OpticalLatticeAction::getActionDifference(), TwoQDAction::getActionDifference(), PrimAnisSHOAction::getActionDifference(), PrimShellAction::getActionDifference(), PrimSHOAction::getActionDifference(), PrimTorusAction::getActionDifference(), SHODotAction::getActionDifference(), SphereAction::getActionDifference(), GridPotential::getActionDifference(), SpringTensorAction::getActionDifference(), DotGeomAction::getActionDifference(), PrimCosineAction::getActionDifference(), EFieldAction::getActionDifference(), SpringAction::getActionDifference(), QPCAction::getActionDifference(), AnisotropicNodes::getActionDifference(), SpinAction::getActionDifference(), TimpQPC::getActionDifference(), HyperbolicAction::getActionDifference(), StillWebAction::getActionDifference(), SHOAction::getActionDifference(), ImagePairAction::getActionDifference(), JelliumSlab::getActionDifference(), SmoothedGridPotential::getActionDifference(), PairAction::getActionDifference(), FixedNodeAction::getActionDifference(), FixedPhaseAction::getActionDifference(), SpinFixedPhaseAction::getActionDifference(), WellImageAction::getActionDifference(), and FreePartNodesNoUpdate::getActionDifference().
virtual const IArray& SectionSamplerInterface::getMovingIndex (const int) const pure virtual
Implemented in MultiLevelSampler, CollectiveSectionSampler, DoubleMLSampler, and DoubleCollectiveSectionSampler.
virtual const Beads<NDIM>& SectionSamplerInterface::getSectionBeads () const pure virtual
Implemented in MultiLevelSampler, and CollectiveSectionSampler.
Referenced by WireNodes::MatrixUpdate::evaluateChange(), FreeParticleNodes::MatrixUpdate::evaluateChange(), AugmentedNodes::MatrixUpdate::evaluateChange(), CoulombAction::getActionDifference(), PrimColloidalAction::getActionDifference(), GrapheneAction::getActionDifference(), RingGateAction::getActionDifference(), GaussianDotAction::getActionDifference(), EwaldImagePairAction::getActionDifference(), EMARateAction::getActionDifference(), GateAction::getActionDifference(), GaussianAction::getActionDifference(), GroundStateWFNodes::getActionDifference(), OpticalLatticeAction::getActionDifference(), TwoQDAction::getActionDifference(), PrimAnisSHOAction::getActionDifference(), PrimShellAction::getActionDifference(), PrimSHOAction::getActionDifference(), PrimTorusAction::getActionDifference(), SHODotAction::getActionDifference(), SphereAction::getActionDifference(), GridPotential::getActionDifference(), SpringTensorAction::getActionDifference(), DotGeomAction::getActionDifference(), PrimCosineAction::getActionDifference(), EFieldAction::getActionDifference(), SpringAction::getActionDifference(), QPCAction::getActionDifference(), AnisotropicNodes::getActionDifference(), SpinAction::getActionDifference(), TimpQPC::getActionDifference(), HyperbolicAction::getActionDifference(), StillWebAction::getActionDifference(), SHOAction::getActionDifference(), ImagePairAction::getActionDifference(), JelliumSlab::getActionDifference(), SmoothedGridPotential::getActionDifference(), PairAction::getActionDifference(), FixedNodeAction::getActionDifference(), FixedPhaseAction::getActionDifference(), SpinFixedPhaseAction::getActionDifference(), WellImageAction::getActionDifference(), and FreePartNodesNoUpdate::getActionDifference().
virtual const Beads<NDIM>& SectionSamplerInterface::getSectionBeads (const int) const pure virtual
Implemented in MultiLevelSampler, DoubleMLSampler, DoubleCollectiveSectionSampler, and CollectiveSectionSampler.
virtual Beads<NDIM>& SectionSamplerInterface::getSectionBeads () pure virtual
Implemented in MultiLevelSampler, and CollectiveSectionSampler.
virtual Beads<NDIM>& SectionSamplerInterface::getSectionBeads (int) pure virtual
Implemented in MultiLevelSampler, DoubleMLSampler, DoubleCollectiveSectionSampler, and CollectiveSectionSampler.
virtual const SuperCell& SectionSamplerInterface::getSuperCell () const pure virtual
Implemented in MultiLevelSampler, and CollectiveSectionSampler.
Referenced by PrimColloidalAction::getActionDifference(), GrapheneAction::getActionDifference(), RingGateAction::getActionDifference(), EwaldImagePairAction::getActionDifference(), GaussianDotAction::getActionDifference(), GateAction::getActionDifference(), GaussianAction::getActionDifference(), EMARateAction::getActionDifference(), GroundStateWFNodes::getActionDifference(), PrimShellAction::getActionDifference(), PrimSHOAction::getActionDifference(), PrimTorusAction::getActionDifference(), OpticalLatticeAction::getActionDifference(), PrimAnisSHOAction::getActionDifference(), SHODotAction::getActionDifference(), SphereAction::getActionDifference(), SpringTensorAction::getActionDifference(), GridPotential::getActionDifference(), DotGeomAction::getActionDifference(), PrimCosineAction::getActionDifference(), SpringAction::getActionDifference(), HyperbolicAction::getActionDifference(), StillWebAction::getActionDifference(), ImagePairAction::getActionDifference(), JelliumSlab::getActionDifference(), SmoothedGridPotential::getActionDifference(), and PairAction::getActionDifference().
virtual bool SectionSamplerInterface::isSamplingBoth () const pure virtual
Implemented in MultiLevelSampler, CollectiveSectionSampler, DoubleMLSampler, and DoubleCollectiveSectionSampler.
Referenced by FixedNodeAction::getActionDifference(), FixedPhaseAction::getActionDifference(), SpinFixedPhaseAction::getActionDifference(), and FreePartNodesNoUpdate::getActionDifference().
The documentation for this class was generated from the following file:
SectionSamplerInterface.h