pi: Path integral Quantum Monte Carlo: SimInfoParser Class Reference
SimInfoParser Class Reference
Class for parsing xml data into a SimulationInfo object.
#include <SimInfoParser.h>
Public Types
typedef blitz::TinyVector
< double, NDIM > Vec
Public Member Functions
SimInfoParser ()
Constructor.
virtual ~SimInfoParser ()
Virtual destructor.
virtual void parse (const xmlXPathContextPtr &ctxt)
Parse some xml, storing the results in simulation info.
SimulationInfo & getSimInfo ()
Get a reference to the simulation info, that remains valid until the parse method is called again.
Private Attributes
SimulationInfo * simInfo
The simulation info.
Private Attributes inherited from XMLUnitParser
const Units * units
Information about the units and conversions.
double value
The most recently parsed value.
std::string unit
The most recently parsed unit name.
Additional Inherited Members
Private Member Functions inherited from XMLUnitParser
XMLUnitParser (const Units *)
Constructor.
virtual ~XMLUnitParser ()
Destructor.
double getEnergyAttribute (const xmlNodePtr &node, const std::string &attName)
Parse a length with unit conversion.
double getLengthAttribute (const xmlNodePtr &node, const std::string &attName)
Parse a energy with unit conversion.
double getTimeAttribute (const xmlNodePtr &node, const std::string &attName)
Parse an inverse energy with unit conversion.
double getInvLengthAttribute (const xmlNodePtr &node, const std::string &attName)
Parse an inverse length with unit conversion.
double getDensityAttribute (const xmlNodePtr &node, const std::string &attName)
Parse a density with unit conversion.
double getMassAttribute (const xmlNodePtr &node, const std::string &attName)
double getFieldStrengthAttribute (const xmlNodePtr &node, const std::string &attName)
Parse a field strength with unit conversion.
void parseUnitAndValue (const xmlNodePtr &node, const std::string &attName)
Internal method to parse a unit and value.
Private Member Functions inherited from XMLParser
virtual ~XMLParser ()
Destructor.
Detailed Description
Class for parsing xml data into a SimulationInfo object.
Version:
$Revision$
Author:
John Shumway
Definition at line 28 of file SimInfoParser.h.
Member Typedef Documentation
typedef blitz::TinyVector<double,NDIM> SimInfoParser::Vec
Reimplemented from XMLParser.
Definition at line 30 of file SimInfoParser.h.
Constructor & Destructor Documentation
SimInfoParser::SimInfoParser () inline
Constructor.
Definition at line 32 of file SimInfoParser.h.
SimInfoParser::~SimInfoParser () virtual
Virtual destructor.
Definition at line 12 of file SimInfoParser.cc.
References simInfo.
Member Function Documentation
SimulationInfo& SimInfoParser::getSimInfo () inline
Get a reference to the simulation info, that remains valid until the parse method is called again.
Definition at line 39 of file SimInfoParser.h.
References simInfo.
Referenced by MainParser::parse().
void SimInfoParser::parse (const xmlXPathContextPtr & ctxt) virtual
Parse some xml, storing the results in simulation info.
Reimplemented from XMLParser.
Definition at line 16 of file SimInfoParser.cc.
References XMLParser::getBoolAttribute(), XMLParser::getDoubleAttribute(), XMLUnitParser::getEnergyAttribute(), XMLParser::getIntAttribute(), XMLUnitParser::getLengthAttribute(), XMLUnitParser::getMassAttribute(), XMLParser::getStringAttribute(), XMLUnitParser::getTimeAttribute(), XMLParser::getVecAttribute(), simInfo, and XMLUnitParser::units.
Referenced by MainParser::parse().
Member Data Documentation
SimulationInfo* SimInfoParser::simInfo private
The simulation info.
Definition at line 42 of file SimInfoParser.h.
Referenced by getSimInfo(), parse(), and ~SimInfoParser().
The documentation for this class was generated from the following files:
SimInfoParser.h
SimInfoParser.cc