pi: Path integral Quantum Monte Carlo: EFieldAction Class Reference
EFieldAction Class Reference
Class for getting action from stepwise electric field.
#include <EFieldAction.h>
Public Types
typedef blitz::Array< double, 1 > Array
Typedefs.
typedef blitz::Array< int, 1 > IArray
typedef blitz::TinyVector
< double, NDIM > Vec
Public Types inherited from Action
typedef blitz::Array< Vec, 1 > VArray
Public Member Functions
EFieldAction (const SimulationInfo &simInfo, double strength, double center, double width, int idir)
Construct by providing SimulationInfo, field strength in atomic units , physical region center and width, and direction index.
virtual ~EFieldAction ()
Virtual destructor.
virtual double getActionDifference (const SectionSamplerInterface &, int level)
Calculate the difference in action.
virtual double getActionDifference (const Paths &, const VArray &displacement, int nmoving, const IArray &movingIndex, int iFirstSlice, int iLastSlice)
Calculate the difference in action.
virtual double getTotalAction (const Paths &, const int level) const
Calculate the total action.
virtual void getBeadAction (const Paths &, const int ipart, const int islice, double &u, double &utau, double &ulambda, Vec &fm, Vec &fp) const
Calculate the and derivatives at a bead.
Public Member Functions inherited from Action
virtual ~Action ()
virtual void initialize (const SectionChooser &)
Initialize for a sampling section.
virtual void acceptLastMove ()
Accept last move.
virtual const Action * getActionPointerByType (const std::type_info &type) const
Returns pointer to Action of type t, otherwise returns null pointer.
Private Member Functions
double v (const double z) const
The electric potential.
Private Attributes
const double tau
The timestep.
Array q
The charges of the particles.
const double strength
The strength of the electric field.
Vec center
The center of the physical region.
const double halfwidth
The half width of the physical region.
const int idir
The component of the electric field (0->x, 1->y, 2->z)
SuperCell & cell
The supercell.
const double slopeIn
Parameters for v method.
const double slopeOut
const double intercept
Detailed Description
Class for getting action from stepwise electric field.
Bug:
Hard coded for NDIM=3.
Version:
$Revision:
Author:
John Shumway and Matthew Harowitz.
Definition at line 32 of file EFieldAction.h.
Member Typedef Documentation
typedef blitz::Array<double, 1> EFieldAction::Array
Typedefs.
Definition at line 35 of file EFieldAction.h.
typedef blitz::Array<int, 1> EFieldAction::IArray
Reimplemented from Action.
Definition at line 36 of file EFieldAction.h.
typedef blitz::TinyVector<double, NDIM> EFieldAction::Vec
Reimplemented from Action.
Definition at line 37 of file EFieldAction.h.
Constructor & Destructor Documentation
EFieldAction::EFieldAction (const SimulationInfo & simInfo, double strength, double center, double width, int idir)
Construct by providing SimulationInfo, field strength in atomic units , physical region center and width, and direction index.
Definition at line 14 of file EFieldAction.cc.
References SuperCell::a, cell, intercept, q, slopeIn, slopeOut, and v().
virtual EFieldAction::~EFieldAction () inline virtual
Virtual destructor.
Definition at line 44 of file EFieldAction.h.
Member Function Documentation
double EFieldAction::getActionDifference (const SectionSamplerInterface & sampler, int level) virtual
Calculate the difference in action.
Implements Action.
Definition at line 40 of file EFieldAction.cc.
References cell, center, idir, SuperCell::pbc(), q, tau, and v().
double EFieldAction::getActionDifference (const Paths & paths, const VArray & displacement, int nmoving, const IArray & movingIndex, int iFirstSlice, int iLastSlice) virtual
Calculate the difference in action.
Reimplemented from Action.
Definition at line 87 of file EFieldAction.cc.
References cell, center, idir, SuperCell::pbc(), q, tau, and v().
void EFieldAction::getBeadAction (const Paths & paths, const int ipart, const int islice, double & u, double & utau, double & ulambda, Vec & fm, Vec & fp) const virtual
Calculate the and derivatives at a bead.
Implements Action.
Definition at line 68 of file EFieldAction.cc.
References cell, center, idir, SuperCell::pbc(), q, tau, and v().
double EFieldAction::getTotalAction (const Paths & paths, const int level) const virtual
Calculate the total action.
Implements Action.
Definition at line 64 of file EFieldAction.cc.
double EFieldAction::v (const double z) const inline private
The electric potential.
Definition at line 78 of file EFieldAction.cc.
References halfwidth, intercept, slopeIn, and slopeOut.
Referenced by EFieldAction(), getActionDifference(), and getBeadAction().
Member Data Documentation
SuperCell& EFieldAction::cell private
The supercell.
Definition at line 70 of file EFieldAction.h.
Referenced by EFieldAction(), getActionDifference(), and getBeadAction().
Vec EFieldAction::center private
The center of the physical region.
Definition at line 64 of file EFieldAction.h.
Referenced by getActionDifference(), and getBeadAction().
const double EFieldAction::halfwidth private
The half width of the physical region.
Definition at line 66 of file EFieldAction.h.
Referenced by v().
const int EFieldAction::idir private
The component of the electric field (0->x, 1->y, 2->z)
Definition at line 68 of file EFieldAction.h.
Referenced by getActionDifference(), and getBeadAction().
const double EFieldAction::intercept private
Definition at line 74 of file EFieldAction.h.
Referenced by EFieldAction(), and v().
Array EFieldAction::q private
The charges of the particles.
Definition at line 60 of file EFieldAction.h.
Referenced by EFieldAction(), getActionDifference(), and getBeadAction().
const double EFieldAction::slopeIn private
Parameters for v method.
Definition at line 74 of file EFieldAction.h.
Referenced by EFieldAction(), and v().
const double EFieldAction::slopeOut private
Definition at line 74 of file EFieldAction.h.
Referenced by EFieldAction(), and v().
const double EFieldAction::strength private
The strength of the electric field.
Definition at line 62 of file EFieldAction.h.
const double EFieldAction::tau private
The timestep.
Definition at line 58 of file EFieldAction.h.
Referenced by getActionDifference(), and getBeadAction().
The documentation for this class was generated from the following files:
EFieldAction.h
EFieldAction.cc