pi: Path integral Quantum Monte Carlo: CoulombAction Class Reference
CoulombAction Class Reference
Class for calculating coulomb action between particles.
#include <CoulombAction.h>
Public Types
typedef blitz::TinyVector
< double, NDIM > Vec
typedef blitz::Array< int, 1 > IArray
typedef blitz::Array< Vec, 1 > VArray1
Public Types inherited from Action
typedef blitz::Array< Vec, 1 > VArray
Public Member Functions
CoulombAction (const double epsilon, const SimulationInfo &, const int norder, double rmin, double rmax, int ngpts, const bool dumpFiles, bool useEwald, int ewaldNDim, double ewaldRcut, double ewaldKcut, double screenDist, const double kappa, const int nimages, const std::string ewaldType, int exLevel)
Constructor by providing the timestep tau.
virtual ~CoulombAction ()
Virtual destructor.
virtual double getActionDifference (const SectionSamplerInterface &, int level)
Calculate the difference in action.
virtual double getActionDifference (const Paths &, const VArray &displacement, int nmoving, const IArray &movingIndex, int iFirstSlice, int iLastSlice)
Calculate the difference in action.
virtual double getTotalAction (const Paths &, const int level) const
Calculate the total action.
virtual void getBeadAction (const Paths &, const int ipart, const int islice, double &u, double &utau, double &ulambda, Vec &fm, Vec &fp) const
Calculate the action and derivatives at a bead.
double getEField (const Paths &, const int ipart, const int islice) const
Calculate the efield at a bead.
double getAction (const Paths &, const int islice) const
Calculate the total action for a slice.
virtual double u (double r, int order) const
EmpiricalPairAction method.
virtual double utau (double r, int order) const
EmpiricalPairAction method.
Public Member Functions inherited from Action
virtual ~Action ()
virtual void initialize (const SectionChooser &)
Initialize for a sampling section.
virtual void acceptLastMove ()
Accept last move.
virtual const Action * getActionPointerByType (const std::type_info &type) const
Returns pointer to Action of type t, otherwise returns null pointer.
Private Attributes
const double epsilon
The dielectric constant.
double tau
The timestep.
int npart
Number of particles.
std::vector< PairAction * > pairActionArray
The gridded pair-actions.
double q1q2
Charge for EmpiricalPairAction method.
double mu
Reduced mass for EmpiricalPairAction method.
double displace2
Displacement variable for EmpricalPairAction method.
double screenDist
Screening distance (zero for no screening).
EwaldSum * ewaldSum
Ewald sums.
VArray1 rewald
Buffer for positions in long range ewald sum.
Detailed Description
Class for calculating coulomb action between particles.
Version:
$Revision$
Bug:
getEField method is not very accurate or efficient.
Author:
John Shumway.
Definition at line 16 of file CoulombAction.h.
Member Typedef Documentation
typedef blitz::Array<int,1> CoulombAction::IArray
Reimplemented from Action.
Definition at line 19 of file CoulombAction.h.
typedef blitz::Array<Vec,1> CoulombAction::VArray1
Definition at line 20 of file CoulombAction.h.
typedef blitz::TinyVector<double,NDIM> CoulombAction::Vec
Reimplemented from Action.
Definition at line 18 of file CoulombAction.h.
Constructor & Destructor Documentation
CoulombAction::CoulombAction (const double epsilon, const SimulationInfo & simInfo, const int norder, double rmin, double rmax, int ngpts, const bool dumpFiles, bool useEwald, int ewaldNDim, double ewaldRcut, double ewaldKcut, double screenDist, const double kappa, const int nimages, const std::string ewaldType, int exLevel)
Constructor by providing the timestep tau.
Hack to handle ion-ion interaction properly.
Definition at line 19 of file CoulombAction.cc.
References SuperCell::a, displace2, epsilon, EwaldSum::evalSelfEnergy(), ewaldSum, EwaldSum::getQArray(), mu, npart, pairActionArray, q1q2, and rewald.
CoulombAction::~CoulombAction () virtual
Virtual destructor.
Definition at line 88 of file CoulombAction.cc.
References ewaldSum, and pairActionArray.
Member Function Documentation
double CoulombAction::getAction (const Paths & paths, const int islice) const
Calculate the total action for a slice.
Definition at line 169 of file CoulombAction.cc.
References epsilon, EwaldSum::evalLongRange(), ewaldSum, getBeadAction(), npart, pairActionArray, rewald, tau, and u().
Referenced by VIndEstimator::handleLink().
double CoulombAction::getActionDifference (const SectionSamplerInterface & sampler, int level) virtual
Calculate the difference in action.
Implements Action.
Definition at line 95 of file CoulombAction.cc.
References epsilon, EwaldSum::evalLongRange(), ewaldSum, npart, pairActionArray, rewald, tau, and u().
double CoulombAction::getActionDifference (const Paths & paths, const VArray & displacement, int nmoving, const IArray & movingIndex, int iFirstSlice, int iLastSlice) virtual
Calculate the difference in action.
Reimplemented from Action.
Definition at line 118 of file CoulombAction.cc.
References epsilon, EwaldSum::evalLongRange(), ewaldSum, npart, pairActionArray, SuperCell::pbc(), rewald, tau, and u().
void CoulombAction::getBeadAction (const Paths & paths, const int ipart, const int islice, double & u, double & utau, double & ulambda, Vec & fm, Vec & fp) const virtual
Calculate the action and derivatives at a bead.
Implements Action.
Definition at line 149 of file CoulombAction.cc.
References epsilon, EwaldSum::evalLongRange(), ewaldSum, pairActionArray, rewald, and tau.
Referenced by getAction(), and getEField().
double CoulombAction::getEField (const Paths & paths, const int ipart, const int islice) const
Calculate the efield at a bead.
Definition at line 189 of file CoulombAction.cc.
References getBeadAction(), pairActionArray, tau, u(), and utau().
Referenced by EIndEstimator::handleLink().
double CoulombAction::getTotalAction (const Paths & paths, const int level) const virtual
Calculate the total action.
Implements Action.
Definition at line 145 of file CoulombAction.cc.
double CoulombAction::u (double r, int order) const virtual
EmpiricalPairAction method.
Implements PairAction::EmpiricalPairAction.
Definition at line 204 of file CoulombAction.cc.
References displace2, mu, q1q2, and tau.
Referenced by getAction(), getActionDifference(), getEField(), and utau().
double CoulombAction::utau (double r, int order) const virtual
EmpiricalPairAction method.
Implements PairAction::EmpiricalPairAction.
Definition at line 245 of file CoulombAction.cc.
References tau, and u().
Referenced by getEField().
Member Data Documentation
double CoulombAction::displace2 private
Displacement variable for EmpricalPairAction method.
Definition at line 63 of file CoulombAction.h.
Referenced by CoulombAction(), and u().
const double CoulombAction::epsilon private
The dielectric constant.
Definition at line 51 of file CoulombAction.h.
Referenced by CoulombAction(), getAction(), getActionDifference(), and getBeadAction().
EwaldSum* CoulombAction::ewaldSum private
Ewald sums.
Definition at line 67 of file CoulombAction.h.
Referenced by CoulombAction(), getAction(), getActionDifference(), getBeadAction(), and ~CoulombAction().
double CoulombAction::mu private
Reduced mass for EmpiricalPairAction method.
Definition at line 61 of file CoulombAction.h.
Referenced by CoulombAction(), and u().
int CoulombAction::npart private
Number of particles.
Definition at line 55 of file CoulombAction.h.
Referenced by CoulombAction(), getAction(), and getActionDifference().
std::vector<PairAction*> CoulombAction::pairActionArray private
The gridded pair-actions.
Definition at line 57 of file CoulombAction.h.
Referenced by CoulombAction(), getAction(), getActionDifference(), getBeadAction(), getEField(), and ~CoulombAction().
double CoulombAction::q1q2 private
Charge for EmpiricalPairAction method.
Definition at line 59 of file CoulombAction.h.
Referenced by CoulombAction(), and u().
VArray1 CoulombAction::rewald mutable private
Buffer for positions in long range ewald sum.
Definition at line 69 of file CoulombAction.h.
Referenced by CoulombAction(), getAction(), getActionDifference(), and getBeadAction().
double CoulombAction::screenDist private
Screening distance (zero for no screening).
Definition at line 65 of file CoulombAction.h.
double CoulombAction::tau mutable private
The timestep.
Definition at line 53 of file CoulombAction.h.
Referenced by getAction(), getActionDifference(), getBeadAction(), getEField(), u(), and utau().
The documentation for this class was generated from the following files:
CoulombAction.h
CoulombAction.cc