pi: Path integral Quantum Monte Carlo: BeadsBase Class Reference
BeadsBase Class Reference
#include <Beads.h>
Public Types
typedef std::vector< BeadsBase * > BeadsArray
typedef blitz::Array< int, 1 > IArray
Public Member Functions
BeadsBase (int npart, int nslice)
virtual BeadsBase * clone (const int npart, const int nslice)=0
Clone method.
BeadsBase * cloneBase (const int npart, const int nslice)
virtual ~BeadsBase ()
Virtual destructor.
BeadsBase & operator= (const BeadsBase &beadsIn)
Copy operatation.
void copySlice (int isliceIn, BeadsBase &beadsOut, int isliceOut) const
Copy a slice.
void copySlice (const Permutation &p, int isliceIn, BeadsBase &beadsOut, int isliceOut) const
void copySlice (int isliceIn, BeadsBase &beadsOut, const Permutation &p, int isliceOut) const
void copySlice (const IArray &indexIn, int isliceIn, BeadsBase &beadsOut, const IArray &indexOut, int isliceOut) const
int getAuxBeadCount () const
Get the number of auxiliary beads.
virtual const void * getAuxBead (const int ipart, const int islice, const int iaux) const
Get a pointer to an auxiliary bead.
virtual void * getAuxBead (const int ipart, const int islice, const int iaux)
Get a pointer to an auxiliary bead.
virtual void print (std::ostream &out) const =0
Support for printing.
const BeadsBase * getAuxBeads (const int i=0) const
Return a pointer to the auxiliary beads.
BeadsBase * getAuxBeads (const int i=0)
Protected Member Functions
virtual void vcopySlice (int isliceIn, BeadsBase *beadsOut, int isliceOut) const =0
virtual void vcopySlice (const Permutation &p, int isliceIn, BeadsBase *beadsOut, int isliceOut) const =0
virtual void vcopySlice (int isliceIn, BeadsBase *beadsOut, const Permutation &p, int isliceOut) const =0
virtual void vcopySlice (const IArray &indexIn, int isliceIn, BeadsBase *beadsOut, const IArray &indexOut, int isliceOut) const =0
virtual const void * vgetAuxBead (const int ipart, const int islice) const =0
virtual void * vgetAuxBead (const int ipart, const int islice)=0
virtual void vcopy (BeadsBase *beadsOut) const =0
Protected Attributes
int nAuxBeads
Number of auxBeads.
BeadsArray auxBeads
Auxiliary beads.
int npart
Number of particles.
int nslice
Number of slices.
Friends
class BeadFactory
BeadFactory is a friend so that it can add to auxBeads.
Detailed Description
Definition at line 29 of file Beads.h.
Member Typedef Documentation
typedef std::vector<BeadsBase*> BeadsBase::BeadsArray
Definition at line 33 of file Beads.h.
typedef blitz::Array<int,1> BeadsBase::IArray
Definition at line 34 of file Beads.h.
Constructor & Destructor Documentation
BeadsBase::BeadsBase (int npart, int nslice) inline
Definition at line 31 of file Beads.h.
virtual BeadsBase::~BeadsBase () inline virtual
Virtual destructor.
Definition at line 54 of file Beads.h.
Member Function Documentation
virtual BeadsBase* BeadsBase::clone (const int npart, const int nslice) pure virtual
Clone method.
Implemented in Beads< TDIM >, and Beads< NDIM >.
BeadsBase* BeadsBase::cloneBase (const int npart, const int nslice) inline
Definition at line 37 of file Beads.h.
References auxBeads, and nAuxBeads.
Referenced by BeadFactory::getNewBeads().
void BeadsBase::copySlice (int isliceIn, BeadsBase & beadsOut, int isliceOut) const inline
Copy a slice.
Definition at line 61 of file Beads.h.
References auxBeads, and nAuxBeads.
Referenced by SerialPaths::getBeads(), SerialPaths::putBeads(), DoubleCollectiveSectionSampler::run(), CollectiveSectionSampler::run(), DoubleMLSampler::run(), MultiLevelSampler::run(), DoubleCollectiveSectionSampler::tryMove(), DoubleMLSampler::tryMove(), CollectiveSectionSampler::tryMove(), and MultiLevelSampler::tryMove().
void BeadsBase::copySlice (const Permutation & p, int isliceIn, BeadsBase & beadsOut, int isliceOut) const inline
Definition at line 66 of file Beads.h.
References auxBeads, and nAuxBeads.
void BeadsBase::copySlice (int isliceIn, BeadsBase & beadsOut, const Permutation & p, int isliceOut) const inline
Definition at line 72 of file Beads.h.
References auxBeads, and nAuxBeads.
void BeadsBase::copySlice (const IArray & indexIn, int isliceIn, BeadsBase & beadsOut, const IArray & indexOut, int isliceOut) const inline
Definition at line 78 of file Beads.h.
References auxBeads, and nAuxBeads.
virtual const void* BeadsBase::getAuxBead (const int ipart, const int islice, const int iaux) const inline virtual
Get a pointer to an auxiliary bead.
Definition at line 88 of file Beads.h.
References auxBeads.
Referenced by SerialPaths::getAuxBead(), DoubleParallelPaths::getAuxBead(), and ParallelPaths::getAuxBead().
virtual void* BeadsBase::getAuxBead (const int ipart, const int islice, const int iaux) inline virtual
Get a pointer to an auxiliary bead.
Definition at line 93 of file Beads.h.
References auxBeads.
int BeadsBase::getAuxBeadCount () const inline
Get the number of auxiliary beads.
Definition at line 86 of file Beads.h.
References nAuxBeads.
const BeadsBase* BeadsBase::getAuxBeads (const int i = 0) const inline
Return a pointer to the auxiliary beads.
Definition at line 100 of file Beads.h.
References auxBeads.
Referenced by SpinAction::getActionDifference(), SpinFixedPhaseAction::getActionDifference(), SpinFixedPhaseAction::initialize(), SpinMover::makeMove(), and FreeSpinMover::makeMove().
BeadsBase* BeadsBase::getAuxBeads (const int i = 0) inline
Definition at line 101 of file Beads.h.
References auxBeads.
BeadsBase& BeadsBase::operator= (const BeadsBase & beadsIn) inline
Copy operatation.
Definition at line 56 of file Beads.h.
References auxBeads, and nAuxBeads.
virtual void BeadsBase::print (std::ostream & out) const pure virtual
Support for printing.
Implemented in Beads< TDIM >, and Beads< NDIM >.
Referenced by operator<<().
virtual void BeadsBase::vcopy (BeadsBase * beadsOut) const protected pure virtual
Implemented in Beads< TDIM >, and Beads< NDIM >.
virtual void BeadsBase::vcopySlice (int isliceIn, BeadsBase * beadsOut, int isliceOut) const protected pure virtual
Implemented in Beads< TDIM >, and Beads< NDIM >.
virtual void BeadsBase::vcopySlice (const Permutation & p, int isliceIn, BeadsBase * beadsOut, int isliceOut) const protected pure virtual
Implemented in Beads< TDIM >, and Beads< NDIM >.
virtual void BeadsBase::vcopySlice (int isliceIn, BeadsBase * beadsOut, const Permutation & p, int isliceOut) const protected pure virtual
Implemented in Beads< TDIM >, and Beads< NDIM >.
virtual void BeadsBase::vcopySlice (const IArray & indexIn, int isliceIn, BeadsBase * beadsOut, const IArray & indexOut, int isliceOut) const protected pure virtual
Implemented in Beads< TDIM >, and Beads< NDIM >.
virtual const void* BeadsBase::vgetAuxBead (const int ipart, const int islice) const protected pure virtual
Implemented in Beads< TDIM >, and Beads< NDIM >.
virtual void* BeadsBase::vgetAuxBead (const int ipart, const int islice) protected pure virtual
Implemented in Beads< TDIM >, and Beads< NDIM >.
Friends And Related Function Documentation
friend class BeadFactory friend
BeadFactory is a friend so that it can add to auxBeads.
Definition at line 103 of file Beads.h.
Member Data Documentation
BeadsArray BeadsBase::auxBeads protected
Auxiliary beads.
Definition at line 108 of file Beads.h.
Referenced by BeadFactory::addAuxBeads(), Beads< TDIM >::Beads(), cloneBase(), copySlice(), getAuxBead(), getAuxBeads(), operator=(), and Beads< NDIM >::~Beads().
int BeadsBase::nAuxBeads protected
Number of auxBeads.
Definition at line 106 of file Beads.h.
Referenced by cloneBase(), copySlice(), getAuxBeadCount(), operator=(), and Beads< NDIM >::~Beads().
int BeadsBase::npart protected
Number of particles.
Definition at line 110 of file Beads.h.
Referenced by Beads< NDIM >::getNPart(), and Beads< NDIM >::vcopySlice().
int BeadsBase::nslice protected
Number of slices.
Definition at line 112 of file Beads.h.
Referenced by Beads< NDIM >::getNSlice().
The documentation for this class was generated from the following file:
Beads.h