pi: Path integral Quantum Monte Carlo: LinkSummable Class Reference
LinkSummable Class Reference
Interface class for objects that can be summed over links.
#include <LinkSummable.h>
Public Types
typedef blitz::TinyVector
< double, NDIM > Vec
Public Member Functions
virtual ~LinkSummable ()
Virtual destructor.
virtual void initCalc (const int nslice, const int firstSlice)
Initialize the calculation.
virtual void handleLink (const Vec &start, const Vec &end, int ipart, int islice, const Paths &)=0
Add contribution from a link.
virtual void endCalc (int nslice)
Finalize the calculation.
Detailed Description
Interface class for objects that can be summed over links.
Version:
$Revision$
Author:
John Shumway
Definition at line 29 of file LinkSummable.h.
Member Typedef Documentation
typedef blitz::TinyVector<double,NDIM> LinkSummable::Vec
Reimplemented in VirialEnergyEstimator, CountCountEstimator, DensDensEstimator, DynamicPCFEstimator, PairCFEstimator< N >, SpinChoiceDensityEstimator, SpinChoicePCFEstimator< N >, DensCountEstimator, SKOmegaEstimator, DensityEstimator, ZeroVarDensityEstimator, DensityCurrentEstimator, AngularMomentumEstimator, BoxEstimator, FrequencyEstimator, BondLengthEstimator, DiamagneticEstimator, EwaldCoulombEstimator, PositionEstimator, ProbDensityGrid, CoulombEnergyEstimator, DipoleMomentEstimator, WindingEstimator, and EMARateEstimator.
Definition at line 31 of file LinkSummable.h.
Constructor & Destructor Documentation
virtual LinkSummable::~LinkSummable () inline virtual
Virtual destructor.
Definition at line 33 of file LinkSummable.h.
Member Function Documentation
virtual void LinkSummable::endCalc (int nslice) inline virtual
Finalize the calculation.
Reimplemented in ZeroVarDensityEstimator, SpinChoicePCFEstimator< N >, PairCFEstimator< N >, ActionChoice, DensDensEstimator, CountCountEstimator, DynamicPCFEstimator, VIndEstimator, ConductanceEstimator, EIndEstimator, SKOmegaEstimator, SpinChargeEstimator, ConductivityEstimator, DensCountEstimator, DensityEstimator, VirialEnergyEstimator, DoubleActionChoice, DensityCurrentEstimator, ProbDensityGrid, EwaldCoulombEstimator, ThermoEnergyEstimator, FrequencyEstimator, BoxEstimator, AngularMomentumEstimator, BondLengthEstimator, WindingEstimator, JEstimator, DiamagneticEstimator, PositionEstimator, SpinEstimator, ConductivityEstimator2D, CoulombEnergyEstimator, ConditionalDensityGrid, DipoleMomentEstimator, and EMARateEstimator.
Definition at line 40 of file LinkSummable.h.
Referenced by SerialPaths::sumOverLinks(), DoubleParallelPaths::sumOverLinks(), and ParallelPaths::sumOverLinks().
virtual void LinkSummable::handleLink (const Vec & start, const Vec & end, int ipart, int islice, const Paths &) pure virtual
Add contribution from a link.
Implemented in ZeroVarDensityEstimator, PairCFEstimator< N >, SpinChoicePCFEstimator< N >, ActionChoice, DensDensEstimator, CountCountEstimator, VIndEstimator, ConductanceEstimator, DynamicPCFEstimator, EIndEstimator, SpinChargeEstimator, SpinChoiceDensityEstimator, ConductivityEstimator, SKOmegaEstimator, DensCountEstimator, DensityEstimator, VirialEnergyEstimator, DoubleActionChoice, DensityCurrentEstimator, ProbDensityGrid, EwaldCoulombEstimator, ThermoEnergyEstimator, FrequencyEstimator, BoxEstimator, AngularMomentumEstimator, BondLengthEstimator, WindingEstimator, JEstimator, DiamagneticEstimator, PositionEstimator, SpinEstimator, ConductivityEstimator2D, CoulombEnergyEstimator, ConditionalDensityGrid, DipoleMomentEstimator, and EMARateEstimator.
Referenced by SerialPaths::sumOverLinks(), DoubleParallelPaths::sumOverLinks(), and ParallelPaths::sumOverLinks().
virtual void LinkSummable::initCalc (const int nslice, const int firstSlice) inline virtual
Initialize the calculation.
Reimplemented in ZeroVarDensityEstimator, PairCFEstimator< N >, SpinChoicePCFEstimator< N >, ActionChoice, DensDensEstimator, CountCountEstimator, VIndEstimator, ConductanceEstimator, DynamicPCFEstimator, EIndEstimator, SpinChargeEstimator, ConductivityEstimator, SKOmegaEstimator, DensCountEstimator, VirialEnergyEstimator, DensityEstimator, DoubleActionChoice, DensityCurrentEstimator, EwaldCoulombEstimator, FrequencyEstimator, ThermoEnergyEstimator, BoxEstimator, AngularMomentumEstimator, BondLengthEstimator, WindingEstimator, JEstimator, DiamagneticEstimator, PositionEstimator, SpinEstimator, CoulombEnergyEstimator, ConductivityEstimator2D, DipoleMomentEstimator, and EMARateEstimator.
Definition at line 35 of file LinkSummable.h.
Referenced by SerialPaths::sumOverLinks(), DoubleParallelPaths::sumOverLinks(), and ParallelPaths::sumOverLinks().
The documentation for this class was generated from the following file:
LinkSummable.h