pi: Path integral Quantum Monte Carlo: EwaldImagePairAction Class Reference
EwaldImagePairAction Class Reference
#include <EwaldImagePairAction.h>
Public Member Functions
EwaldImagePairAction (const Species &, const Species &, const EmpiricalPairAction &, const SimulationInfo &, const int norder, const double rmin, const double rmax, const int ngpts, const int nImages, int exLevel)
Construct by providing the species and EmpiricalPairAction.
virtual ~EwaldImagePairAction ()
Virtual destructor.
virtual double getActionDifference (const SectionSamplerInterface &, int level)
Calculate the difference in action.
virtual double getActionDifference (const Paths &, const VArray &displacement, int nmoving, const IArray &movingIndex, int iFirstSlice, int iLastSlice)
Calculate the difference in action.
virtual double getTotalAction (const Paths &, const int level) const
Calculate the total action.
virtual void getBeadAction (const Paths &, const int ipart, const int islice, double &u, double &utau, double &ulambda, Vec &fm, Vec &fp) const
Calculate the action and derivatives at a bead.
void findBoxImageVectors (std::vector< double >)
Public Member Functions inherited from PairAction
PairAction (const Species &, const Species &, const std::string &filename, const SimulationInfo &, const int norder, const bool hasZ, int exLevel)
Construct by providing the species and squarer pidmu filename.
PairAction (const Species &, const Species &, const std::string &filename, const SimulationInfo &, const int norder, const bool hasZ, const bool isDMD, int exLevel)
Construct by providing the species and dmu filename.
PairAction (const Species &, const Species &, const EmpiricalPairAction &, const SimulationInfo &, const int norder, const double rmin, const double rmax, const int ngpts, const bool hasZ, int exLevel)
Construct by providing the species and EmpiricalPairAction.
PairAction (const Species &, const Species &, PairIntegrator &, const SimulationInfo &, const int norder, const double rmin, const double rmax, const int ngpts, int exLevel)
Construct by providing the species and PairIntegrator.
virtual ~PairAction ()
Virtual destructor.
void write (const std::string &filename, const bool hasZ) const
Write data tables to disk (defaults to speciesNames.dm[eu]).
Public Member Functions inherited from Action
virtual ~Action ()
virtual void initialize (const SectionChooser &)
Initialize for a sampling section.
virtual void acceptLastMove ()
Accept last move.
virtual const Action * getActionPointerByType (const std::type_info &type) const
Returns pointer to Action of type t, otherwise returns null pointer.
Protected Attributes
double sphereR
const int nImages
std::vector< std::vector
< double > > boxImageVecs
Protected Attributes inherited from PairAction
const double tau
The timestep.
int ngpts
The number of gridpoints.
double rgridinv
The first grid radial value.
double logrratioinv
The log of the ratio of consecutive grid points.
Array3 ugrid
The action grid (radial coord is logrithmic).
const Species & species1
The species.
const Species & species2
int ifirst1
Indicies of first particles of each species.
int ifirst2
int npart1
Number of each particle for species in the interaction.
int npart2
int norder
Order of the off-diagonal expansion.
bool isDMD
Flag for using the format from DMD downloaded from Ceperley site.
bool hasZ
Flag for including sum over z.
const int exLevel
Level to start evaluating exchange.
const double mass
Mass of first species, needed for evaluating exchange.
Friends
class EwaldAction
Additional Inherited Members
Public Types inherited from PairAction
typedef blitz::Array< int, 1 > IArray
Typedefs.
typedef blitz::Array< double, 1 > Array
typedef blitz::Array< double, 2 > Array2
typedef blitz::Array< double, 3 > Array3
Public Types inherited from Action
typedef blitz::TinyVector
< double, NDIM > Vec
typedef blitz::Array< Vec, 1 > VArray
Protected Member Functions inherited from PairAction
double u00 (double r) const
Evalute the diagonal action from the grid.
double uk0 (double q, double s2) const
Evalute the off-diagonal action from the grid.
double uk0 (double q, double s2, double z2) const
Evalute the off-diagonal action from the grid.
void uk0CalcDerivatives (double q, double s2, double &u, double &utau, double &uq, double &us2) const
Evaluate the derivatives of the action from the grid.
void uk0CalcDerivatives (double q, double s2, double z2, double &u, double &utau, double &uq, double &us2, double &uz2) const
Evaluate the derivatives of the action from the grid.
Detailed Description
Definition at line 29 of file EwaldImagePairAction.h.
Constructor & Destructor Documentation
EwaldImagePairAction::EwaldImagePairAction (const Species & s1, const Species & s2, const EmpiricalPairAction & action, const SimulationInfo & simInfo, const int norder, const double rmin, const double rmax, const int ngpts, const int nImages, int exLevel)
Construct by providing the species and EmpiricalPairAction.
Definition at line 15 of file EwaldImagePairAction.cc.
References boxImageVecs, findBoxImageVectors(), nImages, and sphereR.
virtual EwaldImagePairAction::~EwaldImagePairAction () inline virtual
Virtual destructor.
Definition at line 38 of file EwaldImagePairAction.h.
Member Function Documentation
void EwaldImagePairAction::findBoxImageVectors (std::vector< double > a)
Definition at line 251 of file EwaldImagePairAction.cc.
References boxImageVecs, nImages, and sphereR.
Referenced by EwaldImagePairAction().
double EwaldImagePairAction::getActionDifference (const SectionSamplerInterface & sampler, int level) virtual
Calculate the difference in action.
Reimplemented from PairAction.
Definition at line 34 of file EwaldImagePairAction.cc.
References boxImageVecs, PairAction::hasZ, PairAction::ifirst1, PairAction::ifirst2, PairAction::npart1, PairAction::npart2, SuperCell::pbc(), PairAction::u00(), and PairAction::uk0().
double EwaldImagePairAction::getActionDifference (const Paths & paths, const VArray & displacement, int nmoving, const IArray & movingIndex, int iFirstSlice, int iLastSlice) virtual
Calculate the difference in action.
Reimplemented from PairAction.
Definition at line 114 of file EwaldImagePairAction.cc.
References boxImageVecs, PairAction::ifirst1, PairAction::ifirst2, PairAction::npart1, PairAction::npart2, SuperCell::pbc(), and PairAction::uk0().
void EwaldImagePairAction::getBeadAction (const Paths & paths, const int ipart, const int islice, double & u, double & utau, double & ulambda, Vec & fm, Vec & fp) const virtual
Calculate the action and derivatives at a bead.
Reimplemented from PairAction.
Definition at line 184 of file EwaldImagePairAction.cc.
References boxImageVecs, PairAction::hasZ, PairAction::ifirst1, PairAction::ifirst2, PairAction::npart1, PairAction::npart2, and PairAction::uk0CalcDerivatives().
double EwaldImagePairAction::getTotalAction (const Paths & paths, const int level) const virtual
Calculate the total action.
Reimplemented from PairAction.
Definition at line 180 of file EwaldImagePairAction.cc.
Friends And Related Function Documentation
friend class EwaldAction friend
Reimplemented from PairAction.
Definition at line 52 of file EwaldImagePairAction.h.
Member Data Documentation
std :: vector<std :: vector<double> > EwaldImagePairAction::boxImageVecs protected
Definition at line 56 of file EwaldImagePairAction.h.
Referenced by EwaldImagePairAction(), findBoxImageVectors(), getActionDifference(), and getBeadAction().
const int EwaldImagePairAction::nImages protected
Definition at line 55 of file EwaldImagePairAction.h.
Referenced by EwaldImagePairAction(), and findBoxImageVectors().
double EwaldImagePairAction::sphereR protected
Definition at line 54 of file EwaldImagePairAction.h.
Referenced by EwaldImagePairAction(), and findBoxImageVectors().
The documentation for this class was generated from the following files:
EwaldImagePairAction.h
EwaldImagePairAction.cc