pi: Path integral Quantum Monte Carlo: DoubleMLSampler Class Reference
DoubleMLSampler Class Reference
Class for multilevel sampling of beads.
#include <DoubleMLSampler.h>
Public Member Functions
DoubleMLSampler (const int nmoving, Paths &, DoubleSectionChooser &, ParticleChooser &, PermutationChooser &, ParticleChooser &, PermutationChooser &, Mover &, Action *, DoubleAction *, const bool sampleBoth, const int nrepeat, const BeadFactory &, const bool delayedRejection, const double defaultFactor, double newFactor)
virtual ~DoubleMLSampler ()
virtual void run ()
virtual Beads< NDIM > & getMovingBeads (const int i)
virtual const Beads< NDIM > & getMovingBeads (const int i) const
virtual Beads< NDIM > & getSectionBeads (const int i)
virtual const Beads< NDIM > & getSectionBeads (const int i) const
virtual IArray & getMovingIndex (const int i)
virtual const IArray & getMovingIndex (const int i) const
bool isSamplingBoth () const
Are both sections being sampled?
void activateSection (const int i)
Set the active section for MultiLevelSampler.
virtual AccRejEstimator * getAccRejEstimator (const std::string &name)
Get a pointer to the accept/reject statistic estimator.
Public Member Functions inherited from MultiLevelSampler
MultiLevelSampler (const int nmoving, Paths &, SectionChooser &, ParticleChooser &, PermutationChooser &, Mover &, Action *, const int nrepeat, const BeadFactory &, const bool delayedRejection, const double defaultFactor, double newFactor)
virtual ~MultiLevelSampler ()
int getNLevel () const
virtual Beads< NDIM > & getMovingBeads ()
virtual const Beads< NDIM > & getMovingBeads () const
virtual int getFirstSliceIndex () const
const Beads< NDIM > & getRejectedBeads () const
Beads< NDIM > & getRejectedBeads ()
double getFactor ()
virtual Beads< NDIM > & getSectionBeads ()
virtual const Beads< NDIM > & getSectionBeads () const
IArray & getMovingIndex ()
const IArray & getMovingIndex () const
void setAction (Action *, const int level=ALL_LEVELS)
Set the action function for a level, or default to level=ALL_LEVELS.
virtual const SuperCell & getSuperCell () const
Get a const reference to the SuperCell.
const Paths & getPaths () const
Get a constant reference to the paths.
const SectionChooser & getSectionChooser () const
Get const reference to the SectionChooser.
Public Member Functions inherited from Algorithm
virtual ~Algorithm ()
Public Member Functions inherited from SectionSamplerInterface
virtual ~SectionSamplerInterface ()
Static Public Attributes
static const int ALL_LEVELS = -1
Represent selecting all levels by -1.
Static Public Attributes inherited from MultiLevelSampler
Private Member Functions
bool tryMove (double)
Attempt a move on the beads.
Private Attributes
Beads< NDIM > * sectionBeads1
Reference to all beads in the section.
Beads< NDIM > * sectionBeads2
Permutation * sectionPermutation1
Reference the permutation of the in the section.
Permutation * sectionPermutation2
Beads< NDIM > * movingBeads1
Storage for the moving beads.
Beads< NDIM > * movingBeads2
Beads< NDIM > * rejectedBeads1
Storage for the rejected beads.
Beads< NDIM > * rejectedBeads2
DoubleAction * doubleAction
Action function.
IArray * movingIndex1
Index of moving particles.
IArray * movingIndex2
IArray pMovingIndex2
More indicies for moving particles.
DoubleSectionChooser & doubleSectionChooser
Reference to the algorithm that selected the section.
bool samplingBoth
Flag for determining whether to sample both sections.
Permutation permutation1
The permutations.
Permutation permutation2
ParticleChooser & particleChooser2
The algorithm for selecting the particles to move.
PermutationChooser & permutationChooser2
The algorithm for selecting the permutation.
const int nrepeat
Number of times to repeat.
Additional Inherited Members
Public Types inherited from MultiLevelSampler
typedef blitz::Array< int, 1 > IArray
Public Types inherited from SectionSamplerInterface
Protected Attributes inherited from MultiLevelSampler
const int nlevel
Number of levels.
const int nmoving
Number of moving particles.
Beads< NDIM > * sectionBeads
Reference to all beads in the section.
Permutation * sectionPermutation
Reference the permutation of the in the section.
Beads< NDIM > * movingBeads
Storage for the moving beads.
Mover & mover
Algorithm to select trial move for the beads.
const SuperCell & cell
Supercell.
Action * action
Action function.
IArray * movingIndex
Index of moving particles.
IArray identityIndex
More indicies for moving particles.
IArray pMovingIndex
ParticleChooser & particleChooser
The algorithm for selecting the particles to move.
PermutationChooser & permutationChooser
The algorithm for selecting the permutation.
SectionChooser & sectionChooser
Reference to the algorithm that selected the section.
const Paths & paths
Reference to the paths (only needed for fixed node reference point).
AccRejEstimator * accRejEst
AccRejEstimator.
const bool delayedRejection
flag for delayed rejection
Beads< NDIM > * rejectedBeads
double newFactor
const double defaultFactor
double factor
Detailed Description
Class for multilevel sampling of beads.
Definition at line 21 of file DoubleMLSampler.h.
Constructor & Destructor Documentation
DoubleMLSampler::DoubleMLSampler (const int nmoving, Paths & paths, DoubleSectionChooser & sectionChooser, ParticleChooser & particleChooser, PermutationChooser & permutationChooser, ParticleChooser & particleChooser2, PermutationChooser & permutationChooser2, Mover & mover, Action * action, DoubleAction * doubleAction, const bool sampleBoth, const int nrepeat, const BeadFactory & beadFactory, const bool delayedRejection, const double defaultFactor, double newFactor)
Definition at line 20 of file DoubleMLSampler.cc.
References MultiLevelSampler::identityIndex, movingIndex2, and MultiLevelSampler::nmoving.
DoubleMLSampler::~DoubleMLSampler () virtual
Definition at line 51 of file DoubleMLSampler.cc.
References movingBeads2, movingIndex2, particleChooser2, permutationChooser2, and rejectedBeads2.
Member Function Documentation
void DoubleMLSampler::activateSection (const int i)
Set the active section for MultiLevelSampler.
Definition at line 240 of file DoubleMLSampler.cc.
References MultiLevelSampler::delayedRejection, MultiLevelSampler::movingBeads, movingBeads1, movingBeads2, MultiLevelSampler::movingIndex, movingIndex1, movingIndex2, MultiLevelSampler::rejectedBeads, rejectedBeads1, rejectedBeads2, MultiLevelSampler::sectionBeads, sectionBeads1, sectionBeads2, MultiLevelSampler::sectionPermutation, sectionPermutation1, and sectionPermutation2.
Referenced by run(), and tryMove().
AccRejEstimator * DoubleMLSampler::getAccRejEstimator (const std::string & name) virtual
Get a pointer to the accept/reject statistic estimator.
(You are responsible for deleting this new object.)
Reimplemented from MultiLevelSampler.
Definition at line 259 of file DoubleMLSampler.cc.
References MultiLevelSampler::accRejEst, ParticleChooser::getName(), MultiLevelSampler::nlevel, MultiLevelSampler::nmoving, MultiLevelSampler::particleChooser, and samplingBoth.
virtual Beads<NDIM>& DoubleMLSampler::getMovingBeads (const int i) inline virtual
Reimplemented from MultiLevelSampler.
Definition at line 34 of file DoubleMLSampler.h.
References movingBeads1, and movingBeads2.
virtual const Beads<NDIM>& DoubleMLSampler::getMovingBeads (const int i) const inline virtual
Reimplemented from MultiLevelSampler.
Definition at line 37 of file DoubleMLSampler.h.
References movingBeads1, and movingBeads2.
virtual IArray& DoubleMLSampler::getMovingIndex (const int i) inline virtual
Reimplemented from MultiLevelSampler.
Definition at line 50 of file DoubleMLSampler.h.
References movingIndex1, and movingIndex2.
virtual const IArray& DoubleMLSampler::getMovingIndex (const int i) const inline virtual
Reimplemented from MultiLevelSampler.
Definition at line 53 of file DoubleMLSampler.h.
References movingIndex1, and movingIndex2.
virtual Beads<NDIM>& DoubleMLSampler::getSectionBeads (const int i) inline virtual
Reimplemented from MultiLevelSampler.
Definition at line 42 of file DoubleMLSampler.h.
References sectionBeads1, and sectionBeads2.
virtual const Beads<NDIM>& DoubleMLSampler::getSectionBeads (const int i) const inline virtual
Reimplemented from MultiLevelSampler.
Definition at line 45 of file DoubleMLSampler.h.
References sectionBeads1, and sectionBeads2.
bool DoubleMLSampler::isSamplingBoth () const inline virtual
Are both sections being sampled?
Reimplemented from MultiLevelSampler.
Definition at line 60 of file DoubleMLSampler.h.
References samplingBoth.
void DoubleMLSampler::run () virtual
Reimplemented from MultiLevelSampler.
Definition at line 59 of file DoubleMLSampler.cc.
References activateSection(), ParticleChooser::chooseParticles(), PermutationChooser::choosePermutation(), BeadsBase::copySlice(), PermutationChooser::getLnTranProb(), Beads< TDIM >::getNSlice(), PermutationChooser::getPermutation(), MultiLevelSampler::identityIndex, PermutationChooser::init(), MultiLevelSampler::movingBeads, movingBeads1, movingBeads2, movingIndex1, movingIndex2, MultiLevelSampler::nmoving, nrepeat, MultiLevelSampler::particleChooser, particleChooser2, permutation1, permutation2, MultiLevelSampler::permutationChooser, permutationChooser2, MultiLevelSampler::pMovingIndex, pMovingIndex2, samplingBoth, sectionBeads1, sectionBeads2, and tryMove().
bool DoubleMLSampler::tryMove (double initialLnTranProb) private
Attempt a move on the beads.
Reimplemented from MultiLevelSampler.
Definition at line 116 of file DoubleMLSampler.cc.
References DoubleAction::acceptLastMove(), Action::acceptLastMove(), MultiLevelSampler::accRejEst, MultiLevelSampler::action, activateSection(), BeadsBase::copySlice(), MultiLevelSampler::defaultFactor, MultiLevelSampler::delayedRejection, doubleAction, MultiLevelSampler::factor, DoubleAction::getActionDifference(), Action::getActionDifference(), Mover::getForwardProb(), Beads< TDIM >::getNSlice(), RandomNumGenerator::getRand(), MultiLevelSampler::identityIndex, Mover::makeDelayedMove(), Mover::makeMove(), AccRejEstimator::moveAccepted(), MultiLevelSampler::mover, movingBeads1, movingBeads2, movingIndex1, movingIndex2, MultiLevelSampler::newFactor, MultiLevelSampler::nlevel, MultiLevelSampler::nmoving, permutation1, permutation2, samplingBoth, MultiLevelSampler::sectionBeads, sectionBeads1, sectionBeads2, and AccRejEstimator::tryingMove().
Referenced by run().
Member Data Documentation
const int DoubleMLSampler::ALL_LEVELS = -1 static
Represent selecting all levels by -1.
Reimplemented from MultiLevelSampler.
Definition at line 58 of file DoubleMLSampler.h.
DoubleAction* DoubleMLSampler::doubleAction private
Action function.
Definition at line 80 of file DoubleMLSampler.h.
Referenced by tryMove().
DoubleSectionChooser& DoubleMLSampler::doubleSectionChooser private
Reference to the algorithm that selected the section.
Definition at line 86 of file DoubleMLSampler.h.
Beads<NDIM>* DoubleMLSampler::movingBeads1 private
Storage for the moving beads.
Definition at line 76 of file DoubleMLSampler.h.
Referenced by activateSection(), getMovingBeads(), run(), and tryMove().
Beads<NDIM> * DoubleMLSampler::movingBeads2 private
Definition at line 76 of file DoubleMLSampler.h.
Referenced by activateSection(), getMovingBeads(), run(), tryMove(), and ~DoubleMLSampler().
IArray* DoubleMLSampler::movingIndex1 private
Index of moving particles.
Definition at line 82 of file DoubleMLSampler.h.
Referenced by activateSection(), getMovingIndex(), run(), and tryMove().
IArray * DoubleMLSampler::movingIndex2 private
Definition at line 82 of file DoubleMLSampler.h.
Referenced by activateSection(), DoubleMLSampler(), getMovingIndex(), run(), tryMove(), and ~DoubleMLSampler().
const int DoubleMLSampler::nrepeat private
Number of times to repeat.
Reimplemented from MultiLevelSampler.
Definition at line 96 of file DoubleMLSampler.h.
Referenced by run().
ParticleChooser& DoubleMLSampler::particleChooser2 private
The algorithm for selecting the particles to move.
Definition at line 92 of file DoubleMLSampler.h.
Referenced by run(), and ~DoubleMLSampler().
Permutation DoubleMLSampler::permutation1 private
The permutations.
Definition at line 90 of file DoubleMLSampler.h.
Referenced by run(), and tryMove().
Permutation DoubleMLSampler::permutation2 private
Definition at line 90 of file DoubleMLSampler.h.
Referenced by run(), and tryMove().
PermutationChooser& DoubleMLSampler::permutationChooser2 private
The algorithm for selecting the permutation.
Definition at line 94 of file DoubleMLSampler.h.
Referenced by run(), and ~DoubleMLSampler().
IArray DoubleMLSampler::pMovingIndex2 private
More indicies for moving particles.
Definition at line 84 of file DoubleMLSampler.h.
Referenced by run().
Beads<NDIM>* DoubleMLSampler::rejectedBeads1 private
Storage for the rejected beads.
Definition at line 78 of file DoubleMLSampler.h.
Referenced by activateSection().
Beads<NDIM> * DoubleMLSampler::rejectedBeads2 private
Definition at line 78 of file DoubleMLSampler.h.
Referenced by activateSection(), and ~DoubleMLSampler().
bool DoubleMLSampler::samplingBoth private
Flag for determining whether to sample both sections.
Definition at line 88 of file DoubleMLSampler.h.
Referenced by getAccRejEstimator(), isSamplingBoth(), run(), and tryMove().
Beads<NDIM>* DoubleMLSampler::sectionBeads1 private
Reference to all beads in the section.
Definition at line 72 of file DoubleMLSampler.h.
Referenced by activateSection(), getSectionBeads(), run(), and tryMove().
Beads<NDIM> * DoubleMLSampler::sectionBeads2 private
Definition at line 72 of file DoubleMLSampler.h.
Referenced by activateSection(), getSectionBeads(), run(), and tryMove().
Permutation* DoubleMLSampler::sectionPermutation1 private
Reference the permutation of the in the section.
Definition at line 74 of file DoubleMLSampler.h.
Referenced by activateSection().
Permutation * DoubleMLSampler::sectionPermutation2 private
Definition at line 74 of file DoubleMLSampler.h.
Referenced by activateSection().
The documentation for this class was generated from the following files:
DoubleMLSampler.h
DoubleMLSampler.cc