pi: Path integral Quantum Monte Carlo: GridPotential Class Reference
GridPotential Class Reference
Class for getting action and potential from a grid.
#include <GridPotential.h>
Public Types
typedef blitz::Array< int, 1 > IArray
Typedefs.
typedef blitz::Array< double,
NDIM > ArrayN
typedef blitz::TinyVector< int,
NDIM > IVecN
Public Types inherited from Action
typedef blitz::TinyVector
< double, NDIM > Vec
typedef blitz::Array< Vec, 1 > VArray
Public Member Functions
GridPotential (const SimulationInfo &simInfo, const std::string &filename, bool usePiezo)
Constructor by providing an HDF5 file name and SimulationInfo.
virtual ~GridPotential ()
Virtual destructor.
virtual double getActionDifference (const SectionSamplerInterface &, const int level)
Calculate the difference in action.
virtual double getActionDifference (const Paths &, const VArray &displacement, int nmoving, const IArray &movingIndex, int iFirstSlice, int nslice)
Calculate the difference in action.
virtual double getTotalAction (const Paths &, const int level) const
Calculate the total action.
virtual void getBeadAction (const Paths &, const int ipart, const int islice, double &u, double &utau, double &ulambda, Vec &fm, Vec &fp) const
Calculate the and derivatives at a bead.
Public Member Functions inherited from Action
virtual ~Action ()
virtual void initialize (const SectionChooser &)
Initialize for a sampling section.
virtual void acceptLastMove ()
Accept last move.
virtual const Action * getActionPointerByType (const std::type_info &type) const
Returns pointer to Action of type t, otherwise returns null pointer.
Private Member Functions
double v (Vec, const int ipart) const
Evaluate the potential at a point.
Private Attributes
const double tau
The timestep.
IVecN nvec
The grid dimensions.
double b
Inverse grid spacing.
ArrayN vegrid
The potential grids.
ArrayN vhgrid
std::vector< ArrayN * > vindex
The grid index that associates the particles and grids.
Detailed Description
Class for getting action and potential from a grid.
Todo:
Set up a potential table.
Version:
$Revision$
Author:
John Shumway.
Definition at line 33 of file GridPotential.h.
Member Typedef Documentation
typedef blitz::Array<double,NDIM> GridPotential::ArrayN
Definition at line 37 of file GridPotential.h.
typedef blitz::Array<int,1> GridPotential::IArray
Typedefs.
Reimplemented from Action.
Definition at line 36 of file GridPotential.h.
typedef blitz::TinyVector<int,NDIM> GridPotential::IVecN
Definition at line 38 of file GridPotential.h.
Constructor & Destructor Documentation
GridPotential::GridPotential (const SimulationInfo & simInfo, const std::string & filename, bool usePiezo)
Constructor by providing an HDF5 file name and SimulationInfo.
Definition at line 14 of file GridPotential.cc.
References b, nvec, vegrid, vhgrid, and vindex.
virtual GridPotential::~GridPotential () inline virtual
Virtual destructor.
Definition at line 42 of file GridPotential.h.
Member Function Documentation
double GridPotential::getActionDifference (const SectionSamplerInterface & sampler, const int level) virtual
Calculate the difference in action.
Implements Action.
Definition at line 99 of file GridPotential.cc.
References SuperCell::pbc(), tau, and v().
double GridPotential::getActionDifference (const Paths & paths, const VArray & displacement, int nmoving, const IArray & movingIndex, int iFirstSlice, int nslice) virtual
Calculate the difference in action.
Reimplemented from Action.
Definition at line 221 of file GridPotential.cc.
References SuperCell::pbc(), tau, and v().
void GridPotential::getBeadAction (const Paths & paths, const int ipart, const int islice, double & u, double & utau, double & ulambda, Vec & fm, Vec & fp) const virtual
Calculate the and derivatives at a bead.
Implements Action.
Definition at line 169 of file GridPotential.cc.
References b, nvec, tau, v(), and vindex.
double GridPotential::getTotalAction (const Paths & paths, const int level) const virtual
Calculate the total action.
Implements Action.
Definition at line 164 of file GridPotential.cc.
double GridPotential::v (Vec r, const int ipart) const private
Evaluate the potential at a point.
Definition at line 133 of file GridPotential.cc.
References b, nvec, and vindex.
Referenced by getActionDifference(), and getBeadAction().
Member Data Documentation
double GridPotential::b private
Inverse grid spacing.
Definition at line 60 of file GridPotential.h.
Referenced by getBeadAction(), GridPotential(), and v().
IVecN GridPotential::nvec private
The grid dimensions.
Definition at line 58 of file GridPotential.h.
Referenced by getBeadAction(), GridPotential(), and v().
const double GridPotential::tau private
The timestep.
Definition at line 56 of file GridPotential.h.
Referenced by getActionDifference(), and getBeadAction().
ArrayN GridPotential::vegrid private
The potential grids.
Definition at line 62 of file GridPotential.h.
Referenced by GridPotential().
ArrayN GridPotential::vhgrid private
Definition at line 62 of file GridPotential.h.
Referenced by GridPotential().
std::vector<ArrayN*> GridPotential::vindex private
The grid index that associates the particles and grids.
Definition at line 66 of file GridPotential.h.
Referenced by getBeadAction(), GridPotential(), and v().
The documentation for this class was generated from the following files:
GridPotential.h
GridPotential.cc