pi: Path integral Quantum Monte Carlo: DoubleSectionChooser Class Reference
DoubleSectionChooser Class Reference
Algorithm class for choosing a double section.
#include <DoubleSectionChooser.h>
Public Member Functions
DoubleSectionChooser (int nlevel, int npart, Paths &, Action &, DoubleAction &, const BeadFactory &)
Constructor.
virtual ~DoubleSectionChooser ()
Virtual destructor.
virtual void run ()
Run the algorithm.
void activateSection (const int i)
Set the active section for SectionChooser.
Beads< NDIM > & getBeads (const int i) const
Get the section beads.
Permutation & getPermutation (const int i) const
Get the section permutation.
int getFirstSliceIndex (const int i) const
Get the index of the first slice of the section.
Public Member Functions inherited from SectionChooser
SectionChooser (int nlevel, int npart, Paths &paths, Action &action, const BeadFactory &)
virtual ~SectionChooser ()
Beads< NDIM > & getBeads () const
Permutation & getPermutation () const
int getFirstSliceIndex () const
int getNLevel () const
const Paths & getPaths () const
Public Member Functions inherited from CompositeAlgorithm
CompositeAlgorithm (const int nstep)
Constructor.
virtual ~CompositeAlgorithm ()
Virtual destructor.
void resize (const int n)
Resize the number of steps in the algorithm.
void set (const int i, Algorithm *a)
Set algorithm for step i.
Public Member Functions inherited from Algorithm
virtual ~Algorithm ()
Private Attributes
DoubleAction & doubleAction
The action (SectionChooser initializes Action objects for the section).
Beads< NDIM > * beads1
The section beads.
Beads< NDIM > * beads2
Permutation * permutation1
The section permutation.
Permutation * permutation2
int iFirstSlice1
The index of the first slice of the section.
int iFirstSlice2
Additional Inherited Members
Protected Attributes inherited from SectionChooser
Paths * paths
Action * action
Beads< NDIM > * beads
Permutation * permutation
const int nlevel
int iFirstSlice
gsl_qrng * qrng
Detailed Description
Algorithm class for choosing a double section.
Version:
$Revision$
Author:
John Shumway
Definition at line 14 of file DoubleSectionChooser.h.
Constructor & Destructor Documentation
DoubleSectionChooser::DoubleSectionChooser (int nlevel, int npart, Paths & paths, Action & action, DoubleAction & doubleAction, const BeadFactory & beadFactory)
Constructor.
Definition at line 16 of file DoubleSectionChooser.cc.
DoubleSectionChooser::~DoubleSectionChooser () virtual
Virtual destructor.
Definition at line 26 of file DoubleSectionChooser.cc.
References activateSection(), beads2, and permutation2.
Member Function Documentation
void DoubleSectionChooser::activateSection (const int i)
Set the active section for SectionChooser.
Definition at line 66 of file DoubleSectionChooser.cc.
References SectionChooser::beads, beads1, beads2, SectionChooser::iFirstSlice, iFirstSlice1, iFirstSlice2, SectionChooser::permutation, permutation1, and permutation2.
Referenced by run(), and ~DoubleSectionChooser().
Beads<NDIM>& DoubleSectionChooser::getBeads (const int i) const inline
Get the section beads.
Definition at line 26 of file DoubleSectionChooser.h.
References beads1, and beads2.
Referenced by AnisotropicNodes::initialize(), FixedNodeAction::initialize(), SpinFixedPhaseAction::initialize(), FixedPhaseAction::initialize(), and FreePartNodesNoUpdate::initialize().
int DoubleSectionChooser::getFirstSliceIndex (const int i) const inline
Get the index of the first slice of the section.
Definition at line 34 of file DoubleSectionChooser.h.
References iFirstSlice1, and iFirstSlice2.
Permutation& DoubleSectionChooser::getPermutation (const int i) const inline
Get the section permutation.
Definition at line 30 of file DoubleSectionChooser.h.
References permutation1, and permutation2.
void DoubleSectionChooser::run () virtual
Run the algorithm.
Reimplemented from SectionChooser.
Definition at line 32 of file DoubleSectionChooser.cc.
References SectionChooser::action, activateSection(), SectionChooser::beads, beads1, beads2, doubleAction, Paths::getBeads(), Paths::getHighestSampledSlice(), Paths::getLowestOwnedSlice(), Paths::getNSlice(), Beads< TDIM >::getNSlice(), RandomNumGenerator::getRand(), iFirstSlice1, iFirstSlice2, DoubleAction::initialize(), Action::initialize(), SectionChooser::paths, permutation1, permutation2, Paths::putDoubleBeads(), Permutation::reset(), and Paths::setBuffers().
Member Data Documentation
Beads<NDIM>* DoubleSectionChooser::beads1 mutable private
The section beads.
Definition at line 41 of file DoubleSectionChooser.h.
Referenced by activateSection(), getBeads(), and run().
Beads<NDIM> * DoubleSectionChooser::beads2 mutable private
Definition at line 41 of file DoubleSectionChooser.h.
Referenced by activateSection(), getBeads(), run(), and ~DoubleSectionChooser().
DoubleAction& DoubleSectionChooser::doubleAction private
The action (SectionChooser initializes Action objects for the section).
Definition at line 39 of file DoubleSectionChooser.h.
Referenced by run().
int DoubleSectionChooser::iFirstSlice1 private
The index of the first slice of the section.
Definition at line 45 of file DoubleSectionChooser.h.
Referenced by activateSection(), getFirstSliceIndex(), and run().
int DoubleSectionChooser::iFirstSlice2 private
Definition at line 45 of file DoubleSectionChooser.h.
Referenced by activateSection(), getFirstSliceIndex(), and run().
Permutation* DoubleSectionChooser::permutation1 mutable private
The section permutation.
Definition at line 43 of file DoubleSectionChooser.h.
Referenced by activateSection(), getPermutation(), and run().
Permutation * DoubleSectionChooser::permutation2 mutable private
Definition at line 43 of file DoubleSectionChooser.h.
Referenced by activateSection(), getPermutation(), run(), and ~DoubleSectionChooser().
The documentation for this class was generated from the following files:
DoubleSectionChooser.h
DoubleSectionChooser.cc