pi: Path integral Quantum Monte Carlo: WriteProbDensity Class Reference
WriteProbDensity Class Reference
Class for writing the probability density to a hdf5 file.
#include <WriteProbDensity.h>
Public Types
typedef blitz::TinyVector< int,
NDIM > IVec
Constants and typedefs.
typedef blitz::TinyVector
< double, NDIM > Vec
typedef blitz::Array< long int,
NDIM > LIArrayN
typedef blitz::Array< float, NDIM > FArrayN
Public Member Functions
WriteProbDensity (const SimulationInfo &, const ProbDensityGrid *, const std::string &filename)
Constructor.
virtual ~WriteProbDensity ()
Virtual destructor.
virtual void run ()
Algorithm run method.
Public Member Functions inherited from Algorithm
virtual ~Algorithm ()
Private Attributes
const std::string filename
Name of output file.
const ProbDensityGrid * grids
The grids.
std::vector< std::string > name
The names of the grids.
Detailed Description
Class for writing the probability density to a hdf5 file.
Version:
$Revision$
Author:
John Shumway
Definition at line 31 of file WriteProbDensity.h.
Member Typedef Documentation
typedef blitz::Array<float,NDIM> WriteProbDensity::FArrayN
Definition at line 37 of file WriteProbDensity.h.
typedef blitz::TinyVector<int,NDIM> WriteProbDensity::IVec
Constants and typedefs.
Definition at line 34 of file WriteProbDensity.h.
typedef blitz::Array<long int,NDIM> WriteProbDensity::LIArrayN
Definition at line 36 of file WriteProbDensity.h.
typedef blitz::TinyVector<double,NDIM> WriteProbDensity::Vec
Definition at line 35 of file WriteProbDensity.h.
Constructor & Destructor Documentation
WriteProbDensity::WriteProbDensity (const SimulationInfo & simInfo, const ProbDensityGrid * grid, const std::string & filename)
Constructor.
Definition at line 15 of file WriteProbDensity.cc.
References name.
WriteProbDensity::~WriteProbDensity () virtual
Virtual destructor.
Definition at line 23 of file WriteProbDensity.cc.
Member Function Documentation
void WriteProbDensity::run () virtual
Algorithm run method.
Write a few more attributes for use with DX ImportHDF5Field
Implements Algorithm.
Definition at line 25 of file WriteProbDensity.cc.
References filename, ProbDensityGrid::getGrid(), ProbDensityGrid::getGridDim(), ProbDensityGrid::getLatticeConstant(), ProbDensityGrid::getNorm(), grids, and name.
Member Data Documentation
const std::string WriteProbDensity::filename private
Name of output file.
Definition at line 47 of file WriteProbDensity.h.
Referenced by run().
const ProbDensityGrid* WriteProbDensity::grids private
The grids.
Definition at line 49 of file WriteProbDensity.h.
Referenced by run().
std::vector<std::string> WriteProbDensity::name private
The names of the grids.
Definition at line 51 of file WriteProbDensity.h.
Referenced by run(), and WriteProbDensity().
The documentation for this class was generated from the following files:
WriteProbDensity.h
WriteProbDensity.cc