pi: Path integral Quantum Monte Carlo: JelliumSlab Class Reference
JelliumSlab Class Reference
Class for calculating the primitive action for a jellium slab.
#include <JelliumSlab.h>
Public Types
typedef blitz::Array< int, 1 > IArray
Typedefs.
Public Types inherited from Action
typedef blitz::TinyVector
< double, NDIM > Vec
typedef blitz::Array< Vec, 1 > VArray
Public Member Functions
JelliumSlab (const SimulationInfo &simInfo, const double qtot, const double slabWidth, const bool isSlabInMiddle)
Construct by providing the timestep tau.
virtual ~JelliumSlab ()
Virtual destructor.
virtual double getActionDifference (const SectionSamplerInterface &, const int level)
Calculate the difference in action.
virtual double getTotalAction (const Paths &, const int level) const
Calculate the total action.
virtual void getBeadAction (const Paths &, int ipart, int islice, double &u, double &utau, double &ulambda, Vec &fm, Vec &fp) const
Calculate the action and derivatives at a bead.
Public Member Functions inherited from Action
virtual ~Action ()
virtual double getActionDifference (const Paths &, const VArray &displacement, int nmoving, const IArray &movingIndex, int iFirstSlice, int iLastSlice)
virtual void initialize (const SectionChooser &)
Initialize for a sampling section.
virtual void acceptLastMove ()
Accept last move.
virtual const Action * getActionPointerByType (const std::type_info &type) const
Returns pointer to Action of type t, otherwise returns null pointer.
Private Member Functions
double phi (double x) const
Calculate the electrostatic potential at a point x.
Private Attributes
const double tau
The timestep.
const double q
const double lx
double w
double rhoMid
double rhoEdge
double phiMid
double phiEdge
Static Private Attributes
static const double PI = acos(-1.0)
Detailed Description
Class for calculating the primitive action for a jellium slab.
Can be used to run PIMC simulations like the DMC simulations of Acioli and Ceperley, PRB 54, 17199-17207 (1996). The slab is normal to the x-direction and has a thickness s. For periodic boundary conditions, we need to include a uniform background charge. The density of Q positive charges in the slab is rhoSlab=Q/(s*Ly*Lz). The uniform background charge density is rhoBack=-Q/(Lx*Ly*Lz). The net density is thus rhoSlab+rhoBack inside the slab and rhoBack outside the slab. The boolean flag isSlabInMiddle determines whether the slab or barrier is in the middle of the cell. Call the respective densities rhoMid and rhoEdge, and let w be the width of the middle region. The solution to the Poisson equation is
The constants are chosen to make the potential continuous and sum to zero across the cell,
Version:
$Revision$
Author:
John Shumway.
Definition at line 65 of file JelliumSlab.h.
Member Typedef Documentation
typedef blitz::Array<int,1> JelliumSlab::IArray
Typedefs.
Reimplemented from Action.
Definition at line 68 of file JelliumSlab.h.
Constructor & Destructor Documentation
JelliumSlab::JelliumSlab (const SimulationInfo & simInfo, const double qtot, const double slabWidth, const bool isSlabInMiddle)
Construct by providing the timestep tau.
Definition at line 15 of file JelliumSlab.cc.
References lx, phi(), phiEdge, phiMid, PI, rhoEdge, rhoMid, and w.
virtual JelliumSlab::~JelliumSlab () inline virtual
Virtual destructor.
Definition at line 73 of file JelliumSlab.h.
Member Function Documentation
double JelliumSlab::getActionDifference (const SectionSamplerInterface & sampler, const int level) virtual
Calculate the difference in action.
Implements Action.
Definition at line 43 of file JelliumSlab.cc.
References EwaldAction::cell, SuperCell::pbc(), phi(), q, and tau.
void JelliumSlab::getBeadAction (const Paths & paths, int ipart, int islice, double & u, double & utau, double & ulambda, Vec & fm, Vec & fp) const virtual
Calculate the action and derivatives at a bead.
Implements Action.
Definition at line 75 of file JelliumSlab.cc.
References phi(), q, and tau.
double JelliumSlab::getTotalAction (const Paths & paths, const int level) const virtual
Calculate the total action.
Implements Action.
Definition at line 70 of file JelliumSlab.cc.
double JelliumSlab::phi (double x) const inline private
Calculate the electrostatic potential at a point x.
Definition at line 84 of file JelliumSlab.h.
References lx, phiEdge, phiMid, PI, rhoEdge, rhoMid, and w.
Referenced by getActionDifference(), getBeadAction(), and JelliumSlab().
Member Data Documentation
const double JelliumSlab::lx private
Definition at line 94 of file JelliumSlab.h.
Referenced by JelliumSlab(), and phi().
double JelliumSlab::phiEdge private
Definition at line 97 of file JelliumSlab.h.
Referenced by JelliumSlab(), and phi().
double JelliumSlab::phiMid private
Definition at line 97 of file JelliumSlab.h.
Referenced by JelliumSlab(), and phi().
const double JelliumSlab::PI = acos(-1.0) static private
Definition at line 98 of file JelliumSlab.h.
Referenced by JelliumSlab(), and phi().
const double JelliumSlab::q private
Definition at line 93 of file JelliumSlab.h.
Referenced by getActionDifference(), and getBeadAction().
double JelliumSlab::rhoEdge private
Definition at line 96 of file JelliumSlab.h.
Referenced by JelliumSlab(), and phi().
double JelliumSlab::rhoMid private
Definition at line 96 of file JelliumSlab.h.
Referenced by JelliumSlab(), and phi().
const double JelliumSlab::tau private
The timestep.
Definition at line 92 of file JelliumSlab.h.
Referenced by getActionDifference(), and getBeadAction().
double JelliumSlab::w private
Definition at line 95 of file JelliumSlab.h.
Referenced by JelliumSlab(), and phi().
The documentation for this class was generated from the following files:
JelliumSlab.h
JelliumSlab.cc