pi: Path integral Quantum Monte Carlo: WritePaths Class Reference
WritePaths Class Reference
Algorithm for writting paths to an ascii file.
#include <WritePaths.h>
Public Member Functions
WritePaths (Paths &, const std::string &, int dumpFreq, int maxConfigs, bool writeMovie, const SimulationInfo &simInfo, MPIManager *, const BeadFactory &)
Construct by providing the paths to write.
virtual ~WritePaths ()
Virtual destructor.
virtual void run ()
Write the paths.
Public Member Functions inherited from Algorithm
virtual ~Algorithm ()
Private Attributes
std::string filename
The filename to write to.
Paths & paths
The paths to write out.
MPIManager * mpi
The MPI manager.
const BeadFactory & beadFactory
The BeadFactory.
const int dumpFreq
const SimulationInfo & simInfo
const int maxConfigs
const bool writeMovie
std::ofstream * movieFile
Detailed Description
Algorithm for writting paths to an ascii file.
Last line of the file is the same positions as the first lines, just with the net permuation.
If there are clones (see MPIManager::nclone), then each clone gets its own file, with its cloneID in the name.
To handle mulitiple workers (see MPIManager::nworker) writing is done in stages. Only the first worker writes. The first worker writes from its lowest sample slice to half its highest stored slice. Then the beads are shifted. This process continues until all beads are written.
Because of the uni-directionality of shift, beads are written in reverse time order.
Version:
$Revision$
Bug:
Reading and writting are done backwards because of Paths::shift
Author:
John Shumway
Definition at line 47 of file WritePaths.h.
Constructor & Destructor Documentation
WritePaths::WritePaths (Paths & paths, const std::string & filename, int dumpFreq, int maxConfigs, bool writeMovie, const SimulationInfo & simInfo, MPIManager * mpi, const BeadFactory & beadFactory)
Construct by providing the paths to write.
Definition at line 16 of file WritePaths.cc.
References movieFile.
virtual WritePaths::~WritePaths () inline virtual
Virtual destructor.
Definition at line 54 of file WritePaths.h.
Member Function Documentation
void WritePaths::run () virtual
Write the paths.
Now determine how many chunked steps we need to write out all slices.
Loop over chunks.
Implements Algorithm.
Definition at line 25 of file WritePaths.cc.
References dumpFreq, filename, MPIManager::getCloneID(), MPIManager::getNClone(), MPIManager::getNWorker(), MPIManager::getWorkerID(), maxConfigs, movieFile, mpi, paths, and writeMovie.
Member Data Documentation
const BeadFactory& WritePaths::beadFactory private
The BeadFactory.
Definition at line 65 of file WritePaths.h.
const int WritePaths::dumpFreq private
Definition at line 66 of file WritePaths.h.
Referenced by run().
std::string WritePaths::filename private
The filename to write to.
Definition at line 59 of file WritePaths.h.
Referenced by run().
const int WritePaths::maxConfigs private
Definition at line 68 of file WritePaths.h.
Referenced by run().
std::ofstream* WritePaths::movieFile private
Definition at line 70 of file WritePaths.h.
Referenced by run(), and WritePaths().
MPIManager* WritePaths::mpi private
The MPI manager.
Definition at line 63 of file WritePaths.h.
Referenced by run().
Paths& WritePaths::paths private
The paths to write out.
Definition at line 61 of file WritePaths.h.
Referenced by run().
const SimulationInfo& WritePaths::simInfo private
Definition at line 67 of file WritePaths.h.
const bool WritePaths::writeMovie private
Definition at line 69 of file WritePaths.h.
Referenced by run().
The documentation for this class was generated from the following files:
WritePaths.h
WritePaths.cc