pi: Path integral Quantum Monte Carlo: EstimatorReportBuilder Class Reference
EstimatorReportBuilder Class Reference
Base class for reporting estimators.
#include <EstimatorReportBuilder.h>
Public Member Functions
EstimatorReportBuilder ()
Constructor.
virtual ~EstimatorReportBuilder ()
Virtual destructor.
virtual void startWritingGroup (EstimatorManager &)=0
Start a group for writing.
virtual void writeStep (EstimatorManager &)=0
Write a simulation step to the current writing group.
virtual void startScalarReport (const ScalarEstimator &est)
Method to start reporting a ScalarEstimator.
virtual void reportScalarStep (const ScalarEstimator &est)
Method to write a step for a ScalarEstimator.
virtual void startAccRejReport (const AccRejEstimator &est)
Method to start reporting a AccRejEstimator.
virtual void reportAccRejStep (const AccRejEstimator &est)
Method to write a step for a AccRejEstimator.
virtual void startArrayReport (const ArrayEstimator &est)
Method to start reporting a ArrayEstimator.
virtual void reportArrayStep (const ArrayEstimator &est)
Method to write a step for a ArrayEstimator.
virtual void startArrayBlockedReport (const ArrayBlockedEstimator &est)
Method to start reporting a ArrayBlockedEstimator.
virtual void reportArrayBlockedStep (const ArrayBlockedEstimator &est)
Method to write a step for a ArrayBlockedEstimator.
virtual void recordInputDocument (const std::string &docstring)
Method to record the input file contents.
Detailed Description
Base class for reporting estimators.
We need to write methods for reporting each type of Estimator data.
Version:
$Revision$
Author:
John Shumway
Definition at line 34 of file EstimatorReportBuilder.h.
Constructor & Destructor Documentation
EstimatorReportBuilder::EstimatorReportBuilder () inline
Constructor.
Definition at line 37 of file EstimatorReportBuilder.h.
virtual EstimatorReportBuilder::~EstimatorReportBuilder () inline virtual
Virtual destructor.
Definition at line 39 of file EstimatorReportBuilder.h.
Member Function Documentation
virtual void EstimatorReportBuilder::recordInputDocument (const std::string & docstring) inline virtual
Method to record the input file contents.
Reimplemented in H5ReportBuilder.
Definition at line 61 of file EstimatorReportBuilder.h.
virtual void EstimatorReportBuilder::reportAccRejStep (const AccRejEstimator & est) inline virtual
Method to write a step for a AccRejEstimator.
Reimplemented in H5ReportBuilder, and StdoutReportBuilder.
Definition at line 51 of file EstimatorReportBuilder.h.
Referenced by AccRejEstimator::reportStep().
virtual void EstimatorReportBuilder::reportArrayBlockedStep (const ArrayBlockedEstimator & est) inline virtual
Method to write a step for a ArrayBlockedEstimator.
Reimplemented in H5ReportBuilder, and StdoutReportBuilder.
Definition at line 59 of file EstimatorReportBuilder.h.
Referenced by ArrayBlockedEstimator::reportStep().
virtual void EstimatorReportBuilder::reportArrayStep (const ArrayEstimator & est) inline virtual
Method to write a step for a ArrayEstimator.
Definition at line 55 of file EstimatorReportBuilder.h.
Referenced by ArrayEstimator::reportStep().
virtual void EstimatorReportBuilder::reportScalarStep (const ScalarEstimator & est) inline virtual
Method to write a step for a ScalarEstimator.
Reimplemented in H5ReportBuilder, StdoutReportBuilder, and AsciiReportBuilder.
Definition at line 47 of file EstimatorReportBuilder.h.
Referenced by ScalarEstimator::reportStep().
virtual void EstimatorReportBuilder::startAccRejReport (const AccRejEstimator & est) inline virtual
Method to start reporting a AccRejEstimator.
Reimplemented in H5ReportBuilder, and StdoutReportBuilder.
Definition at line 49 of file EstimatorReportBuilder.h.
Referenced by AccRejEstimator::startReport().
virtual void EstimatorReportBuilder::startArrayBlockedReport (const ArrayBlockedEstimator & est) inline virtual
Method to start reporting a ArrayBlockedEstimator.
Reimplemented in H5ReportBuilder.
Definition at line 57 of file EstimatorReportBuilder.h.
Referenced by ArrayBlockedEstimator::startReport().
virtual void EstimatorReportBuilder::startArrayReport (const ArrayEstimator & est) inline virtual
Method to start reporting a ArrayEstimator.
Definition at line 53 of file EstimatorReportBuilder.h.
Referenced by ArrayEstimator::startReport().
virtual void EstimatorReportBuilder::startScalarReport (const ScalarEstimator & est) inline virtual
Method to start reporting a ScalarEstimator.
Reimplemented in H5ReportBuilder.
Definition at line 45 of file EstimatorReportBuilder.h.
Referenced by ScalarEstimator::startReport().
virtual void EstimatorReportBuilder::startWritingGroup (EstimatorManager &) pure virtual
Start a group for writing.
Implemented in H5ReportBuilder, StdoutReportBuilder, and AsciiReportBuilder.
virtual void EstimatorReportBuilder::writeStep (EstimatorManager &) pure virtual
Write a simulation step to the current writing group.
Implemented in H5ReportBuilder, StdoutReportBuilder, and AsciiReportBuilder.
The documentation for this class was generated from the following file:
EstimatorReportBuilder.h