pi: Path integral Quantum Monte Carlo: DoubleCollectiveSectionSampler Class Reference
DoubleCollectiveSectionSampler Class Reference
#include <DoubleCollectiveSectionSampler.h>
Public Member Functions
DoubleCollectiveSectionSampler (int, DoubleSectionChooser &, Action *, DoubleAction *, int nrepeat, const BeadFactory &, CollectiveSectionMover *, bool, SuperCell *)
virtual ~DoubleCollectiveSectionSampler ()
virtual void run ()
virtual Beads< NDIM > & getMovingBeads (const int i)
virtual const Beads< NDIM > & getMovingBeads (const int i) const
virtual Beads< NDIM > & getSectionBeads (const int i)
virtual const Beads< NDIM > & getSectionBeads (const int i) const
virtual IArray & getMovingIndex (const int i)
virtual const IArray & getMovingIndex (const int i) const
virtual bool isSamplingBoth () const
virtual AccRejEstimator * getAccRejEstimator (const std::string &name)
Public Member Functions inherited from CollectiveSectionSampler
CollectiveSectionSampler (int, SectionChooser &, Action *, int, const BeadFactory &, CollectiveSectionMover *, SuperCell *)
virtual ~CollectiveSectionSampler ()
virtual Beads< NDIM > & getSectionBeads ()
virtual const Beads< NDIM > & getSectionBeads () const
virtual Beads< NDIM > & getMovingBeads ()
virtual const Beads< NDIM > & getMovingBeads () const
virtual const IArray & getMovingIndex () const
virtual const SuperCell & getSuperCell () const
virtual int getFirstSliceIndex () const
Public Member Functions inherited from Algorithm
virtual ~Algorithm ()
Public Member Functions inherited from SectionSamplerInterface
virtual ~SectionSamplerInterface ()
Private Member Functions
bool tryMove ()
Private Attributes
Beads< NDIM > * sectionBeads1
Beads< NDIM > * sectionBeads2
Beads< NDIM > * movingBeads1
Beads< NDIM > * movingBeads2
IArray * movingIndex1
IArray * movingIndex2
DoubleAction * doubleAction
bool samplingBoth
Additional Inherited Members
Protected Attributes inherited from CollectiveSectionSampler
const int nlevel
const int npart
Beads< NDIM > * sectionBeads
Beads< NDIM > * movingBeads
IArray * movingIndex
IArray identityIndex
SectionChooser & sectionChooser
SuperCell * cell
Action * action
const int nrepeat
const int maximumMovingCount
CollectiveSectionMover * mover
AccRejEstimator * accRejEst
Detailed Description
Definition at line 14 of file DoubleCollectiveSectionSampler.h.
Constructor & Destructor Documentation
DoubleCollectiveSectionSampler::DoubleCollectiveSectionSampler (int npart, DoubleSectionChooser & sectionChooser, Action * action, DoubleAction * doubleAction, int nrepeat, const BeadFactory & beadFactory, CollectiveSectionMover * mover, bool both, SuperCell * cell)
Definition at line 18 of file DoubleCollectiveSectionSampler.cc.
References movingIndex2, and CollectiveSectionSampler::npart.
DoubleCollectiveSectionSampler::~DoubleCollectiveSectionSampler () virtual
Definition at line 33 of file DoubleCollectiveSectionSampler.cc.
References movingBeads2, and movingIndex2.
Member Function Documentation
AccRejEstimator * DoubleCollectiveSectionSampler::getAccRejEstimator (const std::string & name) virtual
Reimplemented from CollectiveSectionSampler.
Definition at line 94 of file DoubleCollectiveSectionSampler.cc.
References CollectiveSectionSampler::accRejEst, CollectiveSectionSampler::npart, and samplingBoth.
virtual Beads<NDIM>& DoubleCollectiveSectionSampler::getMovingBeads (const int i) inline virtual
Reimplemented from CollectiveSectionSampler.
Definition at line 24 of file DoubleCollectiveSectionSampler.h.
References movingBeads1, and movingBeads2.
virtual const Beads<NDIM>& DoubleCollectiveSectionSampler::getMovingBeads (const int i) const inline virtual
Reimplemented from CollectiveSectionSampler.
Definition at line 27 of file DoubleCollectiveSectionSampler.h.
References movingBeads1, and movingBeads2.
virtual IArray& DoubleCollectiveSectionSampler::getMovingIndex (const int i) inline virtual
Definition at line 40 of file DoubleCollectiveSectionSampler.h.
References movingIndex1, and movingIndex2.
virtual const IArray& DoubleCollectiveSectionSampler::getMovingIndex (const int i) const inline virtual
Reimplemented from CollectiveSectionSampler.
Definition at line 43 of file DoubleCollectiveSectionSampler.h.
References movingIndex1, and movingIndex2.
virtual Beads<NDIM>& DoubleCollectiveSectionSampler::getSectionBeads (const int i) inline virtual
Reimplemented from CollectiveSectionSampler.
Definition at line 32 of file DoubleCollectiveSectionSampler.h.
References sectionBeads1, and sectionBeads2.
virtual const Beads<NDIM>& DoubleCollectiveSectionSampler::getSectionBeads (const int i) const inline virtual
Reimplemented from CollectiveSectionSampler.
Definition at line 35 of file DoubleCollectiveSectionSampler.h.
References sectionBeads1, and sectionBeads2.
virtual bool DoubleCollectiveSectionSampler::isSamplingBoth () const inline virtual
Reimplemented from CollectiveSectionSampler.
Definition at line 47 of file DoubleCollectiveSectionSampler.h.
References samplingBoth.
void DoubleCollectiveSectionSampler::run () virtual
Reimplemented from CollectiveSectionSampler.
Definition at line 39 of file DoubleCollectiveSectionSampler.cc.
References BeadsBase::copySlice(), Beads< TDIM >::getNSlice(), CollectiveSectionSampler::identityIndex, CollectiveSectionSampler::movingBeads, movingBeads1, movingBeads2, movingIndex1, movingIndex2, CollectiveSectionSampler::nrepeat, samplingBoth, sectionBeads1, sectionBeads2, and tryMove().
bool DoubleCollectiveSectionSampler::tryMove () private
Reimplemented from CollectiveSectionSampler.
Definition at line 56 of file DoubleCollectiveSectionSampler.cc.
References DoubleAction::acceptLastMove(), Action::acceptLastMove(), CollectiveSectionSampler::accRejEst, CollectiveSectionSampler::action, BeadsBase::copySlice(), doubleAction, DoubleAction::getActionDifference(), Action::getActionDifference(), Beads< TDIM >::getNSlice(), RandomNumGenerator::getRand(), CollectiveSectionSampler::identityIndex, CollectiveSectionMover::makeMove(), AccRejEstimator::moveAccepted(), CollectiveSectionSampler::mover, CollectiveSectionSampler::movingBeads, movingBeads1, movingBeads2, CollectiveSectionSampler::movingIndex, movingIndex1, movingIndex2, samplingBoth, CollectiveSectionSampler::sectionBeads, sectionBeads1, sectionBeads2, and AccRejEstimator::tryingMove().
Referenced by run().
Member Data Documentation
DoubleAction* DoubleCollectiveSectionSampler::doubleAction private
Definition at line 58 of file DoubleCollectiveSectionSampler.h.
Referenced by tryMove().
Beads<NDIM>* DoubleCollectiveSectionSampler::movingBeads1 private
Definition at line 56 of file DoubleCollectiveSectionSampler.h.
Referenced by getMovingBeads(), run(), and tryMove().
Beads<NDIM> * DoubleCollectiveSectionSampler::movingBeads2 private
Definition at line 56 of file DoubleCollectiveSectionSampler.h.
Referenced by getMovingBeads(), run(), tryMove(), and ~DoubleCollectiveSectionSampler().
IArray* DoubleCollectiveSectionSampler::movingIndex1 private
Definition at line 57 of file DoubleCollectiveSectionSampler.h.
Referenced by getMovingIndex(), run(), and tryMove().
IArray * DoubleCollectiveSectionSampler::movingIndex2 private
Definition at line 57 of file DoubleCollectiveSectionSampler.h.
Referenced by DoubleCollectiveSectionSampler(), getMovingIndex(), run(), tryMove(), and ~DoubleCollectiveSectionSampler().
bool DoubleCollectiveSectionSampler::samplingBoth private
Definition at line 59 of file DoubleCollectiveSectionSampler.h.
Referenced by getAccRejEstimator(), isSamplingBoth(), run(), and tryMove().
Beads<NDIM>* DoubleCollectiveSectionSampler::sectionBeads1 private
Definition at line 55 of file DoubleCollectiveSectionSampler.h.
Referenced by getSectionBeads(), run(), and tryMove().
Beads<NDIM> * DoubleCollectiveSectionSampler::sectionBeads2 private
Definition at line 55 of file DoubleCollectiveSectionSampler.h.
Referenced by getSectionBeads(), run(), and tryMove().
The documentation for this class was generated from the following files:
DoubleCollectiveSectionSampler.h
DoubleCollectiveSectionSampler.cc