pi: Path integral Quantum Monte Carlo: CompositeAlgorithm Class Reference
CompositeAlgorithm Class Reference
Algorithm class combining several steps.
#include <CompositeAlgorithm.h>
Public Member Functions
CompositeAlgorithm (const int nstep)
Constructor.
virtual ~CompositeAlgorithm ()
Virtual destructor.
virtual void run ()
Run the algorithm.
void resize (const int n)
Resize the number of steps in the algorithm.
void set (const int i, Algorithm *a)
Set algorithm for step i.
Public Member Functions inherited from Algorithm
virtual ~Algorithm ()
Private Attributes
std::vector< Algorithm * > step
Steps in the algorithm.
Detailed Description
Algorithm class combining several steps.
Version:
$Revision$
Author:
John Shumway
Definition at line 26 of file CompositeAlgorithm.h.
Constructor & Destructor Documentation
CompositeAlgorithm::CompositeAlgorithm (const int nstep) inline
Constructor.
Definition at line 29 of file CompositeAlgorithm.h.
virtual CompositeAlgorithm::~CompositeAlgorithm () inline virtual
Virtual destructor.
Definition at line 31 of file CompositeAlgorithm.h.
References step.
Member Function Documentation
void CompositeAlgorithm::resize (const int n) inline
Resize the number of steps in the algorithm.
Definition at line 39 of file CompositeAlgorithm.h.
References step.
Referenced by PIMCParser::parseBody().
virtual void CompositeAlgorithm::run () inline virtual
Run the algorithm.
Implements Algorithm.
Reimplemented in Loop, and WorkerShifter.
Definition at line 35 of file CompositeAlgorithm.h.
References step.
Referenced by Loop::run().
void CompositeAlgorithm::set (const int i, Algorithm * a) inline
Set algorithm for step i.
Definition at line 44 of file CompositeAlgorithm.h.
References step.
Referenced by PIMCParser::parseBody().
Member Data Documentation
std::vector<Algorithm*> CompositeAlgorithm::step private
Steps in the algorithm.
Definition at line 47 of file CompositeAlgorithm.h.
Referenced by resize(), run(), set(), and ~CompositeAlgorithm().
The documentation for this class was generated from the following file:
CompositeAlgorithm.h