pi: Path integral Quantum Monte Carlo: RandomNumGenerator Class Reference
RandomNumGenerator Class Reference
The random number generator.
#include <RandomNumGenerator.h>
Static Public Member Functions
static void seed (const int iseed)
static double getRand ()
Get a random number.
static void makeRand (blitz::Array< double, 1 > &a)
Fill a blitz array with uniform random numbers.
template<int N>
static void makeRand (blitz::Array< blitz::TinyVector< double, N >, 1 > &a)
Fill a blitz array with uniform random numbers.
static void makeGaussRand (blitz::Array< double, 1 > &a)
Fill a blitz array with Gaussian distributed random numbers using Box-Mueller algorithm.
template<int TDIM>
static void makeGaussRand (blitz::Array< blitz::TinyVector< double, TDIM >, 1 > &a)
Fill a blitz TinyVector Array` with Gaussian distributed random numbers using Box-Mueller algorithm.
Static Private Member Functions
static void makeGaussRand (double *a, const int n)
Fill a c-style array with Gaussian distributed random numbers using Box-Mueller algorithm.
Static Private Attributes
static const double SCALE_RAND = 1./RAND_MAX
Detailed Description
The random number generator.
Version:
$Revision$
Author:
John Shumway
Definition at line 23 of file RandomNumGenerator.h.
Member Function Documentation
static double RandomNumGenerator::getRand () inline static
Get a random number.
Definition at line 42 of file RandomNumGenerator.h.
References SCALE_RAND.
Referenced by EMARateMover::getRandomNumber(), makeGaussRand(), makeRand(), WorkerShifter::run(), and CubicLattice::run().
static void RandomNumGenerator::makeGaussRand (blitz::Array< double, 1 > & a) inline static
Fill a blitz array with Gaussian distributed random numbers using Box-Mueller algorithm.
Definition at line 60 of file RandomNumGenerator.h.
Referenced by EMARateMover::makeGaussianRandomNumbers(), makeGaussRand(), SpinMover::makeMove(), and FreeSpinMover::makeMove().
template<int TDIM> static void RandomNumGenerator::makeGaussRand (blitz::Array< blitz::TinyVector< double, TDIM >, 1 > & a) inline static
Fill a blitz TinyVector Array` with Gaussian distributed random numbers using Box-Mueller algorithm.
Definition at line 67 of file RandomNumGenerator.h.
References makeGaussRand().
static void RandomNumGenerator::makeGaussRand (double * a, const int n) inline static private
Fill a c-style array with Gaussian distributed random numbers using Box-Mueller algorithm.
Definition at line 75 of file RandomNumGenerator.h.
References getRand().
static void RandomNumGenerator::makeRand (blitz::Array< double, 1 > & a) inline static
Fill a blitz array with uniform random numbers.
Definition at line 46 of file RandomNumGenerator.h.
References getRand().
template<int N> static void RandomNumGenerator::makeRand (blitz::Array< blitz::TinyVector< double, N >, 1 > & a) inline static
Fill a blitz array with uniform random numbers.
Definition at line 52 of file RandomNumGenerator.h.
References getRand().
static void RandomNumGenerator::seed (const int iseed) inline static
Definition at line 26 of file RandomNumGenerator.h.
Referenced by SeedRandom::run().
Member Data Documentation
const double RandomNumGenerator::SCALE_RAND = 1./RAND_MAX static private
Definition at line 72 of file RandomNumGenerator.h.
Referenced by getRand().
The documentation for this class was generated from the following files:
RandomNumGenerator.h
RandomNumGenerator.cc