pi: Path integral Quantum Monte Carlo: ImagePairAction Class Reference
ImagePairAction Class Reference
Class for calculating pair action between particles.
#include <ImagePairAction.h>
Public Types
typedef blitz::TinyVector< int,
NDIM > IVec
Typedefs.
Public Types inherited from PairAction
typedef blitz::Array< int, 1 > IArray
Typedefs.
typedef blitz::Array< double, 1 > Array
typedef blitz::Array< double, 2 > Array2
typedef blitz::Array< double, 3 > Array3
Public Types inherited from Action
typedef blitz::TinyVector
< double, NDIM > Vec
typedef blitz::Array< Vec, 1 > VArray
Public Member Functions
ImagePairAction (const Species &, const Species &, const std::string &filename, const SimulationInfo &, const int norder, const IVec nimage, const bool isDMD, int exLevel)
Construct by providing the species and dmu filename.
ImagePairAction (const Species &, const Species &, const EmpiricalPairAction &, const SimulationInfo &, const int norder, const IVec nimage, const double rmin, const double rmax, const int ngpts, int exLevel)
Construct by providing the species and dmu filename.
virtual ~ImagePairAction ()
Virtual destructor.
virtual double getActionDifference (const SectionSamplerInterface &, int level)
Calculate the difference in action.
virtual double getTotalAction (const Paths &, const int level) const
Calculate the total action.
virtual void getBeadAction (const Paths &, const int ipart, const int islice, double &u, double &utau, double &ulambda, Vec &fm, Vec &fp) const
Calculate the action and derivatives at a bead.
Public Member Functions inherited from PairAction
PairAction (const Species &, const Species &, const std::string &filename, const SimulationInfo &, const int norder, const bool hasZ, int exLevel)
Construct by providing the species and squarer pidmu filename.
PairAction (const Species &, const Species &, const std::string &filename, const SimulationInfo &, const int norder, const bool hasZ, const bool isDMD, int exLevel)
Construct by providing the species and dmu filename.
PairAction (const Species &, const Species &, const EmpiricalPairAction &, const SimulationInfo &, const int norder, const double rmin, const double rmax, const int ngpts, const bool hasZ, int exLevel)
Construct by providing the species and EmpiricalPairAction.
PairAction (const Species &, const Species &, PairIntegrator &, const SimulationInfo &, const int norder, const double rmin, const double rmax, const int ngpts, int exLevel)
Construct by providing the species and PairIntegrator.
virtual ~PairAction ()
Virtual destructor.
virtual double getActionDifference (const Paths &, const VArray &displacement, int nmoving, const IArray &movingIndex, int iFirstSlice, int iLastSlice)
Calculate the difference in action.
void write (const std::string &filename, const bool hasZ) const
Write data tables to disk (defaults to speciesNames.dm[eu]).
Public Member Functions inherited from Action
virtual ~Action ()
virtual void initialize (const SectionChooser &)
Initialize for a sampling section.
virtual void acceptLastMove ()
Accept last move.
virtual const Action * getActionPointerByType (const std::type_info &type) const
Returns pointer to Action of type t, otherwise returns null pointer.
Private Attributes
const IVec nimage
The number of images.
Friends
class EwaldAction
Additional Inherited Members
Protected Member Functions inherited from PairAction
double u00 (double r) const
Evalute the diagonal action from the grid.
double uk0 (double q, double s2) const
Evalute the off-diagonal action from the grid.
double uk0 (double q, double s2, double z2) const
Evalute the off-diagonal action from the grid.
void uk0CalcDerivatives (double q, double s2, double &u, double &utau, double &uq, double &us2) const
Evaluate the derivatives of the action from the grid.
void uk0CalcDerivatives (double q, double s2, double z2, double &u, double &utau, double &uq, double &us2, double &uz2) const
Evaluate the derivatives of the action from the grid.
Protected Attributes inherited from PairAction
const double tau
The timestep.
int ngpts
The number of gridpoints.
double rgridinv
The first grid radial value.
double logrratioinv
The log of the ratio of consecutive grid points.
Array3 ugrid
The action grid (radial coord is logrithmic).
const Species & species1
The species.
const Species & species2
int ifirst1
Indicies of first particles of each species.
int ifirst2
int npart1
Number of each particle for species in the interaction.
int npart2
int norder
Order of the off-diagonal expansion.
bool isDMD
Flag for using the format from DMD downloaded from Ceperley site.
bool hasZ
Flag for including sum over z.
const int exLevel
Level to start evaluating exchange.
const double mass
Mass of first species, needed for evaluating exchange.
Detailed Description
Class for calculating pair action between particles.
We tabulate and store the action as a radial function, with angular dependence stored as a power series. We take advantage of the extra symmetry of the coulomb action. The variables are
and
The action and its tau derivative are stored as radial grids,
and
The derivatives of the action (for the VirialEnergyEstimator) are given by
where
and
The partial derivatives of the action are straightforward to calculate:
and
Version:
$Revision$
Todo:
Make a version for non-coulomb actions.
Author:
John Shumway.
Definition at line 56 of file ImagePairAction.h.
Member Typedef Documentation
typedef blitz::TinyVector<int,NDIM> ImagePairAction::IVec
Typedefs.
Definition at line 59 of file ImagePairAction.h.
Constructor & Destructor Documentation
ImagePairAction::ImagePairAction (const Species & s1, const Species & s2, const std::string & filename, const SimulationInfo & simInfo, const int norder, const IVec nimage, const bool isDMD, int exLevel)
Construct by providing the species and dmu filename.
Definition at line 14 of file ImagePairAction.cc.
ImagePairAction::ImagePairAction (const Species & s1, const Species & s2, const EmpiricalPairAction & action, const SimulationInfo & simInfo, const int norder, const IVec nimage, const double rmin, const double rmax, const int ngpts, int exLevel)
Construct by providing the species and dmu filename.
Definition at line 22 of file ImagePairAction.cc.
virtual ImagePairAction::~ImagePairAction () inline virtual
Virtual destructor.
Definition at line 69 of file ImagePairAction.h.
Member Function Documentation
double ImagePairAction::getActionDifference (const SectionSamplerInterface & sampler, int level) virtual
Calculate the difference in action.
Reimplemented from PairAction.
Definition at line 32 of file ImagePairAction.cc.
References SuperCell::a, PairAction::ifirst1, PairAction::ifirst2, nimage, PairAction::npart1, PairAction::npart2, SuperCell::pbc(), PairAction::u00(), and PairAction::uk0().
void ImagePairAction::getBeadAction (const Paths & paths, const int ipart, const int islice, double & u, double & utau, double & ulambda, Vec & fm, Vec & fp) const virtual
Calculate the action and derivatives at a bead.
Reimplemented from PairAction.
Definition at line 108 of file ImagePairAction.cc.
References SuperCell::a, PairAction::ifirst1, PairAction::ifirst2, nimage, PairAction::npart1, PairAction::npart2, SuperCell::pbc(), and PairAction::uk0CalcDerivatives().
double ImagePairAction::getTotalAction (const Paths & paths, const int level) const virtual
Calculate the total action.
Reimplemented from PairAction.
Definition at line 104 of file ImagePairAction.cc.
Friends And Related Function Documentation
friend class EwaldAction friend
Reimplemented from PairAction.
Definition at line 78 of file ImagePairAction.h.
Member Data Documentation
const IVec ImagePairAction::nimage private
The number of images.
Definition at line 81 of file ImagePairAction.h.
Referenced by getActionDifference(), and getBeadAction().
The documentation for this class was generated from the following files:
ImagePairAction.h
ImagePairAction.cc