pi: Path integral Quantum Monte Carlo: UniformMover Class Reference
UniformMover Class Reference
#include <UniformMover.h>
Public Types
typedef blitz::Array< int, 1 > IArray
typedef blitz::Array< double, 1 > Array
typedef blitz::TinyVector
< double, NDIM > Vec
typedef blitz::Array< Vec, 1 > VArray
Public Member Functions
UniformMover (const Vec dist, const MPIManager *mpi)
virtual ~UniformMover ()
virtual double makeMove (VArray &, const IArray &) const
Protected Attributes
const MPIManager * mpi
Private Attributes
const Vec dist
Detailed Description
Definition at line 11 of file UniformMover.h.
Member Typedef Documentation
typedef blitz::Array<double, 1> UniformMover::Array
Reimplemented in CollectiveMover, and ExchangeMover.
Definition at line 14 of file UniformMover.h.
typedef blitz::Array<int, 1> UniformMover::IArray
Reimplemented in CollectiveMover, and ExchangeMover.
Definition at line 13 of file UniformMover.h.
typedef blitz::Array<Vec, 1> UniformMover::VArray
Reimplemented in CollectiveMover, and ExchangeMover.
Definition at line 16 of file UniformMover.h.
typedef blitz::TinyVector<double, NDIM> UniformMover::Vec
Reimplemented in CollectiveMover, and ExchangeMover.
Definition at line 15 of file UniformMover.h.
Constructor & Destructor Documentation
UniformMover::UniformMover (const Vec dist, const MPIManager * mpi)
Definition at line 19 of file UniformMover.cc.
UniformMover::~UniformMover () virtual
Definition at line 24 of file UniformMover.cc.
Member Function Documentation
double UniformMover::makeMove (VArray & displacement, const IArray & movingIndex) const virtual
Reimplemented in CollectiveMover, and ExchangeMover.
Definition at line 27 of file UniformMover.cc.
References dist, MPIManager::getNWorker(), RandomNumGenerator::makeRand(), and mpi.
Referenced by DoubleDisplaceMoveSampler::tryMove(), and DisplaceMoveSampler::tryMove().
Member Data Documentation
const Vec UniformMover::dist private
Definition at line 24 of file UniformMover.h.
Referenced by makeMove().
const MPIManager* UniformMover::mpi protected
Definition at line 22 of file UniformMover.h.
Referenced by makeMove(), and ExchangeMover::makeMove().
The documentation for this class was generated from the following files:
UniformMover.h
UniformMover.cc