pi: Path integral Quantum Monte Carlo: PhaseModel Class Reference
PhaseModel Class Reference
Base class for phase models used in the fixed phase method.
#include <PhaseModel.h>
Public Types
typedef blitz::TinyVector
< double, NDIM > Vec
typedef blitz::Array< Vec, 1 > VArray
Public Member Functions
PhaseModel (const int npart)
Constructor.
virtual ~PhaseModel ()
Virtual destructor.
virtual void evaluate (const VArray &, const VArray &, const int islice)=0
Evaluate the PhaseModel.
double getPhi () const
Get the value of the phase.
const VArray & getGradPhi (const int i) const
Get the value of the gradient of the phase.
const VArray & getVecPot (const int i) const
Get the value of the vector potential.
Protected Attributes
double phi
The value of the phase.
VArray gradPhi1
The gradient of the phase.
VArray gradPhi2
VArray vecPot1
The vector potential.
VArray vecPot2
Detailed Description
Base class for phase models used in the fixed phase method.
Suppose we have density matrix of complex funtion, we can write . We need the derivative of density matrix,
Divide by on each side, we get
Now we can get the derivative of the phase.
How to get in the simulation?
Version:
$Revision$
Author:
Daejin Shin and John Shumway
Definition at line 38 of file PhaseModel.h.
Member Typedef Documentation
typedef blitz::Array<Vec,1> PhaseModel::VArray
Definition at line 41 of file PhaseModel.h.
typedef blitz::TinyVector<double,NDIM> PhaseModel::Vec
Reimplemented in SHOPhase.
Definition at line 40 of file PhaseModel.h.
Constructor & Destructor Documentation
PhaseModel::PhaseModel (const int npart) inline
Constructor.
Definition at line 43 of file PhaseModel.h.
virtual PhaseModel::~PhaseModel () inline virtual
Virtual destructor.
Definition at line 46 of file PhaseModel.h.
Member Function Documentation
virtual void PhaseModel::evaluate (const VArray & , const VArray & , const int islice) pure virtual
Evaluate the PhaseModel.
Implemented in SHOPhase, and Spin4DPhase.
Referenced by FixedPhaseAction::getActionDifference(), FixedPhaseAction::getBeadAction(), AngularMomentumEstimator::handleLink(), and FixedPhaseAction::initialize().
const VArray& PhaseModel::getGradPhi (const int i) const inline
Get the value of the gradient of the phase.
Definition at line 52 of file PhaseModel.h.
References gradPhi1, and gradPhi2.
Referenced by FixedPhaseAction::getActionDifference(), FixedPhaseAction::getBeadAction(), AngularMomentumEstimator::handleLink(), and FixedPhaseAction::initialize().
double PhaseModel::getPhi () const inline
Get the value of the phase.
Definition at line 50 of file PhaseModel.h.
References phi.
Referenced by FixedPhaseAction::getActionDifference(), FixedPhaseAction::getBeadAction(), and FixedPhaseAction::initialize().
const VArray& PhaseModel::getVecPot (const int i) const inline
Get the value of the vector potential.
Definition at line 54 of file PhaseModel.h.
References vecPot1, and vecPot2.
Referenced by FixedPhaseAction::getActionDifference(), FixedPhaseAction::getBeadAction(), and FixedPhaseAction::initialize().
Member Data Documentation
VArray PhaseModel::gradPhi1 protected
The gradient of the phase.
Definition at line 59 of file PhaseModel.h.
Referenced by Spin4DPhase::evaluate(), SHOPhase::evaluate(), and getGradPhi().
VArray PhaseModel::gradPhi2 protected
Definition at line 59 of file PhaseModel.h.
Referenced by Spin4DPhase::evaluate(), SHOPhase::evaluate(), and getGradPhi().
double PhaseModel::phi protected
The value of the phase.
Definition at line 57 of file PhaseModel.h.
Referenced by SHOPhase::evaluate(), and getPhi().
VArray PhaseModel::vecPot1 protected
The vector potential.
Definition at line 61 of file PhaseModel.h.
Referenced by Spin4DPhase::evaluate(), SHOPhase::evaluate(), and getVecPot().
VArray PhaseModel::vecPot2 protected
Definition at line 61 of file PhaseModel.h.
Referenced by Spin4DPhase::evaluate(), SHOPhase::evaluate(), and getVecPot().
The documentation for this class was generated from the following file:
PhaseModel.h