pi: Path integral Quantum Monte Carlo: StdoutReportBuilder Class Reference
StdoutReportBuilder Class Reference
Class for reporting estimators to standard output.
#include <StdoutReportBuilder.h>
Public Member Functions
StdoutReportBuilder ()
Constructor.
virtual ~StdoutReportBuilder ()
Virtual destructor.
virtual void startWritingGroup (EstimatorManager &)
Start a group for writing.
virtual void writeStep (EstimatorManager &)
Write a simulation step to the current writing group.
virtual void reportScalarStep (const ScalarEstimator &est)
Report a step of scalar data.
virtual void startAccRejReport (const AccRejEstimator &est)
Method to start reporting a AccRejEstimator.
virtual void reportAccRejStep (const AccRejEstimator &est)
Method to write a step for a AccRejEstimator.
virtual void reportArrayBlockedStep (const ArrayBlockedEstimator &est)
Report a step of array data.
Public Member Functions inherited from EstimatorReportBuilder
EstimatorReportBuilder ()
Constructor.
virtual ~EstimatorReportBuilder ()
Virtual destructor.
virtual void startScalarReport (const ScalarEstimator &est)
Method to start reporting a ScalarEstimator.
virtual void startArrayReport (const ArrayEstimator &est)
Method to start reporting a ArrayEstimator.
virtual void reportArrayStep (const ArrayEstimator &est)
Method to write a step for a ArrayEstimator.
virtual void startArrayBlockedReport (const ArrayBlockedEstimator &est)
Method to start reporting a ArrayBlockedEstimator.
virtual void recordInputDocument (const std::string &docstring)
Method to record the input file contents.
Private Types
typedef blitz::Array< double, 1 > Array
Private Attributes
int nstep
int istep
int iscalar
Array sum
The sum of the estimator.
Array sum2
Array norm
Detailed Description
Class for reporting estimators to standard output.
Version:
$Revision$
Author:
John Shumway
Definition at line 29 of file StdoutReportBuilder.h.
Member Typedef Documentation
typedef blitz::Array<double,1> StdoutReportBuilder::Array private
Definition at line 48 of file StdoutReportBuilder.h.
Constructor & Destructor Documentation
StdoutReportBuilder::StdoutReportBuilder () inline
Constructor.
Definition at line 32 of file StdoutReportBuilder.h.
virtual StdoutReportBuilder::~StdoutReportBuilder () inline virtual
Virtual destructor.
Definition at line 34 of file StdoutReportBuilder.h.
Member Function Documentation
void StdoutReportBuilder::reportAccRejStep (const AccRejEstimator & est) virtual
Method to write a step for a AccRejEstimator.
Reimplemented from EstimatorReportBuilder.
Definition at line 66 of file StdoutReportBuilder.cc.
References AccRejEstimator::getNAccept(), Estimator::getName(), AccRejEstimator::getNLevel(), and AccRejEstimator::getNTrial().
void StdoutReportBuilder::reportArrayBlockedStep (const ArrayBlockedEstimator & est) virtual
Report a step of array data.
Reimplemented from EstimatorReportBuilder.
Definition at line 82 of file StdoutReportBuilder.cc.
References Estimator::getName().
void StdoutReportBuilder::reportScalarStep (const ScalarEstimator & est) virtual
Report a step of scalar data.
Reimplemented from EstimatorReportBuilder.
Definition at line 53 of file StdoutReportBuilder.cc.
References Estimator::getName(), Estimator::getUnitName(), ScalarEstimator::getValue(), iscalar, norm, sum, and sum2.
virtual void StdoutReportBuilder::startAccRejReport (const AccRejEstimator & est) inline virtual
Method to start reporting a AccRejEstimator.
Reimplemented from EstimatorReportBuilder.
Definition at line 42 of file StdoutReportBuilder.h.
void StdoutReportBuilder::startWritingGroup (EstimatorManager & manager) virtual
Start a group for writing.
Implements EstimatorReportBuilder.
Definition at line 29 of file StdoutReportBuilder.cc.
References EstimatorManager::estimator, istep, norm, nstep, EstimatorManager::nstep, sum, and sum2.
void StdoutReportBuilder::writeStep (EstimatorManager & manager) virtual
Write a simulation step to the current writing group.
Implements EstimatorReportBuilder.
Definition at line 37 of file StdoutReportBuilder.cc.
References EstimatorManager::estimator, iscalar, istep, and nstep.
Member Data Documentation
int StdoutReportBuilder::iscalar private
Definition at line 51 of file StdoutReportBuilder.h.
Referenced by reportScalarStep(), and writeStep().
int StdoutReportBuilder::istep private
Definition at line 50 of file StdoutReportBuilder.h.
Referenced by startWritingGroup(), and writeStep().
Array StdoutReportBuilder::norm private
Definition at line 53 of file StdoutReportBuilder.h.
Referenced by reportScalarStep(), and startWritingGroup().
int StdoutReportBuilder::nstep private
Definition at line 49 of file StdoutReportBuilder.h.
Referenced by startWritingGroup(), and writeStep().
Array StdoutReportBuilder::sum private
The sum of the estimator.
Definition at line 53 of file StdoutReportBuilder.h.
Referenced by reportScalarStep(), and startWritingGroup().
Array StdoutReportBuilder::sum2 private
Definition at line 53 of file StdoutReportBuilder.h.
Referenced by reportScalarStep(), and startWritingGroup().
The documentation for this class was generated from the following files:
StdoutReportBuilder.h
StdoutReportBuilder.cc