pi: Path integral Quantum Monte Carlo: Paths Class Reference
Paths Class Reference
Class for Paths, including Beads, connectivity (including any Permutation), the time step and SuperCell.
#include <Paths.h>
Public Types
typedef blitz::TinyVector
< double, NDIM > Vec
Constants and typedefs.
typedef blitz::Array< Vec, 1 > VArray
Public Member Functions
Paths (int npart, int nslice, double tau, const SuperCell &cell)
Constructor.
virtual ~Paths ()
Destructor.
virtual void sumOverLinks (LinkSummable &) const =0
Loop over links, calling a LinkSummable object.
int getNPart () const
Get the number of particles.
int getNSlice () const
Get the number of slices.
double getTau () const
Get the number of slices on this processor.
const SuperCell & getSuperCell () const
Get the supercell.
virtual Vec & operator() (int ipart, int islice)=0
Get a reference to a bead.
virtual const Vec & operator() (int ipart, int islice) const =0
Get a const reference to a bead.
virtual Vec & operator() (int ipart, int islice, int istep)=0
Get a reference to a bead by offset.
virtual const Vec & operator() (int ipart, int islice, int istep) const =0
Get a const reference to a bead by offset.
virtual Vec delta (int ipart, int islice, int istep) const =0
Get a relative displacement a bead by offset.
virtual void getBeads (int ifirstSlice, Beads< NDIM > &) const =0
Get beads.
virtual const void * getAuxBead (int ipart, int islice, int iaux) const =0
Get auxialiary bead.
virtual void * getAuxBead (int ipart, int islice, int iaux)=0
Get auxialiary bead.
virtual void getSlice (int islice, VArray &) const =0
Get a slice.
virtual void putBeads (int ifirstSlice, const Beads< NDIM > &, const Permutation &) const =0
Put beads.
virtual void putDoubleBeads (int ifirstSlice1, Beads< NDIM > &, Permutation &, int ifirstSlice2, Beads< NDIM > &, Permutation &) const =0
virtual const Permutation & getPermutation () const =0
Get the global permuation.
virtual const Permutation & getGlobalPermutation () const =0
virtual int getLowestOwnedSlice (bool d) const =0
virtual int getHighestOwnedSlice (bool d) const =0
virtual int getHighestSampledSlice (int n, bool d) const =0
virtual bool isOwnedSlice (int islice) const =0
virtual void shift (int ishift)=0
virtual void setBuffers ()
virtual bool isDouble () const
virtual void clearPermutation ()=0
ModelState * getModelState ()
const ModelState * getModelState () const
void setModelState (ModelState *m)
bool hasModelState ()
Protected Attributes
const int npart
Number of particles.
const int nslice
Number of slices.
const double tau
The temperature of one timestep.
const SuperCell & cell
The supercell.
ModelState * modelState
Detailed Description
Class for Paths, including Beads, connectivity (including any Permutation), the time step and SuperCell.
Several operations are needed for paths:
Check out and check in of a section of beads for multi level sampling.
Looping over all beads to accumulate estimators.
Accessing single beads with read-only or read-write access.
Get the global permuation of the particles.
In parallel simulations with multiple workers, each worker owns some of the slices. Further, the worker will have some other workers' slices buffered, which it has access to in read-only mode. To check out paths or set the coordinates, it is necessary to know which slices a path owns. The notion or ownership is also need to perform the sumOverLinks. Note that in parallel simulations is it often necessary to freeze a slice during MultiLevelSampling in order to prevent extra communication; hence the last slice owned in a parallel simulation may be treated as read-only by a SectionChooser. The following methods give information about ownership and allowed sampling
isOwnedSlice
getLowestOwnedSlice
getHighestOwnedSlice
getHigestSampledSlice
Finally, for parallel simulations it is necessary to shift the slices so that boundaries betweenw workers get sampled. For parallel fermion simulations, beads are stored for two sections, and this condition is flagged by the isDoubleMethod.
Version:
$Revision$
Author:
John Shumway
Definition at line 58 of file Paths.h.
Member Typedef Documentation
typedef blitz::Array<Vec,1> Paths::VArray
Definition at line 62 of file Paths.h.
typedef blitz::TinyVector<double,NDIM> Paths::Vec
Constants and typedefs.
Definition at line 61 of file Paths.h.
Constructor & Destructor Documentation
Paths::Paths (int npart, int nslice, double tau, const SuperCell & cell)
Constructor.
Definition at line 22 of file Paths.cc.
virtual Paths::~Paths () inline virtual
Destructor.
Definition at line 66 of file Paths.h.
Member Function Documentation
virtual void Paths::clearPermutation () pure virtual
Implemented in ParallelPaths, DoubleParallelPaths, and SerialPaths.
Referenced by PathReader::run().
virtual Vec Paths::delta (int ipart, int islice, int istep) const pure virtual
Get a relative displacement a bead by offset.
Implemented in ParallelPaths, DoubleParallelPaths, and SerialPaths.
Referenced by SpringTensorAction::getBeadAction(), SpringAction::getBeadAction(), HyperbolicAction::getBeadAction(), and SHOAction::getBeadAction().
virtual const void* Paths::getAuxBead (int ipart, int islice, int iaux) const pure virtual
Get auxialiary bead.
Implemented in ParallelPaths, DoubleParallelPaths, and SerialPaths.
Referenced by SpinEstimator::handleLink(), and SpinSetter::run().
virtual void* Paths::getAuxBead (int ipart, int islice, int iaux) pure virtual
Get auxialiary bead.
Implemented in ParallelPaths, DoubleParallelPaths, and SerialPaths.
virtual void Paths::getBeads (int ifirstSlice, Beads< NDIM > &) const pure virtual
Get beads.
Implemented in ParallelPaths, DoubleParallelPaths, and SerialPaths.
Referenced by MiddleSectionChooser::run(), SectionChooser::run(), NonZeroSectionChooser::run(), and DoubleSectionChooser::run().
virtual const Permutation& Paths::getGlobalPermutation () const pure virtual
Implemented in ParallelPaths, DoubleParallelPaths, and SerialPaths.
Referenced by PermutationEstimator::evaluate(), WritePaths::run(), and SpinModelSampler::tryMove().
virtual int Paths::getHighestOwnedSlice (bool d) const pure virtual
Implemented in ParallelPaths, DoubleParallelPaths, and SerialPaths.
Referenced by DoubleDisplaceMoveSampler::DoubleDisplaceMoveSampler(), SpinChoiceFixedNodeAction::getActionChoiceDifference(), SpinSetter::run(), StructReader::run(), RingLattice::run(), CubicLattice::run(), and WritePaths::run().
virtual int Paths::getHighestSampledSlice (int n, bool d) const pure virtual
Implemented in ParallelPaths, DoubleParallelPaths, and SerialPaths.
Referenced by NonZeroSectionChooser::run(), SectionChooser::run(), and DoubleSectionChooser::run().
virtual int Paths::getLowestOwnedSlice (bool d) const pure virtual
Implemented in ParallelPaths, DoubleParallelPaths, and SerialPaths.
Referenced by DoubleDisplaceMoveSampler::DoubleDisplaceMoveSampler(), SpinChoiceFixedNodeAction::getActionChoiceDifference(), PIMCParser::parseAlgorithm(), NonZeroSectionChooser::run(), SectionChooser::run(), DoubleSectionChooser::run(), SpinSetter::run(), StructReader::run(), RingLattice::run(), CubicLattice::run(), and WritePaths::run().
ModelState* Paths::getModelState () inline
Definition at line 118 of file Paths.h.
References modelState.
Referenced by FreeEnergyEstimator::evaluate(), PIMCParser::parseAlgorithm(), PathReader::run(), and WritePaths::run().
const ModelState* Paths::getModelState () const inline
Definition at line 119 of file Paths.h.
References modelState.
int Paths::getNPart () const inline
Get the number of particles.
Definition at line 70 of file Paths.h.
References npart.
Referenced by GaussianAction::getBeadAction(), DotGeomAction::getBeadAction(), PIMCParser::parseAlgorithm(), PathReader::run(), WritePaths::run(), and EwaldCoulombEstimator::testEwaldTotalCharge().
int Paths::getNSlice () const inline
Get the number of slices.
Definition at line 72 of file Paths.h.
References nslice.
Referenced by SpinChoiceFixedNodeAction::getActionChoiceDifference(), FixedNodeAction::getActionDifference(), SpinAction::getBeadAction(), FixedNodeAction::getBeadAction(), FixedPhaseAction::getBeadAction(), SpinFixedPhaseAction::getBeadAction(), FreePartNodesNoUpdate::getBeadAction(), MiddleSectionChooser::MiddleSectionChooser(), NonZeroSectionChooser::run(), DoubleSectionChooser::run(), SpinSetter::run(), PathReader::run(), StructReader::run(), RingLattice::run(), CubicLattice::run(), and WritePaths::run().
virtual const Permutation& Paths::getPermutation () const pure virtual
Get the global permuation.
Implemented in ParallelPaths, DoubleParallelPaths, and SerialPaths.
Referenced by JEstimator::evaluate(), and DisplaceMoveSampler::getGlobalPermutation().
virtual void Paths::getSlice (int islice, VArray &) const pure virtual
Get a slice.
Implemented in ParallelPaths, DoubleParallelPaths, and SerialPaths.
Referenced by CoulombAction::getAction(), CoulombAction::getBeadAction(), and EwaldCoulombEstimator::handleLink().
const SuperCell& Paths::getSuperCell () const inline
Get the supercell.
Definition at line 80 of file Paths.h.
References cell.
Referenced by CoulombAction::getActionDifference(), EwaldImagePairAction::getActionDifference(), GateAction::getActionDifference(), SHODotAction::getActionDifference(), GridPotential::getActionDifference(), EFieldAction::getActionDifference(), TimpQPC::getActionDifference(), FixedNodeAction::getActionDifference(), PairAction::getActionDifference(), GaussianDotAction::getBeadAction(), GaussianAction::getBeadAction(), EwaldImagePairAction::getBeadAction(), StillWebAction::getBeadAction(), ImagePairAction::getBeadAction(), PairAction::getBeadAction(), CoulombEnergyEstimator::handleLink(), SpinSetter::run(), RingLattice::run(), and CubicLattice::run().
double Paths::getTau () const inline
Get the number of slices on this processor.
Get the number of slices owned by this processor. Get the temperature for a slice.
Definition at line 78 of file Paths.h.
References tau.
bool Paths::hasModelState () inline
Definition at line 121 of file Paths.h.
References modelState.
Referenced by PathReader::run(), and WritePaths::run().
virtual bool Paths::isDouble () const inline virtual
Reimplemented in DoubleParallelPaths.
Definition at line 116 of file Paths.h.
Referenced by SpinSetter::run(), StructReader::run(), RingLattice::run(), and CubicLattice::run().
virtual bool Paths::isOwnedSlice (int islice) const pure virtual
Implemented in ParallelPaths, DoubleParallelPaths, and SerialPaths.
Referenced by PathReader::run().
virtual Vec& Paths::operator() (int ipart, int islice) pure virtual
Get a reference to a bead.
Implemented in ParallelPaths, DoubleParallelPaths, and SerialPaths.
virtual const Vec& Paths::operator() (int ipart, int islice) const pure virtual
Get a const reference to a bead.
Implemented in ParallelPaths, DoubleParallelPaths, and SerialPaths.
virtual Vec& Paths::operator() (int ipart, int islice, int istep) pure virtual
Get a reference to a bead by offset.
Implemented in ParallelPaths, DoubleParallelPaths, and SerialPaths.
virtual const Vec& Paths::operator() (int ipart, int islice, int istep) const pure virtual
Get a const reference to a bead by offset.
Implemented in ParallelPaths, DoubleParallelPaths, and SerialPaths.
virtual void Paths::putBeads (int ifirstSlice, const Beads< NDIM > & , const Permutation &) const pure virtual
Put beads.
Implemented in ParallelPaths, DoubleParallelPaths, and SerialPaths.
Referenced by MiddleSectionChooser::run(), SectionChooser::run(), NonZeroSectionChooser::run(), and PathReader::run().
virtual void Paths::putDoubleBeads (int ifirstSlice1, Beads< NDIM > & , Permutation & , int ifirstSlice2, Beads< NDIM > & , Permutation &) const pure virtual
Implemented in ParallelPaths, DoubleParallelPaths, and SerialPaths.
Referenced by DoubleSectionChooser::run().
virtual void Paths::setBuffers () inline virtual
Reimplemented in ParallelPaths, and DoubleParallelPaths.
Definition at line 115 of file Paths.h.
Referenced by MiddleSectionChooser::run(), NonZeroSectionChooser::run(), SectionChooser::run(), DoubleSectionChooser::run(), PathReader::run(), StructReader::run(), RingLattice::run(), and CubicLattice::run().
void Paths::setModelState (ModelState * m) inline
Definition at line 120 of file Paths.h.
References modelState.
Referenced by PIMCParser::parse().
virtual void Paths::shift (int ishift) pure virtual
Implemented in ParallelPaths, DoubleParallelPaths, and SerialPaths.
Referenced by WorkerShifter::run(), and WritePaths::run().
virtual void Paths::sumOverLinks (LinkSummable &) const pure virtual
Loop over links, calling a LinkSummable object.
Implemented in ParallelPaths, DoubleParallelPaths, and SerialPaths.
Referenced by ProbDensityGrid::bin(), EMARateEstimator::evaluate(), JEstimator::evaluate(), WindingEstimator::evaluate(), DipoleMomentEstimator::evaluate(), ConductivityEstimator2D::evaluate(), CoulombEnergyEstimator::evaluate(), PositionEstimator::evaluate(), DiamagneticEstimator::evaluate(), SpinEstimator::evaluate(), BondLengthEstimator::evaluate(), FrequencyEstimator::evaluate(), AngularMomentumEstimator::evaluate(), BoxEstimator::evaluate(), ThermoEnergyEstimator::evaluate(), EwaldCoulombEstimator::evaluate(), DensityCurrentEstimator::evaluate(), VirialEnergyEstimator::evaluate(), DensityEstimator::evaluate(), ConductivityEstimator::evaluate(), DensCountEstimator::evaluate(), EIndEstimator::evaluate(), ConductanceEstimator::evaluate(), SKOmegaEstimator::evaluate(), SpinChargeEstimator::evaluate(), DynamicPCFEstimator::evaluate(), VIndEstimator::evaluate(), CountCountEstimator::evaluate(), DensDensEstimator::evaluate(), PairCFEstimator< N >::evaluate(), SpinChoicePCFEstimator< N >::evaluate(), ZeroVarDensityEstimator::evaluate(), DoubleActionChoice::getActionChoiceDifference(), and ActionChoice::getActionChoiceDifference().
Member Data Documentation
const SuperCell& Paths::cell protected
The supercell.
Definition at line 130 of file Paths.h.
Referenced by SerialPaths::delta(), DoubleParallelPaths::delta(), ParallelPaths::delta(), and getSuperCell().
ModelState* Paths::modelState protected
Definition at line 132 of file Paths.h.
Referenced by getModelState(), hasModelState(), and setModelState().
const int Paths::npart protected
Number of particles.
Definition at line 124 of file Paths.h.
Referenced by DoubleParallelPaths::getBeads(), ParallelPaths::getBeads(), DoubleParallelPaths::getGlobalPermutation(), ParallelPaths::getGlobalPermutation(), getNPart(), SerialPaths::getSlice(), DoubleParallelPaths::getSlice(), ParallelPaths::getSlice(), DoubleParallelPaths::putBeads(), SerialPaths::putBeads(), ParallelPaths::putBeads(), DoubleParallelPaths::setBuffers(), ParallelPaths::setBuffers(), SerialPaths::shift(), DoubleParallelPaths::shift(), ParallelPaths::shift(), SerialPaths::sumOverLinks(), DoubleParallelPaths::sumOverLinks(), and ParallelPaths::sumOverLinks().
const int Paths::nslice protected
Number of slices.
Definition at line 126 of file Paths.h.
Referenced by SerialPaths::delta(), DoubleParallelPaths::delta(), ParallelPaths::delta(), DoubleParallelPaths::getAuxBead(), ParallelPaths::getAuxBead(), SerialPaths::getBeads(), DoubleParallelPaths::getBeads(), ParallelPaths::getBeads(), getNSlice(), DoubleParallelPaths::getSlice(), ParallelPaths::getSlice(), SerialPaths::isOwnedSlice(), DoubleParallelPaths::isOwnedSlice(), SerialPaths::operator()(), DoubleParallelPaths::operator()(), ParallelPaths::operator()(), DoubleParallelPaths::putBeads(), SerialPaths::putBeads(), ParallelPaths::putBeads(), SerialPaths::putDoubleBeads(), SerialPaths::shift(), SerialPaths::sumOverLinks(), DoubleParallelPaths::sumOverLinks(), and ParallelPaths::sumOverLinks().
const double Paths::tau protected
The temperature of one timestep.
Definition at line 128 of file Paths.h.
Referenced by getTau().
The documentation for this class was generated from the following files:
Paths.h
Paths.cc