pi: Path integral Quantum Monte Carlo: StillWebAction Class Reference
StillWebAction Class Reference
Class for calculating the primitive action for the Stillinger-Weber potential.
#include <StillWebAction.h>
Classes
class SWParam
Subclass for storage of species dependent parameters.
Public Types
typedef blitz::Array< int, 1 > IArray
Typedefs.
typedef blitz::Array< double, 2 > Array2
Public Types inherited from Action
typedef blitz::TinyVector
< double, NDIM > Vec
typedef blitz::Array< Vec, 1 > VArray
Public Member Functions
StillWebAction (const SimulationInfo &, const std::string &filename)
Construct by providing the simulation info and structure file (for neighbor tables).
virtual ~StillWebAction ()
Virtual destructor.
virtual double getActionDifference (const SectionSamplerInterface &, int level)
Calculate the difference in action.
virtual double getTotalAction (const Paths &, const int level) const
Calculate the total action.
virtual void getBeadAction (const Paths &, int ipart, int islice, double &u, double &utau, double &ulambda, Vec &fm, Vec &fp) const
Calculate the action and derivatives at a bead.
virtual double f2 (const double r, const int i, const int j) const
Evaluate the pair potential.
virtual double h (const double r1, const double r2, const double costheta, const int i, const int j, const int k) const
Evaluate the angle potential.
Public Member Functions inherited from Action
virtual ~Action ()
virtual double getActionDifference (const Paths &, const VArray &displacement, int nmoving, const IArray &movingIndex, int iFirstSlice, int iLastSlice)
virtual void initialize (const SectionChooser &)
Initialize for a sampling section.
virtual void acceptLastMove ()
Accept last move.
virtual const Action * getActionPointerByType (const std::type_info &type) const
Returns pointer to Action of type t, otherwise returns null pointer.
Private Attributes
const double tau
The timestep.
const int npart
The number of particles.
double A
SW parameters.
double B
double p
double q
double a
double gamma
std::vector< SWParam > param
Parameters for SiSi, GeGe, SiGe.
Array2 nn
Neighbor tables.
int nnmax
Maximum number of neighbors in neighbor table.
Detailed Description
Class for calculating the primitive action for the Stillinger-Weber potential.
Taken from Stillinger and Weber, PRB 31, 5262-5271 (1985), online at http://link.aps.org/abstract/PRB/v31/p5262. The pairwise interaction is a function of separation,
and zero for larger separations.
There is an angular interaction between bonds,
Si-Si lattice paramters is 10.246 Bohr radii (T=0K).
Bug:
Assumes only one particle is moving.
Todo:
Add neighbor table.
Version:
$Revision$
Author:
John Shumway.
Definition at line 50 of file StillWebAction.h.
Member Typedef Documentation
typedef blitz::Array<double,2> StillWebAction::Array2
Definition at line 54 of file StillWebAction.h.
typedef blitz::Array<int,1> StillWebAction::IArray
Typedefs.
Reimplemented from Action.
Definition at line 53 of file StillWebAction.h.
Constructor & Destructor Documentation
StillWebAction::StillWebAction (const SimulationInfo & simInfo, const std::string & filename)
Construct by providing the simulation info and structure file (for neighbor tables).
Definition at line 14 of file StillWebAction.cc.
References param.
virtual StillWebAction::~StillWebAction () inline virtual
Virtual destructor.
Definition at line 59 of file StillWebAction.h.
Member Function Documentation
double StillWebAction::f2 (const double r, const int i, const int j) const virtual
Evaluate the pair potential.
Definition at line 127 of file StillWebAction.cc.
References A, a, B, StillWebAction::SWParam::epsilon, p, param, and StillWebAction::SWParam::sigmainv.
Referenced by getActionDifference(), and getBeadAction().
double StillWebAction::getActionDifference (const SectionSamplerInterface & sampler, int level) virtual
Calculate the difference in action.
Implements Action.
Definition at line 34 of file StillWebAction.cc.
References f2(), h(), npart, SuperCell::pbc(), and tau.
void StillWebAction::getBeadAction (const Paths & paths, int ipart, int islice, double & u, double & utau, double & ulambda, Vec & fm, Vec & fp) const virtual
Calculate the action and derivatives at a bead.
Implements Action.
Definition at line 87 of file StillWebAction.cc.
References f2(), h(), npart, SuperCell::pbc(), and tau.
double StillWebAction::getTotalAction (const Paths & paths, const int level) const virtual
Calculate the total action.
Implements Action.
Definition at line 82 of file StillWebAction.cc.
double StillWebAction::h (const double r1, const double r2, const double costheta, const int i, const int j, const int k) const virtual
Evaluate the angle potential.
Definition at line 111 of file StillWebAction.cc.
References a, StillWebAction::SWParam::epsilon, gamma, StillWebAction::SWParam::lambda, param, and StillWebAction::SWParam::sigmainv.
Referenced by getActionDifference(), and getBeadAction().
Member Data Documentation
double StillWebAction::A private
SW parameters.
Definition at line 89 of file StillWebAction.h.
Referenced by f2().
double StillWebAction::a private
Definition at line 93 of file StillWebAction.h.
Referenced by f2(), and h().
double StillWebAction::B private
Definition at line 90 of file StillWebAction.h.
Referenced by f2().
double StillWebAction::gamma private
Definition at line 94 of file StillWebAction.h.
Referenced by h().
Array2 StillWebAction::nn private
Neighbor tables.
Definition at line 98 of file StillWebAction.h.
int StillWebAction::nnmax private
Maximum number of neighbors in neighbor table.
Definition at line 100 of file StillWebAction.h.
const int StillWebAction::npart private
The number of particles.
Definition at line 87 of file StillWebAction.h.
Referenced by getActionDifference(), and getBeadAction().
double StillWebAction::p private
Definition at line 91 of file StillWebAction.h.
Referenced by f2().
std::vector<SWParam> StillWebAction::param private
Parameters for SiSi, GeGe, SiGe.
Definition at line 96 of file StillWebAction.h.
Referenced by f2(), h(), and StillWebAction().
double StillWebAction::q private
Definition at line 92 of file StillWebAction.h.
const double StillWebAction::tau private
The timestep.
Definition at line 85 of file StillWebAction.h.
Referenced by getActionDifference(), and getBeadAction().
The documentation for this class was generated from the following files:
StillWebAction.h
StillWebAction.cc