pi: Path integral Quantum Monte Carlo: SpinModelSampler Class Reference
SpinModelSampler Class Reference
Class to sample different action models.
#include <SpinModelSampler.h>
Public Types
typedef blitz::Array< int, 1 > IArray
typedef blitz::TinyVector
< double, NDIM > Vec
typedef blitz::Array< Vec, 1 > VArray
Public Member Functions
SpinModelSampler (Paths &, Action *, ActionChoiceBase *, const MPIManager *mpi)
virtual ~SpinModelSampler ()
virtual void run ()
virtual AccRejEstimator * getAccRejEstimator (const std::string &name)
Get a pointer to the accept/reject statistic estimator.
Public Member Functions inherited from Algorithm
virtual ~Algorithm ()
Protected Member Functions
virtual bool tryMove ()
Protected Attributes
Paths & paths
Action * action
ActionChoiceBase * actionChoice
SpinModelState & modelState
const int nmodel
AccRejEstimator * accRejEst
const MPIManager * mpi
Detailed Description
Class to sample different action models.
Definition at line 19 of file SpinModelSampler.h.
Member Typedef Documentation
typedef blitz::Array<int, 1> SpinModelSampler::IArray
Definition at line 21 of file SpinModelSampler.h.
typedef blitz::Array<Vec, 1> SpinModelSampler::VArray
Definition at line 23 of file SpinModelSampler.h.
typedef blitz::TinyVector<double, NDIM> SpinModelSampler::Vec
Definition at line 22 of file SpinModelSampler.h.
Constructor & Destructor Documentation
SpinModelSampler::SpinModelSampler (Paths & paths, Action * action, ActionChoiceBase * actionChoice, const MPIManager * mpi)
Definition at line 19 of file SpinModelSampler.cc.
SpinModelSampler::~SpinModelSampler () virtual
Definition at line 30 of file SpinModelSampler.cc.
Member Function Documentation
AccRejEstimator * SpinModelSampler::getAccRejEstimator (const std::string & name) virtual
Get a pointer to the accept/reject statistic estimator.
(You are responsible for deleting this new object.)
Definition at line 91 of file SpinModelSampler.cc.
References accRejEst.
void SpinModelSampler::run () virtual
Implements Algorithm.
Definition at line 33 of file SpinModelSampler.cc.
References tryMove().
bool SpinModelSampler::tryMove () protected virtual
Definition at line 38 of file SpinModelSampler.cc.
References accRejEst, actionChoice, SpinModelState::broadcastToMPIWorkers(), SpinModelState::flipSpin(), ActionChoiceBase::getActionChoiceDifference(), Paths::getGlobalPermutation(), RandomNumGenerator::getRand(), MPIManager::getWorkerID(), modelState, AccRejEstimator::moveAccepted(), mpi, nmodel, paths, and AccRejEstimator::tryingMove().
Referenced by run().
Member Data Documentation
AccRejEstimator* SpinModelSampler::accRejEst protected
Definition at line 39 of file SpinModelSampler.h.
Referenced by getAccRejEstimator(), and tryMove().
Action* SpinModelSampler::action protected
Definition at line 35 of file SpinModelSampler.h.
ActionChoiceBase* SpinModelSampler::actionChoice protected
Definition at line 36 of file SpinModelSampler.h.
Referenced by tryMove().
SpinModelState& SpinModelSampler::modelState protected
Definition at line 37 of file SpinModelSampler.h.
Referenced by tryMove().
const MPIManager* SpinModelSampler::mpi protected
Definition at line 40 of file SpinModelSampler.h.
Referenced by tryMove().
const int SpinModelSampler::nmodel protected
Definition at line 38 of file SpinModelSampler.h.
Referenced by tryMove().
Paths& SpinModelSampler::paths protected
Definition at line 34 of file SpinModelSampler.h.
Referenced by tryMove().
The documentation for this class was generated from the following files:
SpinModelSampler.h
SpinModelSampler.cc