pi: Path integral Quantum Monte Carlo: ArrayBlockedEstimator Class Reference
ArrayBlockedEstimator Class Reference
Base class for scalar estimators.
#include <ArrayBlockedEstimator.h>
Public Member Functions
ArrayBlockedEstimator (const std::string &name, const std::string &typeString, bool hasError)
Construct by giving the name.
virtual ~ArrayBlockedEstimator ()
Virtual destructor.
virtual void reset ()=0
Clear the value.
virtual void startReport (EstimatorReportBuilder &builder)
Callback EstimatorReportBuilder method for blocked arrays.
virtual void reportStep (EstimatorReportBuilder &builder)
Callback EstimatorReportBuilder method for blocked arrays.
virtual int getNDim () const =0
Get the number of dimensions in the array.
virtual int getExtent (const int idim) const =0
Get the extent of the array in dimensions idim.
virtual const void * getData () const =0
Get a pointer to the data.
virtual const void * getError () const =0
bool hasError () const
virtual void normalize () const =0
virtual void unnormalize () const =0
virtual bool hasScale () const =0
virtual bool hasOrigin () const =0
virtual const void * getScale () const =0
virtual const void * getOrigin () const =0
virtual bool hasMin () const =0
virtual bool hasMax () const =0
virtual const void * getMin () const =0
virtual const void * getMax () const =0
Public Member Functions inherited from Estimator
Estimator (const std::string &name)
Construct by giving the name of the estimator.
Estimator (const std::string &name, const std::string &typeString, const std::string &unitName)
Construct by giving the name of the estimator.
virtual ~Estimator ()
Virtual destructor.
const std::string & getName () const
Get the name of the estimator.
const std::string & getUnitName () const
Get the name of the unit for the estimator.
const std::string & getTypeString () const
Get the type string for this estimators.
virtual void evaluate (const Paths &)=0
Evaluate estimator for a path configuration.
virtual void averageOverClones (const MPIManager *)
Average over clones.
Protected Attributes
bool hasErrorFlag
Detailed Description
Base class for scalar estimators.
Version:
$Revision$
Author:
John Shumway
Definition at line 27 of file ArrayBlockedEstimator.h.
Constructor & Destructor Documentation
ArrayBlockedEstimator::ArrayBlockedEstimator (const std::string & name, const std::string & typeString, bool hasError)
Construct by giving the name.
Definition at line 22 of file ArrayBlockedEstimator.cc.
ArrayBlockedEstimator::~ArrayBlockedEstimator () virtual
Virtual destructor.
Definition at line 27 of file ArrayBlockedEstimator.cc.
Member Function Documentation
virtual const void* ArrayBlockedEstimator::getData () const pure virtual
Get a pointer to the data.
Implemented in BlitzArrayBlkdEst< N >, BlitzArrayBlkdEst< NDIM+3 >, BlitzArrayBlkdEst< NDIM+2 >, BlitzArrayBlkdEst< 1 >, BlitzArrayBlkdEst< 2 >, BlitzArrayBlkdEst< 3 >, BlitzArrayBlkdEst< 5 >, BlitzArrayBlkdEst< NDIM+1 >, BlitzArrayBlkdEst< 6 >, BlitzArrayBlkdEst< 7 >, BlitzArrayBlkdEst< NDIM >, BlitzArrayBlkdEst< 2 *NDIM+3 >, and BlitzArrayBlkdEst< 2 *NDIM+1 >.
Referenced by H5ReportBuilder::reportArrayBlockedStep().
virtual const void* ArrayBlockedEstimator::getError () const pure virtual
Implemented in BlitzArrayBlkdEst< N >, BlitzArrayBlkdEst< NDIM+3 >, BlitzArrayBlkdEst< NDIM+2 >, BlitzArrayBlkdEst< 1 >, BlitzArrayBlkdEst< 2 >, BlitzArrayBlkdEst< 3 >, BlitzArrayBlkdEst< 5 >, BlitzArrayBlkdEst< NDIM+1 >, BlitzArrayBlkdEst< 6 >, BlitzArrayBlkdEst< 7 >, BlitzArrayBlkdEst< NDIM >, BlitzArrayBlkdEst< 2 *NDIM+3 >, and BlitzArrayBlkdEst< 2 *NDIM+1 >.
Referenced by H5ReportBuilder::reportArrayBlockedStep().
virtual int ArrayBlockedEstimator::getExtent (const int idim) const pure virtual
Get the extent of the array in dimensions idim.
Implemented in BlitzArrayBlkdEst< N >, BlitzArrayBlkdEst< NDIM+3 >, BlitzArrayBlkdEst< NDIM+2 >, BlitzArrayBlkdEst< 1 >, BlitzArrayBlkdEst< 2 >, BlitzArrayBlkdEst< 3 >, BlitzArrayBlkdEst< 5 >, BlitzArrayBlkdEst< NDIM+1 >, BlitzArrayBlkdEst< 6 >, BlitzArrayBlkdEst< 7 >, BlitzArrayBlkdEst< NDIM >, BlitzArrayBlkdEst< 2 *NDIM+3 >, and BlitzArrayBlkdEst< 2 *NDIM+1 >.
Referenced by H5ReportBuilder::startArrayBlockedReport().
virtual const void* ArrayBlockedEstimator::getMax () const pure virtual
Implemented in BlitzArrayBlkdEst< N >, BlitzArrayBlkdEst< NDIM+3 >, BlitzArrayBlkdEst< NDIM+2 >, BlitzArrayBlkdEst< 1 >, BlitzArrayBlkdEst< 2 >, BlitzArrayBlkdEst< 3 >, BlitzArrayBlkdEst< 5 >, BlitzArrayBlkdEst< NDIM+1 >, BlitzArrayBlkdEst< 6 >, BlitzArrayBlkdEst< 7 >, BlitzArrayBlkdEst< NDIM >, BlitzArrayBlkdEst< 2 *NDIM+3 >, and BlitzArrayBlkdEst< 2 *NDIM+1 >.
Referenced by H5ReportBuilder::startArrayBlockedReport().
virtual const void* ArrayBlockedEstimator::getMin () const pure virtual
Implemented in BlitzArrayBlkdEst< N >, BlitzArrayBlkdEst< NDIM+3 >, BlitzArrayBlkdEst< NDIM+2 >, BlitzArrayBlkdEst< 1 >, BlitzArrayBlkdEst< 2 >, BlitzArrayBlkdEst< 3 >, BlitzArrayBlkdEst< 5 >, BlitzArrayBlkdEst< NDIM+1 >, BlitzArrayBlkdEst< 6 >, BlitzArrayBlkdEst< 7 >, BlitzArrayBlkdEst< NDIM >, BlitzArrayBlkdEst< 2 *NDIM+3 >, and BlitzArrayBlkdEst< 2 *NDIM+1 >.
Referenced by H5ReportBuilder::startArrayBlockedReport().
virtual int ArrayBlockedEstimator::getNDim () const pure virtual
Get the number of dimensions in the array.
Implemented in BlitzArrayBlkdEst< N >, BlitzArrayBlkdEst< NDIM+3 >, BlitzArrayBlkdEst< NDIM+2 >, BlitzArrayBlkdEst< 1 >, BlitzArrayBlkdEst< 2 >, BlitzArrayBlkdEst< 3 >, BlitzArrayBlkdEst< 5 >, BlitzArrayBlkdEst< NDIM+1 >, BlitzArrayBlkdEst< 6 >, BlitzArrayBlkdEst< 7 >, BlitzArrayBlkdEst< NDIM >, BlitzArrayBlkdEst< 2 *NDIM+3 >, and BlitzArrayBlkdEst< 2 *NDIM+1 >.
Referenced by H5ReportBuilder::startArrayBlockedReport().
virtual const void* ArrayBlockedEstimator::getOrigin () const pure virtual
Implemented in BlitzArrayBlkdEst< N >, BlitzArrayBlkdEst< NDIM+3 >, BlitzArrayBlkdEst< NDIM+2 >, BlitzArrayBlkdEst< 1 >, BlitzArrayBlkdEst< 2 >, BlitzArrayBlkdEst< 3 >, BlitzArrayBlkdEst< 5 >, BlitzArrayBlkdEst< NDIM+1 >, BlitzArrayBlkdEst< 6 >, BlitzArrayBlkdEst< 7 >, BlitzArrayBlkdEst< NDIM >, BlitzArrayBlkdEst< 2 *NDIM+3 >, and BlitzArrayBlkdEst< 2 *NDIM+1 >.
Referenced by H5ReportBuilder::startArrayBlockedReport().
virtual const void* ArrayBlockedEstimator::getScale () const pure virtual
Implemented in BlitzArrayBlkdEst< N >, BlitzArrayBlkdEst< NDIM+3 >, BlitzArrayBlkdEst< NDIM+2 >, BlitzArrayBlkdEst< 1 >, BlitzArrayBlkdEst< 2 >, BlitzArrayBlkdEst< 3 >, BlitzArrayBlkdEst< 5 >, BlitzArrayBlkdEst< NDIM+1 >, BlitzArrayBlkdEst< 6 >, BlitzArrayBlkdEst< 7 >, BlitzArrayBlkdEst< NDIM >, BlitzArrayBlkdEst< 2 *NDIM+3 >, and BlitzArrayBlkdEst< 2 *NDIM+1 >.
Referenced by H5ReportBuilder::startArrayBlockedReport().
bool ArrayBlockedEstimator::hasError () const inline
Definition at line 49 of file ArrayBlockedEstimator.h.
References hasErrorFlag.
Referenced by H5ReportBuilder::reportArrayBlockedStep(), and H5ReportBuilder::startArrayBlockedReport().
virtual bool ArrayBlockedEstimator::hasMax () const pure virtual
Implemented in BlitzArrayBlkdEst< N >, BlitzArrayBlkdEst< NDIM+3 >, BlitzArrayBlkdEst< NDIM+2 >, BlitzArrayBlkdEst< 1 >, BlitzArrayBlkdEst< 2 >, BlitzArrayBlkdEst< 3 >, BlitzArrayBlkdEst< 5 >, BlitzArrayBlkdEst< NDIM+1 >, BlitzArrayBlkdEst< 6 >, BlitzArrayBlkdEst< 7 >, BlitzArrayBlkdEst< NDIM >, BlitzArrayBlkdEst< 2 *NDIM+3 >, and BlitzArrayBlkdEst< 2 *NDIM+1 >.
Referenced by H5ReportBuilder::startArrayBlockedReport().
virtual bool ArrayBlockedEstimator::hasMin () const pure virtual
Implemented in BlitzArrayBlkdEst< N >, BlitzArrayBlkdEst< NDIM+3 >, BlitzArrayBlkdEst< NDIM+2 >, BlitzArrayBlkdEst< 1 >, BlitzArrayBlkdEst< 2 >, BlitzArrayBlkdEst< 3 >, BlitzArrayBlkdEst< 5 >, BlitzArrayBlkdEst< NDIM+1 >, BlitzArrayBlkdEst< 6 >, BlitzArrayBlkdEst< 7 >, BlitzArrayBlkdEst< NDIM >, BlitzArrayBlkdEst< 2 *NDIM+3 >, and BlitzArrayBlkdEst< 2 *NDIM+1 >.
Referenced by H5ReportBuilder::startArrayBlockedReport().
virtual bool ArrayBlockedEstimator::hasOrigin () const pure virtual
Implemented in BlitzArrayBlkdEst< N >, BlitzArrayBlkdEst< NDIM+3 >, BlitzArrayBlkdEst< NDIM+2 >, BlitzArrayBlkdEst< 1 >, BlitzArrayBlkdEst< 2 >, BlitzArrayBlkdEst< 3 >, BlitzArrayBlkdEst< 5 >, BlitzArrayBlkdEst< NDIM+1 >, BlitzArrayBlkdEst< 6 >, BlitzArrayBlkdEst< 7 >, BlitzArrayBlkdEst< NDIM >, BlitzArrayBlkdEst< 2 *NDIM+3 >, and BlitzArrayBlkdEst< 2 *NDIM+1 >.
Referenced by H5ReportBuilder::startArrayBlockedReport().
virtual bool ArrayBlockedEstimator::hasScale () const pure virtual
Implemented in BlitzArrayBlkdEst< N >, BlitzArrayBlkdEst< NDIM+3 >, BlitzArrayBlkdEst< NDIM+2 >, BlitzArrayBlkdEst< 1 >, BlitzArrayBlkdEst< 2 >, BlitzArrayBlkdEst< 3 >, BlitzArrayBlkdEst< 5 >, BlitzArrayBlkdEst< NDIM+1 >, BlitzArrayBlkdEst< 6 >, BlitzArrayBlkdEst< 7 >, BlitzArrayBlkdEst< NDIM >, BlitzArrayBlkdEst< 2 *NDIM+3 >, and BlitzArrayBlkdEst< 2 *NDIM+1 >.
Referenced by H5ReportBuilder::startArrayBlockedReport().
virtual void ArrayBlockedEstimator::normalize () const pure virtual
Implemented in BlitzArrayBlkdEst< N >, BlitzArrayBlkdEst< NDIM+3 >, BlitzArrayBlkdEst< NDIM+2 >, BlitzArrayBlkdEst< 1 >, BlitzArrayBlkdEst< 2 >, BlitzArrayBlkdEst< 3 >, BlitzArrayBlkdEst< 5 >, BlitzArrayBlkdEst< NDIM+1 >, BlitzArrayBlkdEst< 6 >, BlitzArrayBlkdEst< 7 >, BlitzArrayBlkdEst< NDIM >, BlitzArrayBlkdEst< 2 *NDIM+3 >, and BlitzArrayBlkdEst< 2 *NDIM+1 >.
Referenced by H5ReportBuilder::reportArrayBlockedStep().
virtual void ArrayBlockedEstimator::reportStep (EstimatorReportBuilder & builder) inline virtual
Callback EstimatorReportBuilder method for blocked arrays.
Reimplemented from Estimator.
Definition at line 40 of file ArrayBlockedEstimator.h.
References EstimatorReportBuilder::reportArrayBlockedStep().
virtual void ArrayBlockedEstimator::reset () pure virtual
Clear the value.
Implemented in ZeroVarDensityEstimator, SpinChoicePCFEstimator< N >, PairCFEstimator< N >, DensCountEstimator, VIndEstimator, ConductanceEstimator, CountCountEstimator, DensDensEstimator, DynamicPCFEstimator, EIndEstimator, SpinChargeEstimator, ConductivityEstimator, SKOmegaEstimator, DensityEstimator, DensityCurrentEstimator, BlitzArrayBlkdEst< N >, BlitzArrayBlkdEst< NDIM+3 >, BlitzArrayBlkdEst< NDIM+2 >, BlitzArrayBlkdEst< 1 >, BlitzArrayBlkdEst< 2 >, BlitzArrayBlkdEst< 3 >, BlitzArrayBlkdEst< 5 >, BlitzArrayBlkdEst< NDIM+1 >, BlitzArrayBlkdEst< 6 >, BlitzArrayBlkdEst< 7 >, BlitzArrayBlkdEst< NDIM >, BlitzArrayBlkdEst< 2 *NDIM+3 >, BlitzArrayBlkdEst< 2 *NDIM+1 >, FrequencyEstimator, ConductivityEstimator2D, FreeEnergyEstimator, PermutationEstimator, JEstimator, and WindingEstimator.
virtual void ArrayBlockedEstimator::startReport (EstimatorReportBuilder & builder) inline virtual
Callback EstimatorReportBuilder method for blocked arrays.
Reimplemented from Estimator.
Definition at line 37 of file ArrayBlockedEstimator.h.
References EstimatorReportBuilder::startArrayBlockedReport().
virtual void ArrayBlockedEstimator::unnormalize () const pure virtual
Implemented in BlitzArrayBlkdEst< N >, BlitzArrayBlkdEst< NDIM+3 >, BlitzArrayBlkdEst< NDIM+2 >, BlitzArrayBlkdEst< 1 >, BlitzArrayBlkdEst< 2 >, BlitzArrayBlkdEst< 3 >, BlitzArrayBlkdEst< 5 >, BlitzArrayBlkdEst< NDIM+1 >, BlitzArrayBlkdEst< 6 >, BlitzArrayBlkdEst< 7 >, BlitzArrayBlkdEst< NDIM >, BlitzArrayBlkdEst< 2 *NDIM+3 >, and BlitzArrayBlkdEst< 2 *NDIM+1 >.
Referenced by H5ReportBuilder::reportArrayBlockedStep().
Member Data Documentation
bool ArrayBlockedEstimator::hasErrorFlag protected
Definition at line 61 of file ArrayBlockedEstimator.h.
Referenced by PermutationEstimator::averageOverClones(), FreeEnergyEstimator::averageOverClones(), BlitzArrayBlkdEst< 2 *NDIM+1 >::getError(), hasError(), BlitzArrayBlkdEst< 2 *NDIM+1 >::normalize(), and BlitzArrayBlkdEst< 2 *NDIM+1 >::unnormalize().
The documentation for this class was generated from the following files:
ArrayBlockedEstimator.h
ArrayBlockedEstimator.cc