pi: Path integral Quantum Monte Carlo: XMLParser Class Reference
XMLParser Class Reference
Base class for classes that parse XML data.
#include <XMLParser.h>
Public Types
typedef blitz::TinyVector
< double, NDIM > Vec
typedef blitz::TinyVector< int,
NDIM > IVec
Public Member Functions
virtual ~XMLParser ()
Destructor.
virtual void parse (const xmlXPathContextPtr &ctxt)
Parse some xml.
Static Public Member Functions
static std::string getName (const xmlNodePtr &node)
Get the name of the node.
static double getDoubleAttribute (const xmlNodePtr &node, const std::string &attName)
Get a double valued attribute.
static int getIntAttribute (const xmlNodePtr &node, const std::string &attName)
Get an integer valued attribute.
static std::string getStringAttribute (const xmlNodePtr &node, const std::string &attName)
Get a string valued attribute.
static bool getBoolAttribute (const xmlNodePtr &node, const std::string &attName)
Get a bool valued attribute.
static Vec getVecAttribute (const xmlNodePtr &node, const std::string &attName)
Get a vector valued attribute.
static IVec getIVecAttribute (const xmlNodePtr &node, const std::string &attName)
Get a vector valued attribute.
static std::string getLinkBase (const xmlNodePtr &node, const std::string &attName="href")
Get the base of a link.
static std::string getLinkPath (const xmlNodePtr &node, const std::string &attName="href")
Get the path of a link.
Static Public Attributes
static const std::string dimName = "xyzklmnopqrstuv"
Letters associated with directions in input file.
Detailed Description
Base class for classes that parse XML data.
Includes helper functions.
Version:
$Revision$
Author:
John Shumway
Definition at line 14 of file XMLParser.h.
Member Typedef Documentation
typedef blitz::TinyVector<int,NDIM> XMLParser::IVec
Reimplemented in PIMCParser.
Definition at line 17 of file XMLParser.h.
typedef blitz::TinyVector<double,NDIM> XMLParser::Vec
Reimplemented in PIMCParser, ActionParser, SimInfoParser, and MainSpinParser.
Definition at line 16 of file XMLParser.h.
Constructor & Destructor Documentation
virtual XMLParser::~XMLParser () inline virtual
Destructor.
Definition at line 19 of file XMLParser.h.
Member Function Documentation
bool XMLParser::getBoolAttribute (const xmlNodePtr & node, const std::string & attName) static
Get a bool valued attribute.
Definition at line 44 of file XMLParser.cc.
Referenced by SimInfoParser::parse(), EstimatorParser::parse(), PIMCParser::parse(), ActionParser::parseActions(), PIMCParser::parseAlgorithm(), and ActionParser::parseNodeModel().
double XMLParser::getDoubleAttribute (const xmlNodePtr & node, const std::string & attName) static
Get a double valued attribute.
Definition at line 23 of file XMLParser.cc.
Referenced by getVecAttribute(), MainSpinParser::parse(), SimInfoParser::parse(), EstimatorParser::parse(), ActionParser::parseActions(), PIMCParser::parseAlgorithm(), ActionParser::parseEwaldActions(), ActionParser::parseNodeModel(), ActionParser::parseOrbitalDM(), EstimatorParser::parsePairCF(), and EstimatorParser::parsePairDistance().
int XMLParser::getIntAttribute (const xmlNodePtr & node, const std::string & attName) static
Get an integer valued attribute.
Definition at line 31 of file XMLParser.cc.
Referenced by getIVecAttribute(), PIMCParser::getLoopCount(), MainParser::parse(), SimInfoParser::parse(), EstimatorParser::parse(), ActionParser::parseActions(), PIMCParser::parseAlgorithm(), EstimatorParser::parseDistance(), ActionParser::parseEwaldActions(), ActionParser::parseNodeModel(), EstimatorParser::parsePairCF(), and EstimatorParser::parsePairDistance().
XMLParser::IVec XMLParser::getIVecAttribute (const xmlNodePtr & node, const std::string & attName) static
Get a vector valued attribute.
Definition at line 69 of file XMLParser.cc.
References dimName, and getIntAttribute().
Referenced by EstimatorParser::parse().
std::string XMLParser::getLinkBase (const xmlNodePtr & node, const std::string & attName = "href") static
Get the base of a link.
Definition at line 78 of file XMLParser.cc.
std::string XMLParser::getLinkPath (const xmlNodePtr & node, const std::string & attName = "href") static
Get the path of a link.
Definition at line 86 of file XMLParser.cc.
std::string XMLParser::getName (const xmlNodePtr & node) static
Get the name of the node.
Definition at line 39 of file XMLParser.cc.
Referenced by EstimatorParser::parse(), ActionParser::parseActions(), PIMCParser::parseBoundary(), EstimatorParser::parseDistance(), ActionParser::parseOrbitalDM(), EstimatorParser::parsePairCF(), and EstimatorParser::parsePairDistance().
std::string XMLParser::getStringAttribute (const xmlNodePtr & node, const std::string & attName) static
Get a string valued attribute.
Definition at line 52 of file XMLParser.cc.
Referenced by SimInfoParser::parse(), EstimatorParser::parse(), ActionParser::parseActions(), PIMCParser::parseAlgorithm(), PIMCParser::parseBoundary(), EstimatorParser::parseDistance(), ActionParser::parseEwaldActions(), ActionParser::parseNodeModel(), ActionParser::parseOrbitalDM(), EstimatorParser::parsePairCF(), and EstimatorParser::parsePairDistance().
XMLParser::Vec XMLParser::getVecAttribute (const xmlNodePtr & node, const std::string & attName) static
Get a vector valued attribute.
Definition at line 60 of file XMLParser.cc.
References dimName, and getDoubleAttribute().
Referenced by SimInfoParser::parse().
virtual void XMLParser::parse (const xmlXPathContextPtr & ctxt) inline virtual
Parse some xml.
Reimplemented in PIMCParser, ActionParser, SimInfoParser, MainSpinParser, and MainParser.
Definition at line 21 of file XMLParser.h.
Member Data Documentation
const std::string XMLParser::dimName = "xyzklmnopqrstuv" static
Letters associated with directions in input file.
Reimplemented in ActionParser.
Definition at line 51 of file XMLParser.h.
Referenced by getIVecAttribute(), getVecAttribute(), PIMCParser::parseAlgorithm(), PIMCParser::parseBoundary(), EstimatorParser::parseDistance(), and EstimatorParser::parsePairDistance().
The documentation for this class was generated from the following files:
XMLParser.h
XMLParser.cc