pi: Path integral Quantum Monte Carlo: PeriodicGaussian Class Reference
PeriodicGaussian Class Reference
Function object for a periodic Gaussian.
#include <PeriodicGaussian.h>
Public Member Functions
PeriodicGaussian (double alpha, double length)
double evaluate (double x) const
double getValue () const
double getGradient () const
double getSecondDerivative () const
Static Public Member Functions
static int numberOfTerms (double alpha, double length)
Private Attributes
double value
double gradient
double secondDerivative
const double alpha
const double length
const double nome
const double prefactor
const double k
const int nmax
Static Private Attributes
static const double PI = 3.141592653589793
Detailed Description
Function object for a periodic Gaussian.
Call evalauate first, the use the getter methods for the function value and derivatives.
We start from the k-space representation of a Gaussian,
To make this periodic function f(x) on the interval , we restrict k to integer values, , where n runs over all integers. Now the integral is a series,
The quantity in the square brackets in a theta function with real value `nome' and complex argument ,
The series converges quickly in n, and we choose , so that . Since we are working in k-space, the first and second derivatives are easily found by multiplying each term by and , respectively.
Definition at line 36 of file PeriodicGaussian.h.
Constructor & Destructor Documentation
PeriodicGaussian::PeriodicGaussian (double alpha, double length)
Definition at line 7 of file PeriodicGaussian.cc.
Member Function Documentation
double PeriodicGaussian::evaluate (double x) const
Definition at line 20 of file PeriodicGaussian.cc.
References gradient, k, nmax, nome, prefactor, secondDerivative, and value.
Referenced by AnisotropicNodes::evaluate(), WireNodes::evaluate(), FreePartNodesNoUpdate::evaluate(), WireNodes::evaluateDistance(), FreePartNodesNoUpdate::evaluateDistance(), AnisotropicNodes::evaluateDistances(), AnisotropicNodes::evaluateGrad(), AnisotropicNodes::evaluateUpdate(), and FreePartNodesNoUpdate::getBeadAction().
double PeriodicGaussian::getGradient () const inline
Definition at line 44 of file PeriodicGaussian.h.
References gradient.
Referenced by WireNodes::evaluateDistance(), FreePartNodesNoUpdate::evaluateDistance(), AnisotropicNodes::evaluateDistances(), AnisotropicNodes::evaluateGrad(), and FreePartNodesNoUpdate::getBeadAction().
double PeriodicGaussian::getSecondDerivative () const inline
Definition at line 47 of file PeriodicGaussian.h.
References secondDerivative.
Referenced by FreePartNodesNoUpdate::getBeadAction().
double PeriodicGaussian::getValue () const inline
Definition at line 41 of file PeriodicGaussian.h.
References value.
int PeriodicGaussian::numberOfTerms (double alpha, double length) static
Definition at line 16 of file PeriodicGaussian.cc.
Referenced by SpringAction::SpringAction().
Member Data Documentation
const double PeriodicGaussian::alpha private
Definition at line 55 of file PeriodicGaussian.h.
double PeriodicGaussian::gradient mutable private
Definition at line 53 of file PeriodicGaussian.h.
Referenced by evaluate(), and getGradient().
const double PeriodicGaussian::k private
Definition at line 59 of file PeriodicGaussian.h.
Referenced by evaluate().
const double PeriodicGaussian::length private
Definition at line 56 of file PeriodicGaussian.h.
const int PeriodicGaussian::nmax private
Definition at line 60 of file PeriodicGaussian.h.
Referenced by evaluate().
const double PeriodicGaussian::nome private
Definition at line 57 of file PeriodicGaussian.h.
Referenced by evaluate().
const double PeriodicGaussian::PI = 3.141592653589793 static private
Definition at line 61 of file PeriodicGaussian.h.
const double PeriodicGaussian::prefactor private
Definition at line 58 of file PeriodicGaussian.h.
Referenced by evaluate().
double PeriodicGaussian::secondDerivative mutable private
Definition at line 54 of file PeriodicGaussian.h.
Referenced by evaluate(), and getSecondDerivative().
double PeriodicGaussian::value mutable private
Definition at line 52 of file PeriodicGaussian.h.
Referenced by evaluate(), and getValue().
The documentation for this class was generated from the following files:
PeriodicGaussian.h
PeriodicGaussian.cc