pi: Path integral Quantum Monte Carlo: SpinStatePermutationChooser Class Reference
SpinStatePermutationChooser Class Reference
#include <SpinStatePermutationChooser.h>
Public Types
typedef blitz::Array< int, 1 > IArray
Public Types inherited from WalkingChooser
typedef blitz::Array< double, 1 > Array
typedef blitz::Array< double, 2 > Mat
typedef blitz::TinyVector
< double, NDIM > Vec
typedef blitz::Array
< PeriodicGaussian *, 1 > PGArray
Public Member Functions
SpinStatePermutationChooser (const int nsize, const Species &, const int nlevel, const SimulationInfo &, ModelState &modelState)
virtual ~SpinStatePermutationChooser ()
virtual void init ()
Public Member Functions inherited from WalkingChooser
WalkingChooser (const int nsize, const Species &, const int nlevel, const SimulationInfo &)
virtual ~WalkingChooser ()
virtual void setMLSampler (const MultiLevelSampler *)
virtual bool choosePermutation ()
virtual void chooseParticles ()
int iSearch (int part, double x)
virtual double getLnTranProb () const
Public Member Functions inherited from PermutationChooser
PermutationChooser (int size)
virtual ~PermutationChooser ()
const Permutation & getPermutation ()
Public Member Functions inherited from SpeciesParticleChooser
SpeciesParticleChooser (const Species &, const int nmoving)
virtual ~SpeciesParticleChooser ()
Public Member Functions inherited from ParticleChooser
ParticleChooser (const int npart)
virtual ~ParticleChooser ()
int operator[] (const int i) const
std::string & getName ()
Private Attributes
const IArray & spinState
Additional Inherited Members
Protected Attributes inherited from WalkingChooser
Mat t
Mat cump
const MultiLevelSampler * multiLevelSampler
PGArray pg
Protected Attributes inherited from PermutationChooser
Permutation * permutation
Protected Attributes inherited from SpeciesParticleChooser
const int npart
const int ifirst
Protected Attributes inherited from ParticleChooser
IArray index
std::string name
Detailed Description
Definition at line 13 of file SpinStatePermutationChooser.h.
Member Typedef Documentation
typedef blitz::Array<int, 1> SpinStatePermutationChooser::IArray
Reimplemented from WalkingChooser.
Definition at line 15 of file SpinStatePermutationChooser.h.
Constructor & Destructor Documentation
SpinStatePermutationChooser::SpinStatePermutationChooser (const int nsize, const Species & species, const int nlevel, const SimulationInfo & simInfo, ModelState & modelState)
Definition at line 22 of file SpinStatePermutationChooser.cc.
SpinStatePermutationChooser::~SpinStatePermutationChooser () virtual
Definition at line 29 of file SpinStatePermutationChooser.cc.
Member Function Documentation
void SpinStatePermutationChooser::init () virtual
Reimplemented from WalkingChooser.
Definition at line 32 of file SpinStatePermutationChooser.cc.
References WalkingChooser::cump, Beads< TDIM >::getNSlice(), MultiLevelSampler::getSectionBeads(), MultiLevelSampler::getSuperCell(), SpeciesParticleChooser::ifirst, WalkingChooser::multiLevelSampler, SpeciesParticleChooser::npart, SuperCell::pbc(), WalkingChooser::pg, spinState, and WalkingChooser::t.
Member Data Documentation
const IArray& SpinStatePermutationChooser::spinState private
Definition at line 21 of file SpinStatePermutationChooser.h.
Referenced by init().
The documentation for this class was generated from the following files:
SpinStatePermutationChooser.h
SpinStatePermutationChooser.cc