pi: Path integral Quantum Monte Carlo: DoubleAction Class Reference
DoubleAction Class Reference
Virtual base class for calculating the fermi action that depends on two slices Action objects can compute differences in action from a MultiLevelDoubleSampler, the total action, and the action and its derivatives at a bead.
#include <DoubleAction.h>
Public Types
typedef blitz::TinyVector
< double, NDIM > Vec
Typdefs and constants.
typedef blitz::Array< int, 1 > IArray
typedef blitz::Array< Vec, 1 > VArray
Public Member Functions
virtual ~DoubleAction ()
Virtual destructor.
virtual double getActionDifference (const SectionSamplerInterface &, const int level)
Calculate the difference in action.
virtual double getActionDifference (const Paths &, const VArray &displacement, int nmoving, const IArray &movingIndex, int iFirstSlice, int iLastSlice)
Calculate the difference in action.
virtual double getTotalAction (const Paths &, const int level) const =0
Calculate the total action.
virtual void getBeadAction (const Paths &, int ipart, int islice, double &u, double &utau, double &ulambda, Vec &fm, Vec &fp) const =0
Calculate action and derivatives at a bead (defaults to no contribution).
virtual void initialize (const DoubleSectionChooser &)
Initialize for a sampling section.
virtual void acceptLastMove ()
Accept last move.
Detailed Description
Virtual base class for calculating the fermi action that depends on two slices Action objects can compute differences in action from a MultiLevelDoubleSampler, the total action, and the action and its derivatives at a bead.
Version:
$Revision$
Author:
John Shumway.
Definition at line 32 of file DoubleAction.h.
Member Typedef Documentation
typedef blitz::Array<int,1> DoubleAction::IArray
Reimplemented in FreePartNodesNoUpdate, SpinFixedPhaseAction, FixedPhaseAction, FixedNodeAction, AnisotropicNodes, and SpinChoiceFixedNodeAction.
Definition at line 36 of file DoubleAction.h.
typedef blitz::Array<Vec,1> DoubleAction::VArray
Reimplemented in FreePartNodesNoUpdate, SpinFixedPhaseAction, FixedPhaseAction, FixedNodeAction, and AnisotropicNodes.
Definition at line 37 of file DoubleAction.h.
typedef blitz::TinyVector<double,NDIM> DoubleAction::Vec
Typdefs and constants.
Reimplemented in FreePartNodesNoUpdate, FixedPhaseAction, SpinFixedPhaseAction, FixedNodeAction, and AnisotropicNodes.
Definition at line 35 of file DoubleAction.h.
Constructor & Destructor Documentation
virtual DoubleAction::~DoubleAction () inline virtual
Virtual destructor.
Definition at line 39 of file DoubleAction.h.
Member Function Documentation
virtual void DoubleAction::acceptLastMove () inline virtual
Accept last move.
Reimplemented in FreePartNodesNoUpdate, FixedPhaseAction, SpinFixedPhaseAction, FixedNodeAction, AnisotropicNodes, CompositeDoubleAction, and DoubleActionChoice.
Definition at line 58 of file DoubleAction.h.
virtual double DoubleAction::getActionDifference (const SectionSamplerInterface & , const int level) inline virtual
Calculate the difference in action.
Reimplemented in FreePartNodesNoUpdate, SpinFixedPhaseAction, FixedPhaseAction, FixedNodeAction, AnisotropicNodes, CompositeDoubleAction, and DoubleActionChoice.
Definition at line 41 of file DoubleAction.h.
virtual double DoubleAction::getActionDifference (const Paths & , const VArray & displacement, int nmoving, const IArray & movingIndex, int iFirstSlice, int iLastSlice) inline virtual
Calculate the difference in action.
Reimplemented in FixedNodeAction, CompositeDoubleAction, and DoubleActionChoice.
Definition at line 44 of file DoubleAction.h.
virtual void DoubleAction::getBeadAction (const Paths & , int ipart, int islice, double & u, double & utau, double & ulambda, Vec & fm, Vec & fp) const pure virtual
Calculate action and derivatives at a bead (defaults to no contribution).
Implemented in FreePartNodesNoUpdate, FixedPhaseAction, SpinFixedPhaseAction, FixedNodeAction, AnisotropicNodes, CompositeDoubleAction, and DoubleActionChoice.
Referenced by ThermoEnergyEstimator::handleLink(), VirialEnergyEstimator::handleLink(), and ZeroVarDensityEstimator::handleLink().
virtual double DoubleAction::getTotalAction (const Paths & , const int level) const pure virtual
Calculate the total action.
Implemented in FreePartNodesNoUpdate, FixedPhaseAction, SpinFixedPhaseAction, FixedNodeAction, AnisotropicNodes, CompositeDoubleAction, and DoubleActionChoice.
virtual void DoubleAction::initialize (const DoubleSectionChooser &) inline virtual
Initialize for a sampling section.
Reimplemented in FreePartNodesNoUpdate, FixedPhaseAction, SpinFixedPhaseAction, FixedNodeAction, AnisotropicNodes, CompositeDoubleAction, and DoubleActionChoice.
Definition at line 55 of file DoubleAction.h.
The documentation for this class was generated from the following file:
DoubleAction.h