pi: Path integral Quantum Monte Carlo: BeadFactory Class Reference
BeadFactory Class Reference
Factory for Beads.
#include <BeadFactory.h>
Public Member Functions
BeadFactory ()
Constructor.
BeadFactory (const BeadFactory &)
Copy constructor.
~BeadFactory ()
Destructor.
Beads< NDIM > * getNewBeads (const int npart, const int nslice) const
Get new beads.
int addAuxBeads (BeadsBase *, const std::string &name)
Add prototype beads to factory.
Private Attributes
std::vector< std::string > beadNames
Array of bead names.
Beads< NDIM > & protoBeads
Prototype beads.
Detailed Description
Factory for Beads.
Uses cloneBase method of Beads to produce specialized Beads for the simulation.
Version:
$Revision$
Author:
John Shumway
Definition at line 35 of file BeadFactory.h.
Constructor & Destructor Documentation
BeadFactory::BeadFactory ()
Constructor.
Definition at line 19 of file BeadFactory.cc.
References beadNames.
BeadFactory::BeadFactory (const BeadFactory &)
Copy constructor.
BeadFactory::~BeadFactory ()
Destructor.
Definition at line 23 of file BeadFactory.cc.
References protoBeads.
Member Function Documentation
int BeadFactory::addAuxBeads (BeadsBase * auxBeads, const std::string & name)
Add prototype beads to factory.
Definition at line 31 of file BeadFactory.cc.
References BeadsBase::auxBeads, beadNames, and protoBeads.
Referenced by MainSpinParser::parse().
Beads< NDIM > * BeadFactory::getNewBeads (const int npart, const int nslice) const
Get new beads.
Definition at line 27 of file BeadFactory.cc.
References BeadsBase::cloneBase(), and protoBeads.
Referenced by PathReader::run().
Member Data Documentation
std::vector<std::string> BeadFactory::beadNames private
Array of bead names.
Definition at line 49 of file BeadFactory.h.
Referenced by addAuxBeads(), and BeadFactory().
Beads<NDIM>& BeadFactory::protoBeads private
Prototype beads.
Definition at line 51 of file BeadFactory.h.
Referenced by addAuxBeads(), getNewBeads(), and ~BeadFactory().
The documentation for this class was generated from the following files:
BeadFactory.h
BeadFactory.cc