pi: Path integral Quantum Monte Carlo: HyperbolicMover Class Reference
HyperbolicMover Class Reference
Select a trial move for beads by free particle sampling.
#include <HyperbolicMover.h>
Public Types
typedef blitz::Array< double, 1 > Array
Typedefs.
typedef blitz::Array< double, 2 > Array2
typedef blitz::TinyVector
< double, NDIM > Vec
Public Member Functions
HyperbolicMover (const SimulationInfo &, const int maxlevel)
Construct by providing simInfo.
virtual ~HyperbolicMover ()
Virtual destructor.
virtual double makeMove (MultiLevelSampler &, const int level)
Move the samplers moving beads for a given level, returning the probability for the old move divided by the probability for the new move.
virtual double makeDelayedMove (MultiLevelSampler &, const int level)
virtual double getForwardProb ()
Public Member Functions inherited from Mover
virtual ~Mover ()
Private Member Functions
double fG (const double r, const int ilevel) const
Sampling scale function for g.
double fG2 (const double r, const int ilevel) const
Sampling scale function for g2.
double g (const double r, const double t, const int ilevel) const
Propagator.
double g0 (const double r, const double t) const
Unscaled gaussian propogator.
void setFTable (int maxlevel)
Set scale function table for sampling.
Vec sampleDelta (Vec &deltaOver2, const double teff, const int ilevel)
Sample the displacement from a midpoint.
double g1g2 (const Vec center, const Vec delta, const double teff, const int level)
Calculate the sampling probability.
Private Attributes
const double tau
The timestep.
const double mass
The mass.
const double alpha
The anisotropy parameter.
Array2 fGtable
Sampling scale function lookup table.
Array2 fG2table
double drinv
Inverse of grid spacing for scale function table.
Array normG
Norm for g and g2.
Array normG2
Static Private Attributes
static const double pi
Pi.
Detailed Description
Select a trial move for beads by free particle sampling.
Todo:
May want to make this a subclass of Action, with a flag for whether to return probability or allow to cancel for efficiency
Definition at line 13 of file HyperbolicMover.h.
Member Typedef Documentation
typedef blitz::Array<double, 1> HyperbolicMover::Array
Typedefs.
Definition at line 16 of file HyperbolicMover.h.
typedef blitz::Array<double, 2> HyperbolicMover::Array2
Definition at line 17 of file HyperbolicMover.h.
typedef blitz::TinyVector<double, NDIM> HyperbolicMover::Vec
Definition at line 18 of file HyperbolicMover.h.
Constructor & Destructor Documentation
HyperbolicMover::HyperbolicMover (const SimulationInfo & simInfo, const int maxlevel)
Construct by providing simInfo.
Definition at line 21 of file HyperbolicMover.cc.
References normG2, and setFTable().
HyperbolicMover::~HyperbolicMover () virtual
Virtual destructor.
Definition at line 29 of file HyperbolicMover.cc.
Member Function Documentation
double HyperbolicMover::fG (const double r, const int ilevel) const private
Sampling scale function for g.
Definition at line 136 of file HyperbolicMover.cc.
References drinv, and fGtable.
Referenced by sampleDelta().
double HyperbolicMover::fG2 (const double r, const int ilevel) const private
Sampling scale function for g2.
Definition at line 144 of file HyperbolicMover.cc.
References drinv, and fG2table.
Referenced by sampleDelta().
double HyperbolicMover::g (const double r, const double t, const int ilevel) const private
Propagator.
Definition at line 152 of file HyperbolicMover.cc.
References alpha, mass, and pi.
Referenced by g1g2(), sampleDelta(), and setFTable().
double HyperbolicMover::g0 (const double r, const double t) const private
Unscaled gaussian propogator.
Definition at line 160 of file HyperbolicMover.cc.
References pi.
Referenced by setFTable().
double HyperbolicMover::g1g2 (const Vec center, const Vec delta, const double teff, const int level) private
Calculate the sampling probability.
Definition at line 294 of file HyperbolicMover.cc.
References g().
Referenced by makeMove(), and sampleDelta().
virtual double HyperbolicMover::getForwardProb () inline virtual
Implements Mover.
Definition at line 30 of file HyperbolicMover.h.
virtual double HyperbolicMover::makeDelayedMove (MultiLevelSampler & , const int level) inline virtual
Implements Mover.
Definition at line 27 of file HyperbolicMover.h.
double HyperbolicMover::makeMove (MultiLevelSampler & sampler, const int level) virtual
Move the samplers moving beads for a given level, returning the probability for the old move divided by the probability for the new move.
Implements Mover.
Definition at line 84 of file HyperbolicMover.cc.
References Beads< TDIM >::delta(), g1g2(), MultiLevelSampler::getMovingBeads(), MultiLevelSampler::getMovingIndex(), Beads< TDIM >::getNSlice(), MultiLevelSampler::getSectionBeads(), MultiLevelSampler::getSuperCell(), RandomNumGenerator::makeGaussRand(), SuperCell::pbc(), sampleDelta(), and tau.
HyperbolicMover::Vec HyperbolicMover::sampleDelta (Vec & deltaOver2, const double teff, const int ilevel) private
Sample the displacement from a midpoint.
Go ahead and use squared envelope.
Use sum envelope instead.
Definition at line 32 of file HyperbolicMover.cc.
References fG(), fG2(), g(), g1g2(), RandomNumGenerator::getRand(), RandomNumGenerator::makeGaussRand(), and normG2.
Referenced by makeMove().
void HyperbolicMover::setFTable (int maxlevel) private
Set scale function table for sampling.
Set normalization for g and g2.
Definition at line 164 of file HyperbolicMover.cc.
References alpha, drinv, fG2table, fGtable, g(), g0(), mass, normG2, pi, and tau.
Referenced by HyperbolicMover().
Member Data Documentation
const double HyperbolicMover::alpha private
The anisotropy parameter.
Definition at line 39 of file HyperbolicMover.h.
Referenced by g(), and setFTable().
double HyperbolicMover::drinv private
Inverse of grid spacing for scale function table.
Definition at line 43 of file HyperbolicMover.h.
Referenced by fG(), fG2(), and setFTable().
Array2 HyperbolicMover::fG2table private
Definition at line 41 of file HyperbolicMover.h.
Referenced by fG2(), and setFTable().
Array2 HyperbolicMover::fGtable private
Sampling scale function lookup table.
Definition at line 41 of file HyperbolicMover.h.
Referenced by fG(), and setFTable().
const double HyperbolicMover::mass private
The mass.
Definition at line 37 of file HyperbolicMover.h.
Referenced by g(), and setFTable().
Array HyperbolicMover::normG private
Norm for g and g2.
Definition at line 57 of file HyperbolicMover.h.
Array HyperbolicMover::normG2 private
Definition at line 57 of file HyperbolicMover.h.
Referenced by HyperbolicMover(), sampleDelta(), and setFTable().
const double HyperbolicMover::pi static private
Pi.
Definition at line 55 of file HyperbolicMover.h.
Referenced by g(), g0(), and setFTable().
const double HyperbolicMover::tau private
The timestep.
Definition at line 35 of file HyperbolicMover.h.
Referenced by makeMove(), and setFTable().
The documentation for this class was generated from the following files:
HyperbolicMover.h
HyperbolicMover.cc