pi: Path integral Quantum Monte Carlo: TradEwaldSum Class Reference
TradEwaldSum Class Reference
Class for creating and evaluating Ewald sums.
#include <TradEwaldSum.h>
Public Member Functions
TradEwaldSum (const SuperCell &, const int npart, const double rcut, const double kcut, const double kappa)
Constructor calcuates the k-vectors for a given rcut and kcut.
virtual ~TradEwaldSum ()
Virtual destructor.
virtual double evalFR (const double r) const
Returns , used to cancel tails on actions or potentials.
virtual double evalFR0 () const
Returns , used in evalSelfEnergy.
virtual double evalFK (const double k) const
Returns , used to set up vk array.
virtual double evalFK0 () const
Returns , used in evalSelfEnergy for interaction with neutralizing background if system has a net charge.
Public Member Functions inherited from EwaldSum
EwaldSum (const SuperCell &, const int npart, const double rcut, const double kcut)
Constructor calcuates the k-vectors for a given rcut and kcut.
virtual ~EwaldSum ()
Virtual destructor.
double getkvec2 (const int index)
int gettotk ()
Vec getDeltak ()
Vec getkvec (int i)
double evalLongRange (const VArray &r) const
Evaluate the long range sum.
void evalSelfEnergy ()
Evaluate the self energy using evalFR0 and evalFK0 virtual methods.
Array & getQArray ()
Get a reference to the charge array.
void setLongRangeArray ()
Set the long range table using the evalFK virtual method.
Private Attributes
const double kappa
Screening parameter.
Additional Inherited Members
Public Types inherited from EwaldSum
typedef blitz::TinyVector
< double, NDIM > Vec
typedef blitz::TinyVector< int,
NDIM > IVec
typedef blitz::Array< int, 1 > IArray
typedef blitz::Array< double, 1 > Array
typedef blitz::Array< Vec, 1 > VArray
typedef blitz::Array< IVec, 1 > IVArray
typedef std::complex< double > Complex
typedef blitz::Array< Complex, 2 > CArray2
Protected Member Functions inherited from EwaldSum
double calcLongRangeUtau (VArray &r) const
Calculate the long range part.
Protected Attributes inherited from EwaldSum
const SuperCell & cell
The SuperCell.
const int npart
The number of particles.
const double rcut
Real space cutoff.
const double kcut
K-space cutoff.
double selfEnergy
Self energy;.
Array q
The particle charges.
VArray pos
The particle positions.
IVec ikmax
Integer limits of k-space sums.
Vec deltak
Reciprical space lattice spacing.
int totk
Number of k-vectors.
Array vk
Stored values of k-space potential.
IVArray kvec
Stored k-vectors.
Array kvec2
Stored magnetude of k-vectors.
CArray2 eikx
Arrays to tabulate .
CArray2 eiky
CArray2 eikz
double oneOver2V
The prefactor on the k-space sum, 1/2V.
Static Protected Attributes inherited from EwaldSum
static const double PI = 3.14159265358979
Constants.
Detailed Description
Class for creating and evaluating Ewald sums.
The traditional (and most common) Ewald summation technique splits a sum of potentials into short-range real space and long-range k-space terms,
Thus the following quantity is zero,
For a charged system such as the electron gas, there is an additional constant term,
Todo:
Make a new implementation using optimized Ewald breakup, as described in Natoli and Ceperley, J. Comp. Phys. 117, 171-178 (1995).
Bug:
Only works for NDIM=3.
Version:
$Revision$
Author:
John Shumway.
Definition at line 65 of file TradEwaldSum.h.
Constructor & Destructor Documentation
TradEwaldSum::TradEwaldSum (const SuperCell & cell, const int npart, const double rcut, const double kcut, const double kappa)
Constructor calcuates the k-vectors for a given rcut and kcut.
Definition at line 13 of file TradEwaldSum.cc.
References EwaldSum::evalSelfEnergy(), and EwaldSum::setLongRangeArray().
TradEwaldSum::~TradEwaldSum () virtual
Virtual destructor.
Definition at line 20 of file TradEwaldSum.cc.
Member Function Documentation
double TradEwaldSum::evalFK (const double k) const virtual
Returns , used to set up vk array.
Implements EwaldSum.
Definition at line 31 of file TradEwaldSum.cc.
References kappa, and EwaldSum::PI.
double TradEwaldSum::evalFK0 () const virtual
Returns , used in evalSelfEnergy for interaction with neutralizing background if system has a net charge.
Implements EwaldSum.
Definition at line 35 of file TradEwaldSum.cc.
References kappa, and EwaldSum::PI.
double TradEwaldSum::evalFR (const double r) const virtual
Returns , used to cancel tails on actions or potentials.
Implements EwaldSum.
Definition at line 23 of file TradEwaldSum.cc.
References erf(), and kappa.
double TradEwaldSum::evalFR0 () const virtual
Returns , used in evalSelfEnergy.
Implements EwaldSum.
Definition at line 27 of file TradEwaldSum.cc.
References kappa, and EwaldSum::PI.
Member Data Documentation
const double TradEwaldSum::kappa private
Screening parameter.
Definition at line 83 of file TradEwaldSum.h.
Referenced by evalFK(), evalFK0(), evalFR(), and evalFR0().
The documentation for this class was generated from the following files:
TradEwaldSum.h
TradEwaldSum.cc