pi: Path integral Quantum Monte Carlo: PermutationEstimator Class Reference
PermutationEstimator Class Reference
Permutation estimator for a homogeneous system.
#include <PermutationEstimator.h>
Public Types
typedef blitz::Array< int, 1 > IArray
typedef blitz::Array< bool, 1 > BArray
typedef blitz::Array< double, 1 > Array
Public Types inherited from BlitzArrayBlkdEst< 1 >
typedef blitz::Array< float, N > ArrayN
typedef blitz::TinyVector< int, N > IVecN
typedef blitz::TinyVector
< double, N > VecN
Public Member Functions
PermutationEstimator (const SimulationInfo &simInfo, const std::string &name, const Species &s1, MPIManager *mpi)
Constructor.
virtual ~PermutationEstimator ()
Virtual destructor.
virtual void reset ()
Clear value of the estimator.
virtual void evaluate (const Paths &paths)
Evaluate for Paths configuration.
virtual void averageOverClones (const MPIManager *mpi)
Average over clones.
Public Member Functions inherited from BlitzArrayBlkdEst< 1 >
BlitzArrayBlkdEst (const std::string &name, const std::string &typeString, const IVecN &n, bool hasError)
Construct by giving the name and size.
virtual ~BlitzArrayBlkdEst ()
Virtual destructor.
virtual int getNDim () const
Get the number of dimensions in the array.
virtual int getExtent (const int idim) const
Get the extent of the array in dimensions idim.
virtual const void * getData () const
Get a pointer to the data.
virtual const void * getError () const
virtual void normalize () const
virtual void unnormalize () const
virtual bool hasScale () const
virtual bool hasOrigin () const
virtual const void * getScale () const
virtual const void * getOrigin () const
virtual bool hasMin () const
virtual bool hasMax () const
virtual const void * getMin () const
virtual const void * getMax () const
Public Member Functions inherited from ArrayBlockedEstimator
ArrayBlockedEstimator (const std::string &name, const std::string &typeString, bool hasError)
Construct by giving the name.
virtual ~ArrayBlockedEstimator ()
Virtual destructor.
virtual void startReport (EstimatorReportBuilder &builder)
Callback EstimatorReportBuilder method for blocked arrays.
virtual void reportStep (EstimatorReportBuilder &builder)
Callback EstimatorReportBuilder method for blocked arrays.
bool hasError () const
Public Member Functions inherited from Estimator
Estimator (const std::string &name)
Construct by giving the name of the estimator.
Estimator (const std::string &name, const std::string &typeString, const std::string &unitName)
Construct by giving the name of the estimator.
virtual ~Estimator ()
Virtual destructor.
const std::string & getName () const
Get the name of the estimator.
const std::string & getUnitName () const
Get the name of the unit for the estimator.
const std::string & getTypeString () const
Get the type string for this estimators.
Private Attributes
int ifirst
int nipart
const int npart
bool * visited
MPIManager * mpi
Additional Inherited Members
Protected Attributes inherited from BlitzArrayBlkdEst< 1 >
const IVecN n
ArrayN value
ArrayN accumvalue
ArrayN accumvalue2
double norm
double accumnorm
bool hasError
int iblock
VecN * scale
VecN * origin
VecN * min
VecN * max
Protected Attributes inherited from ArrayBlockedEstimator
bool hasErrorFlag
Static Protected Attributes inherited from BlitzArrayBlkdEst< 1 >
static const int rank
Detailed Description
Permutation estimator for a homogeneous system.
Version:
$Revision$
Bug:
Hard coded for two particles and no MPI.
Author:
John Shumway
Definition at line 17 of file PermutationEstimator.h.
Member Typedef Documentation
typedef blitz::Array<double,1> PermutationEstimator::Array
Definition at line 21 of file PermutationEstimator.h.
typedef blitz::Array<bool,1> PermutationEstimator::BArray
Definition at line 20 of file PermutationEstimator.h.
typedef blitz::Array<int,1> PermutationEstimator::IArray
Definition at line 19 of file PermutationEstimator.h.
Constructor & Destructor Documentation
PermutationEstimator::PermutationEstimator (const SimulationInfo & simInfo, const std::string & name, const Species & s1, MPIManager * mpi)
Constructor.
Definition at line 19 of file PermutationEstimator.cc.
References nipart, BlitzArrayBlkdEst< 1 >::norm, BlitzArrayBlkdEst< 1 >::value, and visited.
PermutationEstimator::~PermutationEstimator () virtual
Virtual destructor.
Definition at line 30 of file PermutationEstimator.cc.
References visited.
Member Function Documentation
void PermutationEstimator::averageOverClones (const MPIManager * mpi) virtual
Average over clones.
Reimplemented from BlitzArrayBlkdEst< 1 >.
Definition at line 64 of file PermutationEstimator.cc.
References BlitzArrayBlkdEst< 1 >::accumnorm, BlitzArrayBlkdEst< 1 >::accumvalue, BlitzArrayBlkdEst< 1 >::accumvalue2, ArrayBlockedEstimator::hasErrorFlag, BlitzArrayBlkdEst< 1 >::iblock, MPIManager::isCloneMain(), BlitzArrayBlkdEst< 1 >::n, BlitzArrayBlkdEst< 1 >::norm, BlitzArrayBlkdEst< 1 >::rank, reset(), and BlitzArrayBlkdEst< 1 >::value.
void PermutationEstimator::evaluate (const Paths & paths) virtual
Evaluate for Paths configuration.
Implements Estimator.
Definition at line 34 of file PermutationEstimator.cc.
References ifirst, nipart, BlitzArrayBlkdEst< 1 >::norm, BlitzArrayBlkdEst< 1 >::value, and visited.
virtual void PermutationEstimator::reset () inline virtual
Clear value of the estimator.
Implements BlitzArrayBlkdEst< 1 >.
Definition at line 28 of file PermutationEstimator.h.
Referenced by averageOverClones().
Member Data Documentation
int PermutationEstimator::ifirst private
Definition at line 34 of file PermutationEstimator.h.
Referenced by evaluate().
MPIManager* PermutationEstimator::mpi private
Definition at line 37 of file PermutationEstimator.h.
int PermutationEstimator::nipart private
Definition at line 34 of file PermutationEstimator.h.
Referenced by evaluate(), and PermutationEstimator().
const int PermutationEstimator::npart private
Definition at line 35 of file PermutationEstimator.h.
bool* PermutationEstimator::visited private
Definition at line 36 of file PermutationEstimator.h.
Referenced by evaluate(), PermutationEstimator(), and ~PermutationEstimator().
The documentation for this class was generated from the following files:
PermutationEstimator.h
PermutationEstimator.cc