pi: Path integral Quantum Monte Carlo: MainParser Class Reference
MainParser Class Reference
Main parser for PIMC code.
#include <MainParser.h>
Public Member Functions
MainParser (const std::string &filename)
Construct by providing an input xml file.
~MainParser ()
Virtual destructor.
void parse ()
Parse from the context.
virtual void parse (const xmlXPathContextPtr &ctxt)
Parse from a context.
Public Member Functions inherited from XMLParser
virtual ~XMLParser ()
Destructor.
Private Attributes
const std::string filename
The input file name.
xmlDocPtr doc
The xml document to parse from.
xmlXPathContextPtr context
The context to parse from.
Additional Inherited Members
Public Types inherited from XMLParser
typedef blitz::TinyVector
< double, NDIM > Vec
typedef blitz::TinyVector< int,
NDIM > IVec
Static Public Member Functions inherited from XMLParser
static std::string getName (const xmlNodePtr &node)
Get the name of the node.
static double getDoubleAttribute (const xmlNodePtr &node, const std::string &attName)
Get a double valued attribute.
static int getIntAttribute (const xmlNodePtr &node, const std::string &attName)
Get an integer valued attribute.
static std::string getStringAttribute (const xmlNodePtr &node, const std::string &attName)
Get a string valued attribute.
static bool getBoolAttribute (const xmlNodePtr &node, const std::string &attName)
Get a bool valued attribute.
static Vec getVecAttribute (const xmlNodePtr &node, const std::string &attName)
Get a vector valued attribute.
static IVec getIVecAttribute (const xmlNodePtr &node, const std::string &attName)
Get a vector valued attribute.
static std::string getLinkBase (const xmlNodePtr &node, const std::string &attName="href")
Get the base of a link.
static std::string getLinkPath (const xmlNodePtr &node, const std::string &attName="href")
Get the path of a link.
Static Public Attributes inherited from XMLParser
static const std::string dimName = "xyzklmnopqrstuv"
Letters associated with directions in input file.
Detailed Description
Main parser for PIMC code.
Version:
$Revision$
Author:
John Shumway
Definition at line 23 of file MainParser.h.
Constructor & Destructor Documentation
MainParser::MainParser (const std::string & filename)
Construct by providing an input xml file.
Definition at line 22 of file MainParser.cc.
References context, and doc.
MainParser::~MainParser ()
Virtual destructor.
Definition at line 28 of file MainParser.cc.
References context, and doc.
Member Function Documentation
void MainParser::parse ()
Parse from the context.
Definition at line 33 of file MainParser.cc.
References context.
Referenced by main().
void MainParser::parse (const xmlXPathContextPtr & ctxt) virtual
Parse from a context.
Reimplemented from XMLParser.
Definition at line 37 of file MainParser.cc.
References filename, ActionParser::getAction(), ActionParser::getActionChoice(), ActionParser::getDoubleAction(), EstimatorParser::getEstimatorManager(), XMLParser::getIntAttribute(), SimInfoParser::getSimInfo(), MPIManager::isMain(), MainSpinParser::parse(), SimInfoParser::parse(), ActionParser::parse(), EstimatorParser::parse(), PIMCParser::parse(), EstimatorManager::recordInputDocument(), and Algorithm::run().
Member Data Documentation
xmlXPathContextPtr MainParser::context private
The context to parse from.
Definition at line 39 of file MainParser.h.
Referenced by MainParser(), parse(), and ~MainParser().
xmlDocPtr MainParser::doc private
The xml document to parse from.
Definition at line 37 of file MainParser.h.
Referenced by MainParser(), and ~MainParser().
const std::string MainParser::filename private
The input file name.
Definition at line 35 of file MainParser.h.
Referenced by parse().
The documentation for this class was generated from the following files:
MainParser.h
MainParser.cc