pi: Path integral Quantum Monte Carlo: NonZeroSectionChooser Class Reference
NonZeroSectionChooser Class Reference
Algorithm class for choosing a section.
#include <NonZeroSectionChooser.h>
Public Member Functions
NonZeroSectionChooser (const int nlevel, Paths &paths, Action &action, const BeadFactory &)
virtual ~NonZeroSectionChooser ()
virtual void run ()
Run the algorithm.
Public Member Functions inherited from SectionChooser
SectionChooser (int nlevel, int npart, Paths &paths, Action &action, const BeadFactory &)
virtual ~SectionChooser ()
Beads< NDIM > & getBeads () const
Permutation & getPermutation () const
int getFirstSliceIndex () const
int getNLevel () const
const Paths & getPaths () const
Public Member Functions inherited from CompositeAlgorithm
CompositeAlgorithm (const int nstep)
Constructor.
virtual ~CompositeAlgorithm ()
Virtual destructor.
void resize (const int n)
Resize the number of steps in the algorithm.
void set (const int i, Algorithm *a)
Set algorithm for step i.
Public Member Functions inherited from Algorithm
virtual ~Algorithm ()
Additional Inherited Members
Protected Attributes inherited from SectionChooser
Paths * paths
Action * action
Beads< NDIM > * beads
Permutation * permutation
const int nlevel
int iFirstSlice
gsl_qrng * qrng
Detailed Description
Algorithm class for choosing a section.
Definition at line 12 of file NonZeroSectionChooser.h.
Constructor & Destructor Documentation
NonZeroSectionChooser::NonZeroSectionChooser (const int nlevel, Paths & paths, Action & action, const BeadFactory & beadFactory)
Definition at line 16 of file NonZeroSectionChooser.cc.
NonZeroSectionChooser::~NonZeroSectionChooser () virtual
Definition at line 21 of file NonZeroSectionChooser.cc.
Member Function Documentation
void NonZeroSectionChooser::run () virtual
Run the algorithm.
Reimplemented from SectionChooser.
Definition at line 24 of file NonZeroSectionChooser.cc.
References SectionChooser::action, SectionChooser::beads, Paths::getBeads(), Paths::getHighestSampledSlice(), Paths::getLowestOwnedSlice(), Paths::getNSlice(), Beads< TDIM >::getNSlice(), RandomNumGenerator::getRand(), SectionChooser::iFirstSlice, Action::initialize(), SectionChooser::paths, SectionChooser::permutation, Paths::putBeads(), Permutation::reset(), and Paths::setBuffers().
The documentation for this class was generated from the following files:
NonZeroSectionChooser.h
NonZeroSectionChooser.cc