pi: Path integral Quantum Monte Carlo: TimpQPC Class Reference
TimpQPC Class Reference
Class for calculating the action for a model of a quantum point contact.
#include <TimpQPC.h>
Public Types
typedef blitz::Array< int, 1 > IArray
Typedefs.
Public Types inherited from Action
typedef blitz::TinyVector
< double, NDIM > Vec
typedef blitz::Array< Vec, 1 > VArray
Public Member Functions
TimpQPC (const SuperCell &cell, const Species &species, const double tau, const double width=189., const double length=587., const double vG=-0.03675, const double z=189., MPIManager *mpi=0)
Constructor by providing the timestep tau.
virtual ~TimpQPC ()
Virtual destructor.
virtual double getActionDifference (const SectionSamplerInterface &, const int level)
Calculate the difference in action.
virtual double getActionDifference (const Paths &, const VArray &displacement, int nmoving, const IArray &movingIndex, int iFirstSlice, int iLastSlice)
virtual double getTotalAction (const Paths &, const int level) const
Calculate the total action.
virtual void getBeadAction (const Paths &, int ipart, int islice, double &u, double &utau, double &ulambda, Vec &fm, Vec &fp) const
Calculate the action and derivatives at a bead.
Public Member Functions inherited from Action
virtual ~Action ()
virtual void initialize (const SectionChooser &)
Initialize for a sampling section.
virtual void acceptLastMove ()
Accept last move.
virtual const Action * getActionPointerByType (const std::type_info &type) const
Returns pointer to Action of type t, otherwise returns null pointer.
Private Member Functions
double v (double x, double y) const
Evaluate the potential at a point.
double f (const double u, const double v) const
Helper functions.
Private Attributes
const double tau
The timestep.
const double width
The width of the barrier electrode.
const double length
The length of the QPC gap.
const double vG
The voltage on the gate.
const double z
The distance from the 2DEG to the gates.
const int ifirst
The first particle in this interaction.
const int npart
The number of particles with this interaction.
const double lx
const double ly
Static Private Attributes
static const double PI = acos(-1.0)
Pi.
Detailed Description
Class for calculating the action for a model of a quantum point contact.
This is a parameterized model of the repulsive potential for gates with potential , width w, a gap length l, a distance z above the 2DEG. From Temp (eq. 1) in Semiconductors and Semimetals 35, 113-190 (1992).
where
We set the default values to w=0.01 um, l=0.03 um, vG=-1V, and z=0.01 um.
Version:
$Revision$
Author:
John Shumway.
Definition at line 30 of file TimpQPC.h.
Member Typedef Documentation
typedef blitz::Array<int,1> TimpQPC::IArray
Typedefs.
Reimplemented from Action.
Definition at line 33 of file TimpQPC.h.
Constructor & Destructor Documentation
TimpQPC::TimpQPC (const SuperCell & cell, const Species & species, const double tau, const double width = 189., const double length = 587., const double vG = -0.03675, const double z = 189., MPIManager * mpi = 0)
Constructor by providing the timestep tau.
Definition at line 11 of file TimpQPC.cc.
References MPIManager::isMain(), lx, ly, and v().
virtual TimpQPC::~TimpQPC () inline virtual
Virtual destructor.
Definition at line 40 of file TimpQPC.h.
Member Function Documentation
double TimpQPC::f (const double u, const double v) const private
Helper functions.
Definition at line 102 of file TimpQPC.cc.
References PI, and vG.
Referenced by v().
double TimpQPC::getActionDifference (const SectionSamplerInterface & sampler, const int level) virtual
Calculate the difference in action.
Implements Action.
Definition at line 33 of file TimpQPC.cc.
References ifirst, npart, tau, and v().
double TimpQPC::getActionDifference (const Paths & paths, const VArray & displacement, int nmoving, const IArray & movingIndex, int iFirstSlice, int iLastSlice) virtual
Reimplemented from Action.
Definition at line 74 of file TimpQPC.cc.
References ifirst, npart, SuperCell::pbc(), tau, and v().
void TimpQPC::getBeadAction (const Paths & paths, int ipart, int islice, double & u, double & utau, double & ulambda, Vec & fm, Vec & fp) const virtual
Calculate the action and derivatives at a bead.
Implements Action.
Definition at line 64 of file TimpQPC.cc.
References ifirst, npart, tau, and v().
double TimpQPC::getTotalAction (const Paths & paths, const int level) const virtual
Calculate the total action.
Implements Action.
Definition at line 60 of file TimpQPC.cc.
double TimpQPC::v (double x, double y) const private
Evaluate the potential at a point.
Definition at line 95 of file TimpQPC.cc.
References f(), length, width, and z.
Referenced by getActionDifference(), getBeadAction(), and TimpQPC().
Member Data Documentation
const int TimpQPC::ifirst private
The first particle in this interaction.
Definition at line 67 of file TimpQPC.h.
Referenced by getActionDifference(), and getBeadAction().
const double TimpQPC::length private
The length of the QPC gap.
Definition at line 61 of file TimpQPC.h.
Referenced by v().
const double TimpQPC::lx private
Definition at line 70 of file TimpQPC.h.
Referenced by TimpQPC().
const double TimpQPC::ly private
Definition at line 70 of file TimpQPC.h.
Referenced by TimpQPC().
const int TimpQPC::npart private
The number of particles with this interaction.
Definition at line 69 of file TimpQPC.h.
Referenced by getActionDifference(), and getBeadAction().
const double TimpQPC::PI = acos(-1.0) static private
Pi.
Definition at line 72 of file TimpQPC.h.
Referenced by f().
const double TimpQPC::tau private
The timestep.
Definition at line 57 of file TimpQPC.h.
Referenced by getActionDifference(), and getBeadAction().
const double TimpQPC::vG private
The voltage on the gate.
Definition at line 63 of file TimpQPC.h.
Referenced by f().
const double TimpQPC::width private
The width of the barrier electrode.
Definition at line 59 of file TimpQPC.h.
Referenced by v().
const double TimpQPC::z private
The distance from the 2DEG to the gates.
Definition at line 65 of file TimpQPC.h.
Referenced by v().
The documentation for this class was generated from the following files:
TimpQPC.h
TimpQPC.cc