pi: Path integral Quantum Monte Carlo: EwaldSum Class Reference
EwaldSum Class Reference
Class for creating and evaluating Ewald sums.
#include <EwaldSum.h>
Public Types
typedef blitz::TinyVector
< double, NDIM > Vec
typedef blitz::TinyVector< int,
NDIM > IVec
typedef blitz::Array< int, 1 > IArray
typedef blitz::Array< double, 1 > Array
typedef blitz::Array< Vec, 1 > VArray
typedef blitz::Array< IVec, 1 > IVArray
typedef std::complex< double > Complex
typedef blitz::Array< Complex, 2 > CArray2
Public Member Functions
EwaldSum (const SuperCell &, const int npart, const double rcut, const double kcut)
Constructor calcuates the k-vectors for a given rcut and kcut.
virtual ~EwaldSum ()
Virtual destructor.
virtual double evalFR (const double r) const =0
Returns , used to cancel tails on actions or potentials.
virtual double evalFR0 () const =0
Returns , used in evalSelfEnergy.
virtual double evalFK (const double k) const =0
Returns , used to set up vk array.
virtual double evalFK0 () const =0
Returns , used in evalSelfEnergy for interaction with neutralizing background if system has a net charge.
double getkvec2 (const int index)
int gettotk ()
Vec getDeltak ()
Vec getkvec (int i)
double evalLongRange (const VArray &r) const
Evaluate the long range sum.
void evalSelfEnergy ()
Evaluate the self energy using evalFR0 and evalFK0 virtual methods.
Array & getQArray ()
Get a reference to the charge array.
void setLongRangeArray ()
Set the long range table using the evalFK virtual method.
Protected Member Functions
double calcLongRangeUtau (VArray &r) const
Calculate the long range part.
Protected Attributes
const SuperCell & cell
The SuperCell.
const int npart
The number of particles.
const double rcut
Real space cutoff.
const double kcut
K-space cutoff.
double selfEnergy
Self energy;.
Array q
The particle charges.
VArray pos
The particle positions.
IVec ikmax
Integer limits of k-space sums.
Vec deltak
Reciprical space lattice spacing.
int totk
Number of k-vectors.
Array vk
Stored values of k-space potential.
IVArray kvec
Stored k-vectors.
Array kvec2
Stored magnetude of k-vectors.
CArray2 eikx
Arrays to tabulate .
CArray2 eiky
CArray2 eikz
double oneOver2V
The prefactor on the k-space sum, 1/2V.
Static Protected Attributes
static const double PI = 3.14159265358979
Constants.
Detailed Description
Class for creating and evaluating Ewald sums.
The Ewald sum technique enables fast evaluation of a periodic sum of long-range potentials. At the heart of the method is a function that behaves as for large r, but is smooth for small r. The traditional choice for this function is . The periodic sum of this smooth function may be evaluated efficiently in k-space.
where the prime on the sum indicates that the i=j term is omitted for L=0. The left hand side of this equation may be subtracted from any sum over pair actions or potentials to remove 1/r tails and periodic images, then the quantity is easily added back in using the k-space sum on the right hand side. Two choices for f(r) are implemented as sub-classes: TradEwaldSum makes the traditional choice that uses an error function, and OptEwaldSum uses a polynomial fit to connect smoothly to the 1/r tail and optimized to converge quickly in k-space.
Version:
$Revision$
Author:
John Shumway.
Definition at line 60 of file EwaldSum.h.
Member Typedef Documentation
typedef blitz::Array<double,1> EwaldSum::Array
Definition at line 65 of file EwaldSum.h.
typedef blitz::Array<Complex,2> EwaldSum::CArray2
Definition at line 69 of file EwaldSum.h.
typedef std::complex<double> EwaldSum::Complex
Definition at line 68 of file EwaldSum.h.
typedef blitz::Array<int,1> EwaldSum::IArray
Definition at line 64 of file EwaldSum.h.
typedef blitz::Array<IVec,1> EwaldSum::IVArray
Definition at line 67 of file EwaldSum.h.
typedef blitz::TinyVector<int,NDIM> EwaldSum::IVec
Definition at line 63 of file EwaldSum.h.
typedef blitz::Array<Vec,1> EwaldSum::VArray
Definition at line 66 of file EwaldSum.h.
typedef blitz::TinyVector<double,NDIM> EwaldSum::Vec
Definition at line 62 of file EwaldSum.h.
Constructor & Destructor Documentation
EwaldSum::EwaldSum (const SuperCell & cell, const int npart, const double rcut, const double kcut)
Constructor calcuates the k-vectors for a given rcut and kcut.
Definition at line 16 of file EwaldSum.cc.
References deltak, ikmax, kvec, kvec2, q, totk, and vk.
EwaldSum::~EwaldSum () virtual
Virtual destructor.
Definition at line 100 of file EwaldSum.cc.
Member Function Documentation
double EwaldSum::calcLongRangeUtau (VArray & r) const protected
Calculate the long range part.
virtual double EwaldSum::evalFK (const double k) const pure virtual
Returns , used to set up vk array.
Implemented in TradEwaldSum, and OptEwaldSum.
Referenced by setLongRangeArray().
virtual double EwaldSum::evalFK0 () const pure virtual
Returns , used in evalSelfEnergy for interaction with neutralizing background if system has a net charge.
Implemented in TradEwaldSum, and OptEwaldSum.
Referenced by evalSelfEnergy().
virtual double EwaldSum::evalFR (const double r) const pure virtual
Returns , used to cancel tails on actions or potentials.
Implemented in TradEwaldSum, and OptEwaldSum.
Referenced by EwaldCoulombEstimator::EwaldCoulombEstimator(), and EwaldCoulombEstimator::handleLink().
virtual double EwaldSum::evalFR0 () const pure virtual
Returns , used in evalSelfEnergy.
Implemented in TradEwaldSum, and OptEwaldSum.
Referenced by evalSelfEnergy(), and EwaldCoulombEstimator::EwaldCoulombEstimator().
double EwaldSum::evalLongRange (const VArray & r) const
Evaluate the long range sum.
Definition at line 103 of file EwaldSum.cc.
References deltak, eikx, eiky, eikz, ikmax, kvec, npart, oneOver2V, q, selfEnergy, totk, and vk.
Referenced by CoulombAction::getAction(), CoulombAction::getActionDifference(), CoulombAction::getBeadAction(), and EwaldCoulombEstimator::handleLink().
void EwaldSum::evalSelfEnergy ()
Evaluate the self energy using evalFR0 and evalFK0 virtual methods.
You must call this function again if you change the charge array.
Definition at line 183 of file EwaldSum.cc.
References evalFK0(), evalFR0(), oneOver2V, q, and selfEnergy.
Referenced by CoulombAction::CoulombAction(), EwaldCoulombEstimator::EwaldCoulombEstimator(), OptEwaldSum::OptEwaldSum(), and TradEwaldSum::TradEwaldSum().
Vec EwaldSum::getDeltak () inline
Definition at line 87 of file EwaldSum.h.
References deltak.
Referenced by EwaldCoulombEstimator::testEwaldTotalCharge().
Vec EwaldSum::getkvec (int i) inline
Definition at line 88 of file EwaldSum.h.
References kvec.
Referenced by EwaldCoulombEstimator::testEwaldTotalCharge().
double EwaldSum::getkvec2 (const int index) inline
Definition at line 85 of file EwaldSum.h.
References kvec2.
Array& EwaldSum::getQArray () inline
Get a reference to the charge array.
Definition at line 96 of file EwaldSum.h.
References q.
Referenced by CoulombAction::CoulombAction(), and EwaldCoulombEstimator::EwaldCoulombEstimator().
int EwaldSum::gettotk () inline
Definition at line 86 of file EwaldSum.h.
References totk.
Referenced by EwaldCoulombEstimator::testEwaldTotalCharge().
void EwaldSum::setLongRangeArray ()
Set the long range table using the evalFK virtual method.
Definition at line 92 of file EwaldSum.cc.
References evalFK(), kvec2, totk, and vk.
Referenced by OptEwaldSum::OptEwaldSum(), and TradEwaldSum::TradEwaldSum().
Member Data Documentation
const SuperCell& EwaldSum::cell protected
The SuperCell.
Definition at line 101 of file EwaldSum.h.
Vec EwaldSum::deltak protected
Reciprical space lattice spacing.
Definition at line 119 of file EwaldSum.h.
Referenced by evalLongRange(), EwaldSum(), getDeltak(), and OptEwaldSum::OptEwaldSum().
CArray2 EwaldSum::eikx mutable protected
Arrays to tabulate .
Definition at line 129 of file EwaldSum.h.
Referenced by evalLongRange().
CArray2 EwaldSum::eiky mutable protected
Definition at line 129 of file EwaldSum.h.
Referenced by evalLongRange().
CArray2 EwaldSum::eikz mutable protected
Definition at line 129 of file EwaldSum.h.
Referenced by evalLongRange().
IVec EwaldSum::ikmax protected
Integer limits of k-space sums.
Definition at line 117 of file EwaldSum.h.
Referenced by evalLongRange(), and EwaldSum().
const double EwaldSum::kcut protected
K-space cutoff.
Definition at line 107 of file EwaldSum.h.
Referenced by OptEwaldSum::OptEwaldSum().
IVArray EwaldSum::kvec protected
Stored k-vectors.
Definition at line 125 of file EwaldSum.h.
Referenced by evalLongRange(), EwaldSum(), and getkvec().
Array EwaldSum::kvec2 protected
Stored magnetude of k-vectors.
Definition at line 127 of file EwaldSum.h.
Referenced by EwaldSum(), getkvec2(), and setLongRangeArray().
const int EwaldSum::npart protected
The number of particles.
Definition at line 103 of file EwaldSum.h.
Referenced by evalLongRange().
double EwaldSum::oneOver2V protected
The prefactor on the k-space sum, 1/2V.
Definition at line 133 of file EwaldSum.h.
Referenced by evalLongRange(), and evalSelfEnergy().
const double EwaldSum::PI = 3.14159265358979 static protected
Constants.
Definition at line 115 of file EwaldSum.h.
Referenced by OptEwaldSum::evalFK(), TradEwaldSum::evalFK(), OptEwaldSum::evalFK0(), TradEwaldSum::evalFK0(), TradEwaldSum::evalFR0(), and OptEwaldSum::OptEwaldSum().
VArray EwaldSum::pos mutable protected
The particle positions.
Definition at line 113 of file EwaldSum.h.
Array EwaldSum::q mutable protected
The particle charges.
Definition at line 111 of file EwaldSum.h.
Referenced by evalLongRange(), evalSelfEnergy(), EwaldSum(), and getQArray().
const double EwaldSum::rcut protected
Real space cutoff.
Definition at line 105 of file EwaldSum.h.
Referenced by OptEwaldSum::evalFK(), OptEwaldSum::evalFK0(), OptEwaldSum::evalFR(), OptEwaldSum::evalFRcut(), and OptEwaldSum::OptEwaldSum().
double EwaldSum::selfEnergy protected
Self energy;.
Definition at line 109 of file EwaldSum.h.
Referenced by evalLongRange(), and evalSelfEnergy().
int EwaldSum::totk protected
Number of k-vectors.
Definition at line 121 of file EwaldSum.h.
Referenced by evalLongRange(), EwaldSum(), gettotk(), and setLongRangeArray().
Array EwaldSum::vk protected
Stored values of k-space potential.
Definition at line 123 of file EwaldSum.h.
Referenced by evalLongRange(), EwaldSum(), and setLongRangeArray().
The documentation for this class was generated from the following files:
EwaldSum.h
EwaldSum.cc