pi: Path integral Quantum Monte Carlo: PermutationChooser Class Reference
PermutationChooser Class Reference
Base class for algorithms for selecting a permutation.
#include <PermutationChooser.h>
Public Member Functions
PermutationChooser (int size)
virtual ~PermutationChooser ()
virtual bool choosePermutation ()
const Permutation & getPermutation ()
virtual void init ()
virtual void setMLSampler (const MultiLevelSampler *)
virtual double getLnTranProb () const
Protected Attributes
Permutation * permutation
Detailed Description
Base class for algorithms for selecting a permutation.
Defaults to the trivial choice of the direct permutation.
Definition at line 8 of file PermutationChooser.h.
Constructor & Destructor Documentation
PermutationChooser::PermutationChooser (int size)
Definition at line 7 of file PermutationChooser.cc.
PermutationChooser::~PermutationChooser () virtual
Definition at line 11 of file PermutationChooser.cc.
References permutation.
Member Function Documentation
bool PermutationChooser::choosePermutation () virtual
Reimplemented in WalkingChooser, PairChooser, and RandomPermutationChooser.
Definition at line 15 of file PermutationChooser.cc.
Referenced by DoubleMLSampler::run(), and MultiLevelSampler::run().
virtual double PermutationChooser::getLnTranProb () const inline virtual
Reimplemented in WalkingChooser, PairChooser, and RandomPermutationChooser.
Definition at line 25 of file PermutationChooser.h.
Referenced by DoubleMLSampler::run(), and MultiLevelSampler::run().
const Permutation& PermutationChooser::getPermutation () inline
Definition at line 15 of file PermutationChooser.h.
References permutation.
Referenced by PairChooser::choosePermutation(), DoubleMLSampler::run(), MultiLevelSampler::run(), and MultiLevelSampler::tryMove().
virtual void PermutationChooser::init () inline virtual
Reimplemented in WalkingChooser, PairChooser, RandomPermutationChooser, and SpinStatePermutationChooser.
Definition at line 19 of file PermutationChooser.h.
Referenced by DoubleMLSampler::run(), and MultiLevelSampler::run().
virtual void PermutationChooser::setMLSampler (const MultiLevelSampler *) inline virtual
Reimplemented in PairChooser, and WalkingChooser.
Definition at line 22 of file PermutationChooser.h.
Referenced by PIMCParser::parseAlgorithm().
Member Data Documentation
Permutation* PermutationChooser::permutation protected
Definition at line 29 of file PermutationChooser.h.
Referenced by RandomPermutationChooser::choosePermutation(), getPermutation(), TwoPairChooser::TwoPairChooser(), WalkingChooser::WalkingChooser(), and ~PermutationChooser().
The documentation for this class was generated from the following files:
PermutationChooser.h
PermutationChooser.cc