pi: Path integral Quantum Monte Carlo: Action Class Reference
Action Class Reference
Virtual base class for calculating the action.
#include <Action.h>
Public Types
typedef blitz::TinyVector
< double, NDIM > Vec
typedef blitz::Array< int, 1 > IArray
typedef blitz::Array< Vec, 1 > VArray
Public Member Functions
virtual ~Action ()
virtual double getActionDifference (const SectionSamplerInterface &, int level)=0
virtual double getActionDifference (const Paths &, const VArray &displacement, int nmoving, const IArray &movingIndex, int iFirstSlice, int iLastSlice)
virtual double getTotalAction (const Paths &, const int level) const =0
virtual void getBeadAction (const Paths &, int ipart, int islice, double &u, double &utau, double &ulambda, Vec &fm, Vec &fp) const =0
Calculate action and derivatives at a bead (defaults to no contribution).
virtual void initialize (const SectionChooser &)
Initialize for a sampling section.
virtual void acceptLastMove ()
Accept last move.
virtual const Action * getActionPointerByType (const std::type_info &type) const
Returns pointer to Action of type t, otherwise returns null pointer.
Detailed Description
Virtual base class for calculating the action.
Action objects can compute differences in action from a MultiLevelSampler, the total action, and the action and its derivatives at a bead.
Version:
$Revision$
Author:
John Shumway.
Definition at line 36 of file Action.h.
Member Typedef Documentation
typedef blitz::Array<int,1> Action::IArray
Reimplemented in WellImageAction, JelliumSlab, EwaldAction, PairAction, SmoothedGridPotential, SHOAction, StillWebAction, HyperbolicAction, SpinAction, QPCAction, SpringAction, PrimCosineAction, SpringTensorAction, GroundStateWFNodes, EFieldAction, GridPotential, SphereAction, GaussianAction, PrimAnisSHOAction, PrimShellAction, PrimSHOAction, PrimTorusAction, SHODotAction, TwoQDAction, PrimImageAction, EMARateAction, GateAction, GrapheneAction, OpticalLatticeAction, RingGateAction, TimpQPC, DotGeomAction, GaussianDotAction, PrimColloidalAction, and CoulombAction.
Definition at line 39 of file Action.h.
typedef blitz::Array<Vec,1> Action::VArray
Reimplemented in SpringTensorAction, DotGeomAction, and GateAction.
Definition at line 40 of file Action.h.
typedef blitz::TinyVector<double,NDIM> Action::Vec
Reimplemented in EwaldAction, SmoothedGridPotential, EFieldAction, GroundStateWFNodes, SphereAction, OpticalLatticeAction, DotGeomAction, GaussianDotAction, GateAction, and CoulombAction.
Definition at line 38 of file Action.h.
Constructor & Destructor Documentation
virtual Action::~Action () inline virtual
Definition at line 42 of file Action.h.
Member Function Documentation
virtual void Action::acceptLastMove () inline virtual
Accept last move.
Reimplemented in EwaldAction, ActionChoice, SpinAction, CompositeAction, and GroundStateWFNodes.
Definition at line 59 of file Action.h.
virtual double Action::getActionDifference (const SectionSamplerInterface & , int level) pure virtual
Implemented in WellImageAction, PairAction, EwaldAction, JelliumSlab, SmoothedGridPotential, ImagePairAction, SHOAction, StillWebAction, HyperbolicAction, SpinAction, QPCAction, SpringAction, EFieldAction, ActionChoice, DotGeomAction, GridPotential, PrimCosineAction, SpringTensorAction, EMARateAction, SHODotAction, SphereAction, OpticalLatticeAction, PrimAnisSHOAction, PrimShellAction, PrimSHOAction, PrimTorusAction, TimpQPC, TwoQDAction, GroundStateWFNodes, GateAction, GaussianAction, PrimImageAction, CompositeAction, EwaldImagePairAction, GaussianDotAction, GrapheneAction, RingGateAction, PrimColloidalAction, and CoulombAction.
virtual double Action::getActionDifference (const Paths & , const VArray & displacement, int nmoving, const IArray & movingIndex, int iFirstSlice, int iLastSlice) inline virtual
Reimplemented in PairAction, SHOAction, SpringAction, EFieldAction, ActionChoice, GridPotential, EMARateAction, GateAction, SHODotAction, TimpQPC, CompositeAction, EwaldImagePairAction, and CoulombAction.
Definition at line 45 of file Action.h.
virtual const Action* Action::getActionPointerByType (const std::type_info & type) const inline virtual
Returns pointer to Action of type t, otherwise returns null pointer.
Reimplemented in CompositeAction.
Definition at line 61 of file Action.h.
Referenced by CompositeAction::getActionPointerByType(), and EstimatorParser::parse().
virtual void Action::getBeadAction (const Paths & , int ipart, int islice, double & u, double & utau, double & ulambda, Vec & fm, Vec & fp) const pure virtual
Calculate action and derivatives at a bead (defaults to no contribution).
Implemented in WellImageAction, PairAction, EwaldAction, JelliumSlab, SmoothedGridPotential, ImagePairAction, SHOAction, StillWebAction, HyperbolicAction, SpinAction, SpringAction, ActionChoice, EFieldAction, QPCAction, EMARateAction, GridPotential, GateAction, SHODotAction, SpringTensorAction, DotGeomAction, PrimCosineAction, TimpQPC, CompositeAction, EwaldImagePairAction, SphereAction, GroundStateWFNodes, OpticalLatticeAction, PrimAnisSHOAction, PrimShellAction, PrimSHOAction, PrimTorusAction, TwoQDAction, GaussianAction, PrimImageAction, GaussianDotAction, GrapheneAction, PrimColloidalAction, RingGateAction, and CoulombAction.
Referenced by ThermoEnergyEstimator::handleLink(), VirialEnergyEstimator::handleLink(), and ZeroVarDensityEstimator::handleLink().
virtual double Action::getTotalAction (const Paths & , const int level) const pure virtual
Implemented in WellImageAction, PairAction, EwaldAction, JelliumSlab, SmoothedGridPotential, ImagePairAction, SHOAction, StillWebAction, HyperbolicAction, SpinAction, SpringAction, ActionChoice, EFieldAction, QPCAction, GridPotential, EMARateAction, GateAction, SHODotAction, DotGeomAction, PrimCosineAction, SpringTensorAction, TimpQPC, CompositeAction, EwaldImagePairAction, SphereAction, OpticalLatticeAction, PrimAnisSHOAction, PrimShellAction, PrimSHOAction, PrimTorusAction, TwoQDAction, GroundStateWFNodes, GaussianAction, PrimImageAction, GaussianDotAction, GrapheneAction, RingGateAction, PrimColloidalAction, and CoulombAction.
virtual void Action::initialize (const SectionChooser &) inline virtual
Initialize for a sampling section.
Reimplemented in EwaldAction, ActionChoice, CompositeAction, and GroundStateWFNodes.
Definition at line 56 of file Action.h.
The documentation for this class was generated from the following file:
Action.h