pi: Path integral Quantum Monte Carlo: ActionParser Class Reference
ActionParser Class Reference
XML Parser for actions.
#include <ActionParser.h>
Public Types
typedef blitz::TinyVector
< double, NDIM > Vec
Public Member Functions
ActionParser (const SimulationInfo &, const int maxlevel, MPIManager *)
Constructor.
~ActionParser ()
Virtual destructor.
void parse (const xmlXPathContextPtr &ctxt)
Parse some xml.
Action * getAction ()
Return the Action object.
DoubleAction * getDoubleAction ()
Return the DoubleAction object.
ActionChoiceBase * getActionChoice ()
Return the ActionChoice object.
Public Member Functions inherited from XMLUnitParser
XMLUnitParser (const Units *)
Constructor.
virtual ~XMLUnitParser ()
Destructor.
double getEnergyAttribute (const xmlNodePtr &node, const std::string &attName)
Parse a length with unit conversion.
double getLengthAttribute (const xmlNodePtr &node, const std::string &attName)
Parse a energy with unit conversion.
double getTimeAttribute (const xmlNodePtr &node, const std::string &attName)
Parse an inverse energy with unit conversion.
double getInvLengthAttribute (const xmlNodePtr &node, const std::string &attName)
Parse an inverse length with unit conversion.
double getDensityAttribute (const xmlNodePtr &node, const std::string &attName)
Parse a density with unit conversion.
double getMassAttribute (const xmlNodePtr &node, const std::string &attName)
double getFieldStrengthAttribute (const xmlNodePtr &node, const std::string &attName)
Parse a field strength with unit conversion.
void parseUnitAndValue (const xmlNodePtr &node, const std::string &attName)
Internal method to parse a unit and value.
Public Member Functions inherited from XMLParser
virtual ~XMLParser ()
Destructor.
Private Member Functions
void parseActions (const xmlXPathContextPtr &ctxt, xmlXPathObjectPtr &obj, CompositeAction *action, CompositeDoubleAction *doubleComposite)
Function to parse all the action xml tags.
Action * parseEwaldActions (const xmlXPathContextPtr &ctxt)
Parse actions for EwaldAction.
void parseOrbitalDM (std::vector< const AtomicOrbitalDM * > &, const Species &, const xmlXPathContextPtr &ctxt)
Parse atomic orbitals for AugmentedNdoes.
NodeModel * parseNodeModel (const xmlXPathContextPtr &ctxt, xmlNodePtr &actNode, const Species &species)
Private Attributes
Action * action
The Action object.
DoubleAction * doubleAction
The DoubleAction object.
ActionChoiceBase * actionChoice
Choice of actions if different models are being sampled.
const SimulationInfo & simInfo
General simulation information.
const double tau
The timestep.
const int maxlevel
The maximum number of levels.
MPIManager * mpi
MPIManager.
Static Private Attributes
static const std::string dimName = "xyzklmnopqrstuv"
Letters associated with directions in input file.
Additional Inherited Members
Public Attributes inherited from XMLUnitParser
const Units * units
Information about the units and conversions.
double value
The most recently parsed value.
std::string unit
The most recently parsed unit name.
Detailed Description
XML Parser for actions.
Version:
$Revision$
Author:
John Shumway
Definition at line 34 of file ActionParser.h.
Member Typedef Documentation
typedef blitz::TinyVector<double,NDIM> ActionParser::Vec
Reimplemented from XMLParser.
Definition at line 36 of file ActionParser.h.
Constructor & Destructor Documentation
ActionParser::ActionParser (const SimulationInfo & simInfo, const int maxlevel, MPIManager * mpi)
Constructor.
Definition at line 78 of file ActionParser.cc.
ActionParser::~ActionParser () inline
Virtual destructor.
Definition at line 40 of file ActionParser.h.
Member Function Documentation
Action* ActionParser::getAction () inline
Return the Action object.
Definition at line 44 of file ActionParser.h.
References action.
Referenced by MainParser::parse().
ActionChoiceBase* ActionParser::getActionChoice () inline
Return the ActionChoice object.
Definition at line 48 of file ActionParser.h.
References actionChoice.
Referenced by MainParser::parse().
DoubleAction* ActionParser::getDoubleAction () inline
Return the DoubleAction object.
Definition at line 46 of file ActionParser.h.
References doubleAction.
Referenced by MainParser::parse().
void ActionParser::parse (const xmlXPathContextPtr & ctxt) virtual
Parse some xml.
Reimplemented from XMLParser.
Definition at line 86 of file ActionParser.cc.
References action, doubleAction, CompositeDoubleAction::getCount(), and parseActions().
Referenced by MainParser::parse().
void ActionParser::parseActions (const xmlXPathContextPtr & ctxt, xmlXPathObjectPtr & obj, CompositeAction * action, CompositeDoubleAction * doubleComposite) private
Function to parse all the action xml tags.
Definition at line 99 of file ActionParser.cc.
References action, actionChoice, CompositeDoubleAction::addAction(), CompositeAction::addAction(), dimName, XMLParser::getBoolAttribute(), CompositeDoubleAction::getCount(), CompositeAction::getCount(), XMLParser::getDoubleAttribute(), XMLUnitParser::getEnergyAttribute(), XMLUnitParser::getFieldStrengthAttribute(), XMLParser::getIntAttribute(), XMLUnitParser::getInvLengthAttribute(), XMLUnitParser::getLengthAttribute(), ActionChoiceBase::getModelState(), XMLParser::getName(), PrimitivePairAction::getScatteringLength(), XMLParser::getStringAttribute(), EMARateAction::includeCoulombContribution(), maxlevel, mpi, parseEwaldActions(), parseNodeModel(), simInfo, and tau.
Referenced by parse().
Action * ActionParser::parseEwaldActions (const xmlXPathContextPtr & ctxt) private
Parse actions for EwaldAction.
Definition at line 703 of file ActionParser.cc.
References EwaldAction::addAction(), XMLParser::getDoubleAttribute(), XMLParser::getIntAttribute(), XMLUnitParser::getLengthAttribute(), XMLParser::getStringAttribute(), EwaldAction::setup(), and simInfo.
Referenced by parseActions().
NodeModel * ActionParser::parseNodeModel (const xmlXPathContextPtr & ctxt, xmlNodePtr & actNode, const Species & species) private
Definition at line 756 of file ActionParser.cc.
References dimName, XMLParser::getBoolAttribute(), XMLParser::getDoubleAttribute(), XMLUnitParser::getEnergyAttribute(), XMLParser::getIntAttribute(), XMLUnitParser::getLengthAttribute(), XMLParser::getStringAttribute(), maxlevel, parseOrbitalDM(), and simInfo.
Referenced by parseActions().
void ActionParser::parseOrbitalDM (std::vector< const AtomicOrbitalDM * > & orbitals, const Species & fSpecies, const xmlXPathContextPtr & ctxt) private
Parse atomic orbitals for AugmentedNdoes.
Definition at line 728 of file ActionParser.cc.
References XMLParser::getDoubleAttribute(), XMLParser::getName(), XMLParser::getStringAttribute(), and simInfo.
Referenced by parseNodeModel().
Member Data Documentation
Action* ActionParser::action private
The Action object.
Definition at line 54 of file ActionParser.h.
Referenced by getAction(), parse(), and parseActions().
ActionChoiceBase* ActionParser::actionChoice private
Choice of actions if different models are being sampled.
Definition at line 58 of file ActionParser.h.
Referenced by getActionChoice(), and parseActions().
const std::string ActionParser::dimName = "xyzklmnopqrstuv" static private
Letters associated with directions in input file.
Reimplemented from XMLParser.
Definition at line 73 of file ActionParser.h.
Referenced by parseActions(), and parseNodeModel().
DoubleAction* ActionParser::doubleAction private
The DoubleAction object.
Definition at line 56 of file ActionParser.h.
Referenced by getDoubleAction(), and parse().
const int ActionParser::maxlevel private
The maximum number of levels.
Definition at line 64 of file ActionParser.h.
Referenced by parseActions(), and parseNodeModel().
MPIManager* ActionParser::mpi private
MPIManager.
Definition at line 75 of file ActionParser.h.
Referenced by parseActions().
const SimulationInfo& ActionParser::simInfo private
General simulation information.
Definition at line 60 of file ActionParser.h.
Referenced by parseActions(), parseEwaldActions(), parseNodeModel(), and parseOrbitalDM().
const double ActionParser::tau private
The timestep.
Definition at line 62 of file ActionParser.h.
Referenced by parseActions().
The documentation for this class was generated from the following files:
ActionParser.h
ActionParser.cc