pi: Path integral Quantum Monte Carlo: Mover Class Reference
Mover Class Reference
Virtual base class for routines to select trial moves for beads.
#include <Mover.h>
Public Member Functions
virtual ~Mover ()
virtual double makeMove (MultiLevelSampler &, const int level)=0
Move the samplers moving beads for a given level, returning the probability for the old move divided by the probability for the new move.
virtual double makeDelayedMove (MultiLevelSampler &, const int level)=0
virtual double getForwardProb ()=0
Detailed Description
Virtual base class for routines to select trial moves for beads.
Definition at line 6 of file Mover.h.
Constructor & Destructor Documentation
virtual Mover::~Mover () inline virtual
Definition at line 8 of file Mover.h.
Member Function Documentation
virtual double Mover::getForwardProb () pure virtual
Implemented in FreeSpinMover, SpinMover, FreeMoverPBC, DampedFreeTensorMover, FreeMover, FreeTensorMover, HyperbolicMover, and EMARateMover.
Referenced by DoubleMLSampler::tryMove(), and MultiLevelSampler::tryMove().
virtual double Mover::makeDelayedMove (MultiLevelSampler & , const int level) pure virtual
Implemented in FreeSpinMover, SpinMover, FreeMoverPBC, FreeMover, DampedFreeTensorMover, FreeTensorMover, EMARateMover, and HyperbolicMover.
Referenced by DoubleMLSampler::tryMove(), and MultiLevelSampler::tryMove().
virtual double Mover::makeMove (MultiLevelSampler & , const int level) pure virtual
Move the samplers moving beads for a given level, returning the probability for the old move divided by the probability for the new move.
Implemented in FreeSpinMover, SpinMover, FreeMoverPBC, FreeMover, DampedFreeTensorMover, FreeTensorMover, EMARateMover, and HyperbolicMover.
Referenced by DoubleMLSampler::tryMove(), and MultiLevelSampler::tryMove().
The documentation for this class was generated from the following file:
Mover.h