pi: Path integral Quantum Monte Carlo: PathReader Class Reference
PathReader Class Reference
Class for positioning particles in a cubic lattice.
#include <PathReader.h>
Public Member Functions
PathReader (Paths &paths, std::string &filename, const BeadFactory &beadFactory, const int bfactor=1, MPIManager *mpi=0)
Constructor.
virtual ~PathReader ()
Virtual destructor.
virtual void run ()
Algorithm run method.
Public Member Functions inherited from Positioner
Positioner ()
Constructor.
virtual ~Positioner ()
Virtual destructor.
Public Member Functions inherited from Algorithm
virtual ~Algorithm ()
Private Attributes
Paths & paths
Reference to the Paths.
const std::string filename
Input file name.
const BeadFactory & beadFactory
Bead factory.
const int bfactor
Optional beta multiplication factor for restarting at lower temperature.
MPIManager * mpi
Pointer to the MPI manager.
Detailed Description
Class for positioning particles in a cubic lattice.
Version:
$Revision$
Author:
John Shumway
Definition at line 29 of file PathReader.h.
Constructor & Destructor Documentation
PathReader::PathReader (Paths & paths, std::string & filename, const BeadFactory & beadFactory, const int bfactor = 1, MPIManager * mpi = 0) inline
Constructor.
Definition at line 32 of file PathReader.h.
virtual PathReader::~PathReader () inline virtual
Virtual destructor.
Definition at line 38 of file PathReader.h.
Member Function Documentation
void PathReader::run () virtual
Algorithm run method.
Add cloneID to name if there are clones.
Implements Positioner.
Definition at line 19 of file PathReader.cc.
References beadFactory, bfactor, filename, MPIManager::getCloneID(), MPIManager::getNClone(), MPIManager::getWorkerID(), mpi, and paths.
Member Data Documentation
const BeadFactory& PathReader::beadFactory private
Bead factory.
Definition at line 47 of file PathReader.h.
Referenced by run().
const int PathReader::bfactor private
Optional beta multiplication factor for restarting at lower temperature.
Definition at line 49 of file PathReader.h.
Referenced by run().
const std::string PathReader::filename private
Input file name.
Definition at line 45 of file PathReader.h.
Referenced by run().
MPIManager* PathReader::mpi private
Pointer to the MPI manager.
Definition at line 51 of file PathReader.h.
Referenced by run().
Paths& PathReader::paths private
Reference to the Paths.
Definition at line 43 of file PathReader.h.
Referenced by run().
The documentation for this class was generated from the following files:
PathReader.h
PathReader.cc