pi: Path integral Quantum Monte Carlo: Loop Class Reference
Loop Class Reference
Algorithm class for looping.
#include <Loop.h>
Public Member Functions
Loop (const int nrepeat, const int totalSimTime, const std::string timer, const MPIManager *mpi, const int nsteps=0)
virtual ~Loop ()
virtual void run ()
Run the algorithm.
void printElapsedTime (double dif)
void printAlgorithmTime (double dt)
Public Member Functions inherited from CompositeAlgorithm
CompositeAlgorithm (const int nstep)
Constructor.
virtual ~CompositeAlgorithm ()
Virtual destructor.
void resize (const int n)
Resize the number of steps in the algorithm.
void set (const int i, Algorithm *a)
Set algorithm for step i.
Public Member Functions inherited from Algorithm
virtual ~Algorithm ()
Private Attributes
const int nrepeat
const int totalSimTime
const std::string timer
const MPIManager * mpi
Detailed Description
Algorithm class for looping.
Version:
$Revision$
Author:
John Shumway
Definition at line 31 of file Loop.h.
Constructor & Destructor Documentation
Loop::Loop (const int nrepeat, const int totalSimTime, const std::string timer, const MPIManager * mpi, const int nsteps = 0) inline
Definition at line 33 of file Loop.h.
virtual Loop::~Loop () inline virtual
Definition at line 39 of file Loop.h.
Member Function Documentation
void Loop::printAlgorithmTime (double dt) inline
Definition at line 110 of file Loop.h.
References timer.
Referenced by run().
void Loop::printElapsedTime (double dif) inline
Definition at line 102 of file Loop.h.
Referenced by run().
virtual void Loop::run () inline virtual
Run the algorithm.
Reimplemented from CompositeAlgorithm.
Definition at line 41 of file Loop.h.
References MPIManager::isMain(), mpi, nrepeat, printAlgorithmTime(), printElapsedTime(), CompositeAlgorithm::run(), timer, and totalSimTime.
Member Data Documentation
const MPIManager* Loop::mpi private
Definition at line 121 of file Loop.h.
Referenced by run().
const int Loop::nrepeat private
Definition at line 118 of file Loop.h.
Referenced by run().
const std::string Loop::timer private
Definition at line 120 of file Loop.h.
Referenced by printAlgorithmTime(), and run().
const int Loop::totalSimTime private
Definition at line 119 of file Loop.h.
Referenced by run().
The documentation for this class was generated from the following file:
Loop.h