pi: Path integral Quantum Monte Carlo: Hungarian Class Reference
Hungarian Class Reference
#include <Hungarian.h>
Public Member Functions
Hungarian (int size)
~Hungarian ()
int operator[] (int index) const
void solve (double *matrix)
double getSum () const
Private Member Functions
void assndx (const int *mode, double *a, int *n, int *m, int *ida, int *k, double *sum, int *iw, int *idw)
Private Attributes
int size
int * kindex
int * work
double sum
Static Private Attributes
static const int MODE = 1
Detailed Description
Definition at line 4 of file Hungarian.h.
Constructor & Destructor Documentation
Hungarian::Hungarian (int size)
Definition at line 7 of file Hungarian.cc.
Hungarian::~Hungarian ()
Definition at line 11 of file Hungarian.cc.
References kindex, and work.
Member Function Documentation
void Hungarian::assndx (const int * mode, double * a, int * n, int * m, int * ida, int * k, double * sum, int * iw, int * idw) private
Definition at line 34 of file Hungarian.cc.
Referenced by solve().
double Hungarian::getSum () const
Definition at line 20 of file Hungarian.cc.
References sum.
int Hungarian::operator[] (int index) const
Definition at line 16 of file Hungarian.cc.
References kindex.
void Hungarian::solve (double * matrix)
Definition at line 24 of file Hungarian.cc.
References assndx(), kindex, MODE, size, sum, and work.
Referenced by ExcitonNodes::evaluate(), SHONodes::evaluate(), WireNodes::evaluate(), FreeParticleNodes::evaluate(), AugmentedNodes::evaluate(), and FreeParticleNodes::getDetInvMat().
Member Data Documentation
int* Hungarian::kindex private
Definition at line 14 of file Hungarian.h.
Referenced by operator[](), solve(), and ~Hungarian().
const int Hungarian::MODE = 1 static private
Definition at line 13 of file Hungarian.h.
Referenced by solve().
int Hungarian::size private
Definition at line 12 of file Hungarian.h.
Referenced by solve().
double Hungarian::sum private
Definition at line 16 of file Hungarian.h.
Referenced by getSum(), and solve().
int* Hungarian::work private
Definition at line 15 of file Hungarian.h.
Referenced by solve(), and ~Hungarian().
The documentation for this class was generated from the following files:
Hungarian.h
Hungarian.cc