pi: Path integral Quantum Monte Carlo: EstimatorParser Class Reference
EstimatorParser Class Reference
XML Parser for estimators.
#include <EstimatorParser.h>
Public Types
typedef blitz::TinyVector
< double, NDIM > Vec
typedef blitz::TinyVector< int,
NDIM > IVec
Public Member Functions
EstimatorParser (const SimulationInfo &, const double tau, const Action *action, const DoubleAction *doubleAction, ActionChoiceBase *actionChoice, MPIManager *mpi=0)
Constructor.
~EstimatorParser ()
Virtual destructor.
void parse (const xmlXPathContextPtr &ctxt)
Parse some xml.
EstimatorManager * getEstimatorManager ()
Return the Estimator object.
Private Member Functions
template<int N>
PairCFEstimator< N > * parsePairCF (xmlNodePtr estNode, xmlXPathObjectPtr ctxt)
Parser for pair correlation estimator.
void parseDistance (xmlNodePtr estNode, const xmlXPathContextPtr &ctxt, std::vector< Distance * > &darray, std::vector< double > &min, std::vector< double > &max, std::vector< int > &nbin)
Parser for distance subtags.
void parsePairDistance (xmlNodePtr estNode, const xmlXPathContextPtr &ctxt, std::vector< PairDistance * > &darray, std::vector< double > &min, std::vector< double > &max, std::vector< int > &nbin)
Parser for distance subtags.
template<int N>
SpinChoicePCFEstimator< N > * parseSpinPair (const std::string &name, const std::vector< double > &tmin, const std::vector< double > &tmax, const std::vector< int > &tnbin, const std::vector< PairDistance * > &dist, const bool &samespin)
Parser for spin pairs.
Private Attributes
XMLUnitParser parser
EstimatorManager * manager
The estimator manager.
const SimulationInfo & simInfo
General simulation information.
const double tau
The timestep.
const Action * action
The action.
const DoubleAction * doubleAction
The double action.
ActionChoiceBase * actionChoice
A choice of action models.
MPIManager * mpi
The MPI manager.
Detailed Description
XML Parser for estimators.
Version:
$Revision$
Author:
John Shumway
Definition at line 34 of file EstimatorParser.h.
Member Typedef Documentation
typedef blitz::TinyVector<int,NDIM> EstimatorParser::IVec
Definition at line 37 of file EstimatorParser.h.
typedef blitz::TinyVector<double,NDIM> EstimatorParser::Vec
Definition at line 36 of file EstimatorParser.h.
Constructor & Destructor Documentation
EstimatorParser::EstimatorParser (const SimulationInfo & simInfo, const double tau, const Action * action, const DoubleAction * doubleAction, ActionChoiceBase * actionChoice, MPIManager * mpi = 0)
Constructor.
Definition at line 57 of file EstimatorParser.cc.
References manager.
EstimatorParser::~EstimatorParser ()
Virtual destructor.
Definition at line 66 of file EstimatorParser.cc.
References manager.
Member Function Documentation
EstimatorManager* EstimatorParser::getEstimatorManager () inline
Return the Estimator object.
Definition at line 47 of file EstimatorParser.h.
References manager.
Referenced by MainParser::parse().
void EstimatorParser::parse (const xmlXPathContextPtr & ctxt)
Parse some xml.
Definition at line 68 of file EstimatorParser.cc.
References action, actionChoice, EstimatorManager::add(), doubleAction, Action::getActionPointerByType(), XMLParser::getBoolAttribute(), XMLParser::getDoubleAttribute(), XMLUnitParser::getEnergyAttribute(), XMLParser::getIntAttribute(), XMLParser::getIVecAttribute(), XMLUnitParser::getLengthAttribute(), ActionChoiceBase::getModelState(), XMLParser::getName(), XMLParser::getStringAttribute(), EMARateEstimator::includeCoulombContribution(), manager, mpi, parseDistance(), parsePairDistance(), parser, and simInfo.
Referenced by MainParser::parse().
void EstimatorParser::parseDistance (xmlNodePtr estNode, const xmlXPathContextPtr & ctxt, std::vector< Distance * > & darray, std::vector< double > & min, std::vector< double > & max, std::vector< int > & nbin) private
Parser for distance subtags.
Definition at line 651 of file EstimatorParser.cc.
References XMLParser::dimName, XMLParser::getIntAttribute(), XMLUnitParser::getLengthAttribute(), XMLParser::getName(), XMLParser::getStringAttribute(), and parser.
Referenced by parse().
template<int N> PairCFEstimator< N > * EstimatorParser::parsePairCF (xmlNodePtr estNode, xmlXPathObjectPtr ctxt) private
Parser for pair correlation estimator.
Definition at line 567 of file EstimatorParser.cc.
References XMLParser::getDoubleAttribute(), XMLParser::getIntAttribute(), XMLUnitParser::getLengthAttribute(), XMLParser::getName(), XMLParser::getStringAttribute(), mpi, parser, PI, and simInfo.
void EstimatorParser::parsePairDistance (xmlNodePtr estNode, const xmlXPathContextPtr & ctxt, std::vector< PairDistance * > & darray, std::vector< double > & min, std::vector< double > & max, std::vector< int > & nbin) private
Parser for distance subtags.
Definition at line 682 of file EstimatorParser.cc.
References XMLParser::dimName, XMLParser::getDoubleAttribute(), XMLParser::getIntAttribute(), XMLUnitParser::getLengthAttribute(), XMLParser::getName(), XMLParser::getStringAttribute(), parser, and PI.
Referenced by parse().
template<int N> SpinChoicePCFEstimator< N > * EstimatorParser::parseSpinPair (const std::string & name, const std::vector< double > & tmin, const std::vector< double > & tmax, const std::vector< int > & tnbin, const std::vector< PairDistance * > & dist, const bool & samespin) private
Parser for spin pairs.
Definition at line 752 of file EstimatorParser.cc.
References actionChoice, ActionChoiceBase::getModelState(), mpi, and simInfo.
Member Data Documentation
const Action* EstimatorParser::action private
The action.
Definition at line 57 of file EstimatorParser.h.
Referenced by parse().
ActionChoiceBase* EstimatorParser::actionChoice private
A choice of action models.
Definition at line 61 of file EstimatorParser.h.
Referenced by parse(), and parseSpinPair().
const DoubleAction* EstimatorParser::doubleAction private
The double action.
Definition at line 59 of file EstimatorParser.h.
Referenced by parse().
EstimatorManager* EstimatorParser::manager private
The estimator manager.
Definition at line 51 of file EstimatorParser.h.
Referenced by EstimatorParser(), getEstimatorManager(), parse(), and ~EstimatorParser().
MPIManager* EstimatorParser::mpi private
The MPI manager.
Definition at line 63 of file EstimatorParser.h.
Referenced by parse(), parsePairCF(), and parseSpinPair().
XMLUnitParser EstimatorParser::parser private
Definition at line 49 of file EstimatorParser.h.
Referenced by parse(), parseDistance(), parsePairCF(), and parsePairDistance().
const SimulationInfo& EstimatorParser::simInfo private
General simulation information.
Definition at line 53 of file EstimatorParser.h.
Referenced by parse(), parsePairCF(), and parseSpinPair().
const double EstimatorParser::tau private
The timestep.
Definition at line 55 of file EstimatorParser.h.
The documentation for this class was generated from the following files:
EstimatorParser.h
EstimatorParser.cc