pi: Path integral Quantum Monte Carlo: FreeMoverPBC Class Reference
FreeMoverPBC Class Reference
Select a trial move for beads by free particle sampling.
#include <FreeMoverPBC.h>
Public Types
typedef blitz::Array< int, 1 > IArray
Typedefs.
typedef blitz::Array< double, 1 > Array
typedef blitz::Array
< PeriodicGaussian *, 3 > PGArray
typedef blitz::TinyVector
< double, NDIM > Vec
typedef blitz::TinyVector< int,
NDIM > IVec
Public Member Functions
FreeMoverPBC (const double lambda, const int npart, const double tau)
Construct by providing lambda () timestep .
FreeMoverPBC (const SimulationInfo &, const int maxlevel, const double pgDelta)
Construct by providing simInfo.
virtual ~FreeMoverPBC ()
Virtual destructor.
virtual double makeMove (MultiLevelSampler &, const int level)
Move the samplers moving beads for a given level, returning the probability for the old move divided by the probability for the new move.
virtual double makeDelayedMove (MultiLevelSampler &, const int level)
virtual double getForwardProb ()
Public Member Functions inherited from Mover
virtual ~Mover ()
Private Attributes
Array lambda
The inverse mass, .
double tau
The timestep.
PGArray pg
Periodic gaussians.
Vec length
Vector with supercell dimensions.
IArray specIndex
Index of species types.
double forwardProb
forward transition prob
Detailed Description
Select a trial move for beads by free particle sampling.
This class treats periodic boundary conditions more carefully, which is necessary for very small box sizes.
The difficulty, is that the bisection algorithm has 2**NDIM midpoints when you consider periodic boundary conditions. If these are not sampled carefully, some windings or permutations may be missed, raising the energy.
Version:
$Revision$
Bug:
Delayed rejection move not properly coded.
Author:
John Shumway.
Definition at line 20 of file FreeMoverPBC.h.
Member Typedef Documentation
typedef blitz::Array<double, 1> FreeMoverPBC::Array
Definition at line 24 of file FreeMoverPBC.h.
typedef blitz::Array<int, 1> FreeMoverPBC::IArray
Typedefs.
Definition at line 23 of file FreeMoverPBC.h.
typedef blitz::TinyVector<int, NDIM> FreeMoverPBC::IVec
Definition at line 27 of file FreeMoverPBC.h.
typedef blitz::Array<PeriodicGaussian*, 3> FreeMoverPBC::PGArray
Definition at line 25 of file FreeMoverPBC.h.
typedef blitz::TinyVector<double, NDIM> FreeMoverPBC::Vec
Definition at line 26 of file FreeMoverPBC.h.
Constructor & Destructor Documentation
FreeMoverPBC::FreeMoverPBC (const double lambda, const int npart, const double tau)
Construct by providing lambda () timestep .
Definition at line 19 of file FreeMoverPBC.cc.
References lambda.
FreeMoverPBC::FreeMoverPBC (const SimulationInfo & simInfo, const int maxlevel, const double pgDelta)
Construct by providing simInfo.
Definition at line 24 of file FreeMoverPBC.cc.
References SimulationInfo::getNPart(), SimulationInfo::getNSpecies(), SimulationInfo::getPartSpecies(), SimulationInfo::getSpecies(), lambda, length, Species::mass, PeriodicGaussian::numberOfTerms(), pg, specIndex, and tau.
FreeMoverPBC::~FreeMoverPBC () virtual
Virtual destructor.
Definition at line 57 of file FreeMoverPBC.cc.
References pg.
Member Function Documentation
virtual double FreeMoverPBC::getForwardProb () inline virtual
Implements Mover.
Definition at line 40 of file FreeMoverPBC.h.
References forwardProb.
double FreeMoverPBC::makeDelayedMove (MultiLevelSampler & sampler, const int level) virtual
Implements Mover.
Definition at line 168 of file FreeMoverPBC.cc.
References Beads< TDIM >::delta(), forwardProb, MultiLevelSampler::getFactor(), MultiLevelSampler::getMovingBeads(), MultiLevelSampler::getMovingIndex(), Beads< TDIM >::getNSlice(), MultiLevelSampler::getRejectedBeads(), MultiLevelSampler::getSuperCell(), lambda, SuperCell::pbc(), pg, specIndex, and tau.
double FreeMoverPBC::makeMove (MultiLevelSampler & sampler, const int level) virtual
Move the samplers moving beads for a given level, returning the probability for the old move divided by the probability for the new move.
Implements Mover.
Definition at line 62 of file FreeMoverPBC.cc.
References SuperCell::a, Beads< TDIM >::delta(), PeriodicGaussian::evaluate(), MultiLevelSampler::getFactor(), MultiLevelSampler::getMovingBeads(), MultiLevelSampler::getMovingIndex(), Beads< TDIM >::getNSlice(), RandomNumGenerator::getRand(), MultiLevelSampler::getSectionBeads(), MultiLevelSampler::getSuperCell(), lambda, RandomNumGenerator::makeGaussRand(), SuperCell::pbc(), pg, specIndex, and tau.
Member Data Documentation
double FreeMoverPBC::forwardProb private
forward transition prob
Definition at line 55 of file FreeMoverPBC.h.
Referenced by getForwardProb(), and makeDelayedMove().
Array FreeMoverPBC::lambda private
The inverse mass, .
Definition at line 45 of file FreeMoverPBC.h.
Referenced by FreeMoverPBC(), makeDelayedMove(), and makeMove().
Vec FreeMoverPBC::length private
Vector with supercell dimensions.
Definition at line 51 of file FreeMoverPBC.h.
Referenced by FreeMoverPBC().
PGArray FreeMoverPBC::pg private
Periodic gaussians.
Definition at line 49 of file FreeMoverPBC.h.
Referenced by FreeMoverPBC(), makeDelayedMove(), makeMove(), and ~FreeMoverPBC().
IArray FreeMoverPBC::specIndex private
Index of species types.
Definition at line 53 of file FreeMoverPBC.h.
Referenced by FreeMoverPBC(), makeDelayedMove(), and makeMove().
double FreeMoverPBC::tau private
The timestep.
Definition at line 47 of file FreeMoverPBC.h.
Referenced by FreeMoverPBC(), makeDelayedMove(), and makeMove().
The documentation for this class was generated from the following files:
FreeMoverPBC.h
FreeMoverPBC.cc