pi: Path integral Quantum Monte Carlo: XMLUnitParser Class Reference
XMLUnitParser Class Reference
Base class for classes that parse XML data with units.
#include <XMLUnitParser.h>
Public Member Functions
XMLUnitParser (const Units *)
Constructor.
virtual ~XMLUnitParser ()
Destructor.
double getEnergyAttribute (const xmlNodePtr &node, const std::string &attName)
Parse a length with unit conversion.
double getLengthAttribute (const xmlNodePtr &node, const std::string &attName)
Parse a energy with unit conversion.
double getTimeAttribute (const xmlNodePtr &node, const std::string &attName)
Parse an inverse energy with unit conversion.
double getInvLengthAttribute (const xmlNodePtr &node, const std::string &attName)
Parse an inverse length with unit conversion.
double getDensityAttribute (const xmlNodePtr &node, const std::string &attName)
Parse a density with unit conversion.
double getMassAttribute (const xmlNodePtr &node, const std::string &attName)
double getFieldStrengthAttribute (const xmlNodePtr &node, const std::string &attName)
Parse a field strength with unit conversion.
void parseUnitAndValue (const xmlNodePtr &node, const std::string &attName)
Internal method to parse a unit and value.
Public Member Functions inherited from XMLParser
virtual ~XMLParser ()
Destructor.
virtual void parse (const xmlXPathContextPtr &ctxt)
Parse some xml.
Public Attributes
const Units * units
Information about the units and conversions.
double value
The most recently parsed value.
std::string unit
The most recently parsed unit name.
Additional Inherited Members
Public Types inherited from XMLParser
typedef blitz::TinyVector
< double, NDIM > Vec
typedef blitz::TinyVector< int,
NDIM > IVec
Static Public Member Functions inherited from XMLParser
static std::string getName (const xmlNodePtr &node)
Get the name of the node.
static double getDoubleAttribute (const xmlNodePtr &node, const std::string &attName)
Get a double valued attribute.
static int getIntAttribute (const xmlNodePtr &node, const std::string &attName)
Get an integer valued attribute.
static std::string getStringAttribute (const xmlNodePtr &node, const std::string &attName)
Get a string valued attribute.
static bool getBoolAttribute (const xmlNodePtr &node, const std::string &attName)
Get a bool valued attribute.
static Vec getVecAttribute (const xmlNodePtr &node, const std::string &attName)
Get a vector valued attribute.
static IVec getIVecAttribute (const xmlNodePtr &node, const std::string &attName)
Get a vector valued attribute.
static std::string getLinkBase (const xmlNodePtr &node, const std::string &attName="href")
Get the base of a link.
static std::string getLinkPath (const xmlNodePtr &node, const std::string &attName="href")
Get the path of a link.
Static Public Attributes inherited from XMLParser
static const std::string dimName = "xyzklmnopqrstuv"
Letters associated with directions in input file.
Detailed Description
Base class for classes that parse XML data with units.
Includes helper functions.
Version:
$Revision$
Author:
John Shumway
Definition at line 27 of file XMLUnitParser.h.
Constructor & Destructor Documentation
XMLUnitParser::XMLUnitParser (const Units * units)
Constructor.
Definition at line 24 of file XMLUnitParser.cc.
virtual XMLUnitParser::~XMLUnitParser () inline virtual
Destructor.
Definition at line 32 of file XMLUnitParser.h.
Member Function Documentation
double XMLUnitParser::getDensityAttribute (const xmlNodePtr & node, const std::string & attName)
Parse a density with unit conversion.
Definition at line 73 of file XMLUnitParser.cc.
References Units::getLengthScaleIn(), parseUnitAndValue(), unit, units, and value.
double XMLUnitParser::getEnergyAttribute (const xmlNodePtr & node, const std::string & attName)
Parse a length with unit conversion.
Definition at line 35 of file XMLUnitParser.cc.
References Units::getEnergyScaleIn(), parseUnitAndValue(), unit, units, and value.
Referenced by SimInfoParser::parse(), EstimatorParser::parse(), ActionParser::parseActions(), and ActionParser::parseNodeModel().
double XMLUnitParser::getFieldStrengthAttribute (const xmlNodePtr & node, const std::string & attName)
Parse a field strength with unit conversion.
Definition at line 84 of file XMLUnitParser.cc.
References Units::getEnergyScaleIn(), Units::getLengthScaleIn(), parseUnitAndValue(), unit, units, and value.
Referenced by ActionParser::parseActions().
double XMLUnitParser::getInvLengthAttribute (const xmlNodePtr & node, const std::string & attName)
Parse an inverse length with unit conversion.
Definition at line 62 of file XMLUnitParser.cc.
References Units::getLengthScaleIn(), parseUnitAndValue(), unit, units, and value.
Referenced by ActionParser::parseActions().
double XMLUnitParser::getLengthAttribute (const xmlNodePtr & node, const std::string & attName)
Parse a energy with unit conversion.
Definition at line 27 of file XMLUnitParser.cc.
References Units::getLengthScaleIn(), parseUnitAndValue(), unit, units, and value.
Referenced by SimInfoParser::parse(), EstimatorParser::parse(), ActionParser::parseActions(), PIMCParser::parseAlgorithm(), PIMCParser::parseBoundary(), EstimatorParser::parseDistance(), ActionParser::parseEwaldActions(), ActionParser::parseNodeModel(), EstimatorParser::parsePairCF(), and EstimatorParser::parsePairDistance().
double XMLUnitParser::getMassAttribute (const xmlNodePtr & node, const std::string & attName)
Parse a mass with unit conversion.
Definition at line 43 of file XMLUnitParser.cc.
References Units::getMassScaleIn(), parseUnitAndValue(), unit, units, and value.
Referenced by SimInfoParser::parse().
double XMLUnitParser::getTimeAttribute (const xmlNodePtr & node, const std::string & attName)
Parse an inverse energy with unit conversion.
Definition at line 51 of file XMLUnitParser.cc.
References Units::getEnergyScaleIn(), parseUnitAndValue(), unit, units, and value.
Referenced by SimInfoParser::parse().
void XMLUnitParser::parseUnitAndValue (const xmlNodePtr & node, const std::string & attName)
Internal method to parse a unit and value.
Definition at line 101 of file XMLUnitParser.cc.
References unit, and value.
Referenced by getDensityAttribute(), getEnergyAttribute(), getFieldStrengthAttribute(), getInvLengthAttribute(), getLengthAttribute(), getMassAttribute(), and getTimeAttribute().
Member Data Documentation
std::string XMLUnitParser::unit
The most recently parsed unit name.
Definition at line 63 of file XMLUnitParser.h.
Referenced by getDensityAttribute(), getEnergyAttribute(), getFieldStrengthAttribute(), getInvLengthAttribute(), getLengthAttribute(), getMassAttribute(), getTimeAttribute(), and parseUnitAndValue().
const Units* XMLUnitParser::units
Information about the units and conversions.
Definition at line 32 of file XMLUnitParser.h.
Referenced by getDensityAttribute(), getEnergyAttribute(), getFieldStrengthAttribute(), getInvLengthAttribute(), getLengthAttribute(), getMassAttribute(), getTimeAttribute(), and SimInfoParser::parse().
double XMLUnitParser::value
The most recently parsed value.
Definition at line 61 of file XMLUnitParser.h.
Referenced by getDensityAttribute(), getEnergyAttribute(), getFieldStrengthAttribute(), getInvLengthAttribute(), getLengthAttribute(), getMassAttribute(), getTimeAttribute(), and parseUnitAndValue().
The documentation for this class was generated from the following files:
XMLUnitParser.h
XMLUnitParser.cc