pi: Path integral Quantum Monte Carlo: QPCAction Class Reference
QPCAction Class Reference
Class for calculating the action for a model of a quantum point contact.
#include <QPCAction.h>
Public Types
typedef blitz::Array< int, 1 > IArray
Typedefs.
Public Types inherited from Action
typedef blitz::TinyVector
< double, NDIM > Vec
typedef blitz::Array< Vec, 1 > VArray
Public Member Functions
QPCAction (const double tau, const double length=780.46, const double v0=0.00011025, const double omega=0.0000735, const double mass=0.0667)
Constructor by providing the timestep tau.
virtual ~QPCAction ()
Virtual destructor.
virtual double getActionDifference (const SectionSamplerInterface &, int level)
Calculate the difference in action.
virtual double getTotalAction (const Paths &, const int level) const
Calculate the total action.
virtual void getBeadAction (const Paths &, int ipart, int islice, double &u, double &utau, double &ulambda, Vec &fm, Vec &fp) const
Calculate the action and derivatives at a bead.
Public Member Functions inherited from Action
virtual ~Action ()
virtual double getActionDifference (const Paths &, const VArray &displacement, int nmoving, const IArray &movingIndex, int iFirstSlice, int iLastSlice)
virtual void initialize (const SectionChooser &)
Initialize for a sampling section.
virtual void acceptLastMove ()
Accept last move.
virtual const Action * getActionPointerByType (const std::type_info &type) const
Returns pointer to Action of type t, otherwise returns null pointer.
Private Member Functions
double v (double x, double y) const
Evaluate the potential at a point.
Private Attributes
const double tau
The timestep.
const double length
The length of the QPC barrier.
const double v0
The height of the QPC barrier.
const double omega
The lateral frequency of the quantum wire.
const double mass
The mass.
Detailed Description
Class for calculating the action for a model of a quantum point contact.
From Hirose, Meir, and Wingreen PRL 90, 026804 (2002),
where and .
Based on Hirose et al, we set the default values to , meV, meV, and nm.
Version:
$Revision$
Author:
John Shumway.
Definition at line 38 of file QPCAction.h.
Member Typedef Documentation
typedef blitz::Array<int,1> QPCAction::IArray
Typedefs.
Reimplemented from Action.
Definition at line 41 of file QPCAction.h.
Constructor & Destructor Documentation
QPCAction::QPCAction (const double tau, const double length = 780.46, const double v0 = 0.00011025, const double omega = 0.0000735, const double mass = 0.0667)
Constructor by providing the timestep tau.
Definition at line 10 of file QPCAction.cc.
virtual QPCAction::~QPCAction () inline virtual
Virtual destructor.
Definition at line 47 of file QPCAction.h.
Member Function Documentation
double QPCAction::getActionDifference (const SectionSamplerInterface & sampler, int level) virtual
Calculate the difference in action.
Implements Action.
Definition at line 15 of file QPCAction.cc.
References tau, and v().
void QPCAction::getBeadAction (const Paths & paths, int ipart, int islice, double & u, double & utau, double & ulambda, Vec & fm, Vec & fp) const virtual
Calculate the action and derivatives at a bead.
Implements Action.
Definition at line 44 of file QPCAction.cc.
References tau, and v().
double QPCAction::getTotalAction (const Paths & paths, const int level) const virtual
Calculate the total action.
Implements Action.
Definition at line 40 of file QPCAction.cc.
double QPCAction::v (double x, double y) const private
Evaluate the potential at a point.
Definition at line 52 of file QPCAction.cc.
References length, mass, omega, and v0.
Referenced by getActionDifference(), and getBeadAction().
Member Data Documentation
const double QPCAction::length private
The length of the QPC barrier.
Definition at line 60 of file QPCAction.h.
Referenced by v().
const double QPCAction::mass private
The mass.
Definition at line 66 of file QPCAction.h.
Referenced by v().
const double QPCAction::omega private
The lateral frequency of the quantum wire.
Definition at line 64 of file QPCAction.h.
Referenced by v().
const double QPCAction::tau private
The timestep.
Definition at line 58 of file QPCAction.h.
Referenced by getActionDifference(), and getBeadAction().
const double QPCAction::v0 private
The height of the QPC barrier.
Definition at line 62 of file QPCAction.h.
Referenced by v().
The documentation for this class was generated from the following files:
QPCAction.h
QPCAction.cc