pi: Path integral Quantum Monte Carlo: EMARateMover Class Reference
EMARateMover Class Reference
#include <EMARateMover.h>
Public Types
typedef blitz::Array< int, 1 > IArray
typedef blitz::Array< double, 1 > Array
typedef blitz::Array
< PeriodicGaussian *, 3 > PGArray
typedef blitz::TinyVector
< double, NDIM > Vec
Public Member Functions
EMARateMover (double tau, double mass1, double mass2, int maxlevel, double C)
virtual ~EMARateMover ()
virtual double makeMove (MultiLevelSampler &, const int level)
Move the samplers moving beads for a given level, returning the probability for the old move divided by the probability for the new move.
virtual double makeDelayedMove (MultiLevelSampler &, const int level)
virtual double getForwardProb ()
virtual void chooseParticles ()
bool chooseDiagonalOrRadiating (const Beads< NDIM > &movingBeads, int nSlice, const SuperCell &)
double calculateDiagonalProbability (const Beads< NDIM > &movingBeads, int nSlice, const SuperCell &)
double calculateRadiatingProbability (const Beads< NDIM > &movingBeads, int nSlice, const SuperCell &)
void moveBeads (int nStride, int nSlice, Beads< NDIM > &movingBeads, const SuperCell &cell)
void sampleRadiating (int nStride, int nSlice, Beads< NDIM > &movingBeads)
void sampleDiagonal (int nStride, int nSlice, Beads< NDIM > &movingBeads, const SuperCell &cell)
double calculateTransitionProbability (int nStride, const Beads< NDIM > &movingBeads, const Beads< NDIM > &sectionBeads, int nSlice, const SuperCell &cell) const
Protected Member Functions
virtual double getRandomNumber () const
virtual void makeGaussianRandomNumbers (blitz::Array< Vec, 1 > &gaussRand)
Private Attributes
double tau
double lambda1
double lambda2
double forwardProb
bool isSamplingRadiating
double earlierTransitions
const double C
Detailed Description
Definition at line 13 of file EMARateMover.h.
Member Typedef Documentation
typedef blitz::Array<double,1> EMARateMover::Array
Definition at line 18 of file EMARateMover.h.
typedef blitz::Array<int,1> EMARateMover::IArray
Definition at line 17 of file EMARateMover.h.
typedef blitz::Array<PeriodicGaussian*,3> EMARateMover::PGArray
Definition at line 19 of file EMARateMover.h.
typedef blitz::TinyVector<double,NDIM> EMARateMover::Vec
Definition at line 20 of file EMARateMover.h.
Constructor & Destructor Documentation
EMARateMover::EMARateMover (double tau, double mass1, double mass2, int maxlevel, double C)
Definition at line 19 of file EMARateMover.cc.
EMARateMover::~EMARateMover () virtual
Definition at line 29 of file EMARateMover.cc.
Member Function Documentation
double EMARateMover::calculateDiagonalProbability (const Beads< NDIM > & movingBeads, int nSlice, const SuperCell & cell)
Definition at line 170 of file EMARateMover.cc.
References lambda1, lambda2, SuperCell::pbc(), and tau.
Referenced by chooseDiagonalOrRadiating().
double EMARateMover::calculateRadiatingProbability (const Beads< NDIM > & movingBeads, int nSlice, const SuperCell & cell)
Definition at line 153 of file EMARateMover.cc.
References lambda1, lambda2, SuperCell::pbc(), and tau.
Referenced by chooseDiagonalOrRadiating().
double EMARateMover::calculateTransitionProbability (int nStride, const Beads< NDIM > & movingBeads, const Beads< NDIM > & sectionBeads, int nSlice, const SuperCell & cell) const
Definition at line 32 of file EMARateMover.cc.
References C, lambda1, lambda2, SuperCell::pbc(), and tau.
Referenced by makeMove().
bool EMARateMover::chooseDiagonalOrRadiating (const Beads< NDIM > & movingBeads, int nSlice, const SuperCell & cell)
Definition at line 188 of file EMARateMover.cc.
References C, calculateDiagonalProbability(), calculateRadiatingProbability(), and getRandomNumber().
Referenced by makeMove().
virtual void EMARateMover::chooseParticles () inline virtual
Definition at line 30 of file EMARateMover.h.
virtual double EMARateMover::getForwardProb () inline virtual
Definition at line 29 of file EMARateMover.h.
References forwardProb.
double EMARateMover::getRandomNumber () const protected virtual
Definition at line 287 of file EMARateMover.cc.
References RandomNumGenerator::getRand().
Referenced by chooseDiagonalOrRadiating().
double EMARateMover::makeDelayedMove (MultiLevelSampler & sampler, const int level) virtual
Definition at line 291 of file EMARateMover.cc.
void EMARateMover::makeGaussianRandomNumbers (blitz::Array< Vec, 1 > & gaussRand) protected virtual
Definition at line 206 of file EMARateMover.cc.
References RandomNumGenerator::makeGaussRand().
Referenced by sampleDiagonal(), and sampleRadiating().
double EMARateMover::makeMove (MultiLevelSampler & sampler, const int level) virtual
Move the samplers moving beads for a given level, returning the probability for the old move divided by the probability for the new move.
Definition at line 127 of file EMARateMover.cc.
References calculateTransitionProbability(), chooseDiagonalOrRadiating(), earlierTransitions, forwardProb, isSamplingRadiating, and moveBeads().
void EMARateMover::moveBeads (int nStride, int nSlice, Beads< NDIM > & movingBeads, const SuperCell & cell)
Definition at line 197 of file EMARateMover.cc.
References isSamplingRadiating, sampleDiagonal(), and sampleRadiating().
Referenced by makeMove().
void EMARateMover::sampleDiagonal (int nStride, int nSlice, Beads< NDIM > & movingBeads, const SuperCell & cell)
Definition at line 267 of file EMARateMover.cc.
References lambda1, lambda2, makeGaussianRandomNumbers(), SuperCell::pbc(), and tau.
Referenced by moveBeads().
void EMARateMover::sampleRadiating (int nStride, int nSlice, Beads< NDIM > & movingBeads)
Definition at line 210 of file EMARateMover.cc.
References lambda1, lambda2, makeGaussianRandomNumbers(), and tau.
Referenced by moveBeads().
Member Data Documentation
const double EMARateMover::C private
Definition at line 54 of file EMARateMover.h.
Referenced by calculateTransitionProbability(), and chooseDiagonalOrRadiating().
double EMARateMover::earlierTransitions private
Definition at line 53 of file EMARateMover.h.
Referenced by makeMove().
double EMARateMover::forwardProb private
Definition at line 51 of file EMARateMover.h.
Referenced by getForwardProb(), and makeMove().
bool EMARateMover::isSamplingRadiating private
Definition at line 52 of file EMARateMover.h.
Referenced by makeMove(), and moveBeads().
double EMARateMover::lambda1 private
Definition at line 49 of file EMARateMover.h.
Referenced by calculateDiagonalProbability(), calculateRadiatingProbability(), calculateTransitionProbability(), sampleDiagonal(), and sampleRadiating().
double EMARateMover::lambda2 private
Definition at line 50 of file EMARateMover.h.
Referenced by calculateDiagonalProbability(), calculateRadiatingProbability(), calculateTransitionProbability(), sampleDiagonal(), and sampleRadiating().
double EMARateMover::tau private
Definition at line 48 of file EMARateMover.h.
Referenced by calculateDiagonalProbability(), calculateRadiatingProbability(), calculateTransitionProbability(), sampleDiagonal(), and sampleRadiating().
The documentation for this class was generated from the following files:
EMARateMover.h
EMARateMover.cc