pi: Path integral Quantum Monte Carlo: WellImageAction Class Reference
WellImageAction Class Reference
Class for calculating the primitive action for image charges around a dielectric slab.
#include <WellImageAction.h>
Public Types
typedef blitz::Array< int, 1 > IArray
Typedefs.
typedef blitz::Array< double, 1 > Array
Public Types inherited from Action
typedef blitz::TinyVector
< double, NDIM > Vec
typedef blitz::Array< Vec, 1 > VArray
Public Member Functions
WellImageAction (const SimulationInfo &simInfo, double epsIn, double epsOut, double width, double z0, double delta)
Construct by providing the timestep tau.
virtual ~WellImageAction ()
Virtual destructor.
virtual double getActionDifference (const SectionSamplerInterface &, int level)
Calculate the difference in action.
virtual double getTotalAction (const Paths &, const int level) const
Calculate the total action.
virtual void getBeadAction (const Paths &, int ipart, int islice, double &u, double &utau, double &ulambda, Vec &fm, Vec &fp) const
Calculate the action and derivatives at a bead.
Public Member Functions inherited from Action
virtual ~Action ()
virtual double getActionDifference (const Paths &, const VArray &displacement, int nmoving, const IArray &movingIndex, int iFirstSlice, int iLastSlice)
virtual void initialize (const SectionChooser &)
Initialize for a sampling section.
virtual void acceptLastMove ()
Accept last move.
virtual const Action * getActionPointerByType (const std::type_info &type) const
Returns pointer to Action of type t, otherwise returns null pointer.
Private Member Functions
double vSelfC (double z) const
Self energy function.
double vSelfR (double z) const
Self energy function.
double vRC (double z1, double z2, double rho) const
Coulomb interaction function.
double vRR (double z1, double z2, double rho) const
Coulomb interaction function.
double vLR (double z1, double z2, double rho) const
Coulomb interaction function.
double vCC (double z1, double z2, double rho) const
Coulomb interaction function.
Private Attributes
const double tau
Simulation timestep.
const int npart
Number of particles.
const double epsIn
Dielectric constants.
const double epsOut
const double width
Well width.
const double z0
Well center coordinate.
const double delta
Distance delta for regularizing self energy divergence.
const double p1
Dielectric factors.
const double p2
Array q
Particle charges.
const SuperCell & cell
The SuperCell.
Detailed Description
Class for calculating the primitive action for image charges around a dielectric slab.
The image charge potential is described in M. Kumagai, and T. Takagahara, "Excitonic and non-linear optical properties of dielectric quantum-well structures," PRB 40, 12359-12381, (1989).
The potential is given by Eqs. (2.8)-(2.15) of that paper. Let and be the coordinates of two particles normal to the center of the well, and let be the component of their separation vector tangental to the plane of the well. Also let L, C, R, refer to the region where the two particles reside. Define the following functions of the dielctrics,
and
Each particle feels the effect of an image charge, or self energy,
The Coulomb interactions become
We will omit the direct terms (that diverge) since they are already handled in CoulombAction. This is an approximation, since CoulombAction does not know about the different dielectric constants.
Version:
$Revision$
Author:
John Shumway.
Definition at line 91 of file WellImageAction.h.
Member Typedef Documentation
typedef blitz::Array<double,1> WellImageAction::Array
Definition at line 95 of file WellImageAction.h.
typedef blitz::Array<int,1> WellImageAction::IArray
Typedefs.
Reimplemented from Action.
Definition at line 94 of file WellImageAction.h.
Constructor & Destructor Documentation
WellImageAction::WellImageAction (const SimulationInfo & simInfo, double epsIn, double epsOut, double width, double z0, double delta)
Construct by providing the timestep tau.
Definition at line 15 of file WellImageAction.cc.
References q.
virtual WellImageAction::~WellImageAction () inline virtual
Virtual destructor.
Definition at line 100 of file WellImageAction.h.
Member Function Documentation
double WellImageAction::getActionDifference (const SectionSamplerInterface & sampler, int level) virtual
Calculate the difference in action.
Implements Action.
Definition at line 24 of file WellImageAction.cc.
References cell, delta, npart, SuperCell::pbc(), tau, vCC(), vLR(), vRC(), vRR(), vSelfC(), vSelfR(), width, and z0.
void WellImageAction::getBeadAction (const Paths & paths, int ipart, int islice, double & u, double & utau, double & ulambda, Vec & fm, Vec & fp) const virtual
Calculate the action and derivatives at a bead.
Implements Action.
Definition at line 138 of file WellImageAction.cc.
References cell, delta, npart, SuperCell::pbc(), tau, vCC(), vLR(), vRC(), vRR(), vSelfC(), vSelfR(), width, and z0.
double WellImageAction::getTotalAction (const Paths & paths, const int level) const virtual
Calculate the total action.
Implements Action.
Definition at line 133 of file WellImageAction.cc.
double WellImageAction::vCC (double z1, double z2, double rho) const inline private
Coulomb interaction function.
Definition at line 240 of file WellImageAction.cc.
References epsIn, epsOut, p1, and width.
Referenced by getActionDifference(), and getBeadAction().
double WellImageAction::vLR (double z1, double z2, double rho) const inline private
Coulomb interaction function.
Definition at line 230 of file WellImageAction.cc.
References epsIn, epsOut, p1, p2, and width.
Referenced by getActionDifference(), and getBeadAction().
double WellImageAction::vRC (double z1, double z2, double rho) const inline private
Coulomb interaction function.
Definition at line 206 of file WellImageAction.cc.
References epsIn, epsOut, p1, p2, and width.
Referenced by getActionDifference(), and getBeadAction().
double WellImageAction::vRR (double z1, double z2, double rho) const inline private
Coulomb interaction function.
Definition at line 219 of file WellImageAction.cc.
References epsIn, epsOut, p1, p2, and width.
Referenced by getActionDifference(), and getBeadAction().
double WellImageAction::vSelfC (double z) const inline private
Self energy function.
Definition at line 182 of file WellImageAction.cc.
References delta, epsIn, p1, and width.
Referenced by getActionDifference(), and getBeadAction().
double WellImageAction::vSelfR (double z) const inline private
Self energy function.
Definition at line 196 of file WellImageAction.cc.
References delta, epsIn, epsOut, p1, p2, and width.
Referenced by getActionDifference(), and getBeadAction().
Member Data Documentation
const SuperCell& WellImageAction::cell private
The SuperCell.
Definition at line 139 of file WellImageAction.h.
Referenced by getActionDifference(), and getBeadAction().
const double WellImageAction::delta private
Distance delta for regularizing self energy divergence.
Definition at line 121 of file WellImageAction.h.
Referenced by getActionDifference(), getBeadAction(), vSelfC(), and vSelfR().
const double WellImageAction::epsIn private
Dielectric constants.
Definition at line 115 of file WellImageAction.h.
Referenced by vCC(), vLR(), vRC(), vRR(), vSelfC(), and vSelfR().
const double WellImageAction::epsOut private
Definition at line 115 of file WellImageAction.h.
Referenced by vCC(), vLR(), vRC(), vRR(), and vSelfR().
const int WellImageAction::npart private
Number of particles.
Definition at line 113 of file WellImageAction.h.
Referenced by getActionDifference(), and getBeadAction().
const double WellImageAction::p1 private
Dielectric factors.
Definition at line 123 of file WellImageAction.h.
Referenced by vCC(), vLR(), vRC(), vRR(), vSelfC(), and vSelfR().
const double WellImageAction::p2 private
Definition at line 123 of file WellImageAction.h.
Referenced by vLR(), vRC(), vRR(), and vSelfR().
Array WellImageAction::q private
Particle charges.
Definition at line 125 of file WellImageAction.h.
Referenced by WellImageAction().
const double WellImageAction::tau private
Simulation timestep.
Definition at line 111 of file WellImageAction.h.
Referenced by getActionDifference(), and getBeadAction().
const double WellImageAction::width private
Well width.
Definition at line 117 of file WellImageAction.h.
Referenced by getActionDifference(), getBeadAction(), vCC(), vLR(), vRC(), vRR(), vSelfC(), and vSelfR().
const double WellImageAction::z0 private
Well center coordinate.
Definition at line 119 of file WellImageAction.h.
Referenced by getActionDifference(), and getBeadAction().
The documentation for this class was generated from the following files:
WellImageAction.h
WellImageAction.cc