pi: Path integral Quantum Monte Carlo: PIMCParser Class Reference
PIMCParser Class Reference
XML Parser for PIMC simulation data.
#include <PIMCParser.h>
Public Types
typedef blitz::TinyVector
< double, NDIM > Vec
typedef blitz::TinyVector< int,
NDIM > IVec
Public Member Functions
PIMCParser (const SimulationInfo &, Action *, DoubleAction *, ActionChoiceBase *, EstimatorManager *, const BeadFactory &, MPIManager *mpi=0)
Constructor.
virtual ~PIMCParser ()
Virtual destructor.
void parse (const xmlXPathContextPtr &ctxt)
Parse some xml.
Algorithm * getAlgorithm ()
Return the Algorithm object.
Public Member Functions inherited from XMLUnitParser
XMLUnitParser (const Units *)
Constructor.
virtual ~XMLUnitParser ()
Destructor.
double getEnergyAttribute (const xmlNodePtr &node, const std::string &attName)
Parse a length with unit conversion.
double getLengthAttribute (const xmlNodePtr &node, const std::string &attName)
Parse a energy with unit conversion.
double getTimeAttribute (const xmlNodePtr &node, const std::string &attName)
Parse an inverse energy with unit conversion.
double getInvLengthAttribute (const xmlNodePtr &node, const std::string &attName)
Parse an inverse length with unit conversion.
double getDensityAttribute (const xmlNodePtr &node, const std::string &attName)
Parse a density with unit conversion.
double getMassAttribute (const xmlNodePtr &node, const std::string &attName)
double getFieldStrengthAttribute (const xmlNodePtr &node, const std::string &attName)
Parse a field strength with unit conversion.
void parseUnitAndValue (const xmlNodePtr &node, const std::string &attName)
Internal method to parse a unit and value.
Public Member Functions inherited from XMLParser
virtual ~XMLParser ()
Destructor.
Private Member Functions
Algorithm * parseAlgorithm (const xmlXPathContextPtr &ctxt)
Parse an algorithm.
void parseBody (const xmlXPathContextPtr &ctxt, CompositeAlgorithm *)
Parse the body of an algorithm.
void parseBoundary (const xmlXPathContextPtr &ctxt, Vec &min, Vec &max)
Parse the boundary.
int getLoopCount (const xmlXPathContextPtr &ctxt)
Count number of loop iterations surrounding an XML node.
Private Attributes
Paths * paths
Holder for the Paths object.
Algorithm * algorithm
Holder for the Algorithm tree.
SectionChooser * sectionChooser
Holder for current the SectionChooser object for parsing.
DoubleSectionChooser * doubleSectionChooser
Holder for current the DoubleSectionChooser object for parsing.
const SimulationInfo & simInfo
General simulation information.
Action * action
The Action.
DoubleAction * doubleAction
The DoubleAction.
ActionChoiceBase * actionChoice
Pointer to ActionChoice.
EstimatorManager * estimators
The estimator manager.
ProbDensityGrid * probDensityGrid
The probability density grid.
std::vector< ProbDensityGrid * > condDensityGrid
const BeadFactory & beadFactory
The BeadFactory.
MPIManager * mpi
The MPIManager.
int nlevel
Current number of levels in sectionChooser or doubleSectionChooser.
Additional Inherited Members
Public Attributes inherited from XMLUnitParser
const Units * units
Information about the units and conversions.
double value
The most recently parsed value.
std::string unit
The most recently parsed unit name.
Detailed Description
XML Parser for PIMC simulation data.
Version:
$Revision$
Todo:
Get rid of explicit use of blitz.
Clean up parsing of ConditionalDensityGrid.
Author:
John Shumway
Definition at line 42 of file PIMCParser.h.
Member Typedef Documentation
typedef blitz::TinyVector<int,NDIM> PIMCParser::IVec
Reimplemented from XMLParser.
Definition at line 45 of file PIMCParser.h.
typedef blitz::TinyVector<double,NDIM> PIMCParser::Vec
Reimplemented from XMLParser.
Definition at line 44 of file PIMCParser.h.
Constructor & Destructor Documentation
PIMCParser::PIMCParser (const SimulationInfo & simInfo, Action * action, DoubleAction * doubleAction, ActionChoiceBase * actionChoice, EstimatorManager * estimators, const BeadFactory & beadFactory, MPIManager * mpi = 0)
Constructor.
Definition at line 75 of file PIMCParser.cc.
PIMCParser::~PIMCParser () virtual
Virtual destructor.
Definition at line 86 of file PIMCParser.cc.
References action, algorithm, doubleAction, paths, and probDensityGrid.
Member Function Documentation
Algorithm* PIMCParser::getAlgorithm () inline
Return the Algorithm object.
Definition at line 54 of file PIMCParser.h.
References algorithm.
int PIMCParser::getLoopCount (const xmlXPathContextPtr & ctxt) private
Count number of loop iterations surrounding an XML node.
Definition at line 653 of file PIMCParser.cc.
References XMLParser::getIntAttribute().
Referenced by parseAlgorithm().
void PIMCParser::parse (const xmlXPathContextPtr & ctxt) virtual
Parse some xml.
Reimplemented from XMLParser.
Definition at line 94 of file PIMCParser.cc.
References actionChoice, algorithm, beadFactory, doubleAction, XMLParser::getBoolAttribute(), ActionChoiceBase::getModelState(), MPIManager::getNWorker(), MPIManager::isMain(), mpi, parseAlgorithm(), paths, and simInfo.
Referenced by MainParser::parse().
Algorithm * PIMCParser::parseAlgorithm (const xmlXPathContextPtr & ctxt) private
Parse an algorithm.
Definition at line 126 of file PIMCParser.cc.
References SuperCell::a, action, actionChoice, EstimatorManager::add(), algorithm, beadFactory, condDensityGrid, XMLParser::dimName, doubleAction, doubleSectionChooser, estimators, XMLParser::getBoolAttribute(), XMLParser::getDoubleAttribute(), EstimatorManager::getEstimatorSet(), XMLParser::getIntAttribute(), XMLUnitParser::getLengthAttribute(), getLoopCount(), ActionChoiceBase::getModelState(), XMLParser::getStringAttribute(), MPIManager::isMain(), mpi, nlevel, parseBody(), parseBoundary(), paths, probDensityGrid, sectionChooser, and simInfo.
Referenced by parse(), and parseBody().
void PIMCParser::parseBody (const xmlXPathContextPtr & ctxt, CompositeAlgorithm * composite) private
Parse the body of an algorithm.
Definition at line 639 of file PIMCParser.cc.
References parseAlgorithm(), CompositeAlgorithm::resize(), and CompositeAlgorithm::set().
Referenced by parseAlgorithm().
void PIMCParser::parseBoundary (const xmlXPathContextPtr & ctxt, Vec & min, Vec & max) private
Parse the boundary.
Definition at line 664 of file PIMCParser.cc.
References XMLParser::dimName, XMLUnitParser::getLengthAttribute(), XMLParser::getName(), and XMLParser::getStringAttribute().
Referenced by parseAlgorithm().
Member Data Documentation
Action* PIMCParser::action private
The Action.
Definition at line 73 of file PIMCParser.h.
Referenced by parseAlgorithm(), and ~PIMCParser().
ActionChoiceBase* PIMCParser::actionChoice private
Pointer to ActionChoice.
Definition at line 77 of file PIMCParser.h.
Referenced by parse(), and parseAlgorithm().
Algorithm* PIMCParser::algorithm private
Holder for the Algorithm tree.
Definition at line 59 of file PIMCParser.h.
Referenced by getAlgorithm(), parse(), parseAlgorithm(), and ~PIMCParser().
const BeadFactory& PIMCParser::beadFactory private
The BeadFactory.
Definition at line 84 of file PIMCParser.h.
Referenced by parse(), and parseAlgorithm().
std::vector<ProbDensityGrid*> PIMCParser::condDensityGrid private
Definition at line 82 of file PIMCParser.h.
Referenced by parseAlgorithm().
DoubleAction* PIMCParser::doubleAction private
The DoubleAction.
Definition at line 75 of file PIMCParser.h.
Referenced by parse(), parseAlgorithm(), and ~PIMCParser().
DoubleSectionChooser* PIMCParser::doubleSectionChooser private
Holder for current the DoubleSectionChooser object for parsing.
Definition at line 63 of file PIMCParser.h.
Referenced by parseAlgorithm().
EstimatorManager* PIMCParser::estimators private
The estimator manager.
Definition at line 79 of file PIMCParser.h.
Referenced by parseAlgorithm().
MPIManager* PIMCParser::mpi private
The MPIManager.
Definition at line 86 of file PIMCParser.h.
Referenced by parse(), and parseAlgorithm().
int PIMCParser::nlevel private
Current number of levels in sectionChooser or doubleSectionChooser.
Definition at line 88 of file PIMCParser.h.
Referenced by parseAlgorithm().
Paths* PIMCParser::paths private
Holder for the Paths object.
Definition at line 57 of file PIMCParser.h.
Referenced by parse(), parseAlgorithm(), and ~PIMCParser().
ProbDensityGrid* PIMCParser::probDensityGrid private
The probability density grid.
Definition at line 81 of file PIMCParser.h.
Referenced by parseAlgorithm(), and ~PIMCParser().
SectionChooser* PIMCParser::sectionChooser private
Holder for current the SectionChooser object for parsing.
Definition at line 61 of file PIMCParser.h.
Referenced by parseAlgorithm().
const SimulationInfo& PIMCParser::simInfo private
General simulation information.
Definition at line 65 of file PIMCParser.h.
Referenced by parse(), and parseAlgorithm().
The documentation for this class was generated from the following files:
PIMCParser.h
PIMCParser.cc