pi: Path integral Quantum Monte Carlo: MultiLevelSampler Class Reference
MultiLevelSampler Class Reference
Class for multilevel sampling of beads.
#include <MultiLevelSampler.h>
Public Types
typedef blitz::Array< int, 1 > IArray
Public Types inherited from SectionSamplerInterface
Public Member Functions
MultiLevelSampler (const int nmoving, Paths &, SectionChooser &, ParticleChooser &, PermutationChooser &, Mover &, Action *, const int nrepeat, const BeadFactory &, const bool delayedRejection, const double defaultFactor, double newFactor)
virtual ~MultiLevelSampler ()
virtual void run ()
int getNLevel () const
virtual Beads< NDIM > & getMovingBeads ()
virtual const Beads< NDIM > & getMovingBeads () const
virtual Beads< NDIM > & getMovingBeads (int i)
virtual const Beads< NDIM > & getMovingBeads (const int i) const
virtual int getFirstSliceIndex () const
const Beads< NDIM > & getRejectedBeads () const
Beads< NDIM > & getRejectedBeads ()
double getFactor ()
virtual Beads< NDIM > & getSectionBeads ()
virtual const Beads< NDIM > & getSectionBeads () const
virtual Beads< NDIM > & getSectionBeads (int i)
virtual const Beads< NDIM > & getSectionBeads (const int i) const
IArray & getMovingIndex ()
const IArray & getMovingIndex () const
IArray & getMovingIndex (int i)
const IArray & getMovingIndex (const int i) const
virtual bool isSamplingBoth () const
void setAction (Action *, const int level=ALL_LEVELS)
Set the action function for a level, or default to level=ALL_LEVELS.
virtual const SuperCell & getSuperCell () const
Get a const reference to the SuperCell.
const Paths & getPaths () const
Get a constant reference to the paths.
virtual AccRejEstimator * getAccRejEstimator (const std::string &name)
Get a pointer to the accept/reject statistic estimator.
const SectionChooser & getSectionChooser () const
Get const reference to the SectionChooser.
Public Member Functions inherited from Algorithm
virtual ~Algorithm ()
Public Member Functions inherited from SectionSamplerInterface
virtual ~SectionSamplerInterface ()
Static Public Attributes
static const int ALL_LEVELS = -1
Protected Member Functions
bool tryMove (double initialTranProb)
Attempt a move on the beads.
Protected Attributes
const int nlevel
Number of levels.
const int nmoving
Number of moving particles.
Beads< NDIM > * sectionBeads
Reference to all beads in the section.
Permutation * sectionPermutation
Reference the permutation of the in the section.
Beads< NDIM > * movingBeads
Storage for the moving beads.
Mover & mover
Algorithm to select trial move for the beads.
const SuperCell & cell
Supercell.
Action * action
Action function.
IArray * movingIndex
Index of moving particles.
IArray identityIndex
More indicies for moving particles.
IArray pMovingIndex
ParticleChooser & particleChooser
The algorithm for selecting the particles to move.
PermutationChooser & permutationChooser
The algorithm for selecting the permutation.
SectionChooser & sectionChooser
Reference to the algorithm that selected the section.
const Paths & paths
Reference to the paths (only needed for fixed node reference point).
AccRejEstimator * accRejEst
AccRejEstimator.
const int nrepeat
Number of times to repeat.
const bool delayedRejection
flag for delayed rejection
Beads< NDIM > * rejectedBeads
double newFactor
const double defaultFactor
double factor
Detailed Description
Class for multilevel sampling of beads.
Definition at line 25 of file MultiLevelSampler.h.
Member Typedef Documentation
typedef blitz::Array<int, 1> MultiLevelSampler::IArray
Reimplemented from SectionSamplerInterface.
Definition at line 27 of file MultiLevelSampler.h.
Constructor & Destructor Documentation
MultiLevelSampler::MultiLevelSampler (const int nmoving, Paths & paths, SectionChooser & sectionChooser, ParticleChooser & particleChooser, PermutationChooser & permutationChooser, Mover & mover, Action * action, const int nrepeat, const BeadFactory & beadFactory, const bool delayedRejection, const double defaultFactor, double newFactor)
Definition at line 25 of file MultiLevelSampler.cc.
References factor, identityIndex, movingIndex, and nmoving.
MultiLevelSampler::~MultiLevelSampler () virtual
Definition at line 50 of file MultiLevelSampler.cc.
References movingBeads, movingIndex, particleChooser, permutationChooser, and rejectedBeads.
Member Function Documentation
AccRejEstimator * MultiLevelSampler::getAccRejEstimator (const std::string & name) virtual
Get a pointer to the accept/reject statistic estimator.
(You are responsible for deleting this new object.)
Reimplemented in DoubleMLSampler.
Definition at line 174 of file MultiLevelSampler.cc.
References accRejEst, ParticleChooser::getName(), nlevel, nmoving, and particleChooser.
double MultiLevelSampler::getFactor () inline
Definition at line 63 of file MultiLevelSampler.h.
References factor.
Referenced by FreeMover::makeDelayedMove(), FreeMoverPBC::makeDelayedMove(), FreeMover::makeMove(), and FreeMoverPBC::makeMove().
int MultiLevelSampler::getFirstSliceIndex () const virtual
Implements SectionSamplerInterface.
Definition at line 181 of file MultiLevelSampler.cc.
References SectionChooser::getFirstSliceIndex(), and sectionChooser.
virtual Beads<NDIM>& MultiLevelSampler::getMovingBeads () inline virtual
Implements SectionSamplerInterface.
Definition at line 42 of file MultiLevelSampler.h.
References movingBeads.
Referenced by FreeMover::makeDelayedMove(), FreeMoverPBC::makeDelayedMove(), HyperbolicMover::makeMove(), EMARateMover::makeMove(), FreeTensorMover::makeMove(), DampedFreeTensorMover::makeMove(), FreeMover::makeMove(), FreeMoverPBC::makeMove(), SpinMover::makeMove(), and FreeSpinMover::makeMove().
virtual const Beads<NDIM>& MultiLevelSampler::getMovingBeads () const inline virtual
Implements SectionSamplerInterface.
Definition at line 45 of file MultiLevelSampler.h.
References movingBeads.
virtual Beads<NDIM>& MultiLevelSampler::getMovingBeads (int i) inline virtual
Implements SectionSamplerInterface.
Reimplemented in DoubleMLSampler.
Definition at line 48 of file MultiLevelSampler.h.
References movingBeads.
virtual const Beads<NDIM>& MultiLevelSampler::getMovingBeads (const int i) const inline virtual
Implements SectionSamplerInterface.
Reimplemented in DoubleMLSampler.
Definition at line 51 of file MultiLevelSampler.h.
References movingBeads.
IArray& MultiLevelSampler::getMovingIndex () inline
Definition at line 82 of file MultiLevelSampler.h.
References movingIndex.
Referenced by FreeMover::makeDelayedMove(), FreeMoverPBC::makeDelayedMove(), HyperbolicMover::makeMove(), FreeTensorMover::makeMove(), DampedFreeTensorMover::makeMove(), FreeMover::makeMove(), FreeMoverPBC::makeMove(), SpinMover::makeMove(), and FreeSpinMover::makeMove().
const IArray& MultiLevelSampler::getMovingIndex () const inline virtual
Implements SectionSamplerInterface.
Definition at line 85 of file MultiLevelSampler.h.
References movingIndex.
IArray& MultiLevelSampler::getMovingIndex (int i) inline
Reimplemented in DoubleMLSampler.
Definition at line 88 of file MultiLevelSampler.h.
References movingIndex.
const IArray& MultiLevelSampler::getMovingIndex (const int i) const inline virtual
Implements SectionSamplerInterface.
Reimplemented in DoubleMLSampler.
Definition at line 91 of file MultiLevelSampler.h.
References movingIndex.
int MultiLevelSampler::getNLevel () const inline
Definition at line 37 of file MultiLevelSampler.h.
References nlevel.
const Paths& MultiLevelSampler::getPaths () const inline
Get a constant reference to the paths.
Definition at line 107 of file MultiLevelSampler.h.
References paths.
const Beads<NDIM>& MultiLevelSampler::getRejectedBeads () const inline
Definition at line 57 of file MultiLevelSampler.h.
References rejectedBeads.
Referenced by FreeMover::makeDelayedMove(), and FreeMoverPBC::makeDelayedMove().
Beads<NDIM>& MultiLevelSampler::getRejectedBeads () inline
Definition at line 60 of file MultiLevelSampler.h.
References rejectedBeads.
virtual Beads<NDIM>& MultiLevelSampler::getSectionBeads () inline virtual
Implements SectionSamplerInterface.
Definition at line 68 of file MultiLevelSampler.h.
References sectionBeads.
Referenced by SpinStatePermutationChooser::init(), WalkingChooser::init(), HyperbolicMover::makeMove(), EMARateMover::makeMove(), FreeTensorMover::makeMove(), DampedFreeTensorMover::makeMove(), FreeMover::makeMove(), FreeMoverPBC::makeMove(), SpinMover::makeMove(), and FreeSpinMover::makeMove().
virtual const Beads<NDIM>& MultiLevelSampler::getSectionBeads () const inline virtual
Implements SectionSamplerInterface.
Definition at line 71 of file MultiLevelSampler.h.
References sectionBeads.
virtual Beads<NDIM>& MultiLevelSampler::getSectionBeads (int i) inline virtual
Implements SectionSamplerInterface.
Reimplemented in DoubleMLSampler.
Definition at line 74 of file MultiLevelSampler.h.
References sectionBeads.
virtual const Beads<NDIM>& MultiLevelSampler::getSectionBeads (const int i) const inline virtual
Implements SectionSamplerInterface.
Reimplemented in DoubleMLSampler.
Definition at line 77 of file MultiLevelSampler.h.
References sectionBeads.
const SectionChooser& MultiLevelSampler::getSectionChooser () const inline
Get const reference to the SectionChooser.
Definition at line 114 of file MultiLevelSampler.h.
References sectionChooser.
virtual const SuperCell& MultiLevelSampler::getSuperCell () const inline virtual
Get a const reference to the SuperCell.
Implements SectionSamplerInterface.
Definition at line 103 of file MultiLevelSampler.h.
References cell.
Referenced by SpinStatePermutationChooser::init(), WalkingChooser::init(), FreeMover::makeDelayedMove(), FreeMoverPBC::makeDelayedMove(), HyperbolicMover::makeMove(), EMARateMover::makeMove(), FreeTensorMover::makeMove(), DampedFreeTensorMover::makeMove(), FreeMover::makeMove(), and FreeMoverPBC::makeMove().
virtual bool MultiLevelSampler::isSamplingBoth () const inline virtual
Implements SectionSamplerInterface.
Reimplemented in DoubleMLSampler.
Definition at line 95 of file MultiLevelSampler.h.
void MultiLevelSampler::run () virtual
Implements Algorithm.
Reimplemented in DoubleMLSampler.
Definition at line 58 of file MultiLevelSampler.cc.
References ParticleChooser::chooseParticles(), PermutationChooser::choosePermutation(), BeadsBase::copySlice(), PermutationChooser::getLnTranProb(), Beads< TDIM >::getNSlice(), PermutationChooser::getPermutation(), identityIndex, PermutationChooser::init(), movingBeads, movingIndex, nmoving, nrepeat, particleChooser, permutationChooser, pMovingIndex, sectionBeads, and tryMove().
void MultiLevelSampler::setAction (Action * act, const int level = ALL_LEVELS)
Set the action function for a level, or default to level=ALL_LEVELS.
Definition at line 169 of file MultiLevelSampler.cc.
References action.
bool MultiLevelSampler::tryMove (double initialTranProb) protected
Attempt a move on the beads.
Reimplemented in DoubleMLSampler.
Definition at line 90 of file MultiLevelSampler.cc.
References Action::acceptLastMove(), accRejEst, action, BeadsBase::copySlice(), defaultFactor, delayedRejection, factor, Action::getActionDifference(), Mover::getForwardProb(), Beads< TDIM >::getNSlice(), PermutationChooser::getPermutation(), RandomNumGenerator::getRand(), identityIndex, Mover::makeDelayedMove(), Mover::makeMove(), AccRejEstimator::moveAccepted(), mover, movingBeads, movingIndex, newFactor, nlevel, nmoving, particleChooser, permutationChooser, sectionBeads, and AccRejEstimator::tryingMove().
Referenced by run().
Member Data Documentation
AccRejEstimator* MultiLevelSampler::accRejEst protected
AccRejEstimator.
Definition at line 149 of file MultiLevelSampler.h.
Referenced by DoubleMLSampler::getAccRejEstimator(), getAccRejEstimator(), DoubleMLSampler::tryMove(), and tryMove().
Action* MultiLevelSampler::action protected
Action function.
Definition at line 135 of file MultiLevelSampler.h.
Referenced by setAction(), DoubleMLSampler::tryMove(), and tryMove().
const int MultiLevelSampler::ALL_LEVELS = -1 static
Reimplemented in DoubleMLSampler.
Definition at line 99 of file MultiLevelSampler.h.
const SuperCell& MultiLevelSampler::cell protected
Supercell.
Definition at line 133 of file MultiLevelSampler.h.
Referenced by getSuperCell().
const double MultiLevelSampler::defaultFactor protected
Definition at line 156 of file MultiLevelSampler.h.
Referenced by DoubleMLSampler::tryMove(), and tryMove().
const bool MultiLevelSampler::delayedRejection protected
flag for delayed rejection
Definition at line 153 of file MultiLevelSampler.h.
Referenced by DoubleMLSampler::activateSection(), DoubleMLSampler::tryMove(), and tryMove().
double MultiLevelSampler::factor protected
Definition at line 157 of file MultiLevelSampler.h.
Referenced by getFactor(), MultiLevelSampler(), DoubleMLSampler::tryMove(), and tryMove().
IArray MultiLevelSampler::identityIndex protected
More indicies for moving particles.
Definition at line 139 of file MultiLevelSampler.h.
Referenced by DoubleMLSampler::DoubleMLSampler(), MultiLevelSampler(), DoubleMLSampler::run(), run(), DoubleMLSampler::tryMove(), and tryMove().
Mover& MultiLevelSampler::mover protected
Algorithm to select trial move for the beads.
Definition at line 131 of file MultiLevelSampler.h.
Referenced by DoubleMLSampler::tryMove(), and tryMove().
Beads<NDIM>* MultiLevelSampler::movingBeads protected
Storage for the moving beads.
Definition at line 129 of file MultiLevelSampler.h.
Referenced by DoubleMLSampler::activateSection(), getMovingBeads(), DoubleMLSampler::run(), run(), tryMove(), and ~MultiLevelSampler().
IArray* MultiLevelSampler::movingIndex protected
Index of moving particles.
Definition at line 137 of file MultiLevelSampler.h.
Referenced by DoubleMLSampler::activateSection(), getMovingIndex(), MultiLevelSampler(), run(), tryMove(), and ~MultiLevelSampler().
double MultiLevelSampler::newFactor protected
Definition at line 155 of file MultiLevelSampler.h.
Referenced by DoubleMLSampler::tryMove(), and tryMove().
const int MultiLevelSampler::nlevel protected
Number of levels.
Definition at line 121 of file MultiLevelSampler.h.
Referenced by DoubleMLSampler::getAccRejEstimator(), getAccRejEstimator(), getNLevel(), DoubleMLSampler::tryMove(), and tryMove().
const int MultiLevelSampler::nmoving protected
Number of moving particles.
Definition at line 123 of file MultiLevelSampler.h.
Referenced by DoubleMLSampler::DoubleMLSampler(), DoubleMLSampler::getAccRejEstimator(), getAccRejEstimator(), MultiLevelSampler(), DoubleMLSampler::run(), run(), DoubleMLSampler::tryMove(), and tryMove().
const int MultiLevelSampler::nrepeat protected
Number of times to repeat.
Reimplemented in DoubleMLSampler.
Definition at line 151 of file MultiLevelSampler.h.
Referenced by run().
ParticleChooser& MultiLevelSampler::particleChooser protected
The algorithm for selecting the particles to move.
Definition at line 141 of file MultiLevelSampler.h.
Referenced by DoubleMLSampler::getAccRejEstimator(), getAccRejEstimator(), DoubleMLSampler::run(), run(), tryMove(), and ~MultiLevelSampler().
const Paths& MultiLevelSampler::paths protected
Reference to the paths (only needed for fixed node reference point).
Definition at line 147 of file MultiLevelSampler.h.
Referenced by getPaths().
PermutationChooser& MultiLevelSampler::permutationChooser protected
The algorithm for selecting the permutation.
Definition at line 143 of file MultiLevelSampler.h.
Referenced by DoubleMLSampler::run(), run(), tryMove(), and ~MultiLevelSampler().
IArray MultiLevelSampler::pMovingIndex protected
Definition at line 139 of file MultiLevelSampler.h.
Referenced by DoubleMLSampler::run(), and run().
Beads<NDIM>* MultiLevelSampler::rejectedBeads protected
Definition at line 154 of file MultiLevelSampler.h.
Referenced by DoubleMLSampler::activateSection(), getRejectedBeads(), and ~MultiLevelSampler().
Beads<NDIM>* MultiLevelSampler::sectionBeads protected
Reference to all beads in the section.
Definition at line 125 of file MultiLevelSampler.h.
Referenced by DoubleMLSampler::activateSection(), getSectionBeads(), run(), DoubleMLSampler::tryMove(), and tryMove().
SectionChooser& MultiLevelSampler::sectionChooser protected
Reference to the algorithm that selected the section.
Definition at line 145 of file MultiLevelSampler.h.
Referenced by getFirstSliceIndex(), and getSectionChooser().
Permutation* MultiLevelSampler::sectionPermutation protected
Reference the permutation of the in the section.
Definition at line 127 of file MultiLevelSampler.h.
Referenced by DoubleMLSampler::activateSection().
The documentation for this class was generated from the following files:
MultiLevelSampler.h
MultiLevelSampler.cc