pi: Path integral Quantum Monte Carlo: NodeModel Class Reference
NodeModel Class Reference
Base class for node models used in the fixed node approximation.
#include <NodeModel.h>
Classes
struct DetWithFlag
class MatrixUpdate
Base class for matrix updates.
Public Types
typedef blitz::TinyVector
< double, NDIM > Vec
typedef blitz::Array< double, 1 > Array
typedef blitz::Array< Vec, 1 > VArray
typedef blitz::Array< Vec, 2 > VMatrix
Public Member Functions
NodeModel (const std::string &name="")
Constructor.
virtual ~NodeModel ()
Virtual destructor.
virtual DetWithFlag evaluate (const VArray &r1, const VArray &r2, const int islice, bool scaleMagnitude)=0
Evaluate the density matrix function, returning the value.
virtual void evaluateDistance (const VArray &r1, const VArray &r2, const int islice, Array &d1, Array &d2)=0
Evaluate distance to the node in units of .
virtual void evaluateDotDistance (const VArray &r1, const VArray &r2, const int islice, Array &d1, Array &d2)
Evaluate the time-derivative of the distance to the node in units of .
virtual void evaluateGradLogDist (const VArray &r1, const VArray &r2, const int islice, VMatrix &gradd1, VMatrix &gradd2, const Array &d1, const Array &d2)=0
Evaluate gradient of log of the distance to the node in units of .
virtual bool dependsOnOtherParticles ()
Returns true if action depends on other particle coordinates.
void testGradLogDist (const VArray &r1, const VArray &r2, const int islice, VMatrix &gradd1, VMatrix &gradd2, const Array &d1, const Array &d2, const int npart, const int ifirst)
Numerically test the gradient of the log of the distance to the node.
MatrixUpdate * getUpdateObj () const
void setSpinModelState (SpinModelState *s)
bool hasSpinModelState () const
Protected Attributes
MatrixUpdate * updateObj
SpinModelState * spinModelState
Detailed Description
Base class for node models used in the fixed node approximation.
The NodeModel is a function that is used by FixedNodeAction.
Author:
John Shumway
Definition at line 32 of file NodeModel.h.
Member Typedef Documentation
typedef blitz::Array<double,1> NodeModel::Array
Reimplemented in AugmentedNodes, SHONodes, FreeParticleNodes, ExcitonNodes, and WireNodes.
Definition at line 35 of file NodeModel.h.
typedef blitz::Array<Vec,1> NodeModel::VArray
Definition at line 36 of file NodeModel.h.
typedef blitz::TinyVector<double,NDIM> NodeModel::Vec
Definition at line 34 of file NodeModel.h.
typedef blitz::Array<Vec,2> NodeModel::VMatrix
Reimplemented in SHONodes, AugmentedNodes, FreeParticleNodes, ExcitonNodes, and WireNodes.
Definition at line 37 of file NodeModel.h.
Constructor & Destructor Documentation
NodeModel::NodeModel (const std::string & name = "")
Constructor.
Definition at line 19 of file NodeModel.cc.
virtual NodeModel::~NodeModel () inline virtual
Virtual destructor.
Definition at line 85 of file NodeModel.h.
Member Function Documentation
virtual bool NodeModel::dependsOnOtherParticles () inline virtual
Returns true if action depends on other particle coordinates.
Reimplemented in AugmentedNodes, ExcitonNodes, and GroundStateSNode.
Definition at line 104 of file NodeModel.h.
Referenced by FixedNodeAction::getActionDifference().
virtual DetWithFlag NodeModel::evaluate (const VArray & r1, const VArray & r2, const int islice, bool scaleMagnitude) pure virtual
Evaluate the density matrix function, returning the value.
Implemented in AugmentedNodes, FreeParticleNodes, WireNodes, SHONodes, ExcitonNodes, SHORealNodes, and GroundStateSNode.
Referenced by SpinChoiceFixedNodeAction::getActionChoiceDifference(), FixedNodeAction::getActionDifference(), FixedNodeAction::getBeadAction(), and FixedNodeAction::initialize().
virtual void NodeModel::evaluateDistance (const VArray & r1, const VArray & r2, const int islice, Array & d1, Array & d2) pure virtual
Evaluate distance to the node in units of .
Assumes that evaluate has already been called on the slice.
Implemented in AugmentedNodes, FreeParticleNodes, WireNodes, SHONodes, ExcitonNodes, SHORealNodes, and GroundStateSNode.
Referenced by SpinChoiceFixedNodeAction::getActionChoiceDifference(), FixedNodeAction::getActionDifference(), FixedNodeAction::getBeadAction(), and FixedNodeAction::initialize().
virtual void NodeModel::evaluateDotDistance (const VArray & r1, const VArray & r2, const int islice, Array & d1, Array & d2) inline virtual
Evaluate the time-derivative of the distance to the node in units of .
Assumes that evaluate has already been called on the slice.
Reimplemented in FreeParticleNodes, AugmentedNodes, WireNodes, and ExcitonNodes.
Definition at line 96 of file NodeModel.h.
Referenced by FixedNodeAction::getBeadAction().
virtual void NodeModel::evaluateGradLogDist (const VArray & r1, const VArray & r2, const int islice, VMatrix & gradd1, VMatrix & gradd2, const Array & d1, const Array & d2) pure virtual
Evaluate gradient of log of the distance to the node in units of .
Implemented in FreeParticleNodes, AugmentedNodes, WireNodes, SHONodes, ExcitonNodes, SHORealNodes, and GroundStateSNode.
MatrixUpdate* NodeModel::getUpdateObj () const inline
Definition at line 112 of file NodeModel.h.
References updateObj.
bool NodeModel::hasSpinModelState () const inline
Definition at line 114 of file NodeModel.h.
References spinModelState.
Referenced by SHONodes::evaluate(), WireNodes::evaluate(), and FreeParticleNodes::evaluate().
void NodeModel::setSpinModelState (SpinModelState * s) inline
Definition at line 113 of file NodeModel.h.
References spinModelState.
Referenced by SpinChoiceFixedNodeAction::SpinChoiceFixedNodeAction().
void NodeModel::testGradLogDist (const VArray & r1, const VArray & r2, const int islice, VMatrix & gradd1, VMatrix & gradd2, const Array & d1, const Array & d2, const int npart, const int ifirst)
Numerically test the gradient of the log of the distance to the node.
This routine can be called from evaluateGradLogDist from subclasses for debugging when preprocessor variable NODE_DIST_DEBUG set.
Definition at line 26 of file NodeModel.cc.
Member Data Documentation
SpinModelState* NodeModel::spinModelState protected
Definition at line 120 of file NodeModel.h.
Referenced by SHONodes::evaluate(), WireNodes::evaluate(), FreeParticleNodes::evaluate(), hasSpinModelState(), and setSpinModelState().
MatrixUpdate* NodeModel::updateObj protected
Definition at line 119 of file NodeModel.h.
Referenced by AugmentedNodes::AugmentedNodes(), FreeParticleNodes::FreeParticleNodes(), getUpdateObj(), WireNodes::WireNodes(), AugmentedNodes::~AugmentedNodes(), ExcitonNodes::~ExcitonNodes(), FreeParticleNodes::~FreeParticleNodes(), and WireNodes::~WireNodes().
The documentation for this class was generated from the following files:
NodeModel.h
NodeModel.cc