pi: Path integral Quantum Monte Carlo: AccRejEstimator Class Reference
AccRejEstimator Class Reference
Base class for scalar estimators.
#include <AccRejEstimator.h>
Public Types
typedef blitz::Array< long int, 1 > IArray
Public Member Functions
AccRejEstimator (const std::string &name, const int nlevel)
Construct by giving the name and number of levels.
virtual ~AccRejEstimator ()
Virtual destructor.
int getNLevel () const
Get the number of levels.
long int getNAccept (const int i) const
Get the number of accept.
long int getNTrial (const int i) const
Get the number of trials.
IArray & getNAccept ()
Get the array for number of acceptances.
IArray & getNTrial ()
Get the number of trials.
const IArray & getNAccept () const
Get the array for number of acceptances.
const IArray & getNTrial () const
Get the number of trials.
virtual void averageOverClones (const MPIManager *mpi)
Average over clones.
virtual void startReport (EstimatorReportBuilder &builder)
Callback EstimatorReportBuilder method for integer arrays.
virtual void reportStep (EstimatorReportBuilder &builder)
Callback EstimatorReportBuilder method for integer arrays.
virtual void evaluate (const Paths &)
Evaluate estimator for a path configuration.
void tryingMove (const int ilevel=0)
Record a trial move.
void moveAccepted (const int ilevel=0)
Record an accepted move.
Public Member Functions inherited from Estimator
Estimator (const std::string &name)
Construct by giving the name of the estimator.
Estimator (const std::string &name, const std::string &typeString, const std::string &unitName)
Construct by giving the name of the estimator.
virtual ~Estimator ()
Virtual destructor.
const std::string & getName () const
Get the name of the estimator.
const std::string & getUnitName () const
Get the name of the unit for the estimator.
const std::string & getTypeString () const
Get the type string for this estimators.
Protected Attributes
const int nlevel
Number of levels.
IArray naccept
Arrays for.
IArray ntrial
IArray sum
Detailed Description
Base class for scalar estimators.
Version:
$Revision$
Author:
John Shumway
Bug:
Need to add results for parallel MPI runs.
Definition at line 28 of file AccRejEstimator.h.
Member Typedef Documentation
typedef blitz::Array<long int,1> AccRejEstimator::IArray
Definition at line 30 of file AccRejEstimator.h.
Constructor & Destructor Documentation
AccRejEstimator::AccRejEstimator (const std::string & name, const int nlevel)
Construct by giving the name and number of levels.
Definition at line 26 of file AccRejEstimator.cc.
References naccept, ntrial, and sum.
virtual AccRejEstimator::~AccRejEstimator () inline virtual
Virtual destructor.
Definition at line 34 of file AccRejEstimator.h.
Member Function Documentation
void AccRejEstimator::averageOverClones (const MPIManager * mpi) virtual
Average over clones.
Reimplemented from Estimator.
Definition at line 33 of file AccRejEstimator.cc.
References MPIManager::isCloneMain(), naccept, nlevel, ntrial, and sum.
virtual void AccRejEstimator::evaluate (const Paths &) inline virtual
Evaluate estimator for a path configuration.
Implements Estimator.
Definition at line 57 of file AccRejEstimator.h.
long int AccRejEstimator::getNAccept (const int i) const inline
Get the number of accept.
Definition at line 38 of file AccRejEstimator.h.
References naccept.
Referenced by StdoutReportBuilder::reportAccRejStep().
IArray& AccRejEstimator::getNAccept () inline
Get the array for number of acceptances.
Definition at line 42 of file AccRejEstimator.h.
References naccept.
const IArray& AccRejEstimator::getNAccept () const inline
Get the array for number of acceptances.
Definition at line 46 of file AccRejEstimator.h.
References naccept.
int AccRejEstimator::getNLevel () const inline
Get the number of levels.
Definition at line 36 of file AccRejEstimator.h.
References nlevel.
Referenced by StdoutReportBuilder::reportAccRejStep().
long int AccRejEstimator::getNTrial (const int i) const inline
Get the number of trials.
Definition at line 40 of file AccRejEstimator.h.
References ntrial.
Referenced by StdoutReportBuilder::reportAccRejStep().
IArray& AccRejEstimator::getNTrial () inline
Get the number of trials.
Definition at line 44 of file AccRejEstimator.h.
References ntrial.
const IArray& AccRejEstimator::getNTrial () const inline
Get the number of trials.
Definition at line 48 of file AccRejEstimator.h.
References ntrial.
void AccRejEstimator::moveAccepted (const int ilevel = 0) inline
Record an accepted move.
Definition at line 61 of file AccRejEstimator.h.
References naccept.
virtual void AccRejEstimator::reportStep (EstimatorReportBuilder & builder) inline virtual
Callback EstimatorReportBuilder method for integer arrays.
Reimplemented from Estimator.
Definition at line 55 of file AccRejEstimator.h.
References EstimatorReportBuilder::reportAccRejStep().
virtual void AccRejEstimator::startReport (EstimatorReportBuilder & builder) inline virtual
Callback EstimatorReportBuilder method for integer arrays.
Reimplemented from Estimator.
Definition at line 52 of file AccRejEstimator.h.
References EstimatorReportBuilder::startAccRejReport().
void AccRejEstimator::tryingMove (const int ilevel = 0) inline
Record a trial move.
Definition at line 59 of file AccRejEstimator.h.
References ntrial.
Member Data Documentation
IArray AccRejEstimator::naccept protected
Arrays for.
Definition at line 66 of file AccRejEstimator.h.
Referenced by AccRejEstimator(), averageOverClones(), getNAccept(), and moveAccepted().
const int AccRejEstimator::nlevel protected
Number of levels.
Definition at line 64 of file AccRejEstimator.h.
Referenced by averageOverClones(), and getNLevel().
IArray AccRejEstimator::ntrial protected
Definition at line 67 of file AccRejEstimator.h.
Referenced by AccRejEstimator(), averageOverClones(), getNTrial(), and tryingMove().
IArray AccRejEstimator::sum protected
Definition at line 68 of file AccRejEstimator.h.
Referenced by AccRejEstimator(), and averageOverClones().
The documentation for this class was generated from the following files:
AccRejEstimator.h
AccRejEstimator.cc