pi: Path integral Quantum Monte Carlo: FreeMover Class Reference
FreeMover Class Reference
Select a trial move for beads by free particle sampling.
#include <FreeMover.h>
Public Types
typedef blitz::Array< int, 1 > IArray
Typedefs.
typedef blitz::Array< double, 1 > Array
typedef blitz::Array
< PeriodicGaussian *, 3 > PGArray
typedef blitz::TinyVector
< double, NDIM > Vec
Public Member Functions
FreeMover (const double lambda, const int npart, const double tau)
Construct by providing lambda () timestep .
FreeMover (const SimulationInfo &, const int maxlevel, const double pgDelta)
Construct by providing simInfo.
virtual ~FreeMover ()
Virtual destructor.
virtual double makeMove (MultiLevelSampler &, const int level)
Move the samplers moving beads for a given level, returning the probability for the old move divided by the probability for the new move.
virtual double makeDelayedMove (MultiLevelSampler &, const int level)
virtual double getForwardProb ()
Public Member Functions inherited from Mover
virtual ~Mover ()
Private Attributes
blitz::Array< double, 1 > lambda
The inverse mass, .
double tau
The timestep.
PGArray pg
Periodic gaussians.
IArray specIndex
double forwardProb
forward transition prob
Detailed Description
Select a trial move for beads by free particle sampling.
Todo:
May want to make this a subclass of Action, with a flag for whether to return probability or allow to cancel for efficiency.
Version:
$Revision$
Author:
John Shumway.
Definition at line 15 of file FreeMover.h.
Member Typedef Documentation
typedef blitz::Array<double, 1> FreeMover::Array
Definition at line 19 of file FreeMover.h.
typedef blitz::Array<int, 1> FreeMover::IArray
Typedefs.
Definition at line 18 of file FreeMover.h.
typedef blitz::Array<PeriodicGaussian*, 3> FreeMover::PGArray
Definition at line 20 of file FreeMover.h.
typedef blitz::TinyVector<double, NDIM> FreeMover::Vec
Definition at line 21 of file FreeMover.h.
Constructor & Destructor Documentation
FreeMover::FreeMover (const double lambda, const int npart, const double tau)
Construct by providing lambda () timestep .
Definition at line 18 of file FreeMover.cc.
References lambda.
FreeMover::FreeMover (const SimulationInfo & simInfo, const int maxlevel, const double pgDelta)
Construct by providing simInfo.
Definition at line 23 of file FreeMover.cc.
References SimulationInfo::getNPart(), SimulationInfo::getNSpecies(), SimulationInfo::getPartSpecies(), SimulationInfo::getSpecies(), SimulationInfo::getSuperCell(), lambda, Species::mass, PeriodicGaussian::numberOfTerms(), pg, specIndex, and tau.
FreeMover::~FreeMover () virtual
Virtual destructor.
Definition at line 56 of file FreeMover.cc.
References pg.
Member Function Documentation
virtual double FreeMover::getForwardProb () inline virtual
Implements Mover.
Definition at line 33 of file FreeMover.h.
References forwardProb.
double FreeMover::makeDelayedMove (MultiLevelSampler & sampler, const int level) virtual
Implements Mover.
Definition at line 129 of file FreeMover.cc.
References Beads< TDIM >::delta(), forwardProb, MultiLevelSampler::getFactor(), MultiLevelSampler::getMovingBeads(), MultiLevelSampler::getMovingIndex(), Beads< TDIM >::getNSlice(), MultiLevelSampler::getRejectedBeads(), MultiLevelSampler::getSuperCell(), lambda, SuperCell::pbc(), pg, specIndex, and tau.
double FreeMover::makeMove (MultiLevelSampler & sampler, const int level) virtual
Move the samplers moving beads for a given level, returning the probability for the old move divided by the probability for the new move.
Implements Mover.
Definition at line 61 of file FreeMover.cc.
References Beads< TDIM >::delta(), forwardProb, MultiLevelSampler::getFactor(), MultiLevelSampler::getMovingBeads(), MultiLevelSampler::getMovingIndex(), Beads< TDIM >::getNSlice(), MultiLevelSampler::getSectionBeads(), MultiLevelSampler::getSuperCell(), lambda, RandomNumGenerator::makeGaussRand(), SuperCell::pbc(), pg, specIndex, and tau.
Referenced by FreeSpinMover::makeMove().
Member Data Documentation
double FreeMover::forwardProb private
forward transition prob
Definition at line 45 of file FreeMover.h.
Referenced by getForwardProb(), makeDelayedMove(), and makeMove().
blitz::Array<double, 1> FreeMover::lambda private
The inverse mass, .
Definition at line 38 of file FreeMover.h.
Referenced by FreeMover(), makeDelayedMove(), and makeMove().
PGArray FreeMover::pg private
Periodic gaussians.
Definition at line 42 of file FreeMover.h.
Referenced by FreeMover(), makeDelayedMove(), makeMove(), and ~FreeMover().
IArray FreeMover::specIndex private
Definition at line 43 of file FreeMover.h.
Referenced by FreeMover(), makeDelayedMove(), and makeMove().
double FreeMover::tau private
The timestep.
Definition at line 40 of file FreeMover.h.
Referenced by FreeMover(), makeDelayedMove(), and makeMove().
The documentation for this class was generated from the following files:
FreeMover.h
FreeMover.cc