pi: Path integral Quantum Monte Carlo: MPIManager Class Reference
MPIManager Class Reference
#include <MPIManager.h>
Public Member Functions
MPIManager (const int nworker, const int nclone)
~MPIManager ()
bool isMain () const
bool isCloneMain () const
int getNWorker () const
int getNClone () const
int getWorkerID () const
int getCloneID () const
Private Attributes
const int nworker
const int nclone
int workerID
int cloneID
bool isMainFlag
bool isCloneMainFlag
Detailed Description
Definition at line 23 of file MPIManager.h.
Constructor & Destructor Documentation
MPIManager::MPIManager (const int nworker, const int nclone)
Definition at line 10 of file MPIManager.cc.
References cloneID, isCloneMainFlag, isMainFlag, nworker, and workerID.
MPIManager::~MPIManager ()
Member Function Documentation
int MPIManager::getCloneID () const inline
Definition at line 32 of file MPIManager.h.
References cloneID.
Referenced by FixedNodeAction::initialize(), PathReader::run(), and WritePaths::run().
int MPIManager::getNClone () const inline
Definition at line 30 of file MPIManager.h.
References nclone.
Referenced by PathReader::run(), and WritePaths::run().
int MPIManager::getNWorker () const inline
Definition at line 29 of file MPIManager.h.
References nworker.
Referenced by PIMCParser::parse(), and WritePaths::run().
int MPIManager::getWorkerID () const inline
Definition at line 31 of file MPIManager.h.
References workerID.
Referenced by ConductivityEstimator2D::endCalc(), FrequencyEstimator::endCalc(), DensityCurrentEstimator::endCalc(), DensityEstimator::endCalc(), SKOmegaEstimator::endCalc(), ConductivityEstimator::endCalc(), ConductanceEstimator::endCalc(), EIndEstimator::endCalc(), SpinChargeEstimator::endCalc(), VIndEstimator::endCalc(), CountCountEstimator::endCalc(), DynamicPCFEstimator::endCalc(), DensDensEstimator::endCalc(), DensCountEstimator::endCalc(), PairCFEstimator< N >::endCalc(), SpinChoicePCFEstimator< N >::endCalc(), ZeroVarDensityEstimator::endCalc(), PathReader::run(), and WritePaths::run().
bool MPIManager::isCloneMain () const inline
Definition at line 28 of file MPIManager.h.
References isCloneMainFlag.
Referenced by PermutationEstimator::averageOverClones(), FreeEnergyEstimator::averageOverClones(), BlitzArrayBlkdEst< N >::averageOverClones(), ScalarEstimator::averageOverClones(), AccRejEstimator::averageOverClones(), SpinSetter::run(), StructReader::run(), RingLattice::run(), CubicLattice::run(), and EstimatorManager::writeStep().
bool MPIManager::isMain () const inline
Definition at line 27 of file MPIManager.h.
References isMainFlag.
Referenced by EwaldCoulombEstimator::handleLink(), MainParser::parse(), PIMCParser::parse(), PIMCParser::parseAlgorithm(), Loop::run(), TimpQPC::TimpQPC(), and EstimatorManager::writeStep().
Member Data Documentation
int MPIManager::cloneID private
Definition at line 41 of file MPIManager.h.
Referenced by getCloneID(), and MPIManager().
bool MPIManager::isCloneMainFlag private
Definition at line 43 of file MPIManager.h.
Referenced by isCloneMain(), and MPIManager().
bool MPIManager::isMainFlag private
Definition at line 42 of file MPIManager.h.
Referenced by isMain(), and MPIManager().
const int MPIManager::nclone private
Definition at line 39 of file MPIManager.h.
Referenced by getNClone().
const int MPIManager::nworker private
Definition at line 38 of file MPIManager.h.
Referenced by getNWorker(), and MPIManager().
int MPIManager::workerID private
Definition at line 40 of file MPIManager.h.
Referenced by getWorkerID(), and MPIManager().
The documentation for this class was generated from the following files:
MPIManager.h
MPIManager.cc