pi: Path integral Quantum Monte Carlo: SpinPhaseModel Class Reference
SpinPhaseModel Class Reference
Base class for phase models used in the fixed phase method.
#include <SpinPhaseModel.h>
Public Types
typedef blitz::TinyVector
< double, NDIM > Vec
typedef blitz::Array< Vec, 1 > VArray
typedef blitz::TinyVector
< double, 4 > SVec
typedef blitz::Array< SVec, 1 > SArray
Public Member Functions
SpinPhaseModel (const int npart)
Constructor.
virtual ~SpinPhaseModel ()
Virtual destructor.
virtual void evaluate (const VArray &, const VArray &, const SArray &, const SArray &, const int islice)=0
Evaluate the SpinPhaseModel.
double getPhi () const
Get the value of the phase.
const VArray & getGradPhi (const int i) const
Get the value of the gradient of the phase.
const SArray & getSGradPhi (const int i) const
Get the value of the spin gradient of the phase.
const VArray & getVecPot (const int i) const
Get the value of the vector potential.
Protected Attributes
double phi
The value of the phase.
VArray gradPhi1
The gradient of the phase.
VArray gradPhi2
SArray sgradPhi1
The spin gradient of the phase.
SArray sgradPhi2
VArray vecPot1
The vector potential.
VArray vecPot2
Detailed Description
Base class for phase models used in the fixed phase method.
Suppose we have density matrix of complex funtion, we can write . We need the derivative of density matrix,
Divide by on each side, we get
Now we can get the derivative of the phase.
How to get in the simulation?
Version:
$Revision$
Author:
Daejin Shin and John Shumway
Definition at line 38 of file SpinPhaseModel.h.
Member Typedef Documentation
typedef blitz::Array<SVec,1> SpinPhaseModel::SArray
Definition at line 43 of file SpinPhaseModel.h.
typedef blitz::TinyVector<double,4> SpinPhaseModel::SVec
Reimplemented in LatticeSpinPhase, and SpinPhase.
Definition at line 42 of file SpinPhaseModel.h.
typedef blitz::Array<Vec,1> SpinPhaseModel::VArray
Definition at line 41 of file SpinPhaseModel.h.
typedef blitz::TinyVector<double,NDIM> SpinPhaseModel::Vec
Definition at line 40 of file SpinPhaseModel.h.
Constructor & Destructor Documentation
SpinPhaseModel::SpinPhaseModel (const int npart) inline
Constructor.
Definition at line 45 of file SpinPhaseModel.h.
virtual SpinPhaseModel::~SpinPhaseModel () inline virtual
Virtual destructor.
Definition at line 48 of file SpinPhaseModel.h.
Member Function Documentation
virtual void SpinPhaseModel::evaluate (const VArray & , const VArray & , const SArray & , const SArray & , const int islice) pure virtual
Evaluate the SpinPhaseModel.
Implemented in LatticeSpinPhase, and SpinPhase.
Referenced by SpinFixedPhaseAction::getActionDifference(), SpinFixedPhaseAction::getBeadAction(), and SpinFixedPhaseAction::initialize().
const VArray& SpinPhaseModel::getGradPhi (const int i) const inline
Get the value of the gradient of the phase.
Definition at line 55 of file SpinPhaseModel.h.
References gradPhi1, and gradPhi2.
Referenced by SpinFixedPhaseAction::getActionDifference(), SpinFixedPhaseAction::getBeadAction(), and SpinFixedPhaseAction::initialize().
double SpinPhaseModel::getPhi () const inline
Get the value of the phase.
Definition at line 53 of file SpinPhaseModel.h.
References phi.
Referenced by SpinFixedPhaseAction::getActionDifference(), SpinFixedPhaseAction::getBeadAction(), and SpinFixedPhaseAction::initialize().
const SArray& SpinPhaseModel::getSGradPhi (const int i) const inline
Get the value of the spin gradient of the phase.
Definition at line 57 of file SpinPhaseModel.h.
References sgradPhi1, and sgradPhi2.
Referenced by SpinFixedPhaseAction::getActionDifference(), SpinFixedPhaseAction::getBeadAction(), and SpinFixedPhaseAction::initialize().
const VArray& SpinPhaseModel::getVecPot (const int i) const inline
Get the value of the vector potential.
Definition at line 60 of file SpinPhaseModel.h.
References vecPot1, and vecPot2.
Referenced by SpinFixedPhaseAction::getActionDifference(), SpinFixedPhaseAction::getBeadAction(), and SpinFixedPhaseAction::initialize().
Member Data Documentation
VArray SpinPhaseModel::gradPhi1 protected
The gradient of the phase.
Definition at line 65 of file SpinPhaseModel.h.
Referenced by LatticeSpinPhase::evaluate(), SpinPhase::evaluate(), and getGradPhi().
VArray SpinPhaseModel::gradPhi2 protected
Definition at line 65 of file SpinPhaseModel.h.
Referenced by LatticeSpinPhase::evaluate(), SpinPhase::evaluate(), and getGradPhi().
double SpinPhaseModel::phi protected
The value of the phase.
Definition at line 63 of file SpinPhaseModel.h.
Referenced by getPhi().
SArray SpinPhaseModel::sgradPhi1 protected
The spin gradient of the phase.
Definition at line 67 of file SpinPhaseModel.h.
Referenced by LatticeSpinPhase::evaluate(), SpinPhase::evaluate(), and getSGradPhi().
SArray SpinPhaseModel::sgradPhi2 protected
Definition at line 67 of file SpinPhaseModel.h.
Referenced by LatticeSpinPhase::evaluate(), SpinPhase::evaluate(), and getSGradPhi().
VArray SpinPhaseModel::vecPot1 protected
The vector potential.
Definition at line 69 of file SpinPhaseModel.h.
Referenced by LatticeSpinPhase::evaluate(), SpinPhase::evaluate(), and getVecPot().
VArray SpinPhaseModel::vecPot2 protected
Definition at line 69 of file SpinPhaseModel.h.
Referenced by LatticeSpinPhase::evaluate(), SpinPhase::evaluate(), and getVecPot().
The documentation for this class was generated from the following file:
SpinPhaseModel.h