pi: Path integral Quantum Monte Carlo: SpinChoiceFixedNodeAction Class Reference
SpinChoiceFixedNodeAction Class Reference
#include <SpinChoiceFixedNodeAction.h>
Public Types
typedef blitz::Array< int, 1 > IArray
Public Types inherited from FixedNodeAction
typedef blitz::TinyVector
< double, NDIM > Vec
Constants and typedefs.
typedef blitz::TinyMatrix
< double, NDIM, NDIM > Mat
typedef blitz::Array< double, 1 > Array
typedef blitz::Array< double, 2 > Array2
typedef blitz::Array< double, 3 > Array3
typedef blitz::Array< Vec, 1 > VArray
typedef blitz::Array< double, 2 > Matrix
typedef blitz::Array< Vec, 2 > VMatrix
typedef blitz::Array< Mat, 2 > MMatrix
typedef
blitz::ColumnMajorArray< 2 > ColMajor
Public Types inherited from DoubleAction
Public Member Functions
SpinChoiceFixedNodeAction (const SimulationInfo &, int initial, const Species &, NodeModel *, bool withNodalAction, bool useDistDerivative, int maxlevel, bool useManyBodyDistance, const MPIManager *mpi)
virtual ~SpinChoiceFixedNodeAction ()
virtual double getActionChoiceDifference (const Paths &paths, int ipart)
Public Member Functions inherited from FixedNodeAction
FixedNodeAction (const SimulationInfo &, const Species &, NodeModel *, bool withNodalAction, bool useDistDerivative, int maxlevel, bool useManyBodyDistance, int nerrorMax, const MPIManager *mpi)
Constructor.
virtual ~FixedNodeAction ()
Destructor.
virtual double getActionDifference (const SectionSamplerInterface &, int level)
Calculate the difference in action.
virtual double getActionDifference (const Paths &, const VArray &displacement, int nmoving, const IArray &movingIndex, int iFirstSlice, int nslice)
Calculate the difference in action.
virtual double getTotalAction (const Paths &, const int level) const
Calculate the total action.
virtual void getBeadAction (const Paths &, int ipart, int islice, double &u, double &utau, double &ulambda, Vec &fm, Vec &fp) const
Calculate action and derivatives at a bead.
virtual void initialize (const DoubleSectionChooser &)
Initialize for a sampling section.
virtual void acceptLastMove ()
Accept last move.
Public Member Functions inherited from DoubleAction
virtual ~DoubleAction ()
Virtual destructor.
Public Member Functions inherited from ActionChoiceBase
ActionChoiceBase ()
virtual ~ActionChoiceBase ()
ModelState & getModelState ()
const ModelState & getModelState () const
Private Attributes
SpinModelState * spinModelState
const MPIManager * mpi
Additional Inherited Members
Protected Attributes inherited from FixedNodeAction
const double tau
The time step.
const int npart
Total number of particles.
const int nSpeciesPart
Number of particles of this type of fermion.
const int ifirst
Index of first particle of this type of fermion.
int nslice
Number of slices.
VArray r1
Storage for the current slice.
VArray r2
bool notMySpecies
Flag for checking if this species is being moved.
Array dmValue
Determinants.
Array newDMValue
Array3 dist
Distances to the nodes.
Array3 newDist
VArray force
Array to cache forces for getBeadAction.
VMatrix gradd1
VMatrix gradd2
Array dim1
Arrays to store distances for getBeadAction.
Array dip1
Array di1
Array dim2
Array dip2
Array di2
Array dotdim1
Array dotdi1
Array dotdim2
Array dotdi2
NodeModel * nodeModel
The NodeModel.
NodeModel::MatrixUpdate * matrixUpdateObj
The nodeModel's MatrixUpdate object.
bool withNodalAction
Flag for including the nodal action when near the node.
bool useDistDerivative
Flag for calculating time derivative of the distance to the node.
int nerror
int nerrorMax
bool useManyBodyDistance
Protected Attributes inherited from ActionChoiceBase
double actionDifference
ModelState * modelState
Detailed Description
Version:
Revision:
393
Author:
John Shumway and Jianheng Liu
Definition at line 29 of file SpinChoiceFixedNodeAction.h.
Member Typedef Documentation
typedef blitz::Array<int,1> SpinChoiceFixedNodeAction::IArray
Reimplemented from FixedNodeAction.
Definition at line 33 of file SpinChoiceFixedNodeAction.h.
Constructor & Destructor Documentation
SpinChoiceFixedNodeAction::SpinChoiceFixedNodeAction (const SimulationInfo & simInfo, int initial, const Species & species, NodeModel * nodeModel, bool withNodalAction, bool useDistDerivative, int maxlevel, bool useManyBodyDistance, const MPIManager * mpi)
Definition at line 13 of file SpinChoiceFixedNodeAction.cc.
References ActionChoiceBase::modelState, FixedNodeAction::nSpeciesPart, NodeModel::setSpinModelState(), and spinModelState.
SpinChoiceFixedNodeAction::~SpinChoiceFixedNodeAction () virtual
Definition at line 26 of file SpinChoiceFixedNodeAction.cc.
References spinModelState.
Member Function Documentation
double SpinChoiceFixedNodeAction::getActionChoiceDifference (const Paths & paths, int ipart) virtual
Implements ActionChoiceBase.
Definition at line 30 of file SpinChoiceFixedNodeAction.cc.
References NodeModel::DetWithFlag::det, FixedNodeAction::di1, FixedNodeAction::di2, FixedNodeAction::dim1, FixedNodeAction::dim2, NodeModel::DetWithFlag::err, NodeModel::evaluate(), NodeModel::evaluateDistance(), mpi, FixedNodeAction::nodeModel, FixedNodeAction::npart, FixedNodeAction::r1, FixedNodeAction::r2, spinModelState, and FixedNodeAction::useManyBodyDistance.
Member Data Documentation
const MPIManager* SpinChoiceFixedNodeAction::mpi private
Reimplemented from FixedNodeAction.
Definition at line 52 of file SpinChoiceFixedNodeAction.h.
Referenced by getActionChoiceDifference().
SpinModelState* SpinChoiceFixedNodeAction::spinModelState private
Definition at line 50 of file SpinChoiceFixedNodeAction.h.
Referenced by getActionChoiceDifference(), SpinChoiceFixedNodeAction(), and ~SpinChoiceFixedNodeAction().
The documentation for this class was generated from the following files:
SpinChoiceFixedNodeAction.h
SpinChoiceFixedNodeAction.cc