pi: Path integral Quantum Monte Carlo: SpinModelState Class Reference
SpinModelState Class Reference
Model state for spin up and spin down.
#include <SpinModelState.h>
Public Types
typedef blitz::Array< int, 1 > IArray
Public Member Functions
SpinModelState (int npart, int initial)
virtual ~SpinModelState ()
virtual void write (std::ostream &os) const
virtual bool read (const std::string &line)
const IArray & getSpinState () const
IArray & getModelState ()
virtual int getModelCount () const
virtual int getModelState () const
void flipSpin (int i)
virtual bool isSpinModelState ()
virtual void broadcastToMPIWorkers (const MPIManager *mpi)
Public Member Functions inherited from ModelState
virtual ~ModelState ()
Private Attributes
const int npart
IArray spinState
Detailed Description
Model state for spin up and spin down.
Version:
Revision:
338
Author:
John Shumway and Jianheng Liu
Definition at line 27 of file SpinModelState.h.
Member Typedef Documentation
typedef blitz::Array<int,1> SpinModelState::IArray
Definition at line 29 of file SpinModelState.h.
Constructor & Destructor Documentation
SpinModelState::SpinModelState (int npart, int initial)
Definition at line 27 of file SpinModelState.cc.
References npart, and spinState.
virtual SpinModelState::~SpinModelState () inline virtual
Definition at line 31 of file SpinModelState.h.
Member Function Documentation
void SpinModelState::broadcastToMPIWorkers (const MPIManager * mpi) virtual
Reimplemented from ModelState.
Definition at line 63 of file SpinModelState.cc.
References npart, and spinState.
Referenced by SpinChoiceFixedNodeAction::getActionChoiceDifference(), and SpinModelSampler::tryMove().
void SpinModelState::flipSpin (int i) inline
Definition at line 38 of file SpinModelState.h.
References spinState.
Referenced by SpinChoiceFixedNodeAction::getActionChoiceDifference(), and SpinModelSampler::tryMove().
virtual int SpinModelState::getModelCount () const inline virtual
Implements ModelState.
Definition at line 36 of file SpinModelState.h.
References npart.
IArray& SpinModelState::getModelState () inline
Definition at line 35 of file SpinModelState.h.
References spinState.
int SpinModelState::getModelState () const virtual
Implements ModelState.
Definition at line 58 of file SpinModelState.cc.
References spinState.
const IArray& SpinModelState::getSpinState () const inline
Definition at line 34 of file SpinModelState.h.
References spinState.
Referenced by SHONodes::evaluate(), WireNodes::evaluate(), and FreeParticleNodes::evaluate().
virtual bool SpinModelState::isSpinModelState () inline virtual
Reimplemented from ModelState.
Definition at line 39 of file SpinModelState.h.
bool SpinModelState::read (const std::string & line) virtual
Implements ModelState.
Definition at line 41 of file SpinModelState.cc.
References npart, and spinState.
void SpinModelState::write (std::ostream & os) const virtual
Implements ModelState.
Definition at line 35 of file SpinModelState.cc.
References npart, and spinState.
Member Data Documentation
const int SpinModelState::npart private
Definition at line 42 of file SpinModelState.h.
Referenced by broadcastToMPIWorkers(), getModelCount(), read(), SpinModelState(), and write().
IArray SpinModelState::spinState private
Definition at line 43 of file SpinModelState.h.
Referenced by broadcastToMPIWorkers(), flipSpin(), getModelState(), getSpinState(), read(), SpinModelState(), and write().
The documentation for this class was generated from the following files:
SpinModelState.h
SpinModelState.cc