pi: Path integral Quantum Monte Carlo: Beads< TDIM > Class Template Reference
Beads< TDIM > Class Template Reference
Storage for beads on the path.
#include <Beads.h>
Public Types
typedef blitz::TinyVector
< double, TDIM > Vec
Typedefs and constants.
typedef blitz::Array< Vec, 1 > VArray
typedef blitz::Array< Vec, 2 > VArray2
Public Types inherited from BeadsBase
typedef std::vector< BeadsBase * > BeadsArray
typedef blitz::Array< int, 1 > IArray
Public Member Functions
Beads (const int npart, const int nslice)
Constructor.
Beads (const Beads &)
Copy constructor.
virtual BeadsBase * clone (const int npart, const int nslice)
Clone method.
~Beads ()
Virtual destructor.
virtual void print (std::ostream &out) const
Support for printing.
const Vec operator() (const int ipart, const int islice) const
Const access.
Vec & operator() (const int ipart, const int islice)
Non const access.
const Vec delta (const int ipart, const int islice, const int istep) const
Get a relative displacement.
int getNPart () const
Return the number of particles.
int getNSlice () const
Return the number of slices.
void setSuperCell (const SuperCell *c)
Set the supercell.
const SuperCell * getSuperCell () const
Return a pointer to the supercell.
void permute (const Permutation &)
Permute the beads.
VArray2 & getCoordArray ()
Return a reference to the coordinate array (for MPI calls).
Public Member Functions inherited from BeadsBase
BeadsBase (int npart, int nslice)
BeadsBase * cloneBase (const int npart, const int nslice)
virtual ~BeadsBase ()
Virtual destructor.
BeadsBase & operator= (const BeadsBase &beadsIn)
Copy operatation.
void copySlice (int isliceIn, BeadsBase &beadsOut, int isliceOut) const
Copy a slice.
void copySlice (const Permutation &p, int isliceIn, BeadsBase &beadsOut, int isliceOut) const
void copySlice (int isliceIn, BeadsBase &beadsOut, const Permutation &p, int isliceOut) const
void copySlice (const IArray &indexIn, int isliceIn, BeadsBase &beadsOut, const IArray &indexOut, int isliceOut) const
int getAuxBeadCount () const
Get the number of auxiliary beads.
virtual const void * getAuxBead (const int ipart, const int islice, const int iaux) const
Get a pointer to an auxiliary bead.
virtual void * getAuxBead (const int ipart, const int islice, const int iaux)
Get a pointer to an auxiliary bead.
const BeadsBase * getAuxBeads (const int i=0) const
Return a pointer to the auxiliary beads.
BeadsBase * getAuxBeads (const int i=0)
Protected Member Functions
virtual void vcopySlice (int isliceIn, BeadsBase *beadsOut, int isliceOut) const
Virtual method to copy a slice.
virtual void vcopySlice (const Permutation &p, int isliceIn, BeadsBase *beadsOut, int isliceOut) const
virtual void vcopySlice (int isliceIn, BeadsBase *beadsOut, const Permutation &p, int isliceOut) const
virtual void vcopySlice (const IArray &indexIn, int isliceIn, BeadsBase *beadsOut, const IArray &indexOut, int isliceOut) const
virtual const void * vgetAuxBead (const int ipart, const int islice) const
virtual void * vgetAuxBead (const int ipart, const int islice)
virtual void vcopy (BeadsBase *beadsOut) const
Private Attributes
VArray2 coord
Storage for the bead coordinates.
const SuperCell * cell
The super cell.
Additional Inherited Members
Protected Attributes inherited from BeadsBase
int nAuxBeads
Number of auxBeads.
BeadsArray auxBeads
Auxiliary beads.
int npart
Number of particles.
int nslice
Number of slices.
Detailed Description
template<int TDIM>
class Beads< TDIM >
Storage for beads on the path.
Version:
$Revision$
Author:
John Shumway
Bug:
Permute doesn't move auxilliary beads.
Definition at line 131 of file Beads.h.
Member Typedef Documentation
template<int TDIM> typedef blitz::Array<Vec,1> Beads< TDIM >::VArray
Definition at line 135 of file Beads.h.
template<int TDIM> typedef blitz::Array<Vec,2> Beads< TDIM >::VArray2
Definition at line 136 of file Beads.h.
template<int TDIM> typedef blitz::TinyVector<double,TDIM> Beads< TDIM >::Vec
Typedefs and constants.
Definition at line 134 of file Beads.h.
Constructor & Destructor Documentation
template<int TDIM> Beads< TDIM >::Beads (const int npart, const int nslice)
Constructor.
Definition at line 223 of file Beads.h.
References BeadsBase::auxBeads, and Beads< TDIM >::coord.
Referenced by Beads< NDIM >::clone().
template<int TDIM> Beads< TDIM >::Beads (const Beads< TDIM > & b)
Copy constructor.
Definition at line 231 of file Beads.h.
template<int TDIM> Beads< TDIM >::~Beads () inline
Virtual destructor.
Definition at line 146 of file Beads.h.
Member Function Documentation
template<int TDIM> virtual BeadsBase* Beads< TDIM >::clone (const int npart, const int nslice) inline virtual
Clone method.
Implements BeadsBase.
Definition at line 142 of file Beads.h.
template<int TDIM> const Vec Beads< TDIM >::delta (const int ipart, const int islice, const int istep) const inline
Get a relative displacement.
Definition at line 166 of file Beads.h.
Referenced by SpringAction::getActionDifference(), HyperbolicAction::getActionDifference(), FreeMover::makeDelayedMove(), FreeMoverPBC::makeDelayedMove(), HyperbolicMover::makeMove(), FreeMover::makeMove(), FreeMoverPBC::makeMove(), SpinMover::makeMove(), FreeSpinMover::makeMove(), and EMARateMover::sampleDiagonal().
template<int TDIM> VArray2& Beads< TDIM >::getCoordArray () inline
Return a reference to the coordinate array (for MPI calls).
Definition at line 180 of file Beads.h.
Referenced by DoubleParallelPaths::shift(), and ParallelPaths::shift().
template<int TDIM> int Beads< TDIM >::getNPart () const inline
Return the number of particles.
Definition at line 170 of file Beads.h.
Referenced by GaussianAction::getActionDifference(), DotGeomAction::getActionDifference(), and CollectiveSectionMover::makeMove().
template<int TDIM> int Beads< TDIM >::getNSlice () const inline
Return the number of slices.
Definition at line 172 of file Beads.h.
Referenced by CoulombAction::getActionDifference(), PrimColloidalAction::getActionDifference(), GrapheneAction::getActionDifference(), RingGateAction::getActionDifference(), EwaldImagePairAction::getActionDifference(), GaussianDotAction::getActionDifference(), GaussianAction::getActionDifference(), GateAction::getActionDifference(), GroundStateWFNodes::getActionDifference(), TwoQDAction::getActionDifference(), OpticalLatticeAction::getActionDifference(), PrimAnisSHOAction::getActionDifference(), PrimShellAction::getActionDifference(), PrimSHOAction::getActionDifference(), PrimTorusAction::getActionDifference(), SphereAction::getActionDifference(), SHODotAction::getActionDifference(), DotGeomAction::getActionDifference(), GridPotential::getActionDifference(), SpringTensorAction::getActionDifference(), PrimCosineAction::getActionDifference(), EFieldAction::getActionDifference(), SpringAction::getActionDifference(), QPCAction::getActionDifference(), SpinAction::getActionDifference(), AnisotropicNodes::getActionDifference(), TimpQPC::getActionDifference(), HyperbolicAction::getActionDifference(), StillWebAction::getActionDifference(), SHOAction::getActionDifference(), ImagePairAction::getActionDifference(), JelliumSlab::getActionDifference(), SmoothedGridPotential::getActionDifference(), FixedNodeAction::getActionDifference(), PairAction::getActionDifference(), FixedPhaseAction::getActionDifference(), SpinFixedPhaseAction::getActionDifference(), WellImageAction::getActionDifference(), FreePartNodesNoUpdate::getActionDifference(), SerialPaths::getBeads(), DoubleParallelPaths::getBeads(), ParallelPaths::getBeads(), SpinStatePermutationChooser::init(), WalkingChooser::init(), AnisotropicNodes::initialize(), FixedNodeAction::initialize(), SpinFixedPhaseAction::initialize(), FixedPhaseAction::initialize(), FreePartNodesNoUpdate::initialize(), FreeMover::makeDelayedMove(), FreeMoverPBC::makeDelayedMove(), CollectiveSectionMover::makeMove(), HyperbolicMover::makeMove(), EMARateMover::makeMove(), FreeTensorMover::makeMove(), DampedFreeTensorMover::makeMove(), FreeMover::makeMove(), FreeMoverPBC::makeMove(), SpinMover::makeMove(), FreeSpinMover::makeMove(), MiddleSectionChooser::MiddleSectionChooser(), SerialPaths::putBeads(), DoubleParallelPaths::putBeads(), ParallelPaths::putBeads(), NonZeroSectionChooser::run(), SectionChooser::run(), DoubleCollectiveSectionSampler::run(), DoubleSectionChooser::run(), CollectiveSectionSampler::run(), DoubleMLSampler::run(), MultiLevelSampler::run(), SerialPaths::shift(), DoubleCollectiveSectionSampler::tryMove(), DoubleMLSampler::tryMove(), CollectiveSectionSampler::tryMove(), and MultiLevelSampler::tryMove().
template<int TDIM> const SuperCell* Beads< TDIM >::getSuperCell () const inline
Return a pointer to the supercell.
Definition at line 176 of file Beads.h.
template<int TDIM> const Vec Beads< TDIM >::operator() (const int ipart, const int islice) const inline
Const access.
Definition at line 158 of file Beads.h.
template<int TDIM> Vec& Beads< TDIM >::operator() (const int ipart, const int islice) inline
Non const access.
Definition at line 162 of file Beads.h.
template<int TDIM> void Beads< TDIM >::permute (const Permutation & p)
Permute the beads.
Definition at line 254 of file Beads.h.
Referenced by SerialPaths::putDoubleBeads().
template<int TDIM> void Beads< TDIM >::print (std::ostream & out) const virtual
Support for printing.
Implements BeadsBase.
Definition at line 242 of file Beads.h.
template<int TDIM> void Beads< TDIM >::setSuperCell (const SuperCell * c) inline
Set the supercell.
Definition at line 174 of file Beads.h.
template<int TDIM> virtual void Beads< TDIM >::vcopy (BeadsBase * beadsOut) const inline protected virtual
Implements BeadsBase.
Definition at line 209 of file Beads.h.
template<int TDIM> virtual void Beads< TDIM >::vcopySlice (int isliceIn, BeadsBase * beadsOut, int isliceOut) const inline protected virtual
Virtual method to copy a slice.
Implements BeadsBase.
Definition at line 183 of file Beads.h.
template<int TDIM> virtual void Beads< TDIM >::vcopySlice (const Permutation & p, int isliceIn, BeadsBase * beadsOut, int isliceOut) const inline protected virtual
Implements BeadsBase.
Definition at line 188 of file Beads.h.
template<int TDIM> virtual void Beads< TDIM >::vcopySlice (int isliceIn, BeadsBase * beadsOut, const Permutation & p, int isliceOut) const inline protected virtual
Implements BeadsBase.
Definition at line 193 of file Beads.h.
template<int TDIM> virtual void Beads< TDIM >::vcopySlice (const IArray & indexIn, int isliceIn, BeadsBase * beadsOut, const IArray & indexOut, int isliceOut) const inline protected virtual
Implements BeadsBase.
Definition at line 198 of file Beads.h.
template<int TDIM> virtual const void* Beads< TDIM >::vgetAuxBead (const int ipart, const int islice) const inline protected virtual
Implements BeadsBase.
Definition at line 205 of file Beads.h.
template<int TDIM> virtual void* Beads< TDIM >::vgetAuxBead (const int ipart, const int islice) inline protected virtual
Implements BeadsBase.
Definition at line 207 of file Beads.h.
Member Data Documentation
template<int TDIM> const SuperCell* Beads< TDIM >::cell private
The super cell.
Definition at line 217 of file Beads.h.
Referenced by Beads< NDIM >::getSuperCell(), and Beads< NDIM >::setSuperCell().
template<int TDIM> VArray2 Beads< TDIM >::coord private
Storage for the bead coordinates.
Definition at line 215 of file Beads.h.
Referenced by Beads< TDIM >::Beads(), Beads< NDIM >::delta(), Beads< NDIM >::getCoordArray(), Beads< NDIM >::operator()(), Beads< NDIM >::vcopy(), Beads< NDIM >::vcopySlice(), and Beads< NDIM >::vgetAuxBead().
The documentation for this class was generated from the following file:
Beads.h