pi: Path integral Quantum Monte Carlo: FreeTensorMover Class Reference
FreeTensorMover Class Reference
Select a trial move for beads by free particle sampling.
#include <FreeTensorMover.h>
Public Types
typedef blitz::TinyVector
< double, NDIM > Vec
Public Member Functions
FreeTensorMover (const SimulationInfo &simInfo)
Construct by providing lambda () timestep .
virtual ~FreeTensorMover ()
Virtual destructor.
virtual double makeMove (MultiLevelSampler &, const int level)
Move the samplers moving beads for a given level, returning the probability for the old move divided by the probability for the new move.
virtual double makeDelayedMove (MultiLevelSampler &, const int level)
virtual double getForwardProb ()
Public Member Functions inherited from Mover
virtual ~Mover ()
Private Attributes
blitz::Array
< blitz::TinyVector< double,
NDIM >, 1 > lambda
The inverse mass, .
double tau
The timestep.
Detailed Description
Select a trial move for beads by free particle sampling.
Todo:
May want to make this a subclass of Action, with a flag for whether to return probability or allow to cancel for efficiency.
Bug:
Needs to calculate the transiton probability correctly when periodic images are significant. Currently the routine neglects this.
Hard-coded for Si/Ge electron and hole.
Version:
$Revision$
Author:
John Shumway.
Definition at line 17 of file FreeTensorMover.h.
Member Typedef Documentation
typedef blitz::TinyVector<double, NDIM> FreeTensorMover::Vec
Definition at line 19 of file FreeTensorMover.h.
Constructor & Destructor Documentation
FreeTensorMover::FreeTensorMover (const SimulationInfo & simInfo)
Construct by providing lambda () timestep .
Definition at line 16 of file FreeTensorMover.cc.
References Species::anMass, SimulationInfo::getNPart(), SimulationInfo::getPartSpecies(), and lambda.
virtual FreeTensorMover::~FreeTensorMover () inline virtual
Virtual destructor.
Definition at line 23 of file FreeTensorMover.h.
Member Function Documentation
virtual double FreeTensorMover::getForwardProb () inline virtual
Implements Mover.
Definition at line 32 of file FreeTensorMover.h.
virtual double FreeTensorMover::makeDelayedMove (MultiLevelSampler & , const int level) inline virtual
Implements Mover.
Definition at line 29 of file FreeTensorMover.h.
double FreeTensorMover::makeMove (MultiLevelSampler & sampler, const int level) virtual
Move the samplers moving beads for a given level, returning the probability for the old move divided by the probability for the new move.
toldOverTnew=exp(toldOverTnew);
Implements Mover.
Definition at line 24 of file FreeTensorMover.cc.
References MultiLevelSampler::getMovingBeads(), MultiLevelSampler::getMovingIndex(), Beads< TDIM >::getNSlice(), MultiLevelSampler::getSectionBeads(), MultiLevelSampler::getSuperCell(), lambda, RandomNumGenerator::makeGaussRand(), SuperCell::pbc(), and tau.
Member Data Documentation
blitz::Array<blitz::TinyVector<double, NDIM>, 1> FreeTensorMover::lambda private
The inverse mass, .
Definition at line 37 of file FreeTensorMover.h.
Referenced by FreeTensorMover(), and makeMove().
double FreeTensorMover::tau private
The timestep.
Definition at line 39 of file FreeTensorMover.h.
Referenced by makeMove().
The documentation for this class was generated from the following files:
FreeTensorMover.h
FreeTensorMover.cc