pi: Path integral Quantum Monte Carlo: NodeModel::MatrixUpdate Class Reference
NodeModel::MatrixUpdate Class Reference
Base class for matrix updates.
#include <NodeModel.h>
Public Member Functions
virtual double evaluateChange (const SectionSamplerInterface &, int islice)=0
virtual void evaluateNewInverse (const int islice)=0
virtual void evaluateNewDistance (const VArray &r1, const VArray &r2, const int islice, Array &d1, Array &d2)=0
virtual void acceptLastMove (int nslice)=0
Detailed Description
Base class for matrix updates.
The trial density matrix is
The inverse matrix satisfies , so a change in the density matrix changes the determinant by a factor,
This matrix is the identity matrix, except for rows with moving particles. Using the notation to indicate the index j of the ith moving particle, we construct the nmoving-by-nmoving matrix
so . We calculate and store the vectors for each of the moving particles j.
To calculate the distance to the node, we need to temporarily calculate a new updated matrix, The update formula for a changed row is,
where .
Definition at line 74 of file NodeModel.h.
Member Function Documentation
virtual void NodeModel::MatrixUpdate::acceptLastMove (int nslice) pure virtual
Implemented in AugmentedNodes::MatrixUpdate, FreeParticleNodes::MatrixUpdate, and WireNodes::MatrixUpdate.
Referenced by FixedNodeAction::acceptLastMove().
virtual double NodeModel::MatrixUpdate::evaluateChange (const SectionSamplerInterface & , int islice) pure virtual
Implemented in AugmentedNodes::MatrixUpdate, FreeParticleNodes::MatrixUpdate, and WireNodes::MatrixUpdate.
Referenced by FixedNodeAction::getActionDifference().
virtual void NodeModel::MatrixUpdate::evaluateNewDistance (const VArray & r1, const VArray & r2, const int islice, Array & d1, Array & d2) pure virtual
Implemented in AugmentedNodes::MatrixUpdate, FreeParticleNodes::MatrixUpdate, and WireNodes::MatrixUpdate.
Referenced by FixedNodeAction::getActionDifference().
virtual void NodeModel::MatrixUpdate::evaluateNewInverse (const int islice) pure virtual
Implemented in AugmentedNodes::MatrixUpdate, FreeParticleNodes::MatrixUpdate, and WireNodes::MatrixUpdate.
Referenced by FixedNodeAction::getActionDifference().
The documentation for this class was generated from the following file:
NodeModel.h