pi: Path integral Quantum Monte Carlo: Units Class Reference
Units Class Reference
Class for unit translations.
#include <Units.h>
Public Member Functions
Units (const std::string &eunit, const std::string &lunit)
Construct by giving the name.
~Units ()
Destructor.
double getLengthScaleIn (const std::string &unit, int factor=1) const
Get conversion factor for length input with unit.
double getEnergyScaleIn (const std::string &unit) const
Get conversion factor for energy input with unit.
double getMassScaleIn (const std::string &unit) const
Get conversion factor for mass input with unit.
Protected Types
typedef std::map< std::string,
double > unitMap
Protected Attributes
const std::string internalEnergyUnit
The name of the internal energy unit.
const std::string internalLengthUnit
The name of the internal length unit.
unitMap lengthOut
The conversion factors to different length units.
unitMap energyOut
The conversion factors to different energy units.
unitMap massOut
The conversion factors to different mass units.
Detailed Description
Class for unit translations.
Version:
$Revision$
Author:
John Shumway
Definition at line 25 of file Units.h.
Member Typedef Documentation
typedef std::map<std::string,double> Units::unitMap protected
Definition at line 38 of file Units.h.
Constructor & Destructor Documentation
Units::Units (const std::string & eunit, const std::string & lunit)
Construct by giving the name.
 To set these values, express the atomic unit in terms of named unit.
 Set conversion from bohr radius to common length units.
Set conversion from Hartree to common energy units.
Set conversion from electron mass to common mass units.
Definition at line 25 of file Units.cc.
References energyOut, lengthOut, and massOut.
Units::~Units ()
Destructor.
Member Function Documentation
double Units::getEnergyScaleIn (const std::string & unit) const
Get conversion factor for energy input with unit.
Definition at line 85 of file Units.cc.
References energyOut.
Referenced by XMLUnitParser::getEnergyAttribute(), XMLUnitParser::getFieldStrengthAttribute(), and XMLUnitParser::getTimeAttribute().
double Units::getLengthScaleIn (const std::string & unit, int factor = 1) const
Get conversion factor for length input with unit.
Definition at line 65 of file Units.cc.
References lengthOut.
Referenced by XMLUnitParser::getDensityAttribute(), XMLUnitParser::getFieldStrengthAttribute(), XMLUnitParser::getInvLengthAttribute(), and XMLUnitParser::getLengthAttribute().
double Units::getMassScaleIn (const std::string & unit) const
Get conversion factor for mass input with unit.
Definition at line 95 of file Units.cc.
References massOut.
Referenced by XMLUnitParser::getMassAttribute().
Member Data Documentation
unitMap Units::energyOut protected
The conversion factors to different energy units.
Definition at line 46 of file Units.h.
Referenced by getEnergyScaleIn(), and Units().
const std::string Units::internalEnergyUnit protected
The name of the internal energy unit.
Definition at line 40 of file Units.h.
const std::string Units::internalLengthUnit protected
The name of the internal length unit.
Definition at line 42 of file Units.h.
unitMap Units::lengthOut protected
The conversion factors to different length units.
Definition at line 44 of file Units.h.
Referenced by getLengthScaleIn(), and Units().
unitMap Units::massOut protected
The conversion factors to different mass units.
Definition at line 48 of file Units.h.
Referenced by getMassScaleIn(), and Units().
The documentation for this class was generated from the following files:
Units.h
Units.cc