pi: Path integral Quantum Monte Carlo: ModelState Class Reference
ModelState Class Reference
Base class for model state.
#include <ModelState.h>
Public Member Functions
virtual ~ModelState ()
virtual void write (std::ostream &os) const =0
virtual bool read (const std::string &)=0
virtual int getModelCount () const =0
virtual int getModelState () const =0
virtual void broadcastToMPIWorkers (const MPIManager *mpi)
virtual bool isSpinModelState ()
Detailed Description
Base class for model state.
Version:
Revision:
338
Author:
John Shumway and Jianheng Liu
Definition at line 27 of file ModelState.h.
Constructor & Destructor Documentation
virtual ModelState::~ModelState () inline virtual
Definition at line 29 of file ModelState.h.
Member Function Documentation
virtual void ModelState::broadcastToMPIWorkers (const MPIManager * mpi) inline virtual
Reimplemented in SpinModelState, and EnumeratedModelState.
Definition at line 34 of file ModelState.h.
Referenced by PathReader::run().
virtual int ModelState::getModelCount () const pure virtual
Implemented in SpinModelState, and EnumeratedModelState.
Referenced by EstimatorParser::parse().
virtual int ModelState::getModelState () const pure virtual
Implemented in SpinModelState, and EnumeratedModelState.
Referenced by FreeEnergyEstimator::evaluate().
virtual bool ModelState::isSpinModelState () inline virtual
Reimplemented in SpinModelState.
Definition at line 35 of file ModelState.h.
Referenced by PIMCParser::parseAlgorithm().
virtual bool ModelState::read (const std::string &) pure virtual
Implemented in SpinModelState, and EnumeratedModelState.
Referenced by PathReader::run().
virtual void ModelState::write (std::ostream & os) const pure virtual
Implemented in SpinModelState, and EnumeratedModelState.
Referenced by WritePaths::run().
The documentation for this class was generated from the following file:
ModelState.h