pi: Path integral Quantum Monte Carlo: ModelSampler Class Reference
ModelSampler Class Reference
Class to sample different action models.
#include <ModelSampler.h>
Public Types
typedef blitz::Array< int, 1 > IArray
typedef blitz::TinyVector
< double, NDIM > Vec
typedef blitz::Array< Vec, 1 > VArray
Public Member Functions
ModelSampler (Paths &, Action *, ActionChoiceBase *, int target, const MPIManager *mpi)
virtual ~ModelSampler ()
virtual void run ()
virtual AccRejEstimator * getAccRejEstimator (const std::string &name)
Get a pointer to the accept/reject statistic estimator.
Public Member Functions inherited from Algorithm
virtual ~Algorithm ()
Protected Member Functions
virtual bool tryMove ()
Method to atempt a Monte Carlo move, return true if accepted.
Protected Attributes
Paths & paths
A reference to the paths.
Action * action
The action to be evaluated during the move.
ActionChoiceBase * actionChoice
The action to be evaluated during the move.
EnumeratedModelState & modelState
const int nmodel
AccRejEstimator * accRejEst
A pointer to the accept-reject estimator.
const int target
const MPIManager * mpi
A pointer to the MPI manager, zero if MPI is not used.
Detailed Description
Class to sample different action models.
Definition at line 17 of file ModelSampler.h.
Member Typedef Documentation
typedef blitz::Array<int, 1> ModelSampler::IArray
Definition at line 19 of file ModelSampler.h.
typedef blitz::Array<Vec, 1> ModelSampler::VArray
Definition at line 21 of file ModelSampler.h.
typedef blitz::TinyVector<double, NDIM> ModelSampler::Vec
Definition at line 20 of file ModelSampler.h.
Constructor & Destructor Documentation
ModelSampler::ModelSampler (Paths & paths, Action * action, ActionChoiceBase * actionChoice, int target, const MPIManager * mpi)
Definition at line 19 of file ModelSampler.cc.
ModelSampler::~ModelSampler () virtual
Definition at line 27 of file ModelSampler.cc.
Member Function Documentation
AccRejEstimator * ModelSampler::getAccRejEstimator (const std::string & name) virtual
Get a pointer to the accept/reject statistic estimator.
(You are responsible for deleting this new object.)
Definition at line 105 of file ModelSampler.cc.
References accRejEst.
void ModelSampler::run () virtual
Implements Algorithm.
Definition at line 30 of file ModelSampler.cc.
References tryMove().
bool ModelSampler::tryMove () protected virtual
Method to atempt a Monte Carlo move, return true if accepted.
Definition at line 35 of file ModelSampler.cc.
References accRejEst, actionChoice, EnumeratedModelState::broadcastToMPIWorkers(), ActionChoiceBase::getActionChoiceDifference(), EnumeratedModelState::getModelState(), MPIManager::getNWorker(), RandomNumGenerator::getRand(), MPIManager::getWorkerID(), modelState, AccRejEstimator::moveAccepted(), mpi, nmodel, paths, EnumeratedModelState::setModelState(), target, and AccRejEstimator::tryingMove().
Referenced by run().
Member Data Documentation
AccRejEstimator* ModelSampler::accRejEst protected
A pointer to the accept-reject estimator.
Definition at line 42 of file ModelSampler.h.
Referenced by getAccRejEstimator(), and tryMove().
Action* ModelSampler::action protected
The action to be evaluated during the move.
Definition at line 36 of file ModelSampler.h.
ActionChoiceBase* ModelSampler::actionChoice protected
The action to be evaluated during the move.
Definition at line 38 of file ModelSampler.h.
Referenced by tryMove().
EnumeratedModelState& ModelSampler::modelState protected
Definition at line 39 of file ModelSampler.h.
Referenced by tryMove().
const MPIManager* ModelSampler::mpi protected
A pointer to the MPI manager, zero if MPI is not used.
Definition at line 47 of file ModelSampler.h.
Referenced by tryMove().
const int ModelSampler::nmodel protected
Definition at line 40 of file ModelSampler.h.
Referenced by tryMove().
Paths& ModelSampler::paths protected
A reference to the paths.
Definition at line 34 of file ModelSampler.h.
Referenced by tryMove().
const int ModelSampler::target protected
Definition at line 45 of file ModelSampler.h.
Referenced by tryMove().
The documentation for this class was generated from the following files:
ModelSampler.h
ModelSampler.cc