pi: Path integral Quantum Monte Carlo: H5ReportBuilder Class Reference
H5ReportBuilder Class Reference
Class for recording statistical data to an HDF5 file.
#include <H5ReportBuilder.h>
Public Member Functions
H5ReportBuilder (const std::string &filename, const EstimatorManager::SimInfoWriter *)
Constructor.
virtual ~H5ReportBuilder ()
Virtual destructor.
virtual void startWritingGroup (EstimatorManager &)
Start a group for writing.
virtual void writeStep (EstimatorManager &)
Write a simulation step to the current writing group.
virtual void startScalarReport (const ScalarEstimator &est)
Method to start reporting a ScalarEstimator.
virtual void reportScalarStep (const ScalarEstimator &est)
Method to write a step for a ScalarEstimator.
virtual void startArrayBlockedReport (const ArrayBlockedEstimator &est)
Method to start reporting a ArrayBlockedEstimator.
virtual void reportArrayBlockedStep (const ArrayBlockedEstimator &est)
Method to write a step for a ArrayBlockedEstimator.
virtual void startAccRejReport (const AccRejEstimator &est)
Method to start reporting a AccRejEstimator.
virtual void reportAccRejStep (const AccRejEstimator &est)
Method to write a step for a AccRejEstimator.
virtual void recordInputDocument (const std::string &docstring)
Method to record the input file contents.
Public Member Functions inherited from EstimatorReportBuilder
EstimatorReportBuilder ()
Constructor.
virtual ~EstimatorReportBuilder ()
Virtual destructor.
virtual void startArrayReport (const ArrayEstimator &est)
Method to start reporting a ArrayEstimator.
virtual void reportArrayStep (const ArrayEstimator &est)
Method to write a step for a ArrayEstimator.
Private Types
typedef std::vector< hid_t > DataSetContainer
typedef DataSetContainer::iterator DataSetIter
Private Attributes
std::string filename
const
EstimatorManager::SimInfoWriter * simInfoWriter
int nstep
int istep
hid_t fileID
The HDF5 file.
hid_t writingGroupID
The current HDF5 writing group.
hid_t stepAttrID
The group's step counter.
DataSetContainer dataset
The current HDF5 datasets.
DataSetIter dset
Iterator pointing at the current dataset.
Detailed Description
Class for recording statistical data to an HDF5 file.
The H5ReportBuilder s responsible for recording data recording it to disk. We have choosen an HDF5 file format (http://hdf.ncsa.uiuc.edu/HDF5) so that we can compress the data and include meta data and other structure.
Version:
$Revision$
Author:
John Shumway
Definition at line 35 of file H5ReportBuilder.h.
Member Typedef Documentation
typedef std::vector<hid_t> H5ReportBuilder::DataSetContainer private
Definition at line 65 of file H5ReportBuilder.h.
typedef DataSetContainer::iterator H5ReportBuilder::DataSetIter private
Definition at line 67 of file H5ReportBuilder.h.
Constructor & Destructor Documentation
H5ReportBuilder::H5ReportBuilder (const std::string & filename, const EstimatorManager::SimInfoWriter * simInfoWriter)
Constructor.
Definition at line 25 of file H5ReportBuilder.cc.
References fileID, and EstimatorManager::SimInfoWriter::writeH5().
H5ReportBuilder::~H5ReportBuilder () virtual
Virtual destructor.
Definition at line 33 of file H5ReportBuilder.cc.
References fileID.
Member Function Documentation
void H5ReportBuilder::recordInputDocument (const std::string & docstring) virtual
Method to record the input file contents.
Reimplemented from EstimatorReportBuilder.
Definition at line 293 of file H5ReportBuilder.cc.
References fileID.
void H5ReportBuilder::reportAccRejStep (const AccRejEstimator & est) virtual
Method to write a step for a AccRejEstimator.
Reimplemented from EstimatorReportBuilder.
Definition at line 117 of file H5ReportBuilder.cc.
void H5ReportBuilder::reportArrayBlockedStep (const ArrayBlockedEstimator & est) virtual
Method to write a step for a ArrayBlockedEstimator.
Reimplemented from EstimatorReportBuilder.
Definition at line 156 of file H5ReportBuilder.cc.
References dset, ArrayBlockedEstimator::getData(), ArrayBlockedEstimator::getError(), ArrayBlockedEstimator::hasError(), ArrayBlockedEstimator::normalize(), and ArrayBlockedEstimator::unnormalize().
void H5ReportBuilder::reportScalarStep (const ScalarEstimator & est) virtual
Method to write a step for a ScalarEstimator.
Reimplemented from EstimatorReportBuilder.
Definition at line 138 of file H5ReportBuilder.cc.
References dset, ScalarEstimator::getValue(), and istep.
void H5ReportBuilder::startAccRejReport (const AccRejEstimator & est) virtual
Method to start reporting a AccRejEstimator.
Reimplemented from EstimatorReportBuilder.
Definition at line 113 of file H5ReportBuilder.cc.
void H5ReportBuilder::startArrayBlockedReport (const ArrayBlockedEstimator & est) virtual
Method to start reporting a ArrayBlockedEstimator.
Reimplemented from EstimatorReportBuilder.
Definition at line 169 of file H5ReportBuilder.cc.
References dataset, ArrayBlockedEstimator::getExtent(), ArrayBlockedEstimator::getMax(), ArrayBlockedEstimator::getMin(), Estimator::getName(), ArrayBlockedEstimator::getNDim(), ArrayBlockedEstimator::getOrigin(), ArrayBlockedEstimator::getScale(), Estimator::getTypeString(), ArrayBlockedEstimator::hasError(), ArrayBlockedEstimator::hasMax(), ArrayBlockedEstimator::hasMin(), ArrayBlockedEstimator::hasOrigin(), ArrayBlockedEstimator::hasScale(), and writingGroupID.
void H5ReportBuilder::startScalarReport (const ScalarEstimator & est) virtual
Method to start reporting a ScalarEstimator.
Reimplemented from EstimatorReportBuilder.
Definition at line 64 of file H5ReportBuilder.cc.
References dataset, Estimator::getName(), Estimator::getTypeString(), Estimator::getUnitName(), nstep, and writingGroupID.
void H5ReportBuilder::startWritingGroup (EstimatorManager & manager) virtual
Start a group for writing.
Implements EstimatorReportBuilder.
Definition at line 37 of file H5ReportBuilder.cc.
References dataset, EstimatorManager::estimator, fileID, istep, nstep, EstimatorManager::nstep, stepAttrID, and writingGroupID.
void H5ReportBuilder::writeStep (EstimatorManager & manager) virtual
Write a simulation step to the current writing group.
Implements EstimatorReportBuilder.
Definition at line 120 of file H5ReportBuilder.cc.
References dataset, dset, EstimatorManager::estimator, fileID, istep, nstep, stepAttrID, and writingGroupID.
Member Data Documentation
DataSetContainer H5ReportBuilder::dataset private
The current HDF5 datasets.
Definition at line 78 of file H5ReportBuilder.h.
Referenced by startArrayBlockedReport(), startScalarReport(), startWritingGroup(), and writeStep().
DataSetIter H5ReportBuilder::dset private
Iterator pointing at the current dataset.
Definition at line 80 of file H5ReportBuilder.h.
Referenced by reportArrayBlockedStep(), reportScalarStep(), and writeStep().
hid_t H5ReportBuilder::fileID private
The HDF5 file.
Definition at line 69 of file H5ReportBuilder.h.
Referenced by H5ReportBuilder(), recordInputDocument(), startWritingGroup(), writeStep(), and ~H5ReportBuilder().
std::string H5ReportBuilder::filename private
Definition at line 61 of file H5ReportBuilder.h.
int H5ReportBuilder::istep private
Definition at line 64 of file H5ReportBuilder.h.
Referenced by reportScalarStep(), startWritingGroup(), and writeStep().
int H5ReportBuilder::nstep private
Definition at line 63 of file H5ReportBuilder.h.
Referenced by startScalarReport(), startWritingGroup(), and writeStep().
const EstimatorManager::SimInfoWriter* H5ReportBuilder::simInfoWriter private
Definition at line 62 of file H5ReportBuilder.h.
hid_t H5ReportBuilder::stepAttrID private
The group's step counter.
Definition at line 75 of file H5ReportBuilder.h.
Referenced by startWritingGroup(), and writeStep().
hid_t H5ReportBuilder::writingGroupID private
The current HDF5 writing group.
Definition at line 72 of file H5ReportBuilder.h.
Referenced by startArrayBlockedReport(), startScalarReport(), startWritingGroup(), and writeStep().
The documentation for this class was generated from the following files:
H5ReportBuilder.h
H5ReportBuilder.cc