pi: Path integral Quantum Monte Carlo: SimulationInfo Class Reference
SimulationInfo Class Reference
Class for storing the description of the simulation, used in parsing and setup.
#include <SimulationInfo.h>
Public Member Functions
SimulationInfo ()
Constructor.
SimulationInfo (SuperCell *, int npart, std::vector< Species * > &, std::vector< Species * > &, double temperature, double tau, int nslice)
Constructor.
virtual ~SimulationInfo ()
Destructor.
SuperCell * getSuperCell () const
Get a pointer to the supercell.
int getNSpecies () const
Get the number of species.
const Species & getSpecies (const int i) const
Get species by species index.
const Species & getPartSpecies (const int i) const
Get species by particle index.
const Species & getSpecies (const std::string &) const
Get species by name.
int getNPart () const
Get the number of particles.
double getTemperature () const
Get the temperature value.
double getTau () const
Get the time step.
void setTau (double value)
int getNSlice () const
Get the number of slices.
const Units * getUnits () const
Get information about units.
BeadFactory & getBeadFactory () const
Get a reference to the BeadFactory.
Public Attributes
double spinOmega
The energy scale for spinors.
SuperCell * superCell
The supercell.
Units * units
Unit information.
int npart
The number of particles.
std::vector< Species * > speciesList
The species list.
std::vector< Species * > speciesIndex
Index from each particle to it's species.
double temperature
The temperature.
double tau
The timestep.
int nslice
The number of slices.
BeadFactory & beadFactory
The bead factory.
Friends
class SimInfoParser
class SimInfoWriter
std::ostream & operator<< (std::ostream &, const SimulationInfo &)
Detailed Description
Class for storing the description of the simulation, used in parsing and setup.
Version:
$Revision$
Author:
John Shumway
Definition at line 32 of file SimulationInfo.h.
Constructor & Destructor Documentation
SimulationInfo::SimulationInfo ()
Constructor.
Definition at line 25 of file SimulationInfo.cc.
SimulationInfo::SimulationInfo (SuperCell * cell, int npart, std::vector< Species * > & specList, std::vector< Species * > & specIndex, double temperature, double tau, int nslice)
Constructor.
Definition at line 30 of file SimulationInfo.cc.
SimulationInfo::~SimulationInfo () virtual
Destructor.
Definition at line 38 of file SimulationInfo.cc.
References beadFactory, speciesList, and superCell.
Member Function Documentation
BeadFactory& SimulationInfo::getBeadFactory () const inline
Get a reference to the BeadFactory.
Definition at line 63 of file SimulationInfo.h.
References beadFactory.
Referenced by MainParser::parse(), and MainSpinParser::parse().
int SimulationInfo::getNPart () const inline
Get the number of particles.
Definition at line 52 of file SimulationInfo.h.
References npart.
Referenced by DampedFreeTensorMover::DampedFreeTensorMover(), FreeMover::FreeMover(), FreeMoverPBC::FreeMoverPBC(), FreeSpinMover::FreeSpinMover(), FreeTensorMover::FreeTensorMover(), GridPotential::GridPotential(), EstimatorParser::parse(), PIMCParser::parse(), ActionParser::parseActions(), PIMCParser::parseAlgorithm(), ProbDensityGrid::ProbDensityGrid(), SmoothedGridPotential::SmoothedGridPotential(), SpinMover::SpinMover(), SpringAction::SpringAction(), SpringTensorAction::SpringTensorAction(), and ZeroVarDensityEstimator::ZeroVarDensityEstimator().
int SimulationInfo::getNSlice () const inline
Get the number of slices.
Definition at line 59 of file SimulationInfo.h.
References nslice.
Referenced by DiamagneticEstimator::DiamagneticEstimator(), and EstimatorParser::parse().
int SimulationInfo::getNSpecies () const inline
Get the number of species.
Definition at line 44 of file SimulationInfo.h.
References speciesList.
Referenced by CoulombAction::CoulombAction(), FreeMover::FreeMover(), FreeMoverPBC::FreeMoverPBC(), EstimatorParser::parse(), ProbDensityGrid::ProbDensityGrid(), and SpringAction::SpringAction().
const Species& SimulationInfo::getPartSpecies (const int i) const inline
Get species by particle index.
Definition at line 48 of file SimulationInfo.h.
References speciesIndex.
Referenced by BondLengthEstimator::BondLengthEstimator(), BoxEstimator::BoxEstimator(), ConductanceEstimator::ConductanceEstimator(), ConductivityEstimator::ConductivityEstimator(), ConductivityEstimator2D::ConductivityEstimator2D(), CoulombAction::CoulombAction(), CoulombEnergyEstimator::CoulombEnergyEstimator(), DampedFreeTensorMover::DampedFreeTensorMover(), DensityCurrentEstimator::DensityCurrentEstimator(), DiamagneticEstimator::DiamagneticEstimator(), DipoleMomentEstimator::DipoleMomentEstimator(), EFieldAction::EFieldAction(), EIndEstimator::EIndEstimator(), EwaldCoulombEstimator::EwaldCoulombEstimator(), FreeMover::FreeMover(), FreeMoverPBC::FreeMoverPBC(), FreeSpinMover::FreeSpinMover(), FreeTensorMover::FreeTensorMover(), GridPotential::GridPotential(), PositionEstimator::PositionEstimator(), ProbDensityGrid::ProbDensityGrid(), SKOmegaEstimator::SKOmegaEstimator(), SmoothedGridPotential::SmoothedGridPotential(), SpinChargeEstimator::SpinChargeEstimator(), SpinMover::SpinMover(), SpringAction::SpringAction(), SpringTensorAction::SpringTensorAction(), VIndEstimator::VIndEstimator(), VirialEnergyEstimator::VirialEnergyEstimator(), WindingEstimator::WindingEstimator(), and ZeroVarDensityEstimator::ZeroVarDensityEstimator().
const Species& SimulationInfo::getSpecies (const int i) const inline
Get species by species index.
Definition at line 46 of file SimulationInfo.h.
References speciesList.
Referenced by CoulombAction::CoulombAction(), FreeMover::FreeMover(), FreeMoverPBC::FreeMoverPBC(), EstimatorParser::parse(), ActionParser::parseActions(), PIMCParser::parseAlgorithm(), ActionParser::parseEwaldActions(), ActionParser::parseNodeModel(), ActionParser::parseOrbitalDM(), EstimatorParser::parsePairCF(), ProbDensityGrid::ProbDensityGrid(), SKOmegaEstimator::SKOmegaEstimator(), SpringAction::SpringAction(), and WriteProbDensity::WriteProbDensity().
const Species & SimulationInfo::getSpecies (const std::string & name) const
Get species by name.
Definition at line 46 of file SimulationInfo.cc.
References speciesList.
SuperCell* SimulationInfo::getSuperCell () const inline
Get a pointer to the supercell.
Definition at line 42 of file SimulationInfo.h.
References superCell.
Referenced by CoulombAction::CoulombAction(), EwaldImagePairAction::EwaldImagePairAction(), FreeMover::FreeMover(), JelliumSlab::JelliumSlab(), EstimatorParser::parse(), PIMCParser::parse(), ActionParser::parseActions(), PIMCParser::parseAlgorithm(), SpringAction::SpringAction(), and WalkingChooser::WalkingChooser().
double SimulationInfo::getTau () const inline
Get the time step.
Definition at line 56 of file SimulationInfo.h.
References tau.
Referenced by DiamagneticEstimator::DiamagneticEstimator(), MainParser::parse(), PIMCParser::parse(), ActionParser::parseActions(), and ActionParser::parseNodeModel().
double SimulationInfo::getTemperature () const inline
Get the temperature value.
Definition at line 54 of file SimulationInfo.h.
References temperature.
Referenced by AugmentedNodes::AugmentedNodes(), CountCountEstimator::CountCountEstimator(), DensDensEstimator::DensDensEstimator(), DynamicPCFEstimator::DynamicPCFEstimator(), FreeParticleNodes::FreeParticleNodes(), EstimatorParser::parse(), PIMCParser::parse(), ActionParser::parseActions(), and ActionParser::parseNodeModel().
const Units* SimulationInfo::getUnits () const inline
Get information about units.
Definition at line 61 of file SimulationInfo.h.
References units.
Referenced by EstimatorParser::parse().
void SimulationInfo::setTau (double value) inline
Definition at line 57 of file SimulationInfo.h.
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const SimulationInfo & si) friend
Definition at line 53 of file SimulationInfo.cc.
friend class SimInfoParser friend
Definition at line 84 of file SimulationInfo.h.
friend class SimInfoWriter friend
Definition at line 85 of file SimulationInfo.h.
Member Data Documentation
BeadFactory& SimulationInfo::beadFactory
The bead factory.
Definition at line 83 of file SimulationInfo.h.
Referenced by getBeadFactory(), and ~SimulationInfo().
int SimulationInfo::npart
The number of particles.
Definition at line 71 of file SimulationInfo.h.
Referenced by getNPart(), SimInfoParser::parse(), and SimInfoWriter::writeH5().
int SimulationInfo::nslice
The number of slices.
Definition at line 81 of file SimulationInfo.h.
Referenced by getNSlice(), SimInfoParser::parse(), and SimInfoWriter::writeH5().
std::vector<Species*> SimulationInfo::speciesIndex
Index from each particle to it's species.
Definition at line 75 of file SimulationInfo.h.
Referenced by getPartSpecies(), and SimInfoParser::parse().
std::vector<Species*> SimulationInfo::speciesList
The species list.
Definition at line 73 of file SimulationInfo.h.
Referenced by getNSpecies(), getSpecies(), operator<<(), SimInfoParser::parse(), and ~SimulationInfo().
double SimulationInfo::spinOmega
The energy scale for spinors.
Definition at line 65 of file SimulationInfo.h.
Referenced by MainSpinParser::parse(), and ActionParser::parseActions().
SuperCell* SimulationInfo::superCell
The supercell.
Definition at line 67 of file SimulationInfo.h.
Referenced by getSuperCell(), SimInfoParser::parse(), SimInfoWriter::writeH5(), and ~SimulationInfo().
double SimulationInfo::tau
The timestep.
Definition at line 79 of file SimulationInfo.h.
Referenced by getTau(), SimInfoParser::parse(), PIMCParser::parseAlgorithm(), and SimInfoWriter::writeH5().
double SimulationInfo::temperature
The temperature.
Definition at line 77 of file SimulationInfo.h.
Referenced by getTemperature(), operator<<(), SimInfoParser::parse(), and SimInfoWriter::writeH5().
Units* SimulationInfo::units
Unit information.
Definition at line 69 of file SimulationInfo.h.
Referenced by getUnits(), and SimInfoParser::parse().
The documentation for this class was generated from the following files:
SimulationInfo.h
SimulationInfo.cc