pi: Path integral Quantum Monte Carlo: WalkingChooser Class Reference
WalkingChooser Class Reference
#include <WalkingChooser.h>
Public Types
typedef blitz::Array< int, 1 > IArray
typedef blitz::Array< double, 1 > Array
typedef blitz::Array< double, 2 > Mat
typedef blitz::TinyVector
< double, NDIM > Vec
typedef blitz::Array
< PeriodicGaussian *, 1 > PGArray
Public Member Functions
WalkingChooser (const int nsize, const Species &, const int nlevel, const SimulationInfo &)
virtual ~WalkingChooser ()
virtual void setMLSampler (const MultiLevelSampler *)
virtual bool choosePermutation ()
virtual void chooseParticles ()
virtual void init ()
int iSearch (int part, double x)
virtual double getLnTranProb () const
Public Member Functions inherited from PermutationChooser
PermutationChooser (int size)
virtual ~PermutationChooser ()
const Permutation & getPermutation ()
Public Member Functions inherited from SpeciesParticleChooser
SpeciesParticleChooser (const Species &, const int nmoving)
virtual ~SpeciesParticleChooser ()
Public Member Functions inherited from ParticleChooser
ParticleChooser (const int npart)
virtual ~ParticleChooser ()
int operator[] (const int i) const
std::string & getName ()
Protected Attributes
Mat t
Mat cump
const MultiLevelSampler * multiLevelSampler
PGArray pg
Protected Attributes inherited from PermutationChooser
Permutation * permutation
Protected Attributes inherited from SpeciesParticleChooser
const int npart
const int ifirst
Protected Attributes inherited from ParticleChooser
IArray index
std::string name
Private Attributes
int nsize
const double mass
const double tau
double prob
Detailed Description
Definition at line 13 of file WalkingChooser.h.
Member Typedef Documentation
typedef blitz::Array<double, 1> WalkingChooser::Array
Definition at line 17 of file WalkingChooser.h.
typedef blitz::Array<int, 1> WalkingChooser::IArray
Reimplemented from ParticleChooser.
Reimplemented in SpinStatePermutationChooser.
Definition at line 16 of file WalkingChooser.h.
typedef blitz::Array<double, 2> WalkingChooser::Mat
Definition at line 18 of file WalkingChooser.h.
typedef blitz::Array<PeriodicGaussian*, 1> WalkingChooser::PGArray
Definition at line 20 of file WalkingChooser.h.
typedef blitz::TinyVector<double, NDIM> WalkingChooser::Vec
Definition at line 19 of file WalkingChooser.h.
Constructor & Destructor Documentation
WalkingChooser::WalkingChooser (const int nsize, const Species & species, const int nlevel, const SimulationInfo & simInfo)
Definition at line 18 of file WalkingChooser.cc.
References SimulationInfo::getSuperCell(), mass, nsize, PermutationChooser::permutation, pg, and tau.
WalkingChooser::~WalkingChooser () virtual
Definition at line 33 of file WalkingChooser.cc.
References pg.
Member Function Documentation
void WalkingChooser::chooseParticles () virtual
Reimplemented from SpeciesParticleChooser.
Definition at line 38 of file WalkingChooser.cc.
bool WalkingChooser::choosePermutation () virtual
Reimplemented from PermutationChooser.
Definition at line 41 of file WalkingChooser.cc.
References cump, RandomNumGenerator::getRand(), SpeciesParticleChooser::ifirst, ParticleChooser::index, iSearch(), SpeciesParticleChooser::npart, nsize, prob, and t.
Referenced by PairChooser::choosePermutation().
virtual double WalkingChooser::getLnTranProb () const inline virtual
Reimplemented from PermutationChooser.
Definition at line 29 of file WalkingChooser.h.
References prob.
Referenced by PairChooser::getLnTranProb().
void WalkingChooser::init () virtual
Reimplemented from PermutationChooser.
Reimplemented in SpinStatePermutationChooser.
Definition at line 93 of file WalkingChooser.cc.
References cump, Beads< TDIM >::getNSlice(), MultiLevelSampler::getSectionBeads(), MultiLevelSampler::getSuperCell(), SpeciesParticleChooser::ifirst, multiLevelSampler, SpeciesParticleChooser::npart, SuperCell::pbc(), pg, and t.
Referenced by PairChooser::init().
int WalkingChooser::iSearch (int part, double x)
Definition at line 122 of file WalkingChooser.cc.
References cump, and SpeciesParticleChooser::npart.
Referenced by choosePermutation().
void WalkingChooser::setMLSampler (const MultiLevelSampler * mls) virtual
Reimplemented from PermutationChooser.
Definition at line 146 of file WalkingChooser.cc.
References multiLevelSampler.
Referenced by PairChooser::setMLSampler().
Member Data Documentation
Mat WalkingChooser::cump protected
Definition at line 34 of file WalkingChooser.h.
Referenced by choosePermutation(), SpinStatePermutationChooser::init(), init(), and iSearch().
const double WalkingChooser::mass private
Definition at line 39 of file WalkingChooser.h.
Referenced by WalkingChooser().
const MultiLevelSampler* WalkingChooser::multiLevelSampler protected
Definition at line 35 of file WalkingChooser.h.
Referenced by SpinStatePermutationChooser::init(), init(), and setMLSampler().
int WalkingChooser::nsize private
Definition at line 38 of file WalkingChooser.h.
Referenced by choosePermutation(), and WalkingChooser().
PGArray WalkingChooser::pg protected
Definition at line 36 of file WalkingChooser.h.
Referenced by SpinStatePermutationChooser::init(), init(), WalkingChooser(), and ~WalkingChooser().
double WalkingChooser::prob private
Definition at line 41 of file WalkingChooser.h.
Referenced by choosePermutation(), and getLnTranProb().
Mat WalkingChooser::t protected
Definition at line 33 of file WalkingChooser.h.
Referenced by choosePermutation(), SpinStatePermutationChooser::init(), and init().
const double WalkingChooser::tau private
Definition at line 40 of file WalkingChooser.h.
Referenced by WalkingChooser().
The documentation for this class was generated from the following files:
WalkingChooser.h
WalkingChooser.cc