pi: Path integral Quantum Monte Carlo: SerialPaths Class Reference
SerialPaths Class Reference
Storage for paths in a serial process.
#include <SerialPaths.h>
Public Member Functions
SerialPaths (int npart, int nslice, double tau, const SuperCell &cell, const BeadFactory &)
Constructor.
virtual ~SerialPaths ()
Destructor.
virtual void sumOverLinks (LinkSummable &) const
Loop over links, calling a LinkSummable object.
virtual Vec & operator() (const int ipart, const int islice)
Get a reference to a bead.
virtual const Vec & operator() (const int ipart, const int islice) const
Get a const reference to a bead.
virtual Vec & operator() (const int ipart, const int islice, const int istep)
Get a reference to a bead by offset.
virtual const Vec & operator() (const int ipart, const int islice, const int istep) const
Get a const reference to a bead by offset.
virtual Vec delta (const int ipart, const int islice, const int istep) const
Get a relative displacement a bead by offset.
virtual void getBeads (int ifirstSlice, Beads< NDIM > &) const
Get beads.
virtual void getSlice (int islice, VArray &) const
Get a slice.
virtual const void * getAuxBead (const int ipart, const int islice, const int iaux) const
Get auxialiary bead.
virtual void * getAuxBead (const int ipart, const int islice, const int iaux)
Get auxialiary bead.
virtual void putBeads (int ifirstSlice, const Beads< NDIM > &, const Permutation &) const
Put beads.
virtual void putDoubleBeads (int ifirstSlice1, Beads< NDIM > &, Permutation &, int ifirstSlice2, Beads< NDIM > &, Permutation &) const
virtual const Permutation & getPermutation () const
Get the global permuatation.
virtual const Permutation & getGlobalPermutation () const
virtual int getLowestOwnedSlice (bool d) const
virtual int getHighestOwnedSlice (bool d) const
virtual int getHighestSampledSlice (int n, bool d) const
virtual bool isOwnedSlice (int islice) const
virtual void shift (const int ishift)
virtual void clearPermutation ()
Public Member Functions inherited from Paths
Paths (int npart, int nslice, double tau, const SuperCell &cell)
Constructor.
virtual ~Paths ()
Destructor.
int getNPart () const
Get the number of particles.
int getNSlice () const
Get the number of slices.
double getTau () const
Get the number of slices on this processor.
const SuperCell & getSuperCell () const
Get the supercell.
virtual void setBuffers ()
virtual bool isDouble () const
ModelState * getModelState ()
const ModelState * getModelState () const
void setModelState (ModelState *m)
bool hasModelState ()
Private Member Functions
void putBeads (int ifirstSlice, const Beads< NDIM > &, const Permutation &, int ifirst, int nbslice) const
Private Attributes
Beads< NDIM > & beads
Storage for the beads.
Beads< NDIM > & buffer1
Storage shifting uffers.
Beads< NDIM > & buffer2
Permutation & permutation
Storage for the permutation.
Permutation & inversePermutation
Storage for the inverse permutation.
Additional Inherited Members
Public Types inherited from Paths
typedef blitz::TinyVector
< double, NDIM > Vec
Constants and typedefs.
typedef blitz::Array< Vec, 1 > VArray
Protected Attributes inherited from Paths
const int npart
Number of particles.
const int nslice
Number of slices.
const double tau
The temperature of one timestep.
const SuperCell & cell
The supercell.
ModelState * modelState
Detailed Description
Storage for paths in a serial process.
We own slices 0 through nslice-1. Access methods accept slices -nslice+1 through 2*nslice-1.
Version:
$Revision$
Author:
John Shumway
Definition at line 30 of file SerialPaths.h.
Constructor & Destructor Documentation
SerialPaths::SerialPaths (int npart, int nslice, double tau, const SuperCell & cell, const BeadFactory & beadFactory)
Constructor.
Definition at line 31 of file SerialPaths.cc.
SerialPaths::~SerialPaths () virtual
Destructor.
Definition at line 43 of file SerialPaths.cc.
References beads, buffer1, buffer2, inversePermutation, and permutation.
Member Function Documentation
void SerialPaths::clearPermutation () virtual
Implements Paths.
Definition at line 234 of file SerialPaths.cc.
References inversePermutation, permutation, and Permutation::reset().
Paths::Vec SerialPaths::delta (const int ipart, const int islice, const int istep) const virtual
Get a relative displacement a bead by offset.
Implements Paths.
Definition at line 104 of file SerialPaths.cc.
References beads, Paths::cell, inversePermutation, Paths::nslice, SuperCell::pbc(), and permutation.
const void * SerialPaths::getAuxBead (const int ipart, const int islice, const int iaux) const virtual
Get auxialiary bead.
Implements Paths.
Definition at line 207 of file SerialPaths.cc.
References beads, and BeadsBase::getAuxBead().
void * SerialPaths::getAuxBead (const int ipart, const int islice, const int iaux) virtual
Get auxialiary bead.
Implements Paths.
Definition at line 212 of file SerialPaths.cc.
References beads, and BeadsBase::getAuxBead().
void SerialPaths::getBeads (int ifirstSlice, Beads< NDIM > & outBeads) const virtual
Get beads.
Implements Paths.
Definition at line 119 of file SerialPaths.cc.
References beads, BeadsBase::copySlice(), Beads< TDIM >::getNSlice(), inversePermutation, Paths::nslice, and permutation.
Referenced by shift().
virtual const Permutation& SerialPaths::getGlobalPermutation () const inline virtual
Implements Paths.
Definition at line 68 of file SerialPaths.h.
References permutation.
virtual int SerialPaths::getHighestOwnedSlice (bool d) const inline virtual
Implements Paths.
Definition at line 70 of file SerialPaths.h.
virtual int SerialPaths::getHighestSampledSlice (int n, bool d) const inline virtual
Implements Paths.
Definition at line 72 of file SerialPaths.h.
virtual int SerialPaths::getLowestOwnedSlice (bool d) const inline virtual
Implements Paths.
Definition at line 69 of file SerialPaths.h.
virtual const Permutation& SerialPaths::getPermutation () const inline virtual
Get the global permuatation.
Implements Paths.
Definition at line 67 of file SerialPaths.h.
References permutation.
void SerialPaths::getSlice (int islice, VArray & out) const virtual
Get a slice.
Implements Paths.
Definition at line 134 of file SerialPaths.cc.
References beads, and Paths::npart.
virtual bool SerialPaths::isOwnedSlice (int islice) const inline virtual
Implements Paths.
Definition at line 74 of file SerialPaths.h.
References Paths::nslice.
Paths::Vec & SerialPaths::operator() (const int ipart, const int islice) virtual
Get a reference to a bead.
Implements Paths.
Definition at line 68 of file SerialPaths.cc.
References beads, inversePermutation, and Paths::nslice.
const Paths::Vec & SerialPaths::operator() (const int ipart, const int islice) const virtual
Get a const reference to a bead.
Implements Paths.
Definition at line 74 of file SerialPaths.cc.
References beads, inversePermutation, and Paths::nslice.
Paths::Vec & SerialPaths::operator() (const int ipart, const int islice, const int istep) virtual
Get a reference to a bead by offset.
Implements Paths.
Definition at line 80 of file SerialPaths.cc.
References beads, inversePermutation, Paths::nslice, and permutation.
const Paths::Vec & SerialPaths::operator() (const int ipart, const int islice, const int istep) const virtual
Get a const reference to a bead by offset.
Implements Paths.
Definition at line 92 of file SerialPaths.cc.
References beads, inversePermutation, Paths::nslice, and permutation.
void SerialPaths::putBeads (int ifirstSlice, const Beads< NDIM > & inBeads, const Permutation & inPermutation) const virtual
Put beads.
Implements Paths.
Definition at line 138 of file SerialPaths.cc.
References Beads< TDIM >::getNSlice().
Referenced by putDoubleBeads(), and shift().
void SerialPaths::putBeads (int ifirstSlice, const Beads< NDIM > & inBeads, const Permutation & inPermutation, int ifirst, int nbslice) const private
Definition at line 144 of file SerialPaths.cc.
References Permutation::append(), beads, BeadsBase::copySlice(), inversePermutation, Permutation::isIdentity(), Paths::npart, Paths::nslice, permutation, Permutation::prepend(), and Permutation::setToInverse().
void SerialPaths::putDoubleBeads (int ifirstSlice1, Beads< NDIM > & beads1, Permutation & p1, int ifirstSlice2, Beads< NDIM > & beads2, Permutation & p2) const virtual
Implements Paths.
Definition at line 187 of file SerialPaths.cc.
References Permutation::append(), Paths::nslice, Beads< TDIM >::permute(), Permutation::prepend(), putBeads(), and Permutation::setToInverse().
void SerialPaths::shift (const int ishift) virtual
Implements Paths.
Definition at line 217 of file SerialPaths.cc.
References buffer1, buffer2, getBeads(), Beads< TDIM >::getNSlice(), Paths::npart, Paths::nslice, and putBeads().
void SerialPaths::sumOverLinks (LinkSummable & estimator) const virtual
Loop over links, calling a LinkSummable object.
Implements Paths.
Definition at line 48 of file SerialPaths.cc.
References beads, LinkSummable::endCalc(), LinkSummable::handleLink(), LinkSummable::initCalc(), inversePermutation, Paths::npart, and Paths::nslice.
Member Data Documentation
Beads<NDIM>& SerialPaths::beads private
Storage for the beads.
Definition at line 82 of file SerialPaths.h.
Referenced by delta(), getAuxBead(), getBeads(), getSlice(), operator()(), putBeads(), sumOverLinks(), and ~SerialPaths().
Beads<NDIM>& SerialPaths::buffer1 private
Storage shifting uffers.
Definition at line 84 of file SerialPaths.h.
Referenced by shift(), and ~SerialPaths().
Beads<NDIM> & SerialPaths::buffer2 private
Definition at line 84 of file SerialPaths.h.
Referenced by shift(), and ~SerialPaths().
Permutation& SerialPaths::inversePermutation private
Storage for the inverse permutation.
Definition at line 88 of file SerialPaths.h.
Referenced by clearPermutation(), delta(), getBeads(), operator()(), putBeads(), sumOverLinks(), and ~SerialPaths().
Permutation& SerialPaths::permutation private
Storage for the permutation.
Definition at line 86 of file SerialPaths.h.
Referenced by clearPermutation(), delta(), getBeads(), getGlobalPermutation(), getPermutation(), operator()(), putBeads(), and ~SerialPaths().
The documentation for this class was generated from the following files:
SerialPaths.h
SerialPaths.cc